BattleFrontier_Lounge8_MapScripts::
	.byte 0

BattleFrontier_Lounge8_EventScript_Man::
	msgbox BattleFrontier_Lounge8_Text_WhatATrainerNeeds, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_Woman::
	msgbox BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_NinjaBoy::
	msgbox BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling, MSGBOX_NPC
	end

BattleFrontier_Lounge8_Text_WhatATrainerNeeds:
	.string "训练家所需要的一切……\p"
	.string "知识……战术……运气……毅力……\n"
	.string "精神……英勇……还有能力……\p"
	.string "我可是拥有这一切！在这里我必定是\n"
	.string "战无不胜的！\p"
	.string "嗯？宝可梦？那是什么？$"

BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains:
	.string "你知道开拓之脑吗？\p"
	.string "亚希达是这么称呼管理对战开拓区七\n"
	.string "大设施的那七位特别的训练家的。$"

BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling:
	.string "对战塔里有一位大姐姐告诉我我在对\n"
	.string "战方面的才能非常出色！\p"
	.string "不过我更喜欢宝可梦华丽大赛！\p"
	.string "但我在华丽大赛上完全不行！\p"
	.string "我想也许喜欢和天赋是两码事吧。$"

