SootopolisCity_House5_MapScripts::
	.byte 0

SootopolisCity_House5_EventScript_Maniac::
	msgbox SootopolisCity_House5_Text_SootopolisMtPyreConnection, MSGBOX_NPC
	end

SootopolisCity_House5_EventScript_Girl::
	msgbox SootopolisCity_House5_Text_BrotherUsedToStudySea, MSGBOX_NPC
	end

SootopolisCity_House5_Text_SootopolisMtPyreConnection:
	.string "似乎琉璃市与送神山之间存在着某种\n"
	.string "联系。\p"
	.string "我还在研究所工作的时候和同事一起\n"
	.string "做过这方面的调查。$"

SootopolisCity_House5_Text_BrotherUsedToStudySea:
	.string "我哥哥曾经研究海洋。$"

