SixIsland_WaterPath_Frlg_MapScripts::
	.byte 0

SixIsland_WaterPath_EventScript_HornWantedSign::
	msgbox SixIsland_WaterPath_Text_WantedUltimateHorn, MSGBOX_SIGN
	end

SixIsland_WaterPath_EventScript_RouteSign::
	msgbox SixIsland_WaterPath_Text_RouteSign, MSGBOX_SIGN
	end

SixIsland_WaterPath_Text_RoseIntro::
	.string "我被一阵令人愉快的微风一路带到了\n"
	.string "这儿。$"

SixIsland_WaterPath_Text_RoseDefeat::
	.string "呵呵……你做决定时的样子真是可爱\n"
	.string "。$"

SixIsland_WaterPath_Text_RosePostBattle::
	.string "我想去那边的森林，但是……\p"
	.string "那儿有许多虫属性宝可梦。我有点儿\n"
	.string "害怕。$"

SixIsland_WaterPath_Text_EdwardIntro::
	.string "我正在秘密地练习，所以没有人能看\n"
	.string "见我。$"

SixIsland_WaterPath_Text_EdwardDefeat::
	.string "没有人看见我输了，对吧？$"

SixIsland_WaterPath_Text_EdwardPostBattle::
	.string "最为一个演员，我不想让人知道我付\n"
	.string "出的努力。$"

SixIsland_WaterPath_Text_SamirIntro::
	.string "什么，你的意思是你讨厌看到像我这\n"
	.string "样的游泳的人？\p"
	.string "啊，不要这样！$"

SixIsland_WaterPath_Text_SamirDefeat::
	.string "噢，不，别这样。$"

SixIsland_WaterPath_Text_SamirPostBattle::
	.string "我无法消除一个游泳的人的耻辱……$"

SixIsland_WaterPath_Text_DeniseIntro::
	.string "我男朋友总是很忙，所以我自己出来\n"
	.string "游泳了。$"

SixIsland_WaterPath_Text_DeniseDefeat::
	.string "啊，我就知道会是这样！$"

SixIsland_WaterPath_Text_DenisePostBattle::
	.string "当我不能和我男朋友在一起时，我就\n"
	.string "和他给我的宝可梦一起度过一个人的\l"
	.string "时光。$"

SixIsland_WaterPath_Text_EarlIntro::
	.string "告诉我，这周围哪里有山？$"

SixIsland_WaterPath_Text_EarlDefeat::
	.string "当我忙于战斗时，我迷路了！$"

SixIsland_WaterPath_Text_EarlPostBattle::
	.string "这周围没有山吗？$"

SixIsland_WaterPath_Text_MiuIntro::
	.string "美羽：你好，宝可梦！下面是战斗的\n"
	.string "时间！$"

SixIsland_WaterPath_Text_MiuDefeat::
	.string "美羽：噢，不！妈妈！$"

SixIsland_WaterPath_Text_MiuPostBattle::
	.string "美羽：当我们输的时候我从心底里感\n"
	.string "到悲伤……$"

SixIsland_WaterPath_Text_MiuNotEnoughMons::
	.string "美羽：美绪和我是双胞胎。我们想要\n"
	.string "一起战斗。$"

SixIsland_WaterPath_Text_MiaIntro::
	.string "美绪：你好，宝可梦！下面是战斗时\n"
	.string "间！$"

SixIsland_WaterPath_Text_MiaDefeat::
	.string "美绪：你太狠了！你是坏人，你赢了\n"
	.string "！$"

SixIsland_WaterPath_Text_MiaPostBattle::
	.string "美绪：噢……对不起，我的宝可梦…\n"
	.string "…$"

SixIsland_WaterPath_Text_MiaNotEnoughMons::
	.string "美绪：你只有一只宝可梦？\p"
	.string "你不觉得孤单吗？$"

SixIsland_WaterPath_Text_WantedUltimateHorn::
	.string "通缉！最后的警报！$"

SixIsland_WaterPath_Text_RouteSign::
	.string "水之步道通往遗迹山谷$"

