Route9_Frlg_MapScripts::
	.byte 0

Route9_EventScript_RouteSign::
	msgbox Route9_Text_RouteSign, MSGBOX_SIGN
	end

Route9_Text_AliciaIntro::
	.string "你带着宝可梦！你是我的了！$"

Route9_Text_AliciaDefeat::
	.string "你欺骗了我……$"

Route9_Text_AliciaPostBattle::
	.string "这个隧道里面一片漆黑。\p"
	.string "想要穿过山洞的话，你需要闪光。$"

Route9_Text_ChrisIntro::
	.string "和那些好看的宝可梦一起散步的人是\n"
	.string "谁？$"

Route9_Text_ChrisDefeat::
	.string "就像一束光！$"

Route9_Text_ChrisPostBattle::
	.string "继续走下去！$"

Route9_Text_DrewIntro::
	.string "我正打算穿过岩山隧道去紫苑……$"

Route9_Text_DrewDefeat::
	.string "无法估计啊……$"

Route9_Text_DrewPostBattle::
	.string "你也是去岩山隧道吗？$"

Route9_Text_CaitlinIntro::
	.string "你竟敢这样对我！$"

Route9_Text_CaitlinDefeat::
	.string "不！你太过分了。$"

Route9_Text_CaitlinPostBattle::
	.string "你真的很有天赋。祝你好运！$"

Route9_Text_JeremyIntro::
	.string "啊！好样的！我很无聊，呃！$"

Route9_Text_JeremyDefeat::
	.string "来这儿吧！\p"
	.string "噢，等等。我离开了我的宝可梦！$"

Route9_Text_JeremyPostBattle::
	.string "你确定你有胆量和我对抗，嗯？$"

Route9_Text_BriceIntro::
	.string "哈哈！你有一点鲁莽！$"

Route9_Text_BriceDefeat::
	.string "那是什么？$"

Route9_Text_BricePostBattle::
	.string "哈哈！小孩子应该坚强点！$"

Route9_Text_BrentIntro::
	.string "我每天都起得很早去训练我的宝可\n"
	.string "梦！$"

Route9_Text_BrentDefeat::
	.string "什么\p"
	.string "多么浪费时间！$"

Route9_Text_BrentPostBattle::
	.string "我必须找到更多虫子来使我变得更强\n"
	.string "大……$"

Route9_Text_AlanIntro::
	.string "哈哈！把它带过来！$"

Route9_Text_AlanDefeat::
	.string "呵呵！你堂堂正正地战胜了我！$"

Route9_Text_AlanPostBattle::
	.string "哈哈哈哈哈！健壮的家伙总是会大笑\n"
	.string "的！$"

Route9_Text_ConnerIntro::
	.string "去吧，我的超级虫属性宝可梦$"

Route9_Text_ConnerDefeat::
	.string "我的虫子们……$"

Route9_Text_ConnerPostBattle::
	.string "如果你不喜欢虫属性的宝可梦，那你\n"
	.string "就是看不起我$"

Route9_Text_RouteSign::
	.string "9号道路华蓝市-岩山隧道$"

