PewterCity_Mart_hns_MapScripts::
	.byte 0

PewterCity_Mart_EventScript_Youngster::
	msgbox PewterCity_Mart_Text_Youngster, MSGBOX_NPC
	end

PewterCity_Mart_EventScript_Nerd::
	msgbox PewterCity_Mart_Text_SuperNerd, MSGBOX_NPC
	end

PewterCity_Mart_Text_Youngster:
	.string "嗨！瞧瞧我的暴鲤龙！\p"
	.string "它可是我从鲤鱼王一手养大的。真不\n"
	.string "敢相信它现在变得这么强。$"

PewterCity_Mart_Text_SuperNerd:
	.string "以前有个卖鲤鱼王的古怪大叔。\p"
	.string "他逢人就说愤怒之湖的鲤鱼王品质极\n"
	.string "其出众呢。$"

