RustboroCity_House2_MapScripts::
	.byte 0

RustboroCity_House2_EventScript_PokefanF::
	msgbox RustboroCity_House2_Text_TrainerSchoolExcellent, MSGBOX_NPC
	end

RustboroCity_House2_EventScript_LittleGirl::
	msgbox RustboroCity_House2_Text_RoxanneKnowsALot, MSGBOX_NPC
	end

RustboroCity_House2_Text_TrainerSchoolExcellent:
	.string "训练家学校特别好。\p"
	.string "在那儿学习的话，甚至可能成为道馆\n"
	.string "馆主。$"

RustboroCity_House2_Text_RoxanneKnowsALot:
	.string "道馆馆主杜娟了解很多关于宝可梦的\n"
	.string "知识，\p"
	.string "而且她也很强大！$"

