SafariZone_West_Frlg_MapScripts::
	.byte 0

SafariZone_West_EventScript_RestHouseSign::
	msgbox SafariZone_West_Text_RestHouse, MSGBOX_SIGN
	end

SafariZone_West_EventScript_LostTeethNotice::
	msgbox SafariZone_West_Text_PleaseFindWardensLostTeeth, MSGBOX_SIGN
	end

SafariZone_West_EventScript_TrainerTips::
	msgbox SafariZone_West_Text_SearchForSecretHouse, MSGBOX_SIGN
	end

SafariZone_West_EventScript_AreaSign::
	msgbox SafariZone_West_Text_AreaSign, MSGBOX_SIGN
	end

SafariZone_West_Text_RestHouse::
	.string "休息屋$"

SafariZone_West_Text_PleaseFindWardensLostTeeth::
	.string "寻物启示\p"
	.string "寻找原野区园长丢失了的金假牙。它\n"
	.string "就掉在这里的某个地方。\p"
	.string "是有奖悬赏！联系人：园长$"

SafariZone_West_Text_SearchForSecretHouse::
	.string "训练家贴士\p"
	.string "区域性的探险活动！搜索神秘小屋！$"

SafariZone_West_Text_AreaSign::
	.string "栖息地3往东：中部栖息地$"

