Route11_EastEntrance_1F_Frlg_MapScripts::
	.byte 0

Route11_EastEntrance_1F_EventScript_TopGuard::
	msgbox Route11_EastEntrance_1F_Text_ManInLavenderRatesNames, MSGBOX_NPC
	end

Route11_EastEntrance_1F_EventScript_BottomGuard::
	msgbox Route11_EastEntrance_1F_Text_RockTunnelToReachLavender, MSGBOX_NPC
	end

@ Unclear where this is originally from
Route11_EastEntrance_1F_Text_BagIsFull::
	.string "{PLAYER}{KUN}の　バッグ\n"
	.string "いっぱい　みたい　だね$"

Route11_EastEntrance_1F_Text_ManInLavenderRatesNames::
	.string "难道你不认为给宝可梦取一个好名字\n"
	.string "很难吗？\p"
	.string "尤其是当你已经有了一个队伍的时候\n"
	.string "。\p"
	.string "在紫苑镇 有一个给宝可梦取名字的\n"
	.string "男人。\p"
	.string "他甚至也可以帮你给宝可梦重新起名\n"
	.string "。$"

Route11_EastEntrance_1F_Text_RockTunnelToReachLavender::
	.string "如果你想去紫苑镇 就穿过岩山隧道\n"
	.string "吧。\p"
	.string "你可以从华蓝市到达岩山隧道。$"

