SevenIsland_SevaultCanyon_Frlg_MapScripts::
	.byte 0

SevenIsland_SevaultCanyon_EventScript_RouteSign::
	msgbox SevenIsland_SevaultCanyon_Text_RouteSign, MSGBOX_SIGN
	end

SevenIsland_SevaultCanyon_Text_CyndyIntro::
	.string "我现在是最佳状态！$"

SevenIsland_SevaultCanyon_Text_CyndyDefeat::
	.string "呃？有些环节出问题了……$"

SevenIsland_SevaultCanyon_Text_CyndyPostBattle::
	.string "我现在在的这条路，可能离训练家之\n"
	.string "塔越来越远了……$"

SevenIsland_SevaultCanyon_Text_EvanIntro::
	.string "如果你偶然拥有了最强的宝可梦，那\n"
	.string "也不要紧……\p"
	.string "若你不能正确地使用它们，那你仍然\n"
	.string "一无是处！$"

SevenIsland_SevaultCanyon_Text_EvanDefeat::
	.string "你是这儿的主人！$"

SevenIsland_SevaultCanyon_Text_EvanPostBattle::
	.string "你一定是经常见到，训练家拥有强大\n"
	.string "的宝可梦却不知道如何使用。\p"
	.string "所以在训练宝可梦之前，训练家首先\n"
	.string "自己要成长。$"

SevenIsland_SevaultCanyon_Text_JacksonIntro::
	.string "我致力于保护自然环境。相应地，大\n"
	.string "自然也会保护我！$"

SevenIsland_SevaultCanyon_Text_JacksonDefeat::
	.string "哇！你很强！做我的保镖怎么样？$"

SevenIsland_SevaultCanyon_Text_JacksonPostBattle::
	.string "在众多星系之中，我们的就如一滴水\n"
	.string "那么小。\p"
	.string "但是我们想为了每个人去保护这滴水\n"
	.string "。$"

SevenIsland_SevaultCanyon_Text_KatelynIntro::
	.string "你穿的那双鞋可真漂亮。$"

SevenIsland_SevaultCanyon_Text_KatelynDefeat::
	.string "在你可爱的外表下隐藏着一颗炽热的\n"
	.string "心。$"

SevenIsland_SevaultCanyon_Text_KatelynPostBattle::
	.string "你妈妈给你买了这双漂亮的跑步鞋？\p"
	.string "她一定很爱你。$"

SevenIsland_SevaultCanyon_Text_LeroyIntro::
	.string "你看起来很强大。请让我和你战斗吧\n"
	.string "！$"

SevenIsland_SevaultCanyon_Text_LeroyDefeat::
	.string "我知道！你和我想像的一样强！$"

SevenIsland_SevaultCanyon_Text_LeroyPostBattle::
	.string "你战斗的方式给了我许多启发。\p"
	.string "太感谢了！$"

SevenIsland_SevaultCanyon_Text_MichelleIntro::
	.string "我受到了最好的教育，就是为了变得\n"
	.string "像今天这样强大。\p"
	.string "我不想输给任何人！$"

SevenIsland_SevaultCanyon_Text_MichelleDefeat::
	.string "谢谢你。输给你使我好像解脱了一样\n"
	.string "。$"

SevenIsland_SevaultCanyon_Text_MichellePostBattle::
	.string "有的时候，我会因为一些小事感到愤\n"
	.string "怒。\p"
	.string "我要深呼吸是我自己镇定下来。$"

SevenIsland_SevaultCanyon_Text_LexIntro::
	.string "阿力：我亲爱的阿雪，一起战斗我们\n"
	.string "就能赢！$"

SevenIsland_SevaultCanyon_Text_LexDefeat::
	.string "阿力：我刚刚好像太不小心了……$"

SevenIsland_SevaultCanyon_Text_LexPostBattle::
	.string "阿力：我想这对于阿雪来说是一次好\n"
	.string "的经历。\p"
	.string "谢谢你。$"

SevenIsland_SevaultCanyon_Text_LexNotEnoughMons::
	.string "阿力：你能同时和我们两个人战斗吗\n"
	.string "？$"

SevenIsland_SevaultCanyon_Text_NyaIntro::
	.string "阿雪：我要尽我最大的努力，我不会\n"
	.string "拖我师父阿力的后腿的！$"

SevenIsland_SevaultCanyon_Text_NyaDefeat::
	.string "阿雪：噢，不……对不起，我……$"

SevenIsland_SevaultCanyon_Text_NyaPostBattle::
	.string "阿雪：我想我需要更多来自阿力的调\n"
	.string "教和指导……\p"
	.string "……所以，阿力，拜托了，我可以继\n"
	.string "续和你呆在一起吗？$"

SevenIsland_SevaultCanyon_Text_NyaNotEnoughMons::
	.string "阿雪：不好意思，我们能来一场2对\n"
	.string "2的战斗吗？$"

SevenIsland_SevaultCanyon_Text_RouteSign::
	.string "七宝溪谷前方是阿斯卡纳遗迹$"

SevenIsland_SevaultCanyon_Text_BrunoTrainedWithBrawly::
	.string "一个人单独训练当然很好。\p"
	.string "但是和一个伙伴一起到达顶峰也并不\n"
	.string "坏。\p"
	.string "甚至是希巴……他之前和一个叫做藤\n"
	.string "树的小伙子一起训练。$"
