gText_ApprenticeChallenge0::
	.string "嗯，我是{STR_VAR_1}的\n"
	.string "第{STR_VAR_2}号徒弟。\l"
	.string "抽泣……这种紧张感快压垮我了……$"

gText_ApprenticeChallenge1::
	.string "我是{STR_VAR_1}的第\n"
	.string "{STR_VAR_2}号徒弟！我\l"
	.string "们来了！$"

gText_ApprenticeChallenge2::
	.string "我是{STR_VAR_1}的第\n"
	.string "{STR_VAR_2}号徒弟！接\l"
	.string "受我的挑战吧！$"

gText_ApprenticeChallenge3::
	.string "嗯……我是{STR_VAR_1}\n"
	.string "的第{STR_VAR_2}号徒弟\l"
	.string "……你觉得像我这样的人能赢吗？$"

gText_ApprenticeChallenge4::
	.string "我是{STR_VAR_1}的第\n"
	.string "{STR_VAR_2}号徒弟！我\l"
	.string "就让你挑战我吧！$"

gText_ApprenticeChallenge5::
	.string "我忙得要命，但我碰巧也是\n"
	.string "{STR_VAR_1}的第\l"
	.string "{STR_VAR_2}号徒弟。$"

gText_ApprenticeChallenge6::
	.string "我是{STR_VAR_1}的第\n"
	.string "{STR_VAR_2}号徒弟。很\l"
	.string "高兴见到你！$"

gText_ApprenticeChallenge7::
	.string "我担任{STR_VAR_1}的第\n"
	.string "{STR_VAR_2}号徒弟。我\l"
	.string "可以开始了吗？$"

gText_ApprenticeChallenge8::
	.string "呀！我是{STR_VAR_1}的\n"
	.string "第{STR_VAR_2}号徒弟！\l"
	.string "我会尽力的！$"

gText_ApprenticeChallenge9::
	.string "哟吼！我是{STR_VAR_1}\n"
	.string "的第{STR_VAR_2}号徒弟\l"
	.string "！放马过来吧！$"

gText_ApprenticeChallenge10::
	.string "我是{STR_VAR_1}的第1\n"
	.string "000个徒弟！其实是第\l"
	.string "{STR_VAR_2}号啦！我上\l"
	.string "了！$"

gText_ApprenticeChallenge11::
	.string "没错，我是{STR_VAR_1}\n"
	.string "的第{STR_VAR_2}号徒弟\l"
	.string "！让我们摇滚起来吧！$"

gText_ApprenticeChallenge12::
	.string "哟吼哟吼！我就是人们所说的\n"
	.string "{STR_VAR_1}的第\l"
	.string "{STR_VAR_2}号徒弟！$"

gText_ApprenticeChallenge13::
	.string "咳！我是{STR_VAR_1}的\n"
	.string "第{STR_VAR_2}号徒弟。\l"
	.string "很高兴见到你！咳咳！$"

gText_ApprenticeChallenge14::
	.string "这太紧张了……我是\n"
	.string "{STR_VAR_1}的第\l"
	.string "{STR_VAR_2}号徒弟。$"

gText_ApprenticeChallenge15::
	.string "我是{STR_VAR_1}的第\n"
	.string "{STR_VAR_2}号徒弟，这\l"
	.string "可不是骗人的。$"

gText_ApprenticePleaseTeach0::
	.string "你是……{PLAYER}吗？哦！\n"
	.string "抽泣……呜咽……\p"
	.string "哦！对——对不起……我太紧张了，\n"
	.string "忍不住哭了……\p"
	.string "我是{STR_VAR_1}，我真\n"
	.string "的非常崇拜你，{PLAYER}。\p"
	.string "我……我一直梦想着有一天能见到你\n"
	.string "并向你请教关于宝可梦的事。\p"
	.string "求求你，求求你了，\n"
	.string "{PLAYER}！请务必教我关于\l"
	.string "宝可梦的知识！$"

gText_ApprenticeRejectTeaching0::
	.string "哦……可——可是……抽泣……哇啊\n"
	.string "啊啊！\p"
	.string "求你了！我求求你了，拜托！$"

gText_ApprenticeWhichLevelMode0::
	.string "哦，真的吗？你答应了？太棒了！太\n"
	.string "厉害了！嗷呜！\p"
	.string "哦……对不起……我太高兴了，又哭\n"
	.string "了……\p"
	.string "嗯……那么请告诉我！是关于对战塔\n"
	.string "的事。\p"
	.string "对我来说，Lv. 50级还是自由\n"
	.string "等级哪个更好？$"

gText_ApprenticeLevelModeThanks0::
	.string "{STR_VAR_1}？哇啊啊啊\n"
	.string "！\p"
	.string "哦！真对不起！你替我选择了级别让\n"
	.string "我很高兴，这又让我哭了……\p"
	.string "抽泣……太感谢你了！请再和我聊聊\n"
	.string "！$"

gText_ApprenticePleaseTeach1::
	.string "哇哦！你是{PLAYER}，对吧\n"
	.string "？你超强的，对吧？\p"
	.string "我是{STR_VAR_1}！我刚\n"
	.string "成为训练家！\p"
	.string "求你了，{PLAYER}！你能当\n"
	.string "我的老师，告诉我很多关于成为训练\l"
	.string "家的事吗？$"

gText_ApprenticeRejectTeaching1::
	.string "啊，为什么啊？哦，拜托？求求你了\n"
	.string "？请当我的老师吧，拜托！$"

gText_ApprenticeWhichLevelMode1::
	.string "耶！太好了！\p"
	.string "我想问你的第一件事是关于对战塔的\n"
	.string "！\p"
	.string "Lv. 50级和自由等级的房间…\n"
	.string "…哪个最适合我？$"

gText_ApprenticeLevelModeThanks1::
	.string "{STR_VAR_1}，是吧？没\n"
	.string "错！我会在那里努力的！\p"
	.string "如果我们在这里再见，请再教我点别\n"
	.string "的，老师！$"

gText_ApprenticePleaseTeach2::
	.string "嗯……你是{PLAYER}吗？我\n"
	.string "的名字是{STR_VAR_1}。\p"
	.string "我想成为一名宝可梦训练家，但我不\n"
	.string "知道该怎么办……\p"
	.string "所以我想也许可以请教你，因为你很\n"
	.string "有名。\p"
	.string "{PLAYER}，你能给我一些建\n"
	.string "议吗？$"

gText_ApprenticeRejectTeaching2::
	.string "哦，但是……\p"
	.string "我是真心想成为一名宝可梦训练家的\n"
	.string "！\p"
	.string "拜托，你能回答我的问题吗？$"

gText_ApprenticeWhichLevelMode2::
	.string "谢谢！我马上问第一个问题！\p"
	.string "对战塔有2个级别，Lv. 50级\n"
	.string "和自由等级，对吧？\p"
	.string "你觉得哪个级别更适合我？$"

gText_ApprenticeLevelModeThanks2::
	.string "哦，挑战{STR_VAR_1}？\n"
	.string "明白了！\p"
	.string "如果我有其他问题，我会回来寻求你\n"
	.string "的建议！$"

gText_ApprenticePleaseTeach3::
	.string "哦？啊？你是……不，那不可能是真\n"
	.string "的。\p"
	.string "像我这样的人不可能遇到\n"
	.string "{PLAYER}。\p"
	.string "……你真的是{PLAYER}？真\n"
	.string "不敢相信我正在和你说话！\p"
	.string "当这么好的事情发生时，我知道现在\n"
	.string "只会发生可怕的事情在我身上……\p"
	.string "……对不起……我是……\n"
	.string "{STR_VAR_1}……\p"
	.string "我没什么特别之处可以引以为豪……\p"
	.string "我甚至不应该说任何关于自己的事，\n"
	.string "因为你一定会忘记……\p"
	.string "我曾梦想着如果我能遇到你，\n"
	.string "{PLAYER}，也许我就能以训\l"
	.string "练家的身份向你寻求建议。\p"
	.string "但我觉得你不会同意那样的事。\p"
	.string "……或者你会好心地给我建议吗？$"

gText_ApprenticeRejectTeaching3::
	.string "我就知道会这样……\p"
	.string "这一定是因为我真是个无聊的小人物\n"
	.string "……\p"
	.string "但我以为也许还有机会……你不会重\n"
	.string "新考虑一下，对吧？\p"
	.string "但我不能就这样放弃。趁着我运气还\n"
	.string "在，我要问你！\p"
	.string "拜托，你能好心地给我建议吗？$"

gText_ApprenticeWhichLevelMode3::
	.string "真的吗？我不敢相信！真不敢相信你\n"
	.string "会给我建议！我……我太高兴了……\p"
	.string "我想问你的其实很琐碎，但我无法决\n"
	.string "定……\p"
	.string "在对战塔，他们让你选择Lv. 5\n"
	.string "0级或自由等级。\p"
	.string "你觉得哪个级别哪怕像我这样的人也\n"
	.string "可能有机会？$"

gText_ApprenticeLevelModeThanks3::
	.string "{STR_VAR_1}？好的！但\n"
	.string "你真的觉得像我这样的人会有机会吗\l"
	.string "？\p"
	.string "我会尽力的，尽管我不认为会成功。\p"
	.string "非常感谢你花时间陪伴像我这样的人\n"
	.string "。$"

gText_ApprenticePleaseTeach4::
	.string "哦！你是{PLAYER}\n"
	.string "{KUN}，对吧？\p"
	.string "我听说你在宝可梦方面很强！\p"
	.string "我是{STR_VAR_1}！我会\n"
	.string "成为你的朋友！\p"
	.string "你知道吗？\p"
	.string "如果你只知道训练家学校教的东西，\n"
	.string "你就无法在对战开拓区获胜。\p"
	.string "我愿意听取你的建议。你当然会同意\n"
	.string "吧？$"

gText_ApprenticeRejectTeaching4::
	.string "嗯？你为什么要拒绝我？是我在问你\n"
	.string "啊！你必须重新考虑！$"

gText_ApprenticeWhichLevelMode4::
	.string "好的，所以有件事。我想让你替我决\n"
	.string "定。\p"
	.string "你知道对战塔有Lv. 50级和自\n"
	.string "由等级的房间吧？\p"
	.string "你觉得哪个会适合我，\n"
	.string "{PLAYER}{KUN}？$"

gText_ApprenticeLevelModeThanks4::
	.string "好的，{STR_VAR_1}适合\n"
	.string "我？谢谢你！\p"
	.string "知道是你做的决定，\n"
	.string "{PLAYER}{KUN}，就算\l"
	.string "我输了也不会那么难过。\p"
	.string "好的，我会再来向你寻求建议。再见\n"
	.string "！$"

gText_ApprenticePleaseTeach5::
	.string "哦，嗨，你好！{PLAYER}\n"
	.string "{KUN}！我认识你，因为你很有\l"
	.string "名！叫我{STR_VAR_1}！\l"
	.string "很高兴见到你！\p"
	.string "我是个铁人三项选手，所以我即使在\n"
	.string "培育宝可梦时也保持健康。\p"
	.string "我还参与其他事情，比如工作、打盹\n"
	.string "、交谊舞……\p"
	.string "这么忙，对我来说要成为一个像样的\n"
	.string "训练家可不容易。\p"
	.string "所以，我有个提议！\p"
	.string "我们相遇一定有原因。所以，\n"
	.string "{PLAYER}{KUN}，不如\l"
	.string "你偶尔和我分享你的智慧？$"

gText_ApprenticeRejectTeaching5::
	.string "哦，但是，拜托？像我这样的人需要\n"
	.string "你这样的人，{PLAYER}\l"
	.string "{KUN}！\p"
	.string "老实说，我需要你的建议！$"

gText_ApprenticeWhichLevelMode5::
	.string "谢谢你！这才对嘛！那么，我们从一\n"
	.string "个简单的问题开始！\p"
	.string "你知道对战塔的2个级别，对吧？就\n"
	.string "是Lv. 50级和自由等级。\p"
	.string "像我这样的大忙人，应该为哪个做准\n"
	.string "备？$"

gText_ApprenticeLevelModeThanks5::
	.string "{STR_VAR_1}，是吧？好\n"
	.string "的，明白了。我会想办法找时间试试\l"
	.string "看的！\p"
	.string "……哎呀，我得去上班了！谢谢！回\n"
	.string "头见！$"

gText_ApprenticePleaseTeach6::
	.string "不可能！呃——呃！你该不会是真正\n"
	.string "的{PLAYER}吧？\p"
	.string "啊哈！太棒了！我是\n"
	.string "{STR_VAR_1}，很高兴见\l"
	.string "到你！\p"
	.string "{PLAYER}，你很强，对吧？\p"
	.string "大家都在谈论你！\p"
	.string "哦！我刚刚有个超棒的主意！我要向\n"
	.string "你请教，{PLAYER}！我相信\l"
	.string "这能让我变强！\p"
	.string "这不是个好主意吗？拜托，我想要你\n"
	.string "的建议！$"

gText_ApprenticeRejectTeaching6::
	.string "啊哈哈哈，你可以假装很凶，但你骗\n"
	.string "不了我！你其实是答应的意思，对吧\l"
	.string "？$"

gText_ApprenticeWhichLevelMode6::
	.string "耶！我就知道你心胸宽广，\n"
	.string "{PLAYER}！\p"
	.string "我该先问你什么呢？……哦，我想到\n"
	.string "了！\p"
	.string "请鼓掌！我的问题是……\p"
	.string "如果我要挑战对战塔，我该走哪条路\n"
	.string "？\p"
	.string "Lv. 50级还是自由等级？哪个\n"
	.string "更适合我？$"

gText_ApprenticeLevelModeThanks6::
	.string "哦——哦——哦！\n"
	.string "{STR_VAR_1}，你说！谢\l"
	.string "谢你超级酷的回答！\p"
	.string "我想今天要问你的就这些了。\p"
	.string "让我们在这里再见，好吗？谢谢！$"

gText_ApprenticePleaseTeach7::
	.string "打扰一下，请问……你是\n"
	.string "{PLAYER}吗？\p"
	.string "我是{STR_VAR_1}，很高\n"
	.string "兴认识你。\p"
	.string "我仰慕你很久了……\p"
	.string "…… … … … … …\p"
	.string "嗯……希望你觉得这个请求不会太麻\n"
	.string "烦，但是……\p"
	.string "我可以成为你的徒弟吗，\n"
	.string "{PLAYER}？$"

gText_ApprenticeRejectTeaching7::
	.string "哦……！\p"
	.string "…… … … … … …\n"
	.string "… … … … … …\p"
	.string "……我一定是震惊得晕过去了。对不\n"
	.string "起，我一定是听错了。\p"
	.string "拜托！请说你愿意收我为徒！$"

gText_ApprenticeWhichLevelMode7::
	.string "哦……我很高兴！\p"
	.string "我不想浪费你的时间，所以请在这件\n"
	.string "事上给我建议。\p"
	.string "我计划不久后参加对战塔挑战。\p"
	.string "但是，有2个级别……\p"
	.string "哪个最适合我？Lv. 50级还是\n"
	.string "自由等级？$"

gText_ApprenticeLevelModeThanks7::
	.string "你选择的是{STR_VAR_1}\n"
	.string "啊！我明白了，我会全力以赴的！\p"
	.string "谢谢你，{PLAYER}。以后也\n"
	.string "要拜托你指点哦。请多保重！$"

gText_ApprenticePleaseTeach8::
	.string "呀！呀！{PLAYER}！你居然\n"
	.string "主动跟我说话了！我……我\l"
	.string "太高兴了！\p"
	.string "我！我的名字叫\n"
	.string "{STR_VAR_1}！是刚刚成\l"
	.string "为训练家的新人！\p"
	.string "能见到你真是太荣幸了，\n"
	.string "{PLAYER}，你可是宝可梦界\l"
	.string "的大名人啊！\p"
	.string "啊、啊、对了！{PLAYER}，\n"
	.string "我能求你一个大忙吗？\p"
	.string "请收我为徒吧！我想向你学习！$"

gText_ApprenticeRejectTeaching8::
	.string "哇啊啊！{PLAYER}拒绝了我\n"
	.string "……这……这是宝贵的经验！\p"
	.string "{PLAYER}，拜托！这次我想\n"
	.string "听到肯定的回答！\p"
	.string "我恳求你的指导！$"

gText_ApprenticeWhichLevelMode8::
	.string "咿耶！{PLAYER}说好！\n"
	.string "{PLAYER}说好！\p"
	.string "我今晚会睡不着觉了……太感谢你了\n"
	.string "！\p"
	.string "那么，这是我的问题！\p"
	.string "在对战塔，什么适合我，Lv. 5\n"
	.string "0级还是自由等级？$"

gText_ApprenticeLevelModeThanks8::
	.string "{STR_VAR_1}！完全明白\n"
	.string "了！我完全明白！我高兴得要发狂了\l"
	.string "！\p"
	.string "希望下次你愿意再教我一些东西。$"

gText_ApprenticePleaseTeach9::
	.string "哇！你该不会是……难道是……\n"
	.string "{PLAYER}{KUN}？！那\l"
	.string "个强大又著名的训练家？你好，我简\l"
	.string "直太幸运了！\p"
	.string "你好，我叫{STR_VAR_1}\n"
	.string "！\p"
	.string "我一直在寻找一位宝可梦老师。\p"
	.string "而你来得正是时候，\n"
	.string "{PLAYER}{KUN}！\p"
	.string "所以，就是这样，{PLAYER}\n"
	.string "{KUN}！让我拜你为师吧！$"

gText_ApprenticeRejectTeaching9::
	.string "呱啊啊啊！你真是又酷又硬派……\p"
	.string "别这样，拜托。我是在请求你！$"

gText_ApprenticeWhichLevelMode9::
	.string "哦，耶！这是坚定的回答！太棒了，\n"
	.string "我得说！\p"
	.string "那么，对战塔的第一个建议怎么样？\p"
	.string "如果我要去，哪个更好？Lv. 5\n"
	.string "0级还是自由等级？$"

gText_ApprenticeLevelModeThanks9::
	.string "嗯哼，{STR_VAR_1}是吧\n"
	.string "！好，A——OK！我会去展示我的\l"
	.string "实力，就像，酷炫！\p"
	.string "好的，我会把你当作我的导师！再见\n"
	.string "！$"

gText_ApprenticePleaseTeach10::
	.string "哎呀，这不是{PLAYER}\n"
	.string "{KUN}吗？警察刚刚在到处找你\l"
	.string "呢！\p"
	.string "……骗你的啦\n"
	.string "！\p"
	.string "我叫{STR_VAR_1}。别看\n"
	.string "我长这样，我可是宝可梦冠军！..\l"
	.string "……这也是骗你的！\p"
	.string "不过接下来这句可不是谎话。其实我\n"
	.string "不太擅长宝可梦对战。\p"
	.string "所以，你能收我为徒，教教我关于宝\n"
	.string "可梦的一切吗？$"

gText_ApprenticeRejectTeaching10::
	.string "如果你要表现得这么冷淡，我就让你\n"
	.string "看看我会做什么！\p"
	.string "哇！哇！哇！嗝！\p"
	.string "哈哈哈，那是我装的眼泪！\p"
	.string "来吧，拜托你当我的宝可梦师父好吗\n"
	.string "？$"

gText_ApprenticeWhichLevelMode10::
	.string "耶比！我会给你买艘船！\p"
	.string "当然我又在撒谎！但是……谢谢你，\n"
	.string "师父！\p"
	.string "你知道对战塔有Lv. 50级和自\n"
	.string "由等级吧？\p"
	.string "我正纠结该挑战哪个级别……\p"
	.string "师父你能替我决定吗？$"

gText_ApprenticeLevelModeThanks10::
	.string "好嘞，那就选\n"
	.string "{STR_VAR_1}吧！那我这\l"
	.string "就去挑战另一个级别！\p"
	.string "开玩笑的啦！师父，我绝对听从您的\n"
	.string "教诲！\p"
	.string "多谢师父！以后也请您多多指教啦！$"

gText_ApprenticePleaseTeach11::
	.string "喂--嗬！“喂嗬”就是“嗨”，水\n"
	.string "手向你打招呼！\p"
	.string "我是{STR_VAR_1}，唱着\n"
	.string "说唱的水手就是我本人！\p"
	.string "现在轮到你了，快来做个自我介绍\n"
	.string "吧！\p"
	.string "嗯哼！嗯哼！{PLAYER}\n"
	.string "{KUN}是你的大名，宝可梦是你\l"
	.string "的拿手好戏！\p"
	.string "你正处在闪闪发光的年纪，整个世界\n"
	.string "都是你的舞台！\p"
	.string "总之，我只是想告诉你，你是我今天\n"
	.string "搭话的第十个训练家！\p"
	.string "不如我们好好庆祝一番！你就收我为\n"
	.string "徒作为纪念吧！$"

gText_ApprenticeRejectTeaching11::
	.string "但是！你必须配合我！\p"
	.string "别这么逗我了！请当我的导师吧！$"

gText_ApprenticeWhichLevelMode11::
	.string "就这样！{PLAYER}，你有这\n"
	.string "个精神！\p"
	.string "所以这是我的第一个问题，需要你的\n"
	.string "建议！\p"
	.string "是关于对战塔的，这取决于我的实力\n"
	.string "！\p"
	.string "那里有Lv. 50级和自由等级，\n"
	.string "哪个才是我该选的级别？$"

gText_ApprenticeLevelModeThanks11::
	.string "好的，{STR_VAR_1}，你\n"
	.string "说！我会去的，就在路上！\p"
	.string "如果我需要建议，{PLAYER}\n"
	.string "，你的话我永远听从！$"

gText_ApprenticePleaseTeach12::
	.string "喂喂喂，你不就是{PLAYER}\n"
	.string "吗？我该怎么做？跟你搭话？有什么\l"
	.string "不行，反正我已经在跟你说了！\p"
	.string "{PLAYER}，你觉得很惊讶吗\n"
	.string "？还是先让你知道我何许人也吧！\p"
	.string "你可以叫我{STR_VAR_1}\n"
	.string "。吉他界最耀眼的一颗新星，那就是\l"
	.string "我！\p"
	.string "你能听懂我的电波吗？你一定接收到\n"
	.string "了对吧！\p"
	.string "我今天手气正顺，不如就向你提个请\n"
	.string "求！\p"
	.string "{PLAYER}，收我做你的小弟\n"
	.string "吧！把你的本事全都传授给我吧！$"

gText_ApprenticeRejectTeaching12::
	.string "这么说，你是要拒绝我吗？那我只好\n"
	.string "再求你一次了！\p"
	.string "{PLAYER}，求你收我做小弟\n"
	.string "吧！我想要你把一切都教给我！$"

gText_ApprenticeWhichLevelMode12::
	.string "幸运，耶，呜呼！我该问你个问题吗\n"
	.string "？\p"
	.string "既然我们在对战塔附近，不如问个关\n"
	.string "于它实力的问题？\p"
	.string "在你能看到的选择中，哪个才是我该\n"
	.string "选的？$"

gText_ApprenticeLevelModeThanks12::
	.string "如果{STR_VAR_1}是你建\n"
	.string "议的，那它一定是最棒的！\p"
	.string "嗯，{PLAYER}，我必须自由\n"
	.string "漫游，但你别忘了我。\p"
	.string "再见了，我聪明的朋友！$"

gText_ApprenticePleaseTeach13::
	.string "啊，你好！那边那位！能帮我捏捏肩\n"
	.string "膀吗？\p"
	.string "……对，就是那里！就是那\n"
	.string "样！哎哟，痛痛痛！呼……\l"
	.string "真舒服啊！\p"
	.string "我叫{STR_VAR_1}。我本\n"
	.string "来在练空手道，但我的身体底子实在\l"
	.string "经不起那种折腾……\p"
	.string "所以我想通过宝可梦对战来锻炼自己\n"
	.string "的体魄。\p"
	.string "你是{PLAYER}{KUN}对\n"
	.string "吧？是宝可梦联盟的冠军吧？\p"
	.string "那个，你能给我一些指点吗？$"

gText_ApprenticeRejectTeaching13::
	.string "哎，为什么啊？\p"
	.string "我保证绝不会给你添麻烦的！求求你\n"
	.string "了，好不好嘛？$"

gText_ApprenticeWhichLevelMode13::
	.string "谢谢你。你真是太好了！……咳！咳\n"
	.string "！\p"
	.string "呃，我得快点变强……\p"
	.string "我马上就去对战塔，但对我来说哪个\n"
	.string "更好？Lv. 50级还是自由等级\l"
	.string "？$"

gText_ApprenticeLevelModeThanks13::
	.string "嗯，好的。那就是\n"
	.string "{STR_VAR_1}了。我这就\l"
	.string "去那里。\p"
	.string "希望以后还能向你请教--毕竟你可\n"
	.string "是我的师父啊！$"

gText_ApprenticePleaseTeach14::
	.string "那个……请问……\n"
	.string "是{PLAYER}{KUN}..\l"
	.string "……吗？\p"
	.string "请、请不要那样看着我。搞得我特别\n"
	.string "不自在……\p"
	.string "我……我是\n"
	.string "{STR_VAR_1}。\p"
	.string "说出来挺不好意思的，我平时在到处\n"
	.string "调查古代遗迹……\p"
	.string "更不好意思的是，其实我对对战开拓\n"
	.string "区也很感兴趣。\p"
	.string "{PLAYER}{KUN}，大家\n"
	.string "都说你是一位非常厉害的训练家..\l"
	.string "....\p"
	.string "虽然有些难以启齿，但我有个不情之\n"
	.string "请。\p"
	.string "你能成为我的师父，给我一些指导吗\n"
	.string "？$"

gText_ApprenticeRejectTeaching14::
	.string "求求你别这么不理我！被拒绝的羞耻\n"
	.string "感会让我活不下去的……\p"
	.string "请务必成为我的师父！我需要你的指\n"
	.string "点！$"

gText_ApprenticeWhichLevelMode14::
	.string "太、太感谢你了……\p"
	.string "但请不要那样直勾勾地看着我。我会\n"
	.string "慌乱得手足无措的。\p"
	.string "请不要看着我的眼睛回答我。\p"
	.string "在对战巨塔里……我应该挑\n"
	.string "战哪种级别呢？$"

gText_ApprenticeLevelModeThanks14::
	.string "啊……好的！那我就去挑战\n"
	.string "看看。\p"
	.string "希望我能鼓起勇气英勇应战，不会慌\n"
	.string "乱成一团……\p"
	.string "谢谢你，{PLAYER}\n"
	.string "{KUN}。如果我们再见面的话，\l"
	.string "希望还能得到你的指点。$"

gText_ApprenticePleaseTeach15::
	.string "嗯？你看上去像是{PLAYER}\n"
	.string "{KUN}……但你真的是\l"
	.string "本人吗？\p"
	.string "你可以称呼我为\n"
	.string "{STR_VAR_1}。\p"
	.string "我最近一直在考虑，拜一位强大的训\n"
	.string "练家为师。\p"
	.string "所以能遇上你，可真算得上是幸运！\n"
	.string "……你确实是\l"
	.string "{PLAYER}{KUN}没错吧\l"
	.string "？\p"
	.string "不，不，如果你是本人的话就好办了\n"
	.string "。我只是希望你能收我做徒弟。$"

gText_ApprenticeRejectTeaching15::
	.string "哦？究竟是什么理由促使你拒绝我？\p"
	.string "怀疑你的身份，确实是我的失礼。\p"
	.string "请接受我的歉意，并正式收我为徒吧\n"
	.string "。$"

gText_ApprenticeWhichLevelMode15::
	.string "你真的愿意收我为徒吗？我可不想高\n"
	.string "兴得太早。\p"
	.string "如果是真的，那我向刚才的失礼道歉\n"
	.string "。不过现在，我需要你的建议。\p"
	.string "如果我要挑战对战巨塔，哪种级别才\n"
	.string "配得上我的水准？是50级，还是公\l"
	.string "开级？$"

gText_ApprenticeLevelModeThanks15::
	.string "{STR_VAR_1}吗？你确定\n"
	.string "吗？\p"
	.string "原来如此。既然如此，那就这样吧。\n"
	.string "感谢你抽出时间指导我。\p"
	.string "我知道自己有时有些烦人，但你能接\n"
	.string "纳我，实在令我欣喜。\p"
	.string "那么，我们后会有期！$"

gText_ApprenticeWhatHeldItem0::
	.string "唉……呜呜……啊\n"
	.string "，{PLAYER}！\p"
	.string "我陷入了一个两难的困境，实在拿不\n"
	.string "定主意。\p"
	.string "我决定不好到底该给我的\n"
	.string "{STR_VAR_1}携带什么道\l"
	.string "具。\p"
	.string "请告诉我吧，{PLAYER}。我\n"
	.string "该让它携带什么道具才好？$"

gText_ApprenticeHoldNothing0::
	.string "哦，真的吗？我不该让我的\n"
	.string "{STR_VAR_1}携带任何东\l"
	.string "西？$"

gText_ApprenticeThanksNoHeldItem0::
	.string "哦，好的！很高兴问题解决了！太棒\n"
	.string "了！太厉害了！嗷呜！\p"
	.string "非常感谢你！$"

gText_ApprenticeThanksHeldItem0::
	.string "哦，我太高兴了……我想我也有\n"
	.string "{STR_VAR_1}呢。\p"
	.string "很高兴问题解决了！太棒了！太厉害\n"
	.string "了！嗷呜！\p"
	.string "非常感谢你！$"

gText_ApprenticeItemAlreadyRecommended0::
	.string "哇哇哇！请不要这么刻薄！\p"
	.string "道具{STR_VAR_1}之前已\n"
	.string "经有人推荐过了，呜咽……\p"
	.string "或者你是说我不该让我的\n"
	.string "{STR_VAR_2}携带任何东\l"
	.string "西？$"

gText_ApprenticeWhatHeldItem1::
	.string "耶！是{PLAYER}！太好了！\n"
	.string "我想问你点事！\p"
	.string "你会让宝可梦携带道具吗？我也想让\n"
	.string "我宝可梦携带，但是……\p"
	.string "什么道具适合\n"
	.string "{STR_VAR_1}携带呢？\p"
	.string "你觉得呢？$"

gText_ApprenticeHoldNothing1::
	.string "嗯？你是说我的\n"
	.string "{STR_VAR_1}不用携带任\l"
	.string "何东西？$"

gText_ApprenticeThanksNoHeldItem1::
	.string "哦，明白了！我会照做的！谢谢你教\n"
	.string "我！$"

gText_ApprenticeThanksHeldItem1::
	.string "哦，哇！{STR_VAR_1}，\n"
	.string "是吧？好的，我会用那个！\p"
	.string "谢谢你教我！$"

gText_ApprenticeItemAlreadyRecommended1::
	.string "啊，呃，不，我不是那个意思。我想\n"
	.string "知道一些我还没见过的新道具的情报\l"
	.string "。\p"
	.string "还是说，你的意思是这次我的宝可梦\n"
	.string "什么道具都不用带？$"

gText_ApprenticeWhatHeldItem2::
	.string "{PLAYER}，你好！是关于我\n"
	.string "的{STR_VAR_1}……\p"
	.string "我想让它携带个好道具。什么适合它\n"
	.string "呢？$"

gText_ApprenticeHoldNothing2::
	.string "哦，那我的{STR_VAR_1}\n"
	.string "不需要携带任何东西？$"

gText_ApprenticeThanksNoHeldItem2::
	.string "好的，明白了！下次见！$"

gText_ApprenticeThanksHeldItem2::
	.string "哦，道具{STR_VAR_1}？\n"
	.string "明白了！\p"
	.string "我会尽力找一个的！下次见！$"

gText_ApprenticeItemAlreadyRecommended2::
	.string "有人已经教过我关于\n"
	.string "{STR_VAR_1}的事了。\p"
	.string "我想要我的宝可梦携带不同类型的道\n"
	.string "具。\p"
	.string "或者你觉得{STR_VAR_2}\n"
	.string "不需要携带任何东西？$"

gText_ApprenticeWhatHeldItem3::
	.string "你好，{PLAYER}……很抱歉\n"
	.string "打扰你，但我还有件事想问。\p"
	.string "我觉得自己不够强，无法独自赢比赛\n"
	.string "，所以想让我的\l"
	.string "{STR_VAR_1}携带道具。\p"
	.string "但不知道什么才好。\p"
	.string "{PLAYER}，拜托，你能替我\n"
	.string "决定吗？$"

gText_ApprenticeHoldNothing3::
	.string "像我这样的人的宝可梦不带道具更好\n"
	.string "？$"

gText_ApprenticeThanksNoHeldItem3::
	.string "我明白了……你是说我不该依赖道具\n"
	.string "。我会尽力不依赖的！\p"
	.string "非常感谢你！$"

gText_ApprenticeThanksHeldItem3::
	.string "道具{STR_VAR_1}，好的\n"
	.string "。我不确定能不能弄到一个……不！\l"
	.string "我会尽力搞到的。\p"
	.string "非常感谢你！$"

gText_ApprenticeItemAlreadyRecommended3::
	.string "哦，但是……我想我以前听说过……\p"
	.string "是不是因为我没用好道具\n"
	.string "{STR_VAR_1}？\p"
	.string "或者你是说我不该让我的\n"
	.string "{STR_VAR_2}携带任何东\l"
	.string "西？$"

gText_ApprenticeWhatHeldItem4::
	.string "哦，{PLAYER}{KUN}。\n"
	.string "有件事我想问你。\p"
	.string "你知道你之前决定了我该用哪只宝可\n"
	.string "梦吧？\p"
	.string "但我没问你它该携带什么道具。\p"
	.string "既然你已经给了我建议，不如有始有\n"
	.string "终？\p"
	.string "什么比较好？我想让我的\n"
	.string "{STR_VAR_1}带点东西。$"

gText_ApprenticeHoldNothing4::
	.string "哦！所以我的\n"
	.string "{STR_VAR_1}应该空手上\l"
	.string "阵做到最好？$"

gText_ApprenticeThanksNoHeldItem4::
	.string "如果你觉得这样最好，我会照做。\p"
	.string "知道是你做的决定，\n"
	.string "{PLAYER}{KUN}，就算\l"
	.string "我输了也不会太难过。\p"
	.string "好的，我会再来向你请教。再见！$"

gText_ApprenticeThanksHeldItem4::
	.string "道具{STR_VAR_1}，是吧\n"
	.string "？不错。我会用的！\p"
	.string "知道是你做的决定，\n"
	.string "{PLAYER}{KUN}，就算\l"
	.string "我输了也不会太难过。\p"
	.string "好的，我会再来向你请教。再见！$"

gText_ApprenticeItemAlreadyRecommended4::
	.string "嗯？你在说什么？你之前已经告诉过\n"
	.string "{STR_VAR_1}的事了。\p"
	.string "或者你是说我的\n"
	.string "{STR_VAR_2}应该空手上\l"
	.string "阵做到最好？$"

gText_ApprenticeWhatHeldItem5::
	.string "哟，{PLAYER}{KUN}！\p"
	.string "虽然咱俩都挺忙的，但似乎总能碰上\n"
	.string "面呢！\p"
	.string "我今天得去散散步，打扫打扫，再给\n"
	.string "宝可梦刷刷毛。\p"
	.string "我都还没腾出时间给我心爱的\n"
	.string "{STR_VAR_1}买点什么东\l"
	.string "西呢。\p"
	.string "我实在没时间想了，不如你给我点建\n"
	.string "议，我该让我可爱的\l"
	.string "{STR_VAR_1}携带什么道\l"
	.string "具好呢？$"

gText_ApprenticeHoldNothing5::
	.string "哦，所以像我这样的大忙人，你说我\n"
	.string "的{STR_VAR_1}不需要任\l"
	.string "何东西？$"

gText_ApprenticeThanksNoHeldItem5::
	.string "好的，知道了。我不需要为此花时间\n"
	.string "。\p"
	.string "今天谢谢了！回头见！$"

gText_ApprenticeThanksHeldItem5::
	.string "好的，知道了。我会想办法找时间找\n"
	.string "到你推荐的{STR_VAR_1}\l"
	.string "。\p"
	.string "我很高兴遇到你这样的好导师。谢谢\n"
	.string "！回头见！$"

gText_ApprenticeItemAlreadyRecommended5::
	.string "嗯？我已经知道那个\n"
	.string "{STR_VAR_1}了。\p"
	.string "哦，对了，我懂了。所以像我这样的\n"
	.string "大忙人，你说我的\l"
	.string "{STR_VAR_2}不需要任何\l"
	.string "东西？$"

gText_ApprenticeWhatHeldItem6::
	.string "嗨，{PLAYER}！是我啦！今\n"
	.string "天又得借用一下你的聪明才智了。拜\l"
	.string "托，给我点建议吧！\p"
	.string "请奏擂鼓，当当当！我的问题就是。\n"
	.string ".....\p"
	.string "如果我想让我的\n"
	.string "{STR_VAR_1}携带道具的\l"
	.string "话，带什么最好？$"

gText_ApprenticeHoldNothing6::
	.string "是吗？你是说我的\n"
	.string "{STR_VAR_1}不需要携带\l"
	.string "道具？$"

gText_ApprenticeThanksNoHeldItem6::
	.string "好的，我会照做的！\p"
	.string "我想今天要问的就这些了。\p"
	.string "让我们在这里再见，好吗？谢谢！$"

gText_ApprenticeThanksHeldItem6::
	.string "嗯哼！{STR_VAR_1}。多\n"
	.string "酷的选择！我一定会试试的！\p"
	.string "我想今天要问的就这些了。\p"
	.string "让我们在这里再见，好吗？谢谢！$"

gText_ApprenticeItemAlreadyRecommended6::
	.string "啊哈哈！真傻！你之前已经告诉过\n"
	.string "{STR_VAR_1}的事了！\p"
	.string "你还好吗，{PLAYER}？\p"
	.string "哦，等等！你是说我的\n"
	.string "{STR_VAR_2}不需要携带\l"
	.string "任何道具？$"

gText_ApprenticeWhatHeldItem7::
	.string "你好，{PLAYER}。希望你一\n"
	.string "切安好。\p"
	.string "我可以请教你吗？\p"
	.string "最近一次对战中，对手似乎让他的宝\n"
	.string "可梦携带了道具。\p"
	.string "结果，我被打败了……\p"
	.string "我不想落后。我也想让我\n"
	.string "{STR_VAR_1}携带道具。\p"
	.string "如果你能决定什么适合我的宝可梦就\n"
	.string "太好了……$"

gText_ApprenticeHoldNothing7::
	.string "换句话说……我的宝可梦不需要携带\n"
	.string "道具？$"

gText_ApprenticeThanksNoHeldItem7::
	.string "这下我彻底明白了！我会按照这个方\n"
	.string "向继续努力的。\p"
	.string "谢谢你，{PLAYER}。希望下\n"
	.string "次还能向你请教。请多保重！$"

gText_ApprenticeThanksHeldItem7::
	.string "那就选{STR_VAR_1}了！\n"
	.string "我这就去订购一个。\p"
	.string "谢谢你，{PLAYER}。希望下\n"
	.string "次还能向你请教。请多保重！$"

gText_ApprenticeItemAlreadyRecommended7::
	.string "你已经告诉过我了，而且我已经有了\n"
	.string "。\p"
	.string "或者你是说……我的宝可梦不需要携\n"
	.string "带道具？$"

gText_ApprenticeWhatHeldItem8::
	.string "呀！{PLAYER}！我……又见\n"
	.string "到你我太高兴了！\p"
	.string "哦——哦——哦！有件事我一定要问\n"
	.string "你，{PLAYER}！\p"
	.string "请决定我的{STR_VAR_1}\n"
	.string "该携带什么！$"

gText_ApprenticeHoldNothing8::
	.string "哦，哇！我没想到这个回答！所以，\n"
	.string "携带道具不是必须的？$"

gText_ApprenticeThanksNoHeldItem8::
	.string "完全明白了！我会继续不用道具努力\n"
	.string "的！\p"
	.string "希望下次你愿意再教我些东西。$"

gText_ApprenticeThanksHeldItem8::
	.string "{STR_VAR_1}！就用这个\n"
	.string "了！\p"
	.string "那个……难道说，\n"
	.string "{PLAYER}你也给自己的宝可\l"
	.string "梦带这个道具吗？\p"
	.string "我一定会把它弄到手的！希望下次你\n"
	.string "还能多指教指教我。$"

gText_ApprenticeItemAlreadyRecommended8::
	.string "哦？你之前也推荐过\n"
	.string "{STR_VAR_1}。\p"
	.string "或者这是最好的携带物？还是说我的\n"
	.string "{STR_VAR_2}不需要携带\l"
	.string "任何东西？$"

gText_ApprenticeWhatHeldItem9::
	.string "你好呀！我的大师，\n"
	.string "{PLAYER}{KUN}！\p"
	.string "我想向你请教一下关于宝可梦携带道\n"
	.string "具的问题。\p"
	.string "你觉得让我的\n"
	.string "{STR_VAR_1}带什么道具\l"
	.string "好呢？\p"
	.string "别害羞嘛。尽管脱口而出吧！$"

gText_ApprenticeHoldNothing9::
	.string "哦？所以你是说我的\n"
	.string "{STR_VAR_1}不携带道具\l"
	.string "也能赢？$"

gText_ApprenticeThanksNoHeldItem9::
	.string "好的，行！我会尽力而为，就像，猛\n"
	.string "击！\p"
	.string "好了，一如既往地感谢！再见！$"

gText_ApprenticeThanksHeldItem9::
	.string "嗯哼，{STR_VAR_1}？好\n"
	.string "的，行！我会去找一个，就像，砰！\p"
	.string "好了，一如既往地感谢！再见！$"

gText_ApprenticeItemAlreadyRecommended9::
	.string "不，不！你之前已经告诉过我\n"
	.string "{STR_VAR_1}的事了。\p"
	.string "哦，现在等等……所以你是说我的\n"
	.string "{STR_VAR_2}不携带道具\l"
	.string "也能赢？$"

gText_ApprenticeWhatHeldItem10::
	.string "{PLAYER}{KUN}，发生\n"
	.string "了件不可思议的事！\p"
	.string "我今天早上醒来，发现我的宝可梦居\n"
	.string "然抱着10个金珠！\p"
	.string "骗你的啦！哇哈哈哈哈！\p"
	.string "不过接下来这句可不是骗你的。我实\n"
	.string "在不擅长琢磨宝可梦该携带什么道具\l"
	.string "。\p"
	.string "所以师父，就由您来替我决定让\n"
	.string "{STR_VAR_1}携带什么道\l"
	.string "具好吗？$"

gText_ApprenticeHoldNothing10::
	.string "那是什么意思？不让它带任何东西？$"

gText_ApprenticeThanksNoHeldItem10::
	.string "好的，所以是什么都不用带对吧。那\n"
	.string "我可得赶紧给它带点什么！\p"
	.string "开玩笑的啦！师父，我绝对听您的教\n"
	.string "导！\p"
	.string "多谢师父！以后也要继续指导我哦！$"

gText_ApprenticeThanksHeldItem10::
	.string "好的，带一个\n"
	.string "{STR_VAR_1}对吧！除了\l"
	.string "这个我什么都给它带！\p"
	.string "开玩笑的啦！师父，我绝对听您的教\n"
	.string "导！\p"
	.string "多谢师父！以后也要继续指导我哦！$"

gText_ApprenticeItemAlreadyRecommended10::
	.string "嗯，你之前告诉过我了，对吧？\p"
	.string "没有别的东西了吗？\p"
	.string "或者你是说，不让我的\n"
	.string "{STR_VAR_2}携带任何东\l"
	.string "西？$"

gText_ApprenticeWhatHeldItem11::
	.string "A——H——O——Y！拼出来就是\n"
	.string "Ahoy，嗨！\p"
	.string "说唱水手就是我！向你提个超酷的问\n"
	.string "题！\p"
	.string "这是个道具问题需要你的建议！\p"
	.string "我的{STR_VAR_1}需要携\n"
	.string "带道具，该带什么好，请告诉我！$"

gText_ApprenticeHoldNothing11::
	.string "是吗？我的{STR_VAR_1}\n"
	.string "不需要携带任何东西？$"

gText_ApprenticeThanksNoHeldItem11::
	.string "好的，我听到了，当然！我的宝可梦\n"
	.string "也会空手上阵！\p"
	.string "如果我需要建议，{PLAYER}\n"
	.string "，你的话我永远听从！$"

gText_ApprenticeThanksHeldItem11::
	.string "好的，{STR_VAR_1}，那\n"
	.string "就是我要用的。让你选是对的！\p"
	.string "如果我需要建议，{PLAYER}\n"
	.string "，你的话我永远听从！$"

gText_ApprenticeItemAlreadyRecommended11::
	.string "好的，{STR_VAR_1}，你\n"
	.string "说？你之前告诉过我了。我需要新点\l"
	.string "子，全新的方式。\p"
	.string "或者，什么，是吗？我的宝可梦不需\n"
	.string "要携带任何东西？$"

gText_ApprenticeWhatHeldItem12::
	.string "哟，喂，{PLAYER}！今天又\n"
	.string "让我遇上你了！\p"
	.string "该怎么办呢？向你讨教一下？有何不\n"
	.string "可！反正话都说上了！\p"
	.string "{PLAYER}，你不会嫌我烦了\n"
	.string "吧？哎呀，不可能，绝不可能。\p"
	.string "能听我把话说完吗？我就是想请教点\n"
	.string "建议--正经事。\p"
	.string "关于我的{STR_VAR_1}带\n"
	.string "什么携带物品比较合适，我都纠结得\l"
	.string "愁眉苦脸了。$"

gText_ApprenticeHoldNothing12::
	.string "我的{STR_VAR_1}什么都\n"
	.string "不需要？不需要携带任何东西？$"

gText_ApprenticeThanksNoHeldItem12::
	.string "如果什么都不带是最好的，我会照你\n"
	.string "说的做！\p"
	.string "嗯，{PLAYER}，我必须自由\n"
	.string "漫游，但别忘了我。\p"
	.string "再见，我聪明的朋友！$"

gText_ApprenticeThanksHeldItem12::
	.string "如果携带{STR_VAR_1}是\n"
	.string "最好的，我会照你说的做！\p"
	.string "嗯，{PLAYER}，我必须自由\n"
	.string "漫游，但别忘了我。\p"
	.string "再见，我聪明的朋友！$"

gText_ApprenticeItemAlreadyRecommended12::
	.string "我没听说过那个\n"
	.string "{STR_VAR_1}吗？我肯定\l"
	.string "听说过，那是肯定的！\p"
	.string "我需要新东西！或者我的\n"
	.string "{STR_VAR_2}什么都不需\l"
	.string "要？不需要携带任何东西？$"

gText_ApprenticeWhatHeldItem13::
	.string "嘎！哎哟！{PLAYER}\n"
	.string "{KUN}，我的手臂断了！别碰它\l"
	.string "，拜托！\p"
	.string "一定是我在尝试不同道具和我的宝可\n"
	.string "梦伙伴们时弄断的。\p"
	.string "所以，事已至此，我需要你替我决定\n"
	.string "。\p"
	.string "{PLAYER}{KUN}，你觉\n"
	.string "得我的{STR_VAR_1}携带\l"
	.string "什么好？$"

gText_ApprenticeHoldNothing13::
	.string "哎哟……\p"
	.string "所以你的建议是我的\n"
	.string "{STR_VAR_1}不需要携带\l"
	.string "任何东西？$"

gText_ApprenticeThanksNoHeldItem13::
	.string "嗯，好的。以我现在的情况，那样更\n"
	.string "容易。\p"
	.string "我希望我能继续这样向你求助。$"

gText_ApprenticeThanksHeldItem13::
	.string "嗯，好嘞。那就带一个\n"
	.string "{STR_VAR_1}。我的宝可\l"
	.string "梦手脚利索着呢，这就让它拿上。\p"
	.string "希望以后还能像这样向你求助啊。$"

gText_ApprenticeItemAlreadyRecommended13::
	.string "不对不对，你上次就提过\n"
	.string "{STR_VAR_1}了，忘了吗\l"
	.string "？\p"
	.string "能不能告诉我点更厉害的招数？\p"
	.string "呃，等等。你的意思是，我的\n"
	.string "{STR_VAR_2}什么都不用\l"
	.string "带吗？$"

gText_ApprenticeWhatHeldItem14::
	.string "那个……呜……\n"
	.string "{PLAYER}{KUN}...\l"
	.string "...\p"
	.string "求求你，别用那种眼神看我。我的宝\n"
	.string "可梦身上什么都没带。\p"
	.string "我……虽然觉得很不好意思\n"
	.string "，但我真的很需要你的建议。\p"
	.string "我决定不了带什么物品才能让我的\n"
	.string "{STR_VAR_1}变得更强。\p"
	.string "{PLAYER}{KUN}，你觉\n"
	.string "得带什么好呢？$"

gText_ApprenticeHoldNothing14::
	.string "哦……那么，你觉得我的\n"
	.string "{STR_VAR_1}不带道具更\l"
	.string "好？$"

gText_ApprenticeThanksNoHeldItem14::
	.string "啊……好的！那就什么物品\n"
	.string "都不带。\p"
	.string "虽然很让人紧张……但这样\n"
	.string "会不会太酷了呢？\p"
	.string "谢谢你，{PLAYER}\n"
	.string "{KUN}。如果我们再见面的话，\l"
	.string "希望你还能像这样帮帮我。$"

gText_ApprenticeThanksHeldItem14::
	.string "啊……好的！那就带上那个\n"
	.string "{STR_VAR_1}。\p"
	.string "虽然很让人紧张……但这样\n"
	.string "会不会太酷了呢？\p"
	.string "谢谢你，{PLAYER}\n"
	.string "{KUN}。如果我们再见面的话，\l"
	.string "希望你还能像这样帮帮我。$"

gText_ApprenticeItemAlreadyRecommended14::
	.string "可、可是那个你已经说过了……\n"
	.string "..\p"
	.string "请别这么敷衍我嘛！这也太让人难堪\n"
	.string "了……\p"
	.string "啊……是我自作聪明了吗？\n"
	.string "你是觉得我的\l"
	.string "{STR_VAR_2}什么物品都\l"
	.string "不带比较好吗？$"

gText_ApprenticeWhatHeldItem15::
	.string "嗯？您看起来像是{PLAYER}\n"
	.string "{KUN}……但真的是本\l"
	.string "人吗？莫非是双胞胎？\p"
	.string "噢，不不不，请别介意！如果您确实\n"
	.string "是{PLAYER}，请原谅我的失\l"
	.string "礼。\p"
	.string "在下还想向您请教一些高见。\p"
	.string "在下手头有一只\n"
	.string "{STR_VAR_1}，想让它携\l"
	.string "带一件实用的物品。\p"
	.string "您看配得上它的是什么呢？$"

gText_ApprenticeHoldNothing15::
	.string "不携带任何物品更好？您确定吗？$"

gText_ApprenticeThanksNoHeldItem15::
	.string "原来如此。既然如此，那就这样吧。\n"
	.string "非常感谢您抽空指点。\p"
	.string "我们后会有期！$"

gText_ApprenticeThanksHeldItem15::
	.string "一个{STR_VAR_1}？您确\n"
	.string "定吗？\p"
	.string "原来如此。既然如此，那就这样吧。\n"
	.string "非常感谢您抽空指点。\p"
	.string "真希望我的宝可梦能物尽其用。\p"
	.string "我们后会有期！$"

gText_ApprenticeItemAlreadyRecommended15::
	.string "不不，请稍等片刻。在下记得您之前\n"
	.string "就指导过这点了。\p"
	.string "这次在下希望能得到不同的建议。\p"
	.string "难道您是认为我的\n"
	.string "{STR_VAR_2}什么都不带\l"
	.string "才好？您确定吗？$"

gText_ApprenticeWhichMonFirst0::
	.string "呜哇，{PLAYER}！我有个两\n"
	.string "难困境，抽泣……\p"
	.string "我想开始和别人对战，但不知道该怎\n"
	.string "么办。\p"
	.string "我该如何排列我的宝可梦才能让它们\n"
	.string "最强？\p"
	.string "请告诉我，{PLAYER}。如果\n"
	.string "你是我，这些宝可梦中你会先派出哪\l"
	.string "只？$"

gText_ApprenticeMonFirstThanks0::
	.string "我的{STR_VAR_1}应该先\n"
	.string "上？哇啊啊！\p"
	.string "哦！真对不起！你替我选择首发宝可\n"
	.string "梦让我很高兴，这又让我哭了……\p"
	.string "太感谢你了！$"

gText_ApprenticeWhichMonFirst1::
	.string "耶！是{PLAYER}！太好了！\n"
	.string "我想问你点事！\p"
	.string "嗯，在我的宝可梦中，你觉得哪只应\n"
	.string "该先出场？$"

gText_ApprenticeMonFirstThanks1::
	.string "我的{STR_VAR_1}？没错\n"
	.string "。好的，我会这么做的！\p"
	.string "谢谢你教我！$"

gText_ApprenticeWhichMonFirst2::
	.string "{PLAYER}，你好！\p"
	.string "我觉得在对战中，哪只宝可梦先出场\n"
	.string "非常重要。\p"
	.string "在我拥有的宝可梦中，哪只适合先派\n"
	.string "出去？$"

gText_ApprenticeMonFirstThanks2::
	.string "我的{STR_VAR_1}先上？\n"
	.string "好的，明白了！\p"
	.string "下次见！$"

gText_ApprenticeWhichMonFirst3::
	.string "你好，{PLAYER}……很抱歉\n"
	.string "又打扰你问另一个问题。\p"
	.string "我太没自信了，没有你\n"
	.string "{PLAYER}我都不知道该怎么\l"
	.string "办。\p"
	.string "可能我连担心都是浪费时间，但我就\n"
	.string "是无法决定一件事……\p"
	.string "我的宝可梦中哪只应该在对战中先出\n"
	.string "场？$"

gText_ApprenticeMonFirstThanks3::
	.string "我的{STR_VAR_1}？明白\n"
	.string "了！\p"
	.string "真不敢相信你会经常费心回答我的问\n"
	.string "题！\p"
	.string "我很感激你甚至愿意和我说话……谢\n"
	.string "谢你！$"

gText_ApprenticeWhichMonFirst4::
	.string "哦，{PLAYER}{KUN}！\n"
	.string "是我！很高兴见到你，因为我有个小\l"
	.string "问题。\p"
	.string "我无法决定我的宝可梦该如何排列。\n"
	.string "你能替我决定吗？\p"
	.string "哦，你现在不需要决定整个队伍。\p"
	.string "不如先替我决定首发宝可梦？$"

gText_ApprenticeMonFirstThanks4::
	.string "我的{STR_VAR_1}？太好\n"
	.string "了！\p"
	.string "知道是你做的决定，\n"
	.string "{PLAYER}{KUN}，就算\l"
	.string "我输了也不会太难过。\p"
	.string "好的，我会再来向你请教。再见！$"

gText_ApprenticeWhichMonFirst5::
	.string "嗨，我的老师{PLAYER}\n"
	.string "{KUN}！我今天又很忙！\p"
	.string "我得做些骑车、购物和哼歌的事。\p"
	.string "我甚至没时间决定如何排列我的宝可\n"
	.string "梦队伍。\p"
	.string "所以，不如看看我的队伍？哪只应该\n"
	.string "先出场？$"

gText_ApprenticeMonFirstThanks5::
	.string "好嘞，明白啦。这点时间我还是有的\n"
	.string "，这就把{STR_VAR_1}排\l"
	.string "在第一位！\p"
	.string "哎呀，我女朋友还在等我呢！谢啦！\n"
	.string "回头见！$"

gText_ApprenticeWhichMonFirst6::
	.string "哟嚯！嗨，{PLAYER}！你走\n"
	.string "路总是看起来很酷！\p"
	.string "听着，我又需要你帮忙了！老样子！\p"
	.string "请鼓掌！我的问题是关于我的队伍。\p"
	.string "我的宝可梦中哪只应该在对战中先出\n"
	.string "场？$"

gText_ApprenticeMonFirstThanks6::
	.string "嗯哼！你说我的\n"
	.string "{STR_VAR_1}！感谢这个\l"
	.string "超酷的回答！\p"
	.string "我想今天要问的就这些了。\p"
	.string "让我们在这里再见，好吗？谢谢！$"

gText_ApprenticeWhichMonFirst7::
	.string "非常感谢你停下来和我聊天，\n"
	.string "{PLAYER}。\p"
	.string "我知道我在利用你的善良，但能请教\n"
	.string "一下吗？\p"
	.string "我想让你决定我的宝可梦队伍的顺序\n"
	.string "。\p"
	.string "如果你能决定哪只宝可梦应该先出场\n"
	.string "就太好了。$"

gText_ApprenticeMonFirstThanks7::
	.string "那就是{STR_VAR_1}了！\n"
	.string "我马上就把它排在第一位！\p"
	.string "谢谢你，{PLAYER}。下次也\n"
	.string "拜托你啦。请多保重！$"

gText_ApprenticeWhichMonFirst8::
	.string "呀！我发现了{PLAYER}！我\n"
	.string "……又见到你我太高兴了！\p"
	.string "我的宝可梦变得强多了！\p"
	.string "但我并不总是赢。似乎取决于哪只宝\n"
	.string "可梦先出场。\p"
	.string "{PLAYER}，拜托，我需要你\n"
	.string "的帮助！\p"
	.string "请决定我的宝可梦中哪只应该先出场\n"
	.string "！$"

gText_ApprenticeMonFirstThanks8::
	.string "呼……我幸福得要晕过去了……\p"
	.string "能让你替我决定就像做梦一样，\n"
	.string "{PLAYER}。\p"
	.string "但完全明白了！我会让我的\n"
	.string "{STR_VAR_1}先上！\p"
	.string "希望下次你愿意再教我些东西。$"

gText_ApprenticeWhichMonFirst9::
	.string "嗨嗨！我的导师，{PLAYER}\n"
	.string "{KUN}！今天也用您的金玉良言\l"
	.string "指点指点我吧！\p"
	.string "你看，我凑齐了一支三只宝可梦的队\n"
	.string "伍。到目前为止还挺顺利的。\p"
	.string "可是对战的出场顺序还没定下来。\p"
	.string "这就轮到你出马啦，\n"
	.string "{PLAYER}{KUN}！由你\l"
	.string "来决定哪只宝可梦打头阵！\p"
	.string "别害羞嘛。痛快地说出来吧！$"

gText_ApprenticeMonFirstThanks9::
	.string "嗯哼，我的{STR_VAR_1}\n"
	.string "打头阵！OK，A——OK！我会重\l"
	.string "新排序队伍，就像，砰！\p"
	.string "好了，一如既往地感谢！再见！$"

gText_ApprenticeWhichMonFirst10::
	.string "{PLAYER}{KUN}，快听\n"
	.string "我说！大事不妙啦！\p"
	.string "我的宝可梦，三只全都要一起冲进对\n"
	.string "战场！\p"
	.string "当然啦，那怎么可能嘛！哇哈哈哈哈\n"
	.string "！\p"
	.string "不过说真的，我实在不擅长琢磨该怎\n"
	.string "么安排宝可梦的出场顺序。\p"
	.string "所以，师父，帮我决定一下哪只宝可\n"
	.string "梦打头阵怎么样？$"

gText_ApprenticeMonFirstThanks10::
	.string "好的，所以您挑了我的\n"
	.string "{STR_VAR_1}？除了它我\l"
	.string "让谁先发都行！\p"
	.string "开玩笑的啦！师父，我绝对听您的教\n"
	.string "导！\p"
	.string "多谢师父！以后也要继续指导我哦！$"

gText_ApprenticeWhichMonFirst11::
	.string "A——H——O——Y！拼出来就是\n"
	.string "Ahoy，嗨！\p"
	.string "说唱水手就是我！向你提个超酷的问\n"
	.string "题！\p"
	.string "这是个队伍排序问题需要你的建议！\p"
	.string "这些宝可梦中，哪只应该首先出场？$"

gText_ApprenticeMonFirstThanks11::
	.string "好的，我听到了，当然！我会调整它\n"
	.string "们的位置，就这么办！\p"
	.string "如果我需要建议，{PLAYER}\n"
	.string "，你的话我永远听从！$"

gText_ApprenticeWhichMonFirst12::
	.string "哟嚯，{PLAYER}！你好吗？\p"
	.string "我该怎么办？直接问？嗯哼，我有事\n"
	.string "要问！你收到我的信号了吗？你收到\l"
	.string "了！\p"
	.string "你必须决定，我的宝可梦中哪只是第\n"
	.string "1个上场的！我是说进入战斗！$"

gText_ApprenticeMonFirstThanks12::
	.string "我的{STR_VAR_1}？是的\n"
	.string "！这样就行，没有烦恼！\p"
	.string "嗯，{PLAYER}，我必须自由\n"
	.string "漂泊，但别忘了我。\p"
	.string "再见，我聪明的朋友！$"

gText_ApprenticeWhichMonFirst13::
	.string "……呼……哎哟……\n"
	.string "{PLAYER}{KUN}……我\l"
	.string "的肚子突然好痛……\p"
	.string "……现在好些了……\p"
	.string "一定是我绞尽脑汁思考如何排列我的\n"
	.string "宝可梦伙伴时把自己愁坏了。\p"
	.string "所以，事已至此，我需要你替我决定\n"
	.string "。\p"
	.string "{PLAYER}{KUN}，我的\n"
	.string "宝可梦中哪只应该先上场？我是说，\l"
	.string "才更可能赢。$"

gText_ApprenticeMonFirstThanks13::
	.string "嗯，好的。我的\n"
	.string "{STR_VAR_1}先上。\p"
	.string "等我吃完晚饭就按那样调整顺序。\p"
	.string "我希望我能继续这样向你求助。$"

gText_ApprenticeWhichMonFirst14::
	.string "那个……呜……\n"
	.string "{PLAYER}{KUN}？\p"
	.string "求求你，别用那种眼神看我。你这样\n"
	.string "让我好慌乱呀。\p"
	.string "那个……我真的很需要你的\n"
	.string "建议。\p"
	.string "虽然说出来有点害羞，但我已经挑好\n"
	.string "了三只宝可梦的队伍。只是决定不了\l"
	.string "出场顺序。\p"
	.string "先派哪只宝可梦上场，才能让我看起\n"
	.string "来厉害一点呢？$"

gText_ApprenticeMonFirstThanks14::
	.string "啊……好的！那就让我的\n"
	.string "{STR_VAR_1}首发。\p"
	.string "希望能顺顺利利，不要手忙脚乱才好\n"
	.string "。\p"
	.string "谢谢你，{PLAYER}\n"
	.string "{KUN}。如果我们再见面的话，\l"
	.string "希望你还能像这样帮帮我。$"

gText_ApprenticeWhichMonFirst15::
	.string "嗯？您看起来像是{PLAYER}\n"
	.string "{KUN}……但真的是本\l"
	.string "人吗？莫非是惟妙惟肖的替身？\p"
	.string "噢，不不不，请别介意！如果您确实\n"
	.string "是{PLAYER}，请原谅我的失\l"
	.string "礼。\p"
	.string "在下希望能听取您的高见。\p"
	.string "在下这里组好了一支宝可梦队伍。想\n"
	.string "请教您在对战中应该由哪一只率先出\l"
	.string "战。$"

gText_ApprenticeMonFirstThanks15::
	.string "我的{STR_VAR_1}...\n"
	.string "...您不是在拿在下寻开心吧？\p"
	.string "原来如此。既然如此，那就这样吧。\n"
	.string "非常感谢您抽空指点。\p"
	.string "在下虽不成器，但也必当竭尽全力。\p"
	.string "我们后会有期！$"

gText_ApprenticeWhichMon0::
	.string "抽泣……哦，{PLAYER}！\p"
	.string "来得正是时候！有件事我实在拿不定\n"
	.string "主意……\p"
	.string "我无法决定该用哪只宝可梦。\p"
	.string "在{STR_VAR_1}和\n"
	.string "{STR_VAR_2}之间犹豫不\l"
	.string "决……\p"
	.string "{PLAYER}，你觉得哪只能让\n"
	.string "我也有机会获胜？$"

gText_ApprenticeMonThanks0::
	.string "抽泣……我…我明白了！哦！真对不\n"
	.string "起！你让我太开心，我又哭了……\p"
	.string "我会努力去抓一只\n"
	.string "{STR_VAR_1}！\p"
	.string "太感谢你了！$"

gText_ApprenticeWhichMon1::
	.string "耶！是{PLAYER}！来得正好\n"
	.string "！我又需要你的建议了！\p"
	.string "嗯，我完全搞混了——该用我的\n"
	.string "{STR_VAR_1}还是\l"
	.string "{STR_VAR_2}……\p"
	.string "{PLAYER}，你觉得我该培育\n"
	.string "哪只？$"

gText_ApprenticeMonThanks1::
	.string "哦，所以我的\n"
	.string "{STR_VAR_1}更好！好的\l"
	.string "，就这么办！\p"
	.string "谢谢你的教导！$"

gText_ApprenticeWhichMon2::
	.string "{PLAYER}，你好！有个问题\n"
	.string "想请教。\p"
	.string "我在纠结该培育\n"
	.string "{STR_VAR_1}还是\l"
	.string "{STR_VAR_2}。\p"
	.string "你觉得哪只宝可梦会更强？$"

gText_ApprenticeMonThanks2::
	.string "你选了{STR_VAR_1}？好\n"
	.string "的，明白了！\p"
	.string "我这就去抓只厉害的\n"
	.string "{STR_VAR_1}！\p"
	.string "下次见！$"

gText_ApprenticeWhichMon3::
	.string "你好，{PLAYER}……\p"
	.string "嗯，你可能已经忘记我这样的人了…\n"
	.string "…\p"
	.string "……但如果你能给我建议那也没关系\n"
	.string "……\p"
	.string "我无法决定该培育哪种宝可梦……\p"
	.string "范围缩小到了\n"
	.string "{STR_VAR_1}和\l"
	.string "{STR_VAR_2}，但就在这\l"
	.string "卡住了……\p"
	.string "{PLAYER}，你可能不想费心\n"
	.string "，但请替我决定吧。$"

gText_ApprenticeMonThanks3::
	.string "但野生的{STR_VAR_1}会\n"
	.string "理我吗？\p"
	.string "我会试试的！\p"
	.string "但我能抓到吗……不！我会尽力的！\p"
	.string "谢谢你！$"

gText_ApprenticeWhichMon4::
	.string "哦，{PLAYER}{KUN}！\n"
	.string "见到你真高兴！我正要去找你呢！\p"
	.string "你能决定我该用哪种宝可梦吗？\p"
	.string "比如……{STR_VAR_1}和\n"
	.string "{STR_VAR_2}怎么样？\p"
	.string "你觉得哪只更适合我？$"

gText_ApprenticeMonThanks4::
	.string "{STR_VAR_1}？太棒了！\p"
	.string "只要是你的决定，{PLAYER}\n"
	.string "{KUN}，就算输了我也没那么难\l"
	.string "过。\p"
	.string "好的，下次再向你请教。再见！$"

gText_ApprenticeWhichMon5::
	.string "这不是{PLAYER}{KUN}\n"
	.string "吗！最近怎样？我还是老样子忙得很\l"
	.string "！\p"
	.string "我也想用好宝可梦，但一直没决定该\n"
	.string "用哪只。\p"
	.string "你看{STR_VAR_1}好像很\n"
	.string "强？但{STR_VAR_2}也不\l"
	.string "容忽视。\p"
	.string "{PLAYER}{KUN}，给我\n"
	.string "点好建议！哪只适合我？$"

gText_ApprenticeMonThanks5::
	.string "好的，明白了。我会想办法抓一只你\n"
	.string "推荐的{STR_VAR_1}。\p"
	.string "真高兴遇到你这样的好导师。谢谢！\n"
	.string "回头见！$"

gText_ApprenticeWhichMon6::
	.string "哦！是{PLAYER}！\p"
	.string "我立刻就跟朋友们炫耀遇到你的事！\p"
	.string "今天又要借用你的智慧了。对你来说\n"
	.string "很简单！\p"
	.string "请击鼓助兴！我的问题是……\p"
	.string "如果要培育宝可梦，选\n"
	.string "{STR_VAR_1}还是\l"
	.string "{STR_VAR_2}？$"

gText_ApprenticeMonThanks6::
	.string "啊啊！你说{STR_VAR_1}\n"
	.string "！感谢这超酷的答案！\p"
	.string "今天想问的就这些了。\p"
	.string "我们下次在这里再见，好吗？谢谢！$"

gText_ApprenticeWhichMon7::
	.string "哦，是你吗{PLAYER}？真高\n"
	.string "兴又见到你！\p"
	.string "自从成为你的学徒，我的信心越来越\n"
	.string "强了。\p"
	.string "我觉得准备好培育自己的宝可梦了！\p"
	.string "{PLAYER}，能麻烦你帮我选\n"
	.string "该培育哪只宝可梦吗？\p"
	.string "选项是{STR_VAR_1}或\n"
	.string "{STR_VAR_2}……哪只适\l"
	.string "合我？$"

gText_ApprenticeMonThanks7::
	.string "那就是一个{STR_VAR_1}\n"
	.string "了！我马上就去找一个来！\p"
	.string "谢谢你，{PLAYER}。下次也\n"
	.string "拜托你啦。请多保重！$"

gText_ApprenticeWhichMon8::
	.string "呀！{PLAYER}！又见到你了\n"
	.string "！我……我太高兴了！\p"
	.string "啊、啊、啊，我知道了！我绝不能放\n"
	.string "过这个好机会！\p"
	.string "{PLAYER}，能拜托你一件大\n"
	.string "事吗？请帮我挑选一只宝可梦吧！\p"
	.string "请帮我决定一下，到底是\n"
	.string "{STR_VAR_1}好，还是\l"
	.string "{STR_VAR_2}好！$"

gText_ApprenticeMonThanks8::
	.string "哇！你替我决定了！我会全力培育这\n"
	.string "只{STR_VAR_1}！\p"
	.string "希望下次你还能多教我一些。$"

gText_ApprenticeWhichMon9::
	.string "嘿，嘿！我的导师{PLAYER}\n"
	.string "{KUN}！\p"
	.string "你好，我一直在找你想再听听你的睿\n"
	.string "智建议！\p"
	.string "哪种宝可梦适合我，\n"
	.string "{STR_VAR_1}还是\l"
	.string "{STR_VAR_2}？\p"
	.string "别害羞，直接说出来吧！$"

gText_ApprenticeMonThanks9::
	.string "嗯哼，就选{STR_VAR_1}\n"
	.string "！OK，没问题！我会用精灵球抓一\l"
	.string "只，就像塞进去！\p"
	.string "好的，一如既往地感谢！再见！$"

gText_ApprenticeWhichMon10::
	.string "{PLAYER}{KUN}，听着\n"
	.string "！大新闻！我抓到了幻影宝可梦！\p"
	.string "当然是骗你的！哇哈哈哈！\p"
	.string "不过这不是骗人的。我不太擅长抓宝\n"
	.string "可梦。\p"
	.string "所以，不如替我决定该抓哪种宝可梦\n"
	.string "吧，师父？\p"
	.string "哪只更好？{STR_VAR_1}\n"
	.string "还是{STR_VAR_2}？$"

gText_ApprenticeMonThanks10::
	.string "好，你选的是\n"
	.string "{STR_VAR_1}对吧？那我\l"
	.string "就选另一只！\p"
	.string "开玩笑的啦！师父，徒儿谨遵教诲！\p"
	.string "谢谢师父！以后也请多多指教啦！$"

gText_ApprenticeWhichMon11::
	.string "A——H——O——Y！就是\n"
	.string "Ahoy的拼法！\p"
	.string "我就是那个说唱水手！你肯定记得我\n"
	.string "是谁吧？\p"
	.string "今天有个宝可梦问题需要你的建议！\p"
	.string "我可以在{STR_VAR_1}和\n"
	.string "{STR_VAR_2}之间选择，\l"
	.string "哪只适合抓来陪我？$"

gText_ApprenticeMonThanks11::
	.string "你说{STR_VAR_1}，嘿，\n"
	.string "嘿！我这就去抓一只！\p"
	.string "如果需要建议，{PLAYER}，\n"
	.string "你的话我永远牢记！$"

gText_ApprenticeWhichMon12::
	.string "哇哦，这不是{PLAYER}吗！\p"
	.string "我该怎么做？听听你的建议？既然都\n"
	.string "在聊了，有何不可！\p"
	.string "好久不见啦。先来暖个场，我也想听\n"
	.string "听你的意见！收到我的信号了吗？你\l"
	.string "肯定收到了！\p"
	.string "我的宝可梦--该用哪只？\n"
	.string "{STR_VAR_1}还是\l"
	.string "{STR_VAR_2}。你选哪一\l"
	.string "只？$"

gText_ApprenticeMonThanks12::
	.string "如果{STR_VAR_1}最棒，\n"
	.string "我就照你说的办！\p"
	.string "嗯，{PLAYER}，我得自由闯\n"
	.string "荡，但你可别忘了我。\p"
	.string "再见，我聪明的朋友！$"

gText_ApprenticeWhichMon13::
	.string "哦，嗨，{PLAYER}\n"
	.string "{KUN}……我头疼得厉害……\p"
	.string "肯定是因为太纠结该培育哪种宝可梦\n"
	.string "了。\p"
	.string "所以，情况就是这样，需要你替我决\n"
	.string "定。\p"
	.string "{PLAYER}{KUN}，如果\n"
	.string "必须在{STR_VAR_1}和\l"
	.string "{STR_VAR_2}之间选择，\l"
	.string "该选哪只？$"

gText_ApprenticeMonThanks13::
	.string "嗯，就选{STR_VAR_1}吧\n"
	.string "。等我好些了就去找一只。\p"
	.string "希望能继续这样向你求助。$"

gText_ApprenticeWhichMon14::
	.string "呃……嗯…{PLAYER}\n"
	.string "{KUN}……？\p"
	.string "拜托别那样看我。我都慌乱了……我\n"
	.string "……我需要你的建议。\p"
	.string "我……我真的很不好意思，但无法决\n"
	.string "定该用哪只宝可梦。\p"
	.string "如果选项是{STR_VAR_1}\n"
	.string "或{STR_VAR_2}，哪只更\l"
	.string "好？$"

gText_ApprenticeMonThanks14::
	.string "啊……好的！我会和\n"
	.string "{STR_VAR_1}一起加油的\l"
	.string "。\p"
	.string "希望自己能沉着应对，不会手忙脚乱\n"
	.string "。\p"
	.string "谢谢你，{PLAYER}\n"
	.string "{KUN}。如果下次还能相遇，还\l"
	.string "请多多指教哦。$"

gText_ApprenticeWhichMon15::
	.string "嗯？你看上去像是{PLAYER}\n"
	.string "{KUN}……但你真的是\l"
	.string "本人吗？\p"
	.string "不不，是本人的话那就太好了。顺带\n"
	.string "一提，我有件事想征求一下你的意见\l"
	.string "。\p"
	.string "是关于我要使用的宝可梦。\p"
	.string "如果要在宝可梦\n"
	.string "{STR_VAR_1}与\l"
	.string "{STR_VAR_2}之间做选择\l"
	.string "，哪一只更配得上我呢？$"

gText_ApprenticeMonThanks15::
	.string "{STR_VAR_1}？你确定吗\n"
	.string "？\p"
	.string "我明白了。既然如此，那就它吧。感\n"
	.string "谢你抽空指点。\p"
	.string "希望这是一只连我也能从容驾驭的宝\n"
	.string "可梦。\p"
	.string "期待与你再次相会！$"

gText_ApprenticeWhichMove0::
	.string "哇啊啊！呜，{PLAYER}！抽\n"
	.string "泣……嗝……\p"
	.string "我好纠结啊！我决定不了该让我的\n"
	.string "{STR_VAR_1}学什么招式\l"
	.string "了……\p"
	.string "求求你，求求你，{PLAYER}\n"
	.string "。能帮我决定一下吗？\p"
	.string "对我的{STR_VAR_1}来说\n"
	.string "，{STR_VAR_2}和\l"
	.string "{STR_VAR_3}，哪个招式\l"
	.string "更好呢？$"

gText_ApprenticeMoveThanks0::
	.string "{STR_VAR_1}？哇啊啊啊\n"
	.string "！\p"
	.string "啊！对不起，{PLAYER}！你\n"
	.string "帮我选好了招式，我太高兴了，眼泪\l"
	.string "停不下来……\p"
	.string "抽泣……太谢谢你了！$"

gText_ApprenticeWhichMove1::
	.string "太棒了！嗨，{PLAYER}！我\n"
	.string "又想来请教你了！\p"
	.string "我想让我的{STR_VAR_1}\n"
	.string "学会一个帅气的招式。\p"
	.string "招式{STR_VAR_2}和\n"
	.string "{STR_VAR_3}，我都很喜\l"
	.string "欢。你推荐哪一个呢？$"

gText_ApprenticeMoveThanks1::
	.string "{STR_VAR_1}更好？我想\n"
	.string "是的！好的，我就用那个！\p"
	.string "如果我们在这里再见，请再教我点别\n"
	.string "的，老师！$"

gText_ApprenticeWhichMove2::
	.string "{PLAYER}，你好！是关于我\n"
	.string "的{STR_VAR_1}，我正在\l"
	.string "为它的招式发愁呢。\p"
	.string "就是招式{STR_VAR_2}和\n"
	.string "{STR_VAR_3}。\p"
	.string "哪一个更强，更适合我的\n"
	.string "{STR_VAR_1}呢？$"

gText_ApprenticeMoveThanks2::
	.string "{STR_VAR_1}是你的选择\n"
	.string "？好的，明白了！\p"
	.string "我马上去教我的宝可梦\n"
	.string "{STR_VAR_1}！\p"
	.string "下次见！$"

gText_ApprenticeWhichMove3::
	.string "呜呜，{PLAYER}.....\n"
	.string ".我真是太没用了，真的！\p"
	.string "我下定决心要培育宝可梦，可现在连\n"
	.string "该让它学什么招式都决定不了...\l"
	.string "...\p"
	.string "我知道这对你来说根本不算什么，\n"
	.string "{PLAYER}。\p"
	.string "但这对我来说真的很重要……\n"
	.string ".\p"
	.string "拜托了，{PLAYER}，能帮我\n"
	.string "的{STR_VAR_1}选一个招\l"
	.string "式吗？\p"
	.string "在{STR_VAR_2}和\n"
	.string "{STR_VAR_3}之间帮我选\l"
	.string "一个就好……$"

gText_ApprenticeMoveThanks3::
	.string "我明白了！\p"
	.string "但它会愿意为我学\n"
	.string "{STR_VAR_1}吗……不！\l"
	.string "我会尽力的！\p"
	.string "谢谢你！$"

gText_ApprenticeWhichMove4::
	.string "啊，{PLAYER}{KUN}！\n"
	.string "我也正想着能遇到你就好了！\p"
	.string "我正在想什么招式适合我的\n"
	.string "{STR_VAR_1}。\p"
	.string "我实在拿不定主意，你能帮我做决定\n"
	.string "吗？\p"
	.string "比如……招式\n"
	.string "{STR_VAR_2}和\l"
	.string "{STR_VAR_3}怎么样？哪\l"
	.string "一个会更好呢？$"

gText_ApprenticeMoveThanks4::
	.string "{STR_VAR_1}？太棒了！\p"
	.string "知道是你做的决定，\n"
	.string "{PLAYER}{KUN}，就算\l"
	.string "我输了也不会太难过。\p"
	.string "好的，我会再来向你请教。再见！$"

gText_ApprenticeWhichMove5::
	.string "怎么会这么忙啊？嘿，这不是\n"
	.string "{PLAYER}{KUN}吗！最\l"
	.string "近怎么样？\p"
	.string "我今天一早起床，又是慢跑，又是游\n"
	.string "泳，还做了饭！\p"
	.string "你都不知道我有多忙！\p"
	.string "连我的{STR_VAR_1}该学\n"
	.string "什么招式都没时间决定！\p"
	.string "{STR_VAR_2}看起来不错\n"
	.string "对吧？但{STR_VAR_3}也\l"
	.string "很可取。\p"
	.string "{PLAYER}{KUN}，快给\n"
	.string "我点好建议！哪个招式更适合我？$"

gText_ApprenticeMoveThanks5::
	.string "好，明白了！我会挤出时间把那个招\n"
	.string "式教会的。\p"
	.string "能遇到你这么好的导师真是太棒了。\n"
	.string "多谢啦！回头见！$"

gText_ApprenticeWhichMove6::
	.string "哇！太幸运了！又遇到你了，\n"
	.string "{PLAYER}！今天也要借你的\l"
	.string "智慧用用啦。\p"
	.string "请奏擂鼓！我今天要问的是……\n"
	.string "..\p"
	.string "对于我的{STR_VAR_1}，\n"
	.string "最适合它的招式是\l"
	.string "{STR_VAR_2}还是\l"
	.string "{STR_VAR_3}呢？$"

gText_ApprenticeMoveThanks6::
	.string "啊！{STR_VAR_1}，你说\n"
	.string "！感谢这个超酷的回答！\p"
	.string "我想今天要问的就这些了。\p"
	.string "让我们在这里再见，好吗？谢谢！$"

gText_ApprenticeWhichMove7::
	.string "哎呀，你好，{PLAYER}。近\n"
	.string "来可好？\p"
	.string "我又得向你请教了。是关于我最宝贝\n"
	.string "的{STR_VAR_1}。\p"
	.string "对我可爱的{STR_VAR_1}\n"
	.string "来说，最理想的招式是什么呢？是\l"
	.string "{STR_VAR_2}还是\l"
	.string "{STR_VAR_3}？$"

gText_ApprenticeMoveThanks7::
	.string "就选{STR_VAR_1}了！我\n"
	.string "这就去教它！\p"
	.string "谢谢你，{PLAYER}。下次也\n"
	.string "请多多关照。请多保重！$"

gText_ApprenticeWhichMove8::
	.string "呀！{PLAYER}！又见到你了\n"
	.string "！我……我太高兴了！\p"
	.string "每当我遇到困难时，你总是陪在我身\n"
	.string "边，{PLAYER}！\p"
	.string "今天我想请你给我推荐一个招式！\p"
	.string "请帮我的{STR_VAR_1}选\n"
	.string "一个招式吧！\p"
	.string "招式{STR_VAR_2}和\n"
	.string "{STR_VAR_3}，哪一个会\l"
	.string "更好呢？$"

gText_ApprenticeMoveThanks8::
	.string "哦哦哦！谢谢你！就是\n"
	.string "{STR_VAR_1}了！完全明\l"
	.string "白了！\p"
	.string "下次也希望你能继续指教我哦。$"

gText_ApprenticeWhichMove9::
	.string "Hola，{PLAYER}\n"
	.string "{KUN}，bueno！今天也想\l"
	.string "听听你的高见呢！\p"
	.string "什么招式最适合我的\n"
	.string "{STR_VAR_1}？\p"
	.string "最好是能让我一下子就能赢下来的招\n"
	.string "式！\p"
	.string "是{STR_VAR_2}呢？还是\n"
	.string "{STR_VAR_3}呢？$"

gText_ApprenticeMoveThanks9::
	.string "嗯哼，{STR_VAR_1}！好\n"
	.string "的，行！我会教它，就像，砰！\p"
	.string "好了，一如既往地感谢！再见！$"

gText_ApprenticeWhichMove10::
	.string "{PLAYER}{KUN}，太惊\n"
	.string "人了！\p"
	.string "我的宝可梦！它学会了六个招式！\p"
	.string "当然是骗你的啦！哇哈哈哈哈！\p"
	.string "不过下面这句可不是假话。我真的很\n"
	.string "不擅长给宝可梦挑选招式。\p"
	.string "所以，帮我决定一下该教哪种招式怎\n"
	.string "么样？\p"
	.string "{STR_VAR_2}还是\n"
	.string "{STR_VAR_3}--哪一个\l"
	.string "和我的{STR_VAR_1}最搭\l"
	.string "？$"

gText_ApprenticeMoveThanks10::
	.string "好，你选的是\n"
	.string "{STR_VAR_1}对吧？那我\l"
	.string "就选另一个招式！\p"
	.string "开玩笑的啦！师父，徒儿谨遵教诲！\p"
	.string "谢谢师父！以后也请多多指教啦！$"

gText_ApprenticeWhichMove11::
	.string "A-H-O-Y！拼出来就是喂--\n"
	.string "！\p"
	.string "我是个会说唱的水手！时刻紧跟潮流\n"
	.string "，无需理由。\p"
	.string "今天我有个招式疑问，急需你的指点\n"
	.string "指引！\p"
	.string "{STR_VAR_2}和\n"
	.string "{STR_VAR_3}，哪个能让\l"
	.string "我的{STR_VAR_1}把节奏\l"
	.string "狠狠拿稳？$"

gText_ApprenticeMoveThanks11::
	.string "{STR_VAR_1}，你说，嘿\n"
	.string "，嘿！我马上去教那招！\p"
	.string "如果我需要建议，{PLAYER}\n"
	.string "，你的话我永远听从！$"

gText_ApprenticeWhichMove12::
	.string "哦，耶--这不是{PLAYER}\n"
	.string "吗！\p"
	.string "我该怎么做？听听你的建议？既然都\n"
	.string "在聊了，有何不可！\p"
	.string "{PLAYER}，看到我你惊讶吗\n"
	.string "？想听你的高见，你懂的吧？\p"
	.string "收到我的信号了吗？你肯定收到了！\p"
	.string "我的{STR_VAR_1}--该\n"
	.string "用什么招式？\l"
	.string "{STR_VAR_2}还是\l"
	.string "{STR_VAR_3}，你怎么选\l"
	.string "？$"

gText_ApprenticeMoveThanks12::
	.string "如果{STR_VAR_1}是最好\n"
	.string "的，我会照你说的做！\p"
	.string "嗯，{PLAYER}，我必须自由\n"
	.string "漫游，但别忘了我。\p"
	.string "再见，我聪明的朋友！$"

gText_ApprenticeWhichMove13::
	.string "咳咳！咳！呜，{PLAYER}\n"
	.string "{KUN}……我得了可恶\l"
	.string "的感冒，咳……\p"
	.string "我想给宝可梦挑选招式，可实在没力\n"
	.string "气……\p"
	.string "所以，事情就是这样，我想请你帮我\n"
	.string "做决定。\p"
	.string "{PLAYER}{KUN}，要为\n"
	.string "我的{STR_VAR_1}在\l"
	.string "{STR_VAR_2}和\l"
	.string "{STR_VAR_3}之间挑选，\l"
	.string "应该选哪个呢？$"

gText_ApprenticeMoveThanks13::
	.string "嗯，{STR_VAR_1}，好的\n"
	.string "。咳！等我好起来就去教它。\p"
	.string "希望下次遇到困难也能继续向你求助\n"
	.string "。$"

gText_ApprenticeWhichMove14::
	.string "那个……嗯……\n"
	.string "{PLAYER}{KUN}..\l"
	.string "....？\p"
	.string "求求你，别那样看着我啦。我整个人\n"
	.string "都慌乱起来了……我..\l"
	.string "……我想听听你的建议。\p"
	.string "我……虽然很不好意思，但\n"
	.string "我拿不定主意到底该给我的宝可梦学\l"
	.string "什么招式。\p"
	.string "是我的{STR_VAR_1}要学\n"
	.string "的。如果在{STR_VAR_2}\l"
	.string "和{STR_VAR_3}之间二选\l"
	.string "一，选哪个更好呢？$"

gText_ApprenticeMoveThanks14::
	.string "啊……好的！那我试试\n"
	.string "{STR_VAR_1}吧。\p"
	.string "希望能学会那个招式……真\n"
	.string "是太让人紧张了……\p"
	.string "谢谢你，{PLAYER}\n"
	.string "{KUN}。下次见面时，也希望你\l"
	.string "能再帮帮我。$"

gText_ApprenticeWhichMove15::
	.string "嗯？你看起来是{PLAYER}\n"
	.string "{KUN}……但你真的是\l"
	.string "本人吗？\p"
	.string "该不会是最近很流行的模仿艺人假扮\n"
	.string "的吧？\p"
	.string "哎呀别生气，要是真人的话就没事。\n"
	.string "请放心，完全没必要介意！\p"
	.string "顺带一提，我也想请教一下你的建\n"
	.string "议。\p"
	.string "是关于我的{STR_VAR_1}\n"
	.string "的。\p"
	.string "让它学哪招比较好呢，\n"
	.string "{STR_VAR_2}还是\l"
	.string "{STR_VAR_3}？$"

gText_ApprenticeMoveThanks15::
	.string "{STR_VAR_1}吗？毫无疑\n"
	.string "问就是这个了？\p"
	.string "原来如此，既然你这么说就没错了。\n"
	.string "非常感谢你抽空指点。\p"
	.string "真希望这招连我的宝可梦也能顺利学\n"
	.string "会。\p"
	.string "期待下次再见！$"

gText_ApprenticePickWinSpeech0::
	.string "哦… {PLAYER}？是\n"
	.string "{PLAYER}啊！哦！抽泣……\l"
	.string "呜咽… 请听我说！\p"
	.string "我… 在对战时，我会紧张得不得了\n"
	.string "，就算赢了也忍不住哭出来……\p"
	.string "我真希望赢的时候能说点帅气的话…\n"
	.string "…\p"
	.string "求求你，{PLAYER}！能不能\n"
	.string "教我一句赢了之后说的酷酷的话，这\l"
	.string "样我就不会哭了？$"

gText_ApprenticeWinSpeechThanks0::
	.string "{STR_VAR_1}\p"
	.string "太棒了！帅呆了！呜哦哦！这真的很\n"
	.string "酷！\p"
	.string "哦……对不起……我太高兴了，又哭\n"
	.string "了……\p"
	.string "抽鼻子… {PLAYER}！真的\n"
	.string "非常感谢你为我做的一切！\p"
	.string "为了你，{PLAYER}，我会尽\n"
	.string "我所能去战斗的！\p"
	.string "{PLAYER}……下次… 我们\n"
	.string "来对战吧！$"

gText_ApprenticePickWinSpeech1::
	.string "太棒了！是{PLAYER}！你好\n"
	.string "呀！我刚好有事想问你呢！\p"
	.string "在对战获胜的时候，我想说句很帅气\n"
	.string "的话。\p"
	.string "你有什么帅气的台词可以推荐给我\n"
	.string "吗？$"

gText_ApprenticeWinSpeechThanks1::
	.string "{STR_VAR_1}\p"
	.string "哦，哇！这太酷了！好的，我就说这\n"
	.string "句了！\p"
	.string "谢谢你一直以来的教导！从今以后，\n"
	.string "无论走到哪里，我都会全力以赴的！\p"
	.string "等我们再见面时，就来一场对战吧！$"

gText_ApprenticePickWinSpeech2::
	.string "{PLAYER}，你好！\p"
	.string "我和我的宝可梦已经准备好迎接任何\n"
	.string "挑战了，除了一件事。\p"
	.string "我觉得如果我赢了之后能喊点什么就\n"
	.string "好了。\p"
	.string "你能帮我想一句适合说的话吗？$"

gText_ApprenticeWinSpeechThanks2::
	.string "{STR_VAR_1}\p"
	.string "……酷！我就用这句了！\p"
	.string "我要去各地旅行战斗了。\p"
	.string "说不定有一天，我还能和你对战呢，\n"
	.string "{PLAYER}。\p"
	.string "下次，我们在对战之地再见吧！$"

gText_ApprenticePickWinSpeech3::
	.string "你好，{PLAYER}……抱歉打\n"
	.string "扰你，但我真是没救了……\p"
	.string "即使是……即使我赢了，我也说不出\n"
	.string "什么特别的话来……\p"
	.string "我知道这对你来说可能不算什么，\n"
	.string "{PLAYER}。\p"
	.string "但对我来说意义重大……\p"
	.string "求你了，{PLAYER}，如果我\n"
	.string "赢了比赛，该说什么好呢？$"

gText_ApprenticeWinSpeechThanks3::
	.string "{STR_VAR_1}\p"
	.string "这话真有水平……\p"
	.string "呃……像我这样的人说这个真的合适\n"
	.string "吗？\p"
	.string "不！我会努力的！\p"
	.string "{PLAYER}，真的非常感谢你\n"
	.string "一直这么包容我……\p"
	.string "我保证从现在开始会尽最大努力。\p"
	.string "我知道你大概很快就会忘掉我这样的\n"
	.string "人，但我们一定要在某个地方再见面\l"
	.string "！$"

gText_ApprenticePickWinSpeech4::
	.string "哦，{PLAYER}{KUN}。\n"
	.string "有件事想请你听听。\p"
	.string "我知道我说话有时听起来不太友善或\n"
	.string "礼貌……\p"
	.string "赢了比赛时，我觉得自己显得有点傲\n"
	.string "慢。\p"
	.string "我不想让人讨厌，所以我想对被我打\n"
	.string "败的人说点好话。\p"
	.string "但我就是想不出什么好词！你能帮我\n"
	.string "想一句吗？$"

gText_ApprenticeWinSpeechThanks4::
	.string "{STR_VAR_1}\p"
	.string "不错嘛！嗯，我就用这句了！\p"
	.string "我要踏上旅程，把从你那里学到的东\n"
	.string "西记在脑海里、放在心里，尽我所能\l"
	.string "去做。\p"
	.string "很抱歉我一直对你这么缠人！\p"
	.string "下次，我们来对战吧，好吗？再见！$"

gText_ApprenticePickWinSpeech5::
	.string "哎呀，我真是忙得不可开交！啊，\n"
	.string "喂！我正找你呢，{PLAYER}\l"
	.string "{KUN}。\p"
	.string "你还是老样子很有精神吧？我这边也\n"
	.string "是一点都没变。\p"
	.string "又要跑步、又要对战、还要画地图。\n"
	.string "我怎么会这么忙啊？\p"
	.string "可就算再忙，赢了之后什么话都不说\n"
	.string "就直接扭头走掉，未免太失礼了。\p"
	.string "所以说，在获胜离场时，要说什么话\n"
	.string "才能凸显出我的帅气呢？\l"
	.string "{PLAYER}{KUN}，快帮\l"
	.string "帮我吧！$"

gText_ApprenticeWinSpeechThanks5::
	.string "{STR_VAR_1}\p"
	.string "好的，明白了。我总能挤出时间说这\n"
	.string "句的！\p"
	.string "说实话，能遇到你这样的好导师真是\n"
	.string "太好了。\p"
	.string "我会想办法挤出时间去好好对战的。\p"
	.string "谢谢你做的一切，{PLAYER}\n"
	.string "{KUN}！总有一天，我们一定要\l"
	.string "对战一场！$"

gText_ApprenticePickWinSpeech6::
	.string "我又走运了！{PLAYER}！见\n"
	.string "到你太高兴了！和往常一样，我需要\l"
	.string "你的建议！\p"
	.string "请击鼓助兴！我要问的最后一个问题\n"
	.string "是……\p"
	.string "如果我赢了比赛，想用一句酷炫的结\n"
	.string "束语收尾，我该说什么？$"

gText_ApprenticeWinSpeechThanks6::
	.string "{STR_VAR_1}\p"
	.string "这句……这句太棒了！既体面又帅气\n"
	.string "！我宣布这句归我了！\p"
	.string "……听着，我觉得我现在还挺像样的\n"
	.string "了，对吧？\p"
	.string "所以，我打算从现在开始挑战其他训\n"
	.string "练家了。\p"
	.string "{PLAYER}，你的建议真的帮\n"
	.string "了我大忙。\p"
	.string "也许有一天，就是我们交手的时候了\n"
	.string "！\p"
	.string "感谢你所做的一切！$"

gText_ApprenticePickWinSpeech7::
	.string "哦，{PLAYER}。真高兴能遇\n"
	.string "见你！\p"
	.string "关于我的宝可梦，我已经没有任何顾\n"
	.string "虑了。\p"
	.string "让我担心的是我自己……\p"
	.string "你知道训练家赢了比赛后会说些什么\n"
	.string "吗？\p"
	.string "毫无疑问，我也希望能那样做！\p"
	.string "求你了，赢了比赛后我该说什么好呢\n"
	.string "？$"

gText_ApprenticeWinSpeechThanks7::
	.string "{STR_VAR_1}\p"
	.string "啊！这句话！它让我神清气爽，仿佛\n"
	.string "重获新生！\p"
	.string "我必须马上就用上这句！\p"
	.string "那么现在，我必须告辞了，\n"
	.string "{PLAYER}……\p"
	.string "我会去和很多人对战，但永远不会忘\n"
	.string "记你的教导。\p"
	.string "也许有一天……再会了！$"

gText_ApprenticePickWinSpeech8::
	.string "呀！我看到{PLAYER}了！我\n"
	.string "……我见到你太高兴了！\p"
	.string "哦——哦——哦！有件事我非问你不\n"
	.string "可！\p"
	.string "不久前，我赢了一场对战。那部分让\n"
	.string "我飘飘然！\p"
	.string "但它让我太高兴了，我激动得说不出\n"
	.string "话来！\p"
	.string "所以现在，{PLAYER}，拜托\n"
	.string "了，我想让你帮我想一句赢了之后退\l"
	.string "场的台词！$"

gText_ApprenticeWinSpeechThanks8::
	.string "{STR_VAR_1}\p"
	.string "哇啊啊啊！我要说这句？！我……我\n"
	.string "高兴得快疯了！\p"
	.string "谢——谢——谢谢你！我现在没有遗\n"
	.string "憾了！\p"
	.string "我现在要去旅行了，要和各种各样的\n"
	.string "人对战。\p"
	.string "这一切，都归功于你，\n"
	.string "{PLAYER}。真的，真的，谢\l"
	.string "谢你！\p"
	.string "我得走了，但总有一天我们要在战场\n"
	.string "上见！$"

gText_ApprenticePickWinSpeech9::
	.string "喂，你好！{PLAYER}\n"
	.string "{KUN}！\p"
	.string "你知道吗，我有点想去各地旅行对战\n"
	.string "了。\p"
	.string "但在那之前，我还想再请教你一次，\n"
	.string "拜托了！\p"
	.string "如果我赢了比赛，有什么好的炫耀词\n"
	.string "可以对战败的训练家对手说呢？$"

gText_ApprenticeWinSpeechThanks9::
	.string "{STR_VAR_1}\p"
	.string "嗯哼，这话真棒！Si,\n"
	.string "bueno！嗯哼，我会试着这么说，就像，\l"
	.string "火腿！\p"
	.string "那么，是时候说再见了！感谢你为我\n"
	.string "做的一切！\p"
	.string "改天和我对战一场，好吗？再见！$"

gText_ApprenticePickWinSpeech10::
	.string "{PLAYER}{KUN}，出大\n"
	.string "麻烦了！\p"
	.string "我赢了比赛后，至少要吹嘘一个小时\n"
	.string "！\p"
	.string "当然我是骗你的！哇哈哈哈！\p"
	.string "不过这不是骗人的。我不太擅长聊天\n"
	.string "。\p"
	.string "所以，不如你替我决定一下赢了比赛\n"
	.string "后该说什么吧，师父？$"

gText_ApprenticeWinSpeechThanks10::
	.string "{STR_VAR_1}\p"
	.string "这就是我该说的，是吗？那么，我会\n"
	.string "远离那句的！\p"
	.string "开个玩笑啦！我会遵从您的教诲的，\n"
	.string "师父！\p"
	.string "谢谢您一直以来的教导，师父！\p"
	.string "我终于开始明白身为训练家意味着什\n"
	.string "么了。\p"
	.string "我要出去和任何训练家对战并赢得胜\n"
	.string "利。\p"
	.string "也许有一天会是你，师父！\p"
	.string "就这样吧！再见了，我的师父！$"

gText_ApprenticePickWinSpeech11::
	.string "A——H——O——Y！就是\n"
	.string "Ahoy，嗨的拼法！\p"
	.string "我就是那个说唱水手！这将是我最后\n"
	.string "的问题，你可别哭！\p"
	.string "这是个寻求你建议的台词问题！\p"
	.string "如果我赢了比赛，该怎么说才显得超\n"
	.string "酷？$"

gText_ApprenticeWinSpeechThanks11::
	.string "{STR_VAR_1}\p"
	.string "完美！我就用这句了。让你选果然是\n"
	.string "对的！\p"
	.string "那么现在，我想是时候让我展翅高飞\n"
	.string "了！\p"
	.string "谢谢你教会我的一切。我要出发去大\n"
	.string "干一场了！\p"
	.string "B——O——N——V——O——Y\n"
	.string "——A——G——E！就是Bon \l"
	.string "voyage的拼法，以此向你致敬\l"
	.string "！$"

gText_ApprenticePickWinSpeech12::
	.string "哦，耶，{PLAYER}！今天又\n"
	.string "找到你了！\p"
	.string "我该怎么办？再问你一次？为什么不\n"
	.string "呢？反正我都在问了！\p"
	.string "总之，{PLAYER}……你收到\n"
	.string "我的信号了吗？你收到了！我需要再\l"
	.string "要点建议！\p"
	.string "是关于我该喊什么的。战斗顺利结束\n"
	.string "时该喊点什么酷酷的话。\p"
	.string "来吧，我想听你说出来！$"

gText_ApprenticeWinSpeechThanks12::
	.string "{STR_VAR_1}\p"
	.string "好极了，好极了！我就用这句了，因\n"
	.string "为它太赞了！\p"
	.string "我已经没东西问你了。只剩下挥手告\n"
	.string "别了。\p"
	.string "但也许有一天我们会相遇，其中一人\n"
	.string "注定要败北。\p"
	.string "不过，真的该说再见了。\p"
	.string "嗯，{PLAYER}，我得自由闯\n"
	.string "荡了，但你可别忘了我！\p"
	.string "保重，{PLAYER}！爱你哟！$"

gText_ApprenticePickWinSpeech13::
	.string "{PLAYER}{KUN}，我完\n"
	.string "了……我的鼻涕止不住地流……\p"
	.string "我刚才在努力想赢了比赛时该说的酷\n"
	.string "酷台词。\p"
	.string "它太让我激动了，我哭了，现在我的\n"
	.string "鼻涕就停不下来……\p"
	.string "所以，情况就是这样，我需要你帮我\n"
	.string "决定，{PLAYER}{KUN}\l"
	.string "。\p"
	.string "我赢了比赛后，该说什么呢？$"

gText_ApprenticeWinSpeechThanks13::
	.string "{STR_VAR_1}\p"
	.string "……太棒了。\n"
	.string "不，这简直令人肃然起敬！感动得我\l"
	.string "眼泪都掉下来了！\p"
	.string "虽然眼泪鼻涕直流，但我一定要用这\n"
	.string "句台词！\p"
	.string "我已经没有什么可请教你的了，\n"
	.string "{PLAYER}{KUN}。\p"
	.string "从现在起，我们就是劲敌了！一直以\n"
	.string "来多谢你了！$"

gText_ApprenticePickWinSpeech14::
	.string "呃……嗯…{PLAYER}\n"
	.string "{KUN}……\p"
	.string "拜托，别那样看着我。你让我好紧张\n"
	.string "。\p"
	.string "我……我又需要你的建议了。不过这\n"
	.string "是最后一次了……\p"
	.string "问这个真的很不好意思，但如果我赢\n"
	.string "了比赛呢？我该说什么？$"

gText_ApprenticeWinSpeechThanks14::
	.string "{STR_VAR_1}\p"
	.string "哦……好的！我会试着说这句的！我\n"
	.string "可能会紧张得说不出来……\p"
	.string "谢谢你，{PLAYER}\n"
	.string "{KUN}。我现在得说再见了。\p"
	.string "我会遵从你教给我的一切，\n"
	.string "{PLAYER}{KUN}，尽我\l"
	.string "所能做到最好。$"

gText_ApprenticePickWinSpeech15::
	.string "嗯？你好像是{PLAYER}\n"
	.string "{KUN}……但你真的是吗？或许\l"
	.string "是个聪明的{PLAYER}人偶？\p"
	.string "哦，不不不，别担心！如果你是真的\n"
	.string "，请忘了我的无礼吧。\p"
	.string "没必要这么生气。我所希望的只是更\n"
	.string "多你宝贵的建议。\p"
	.string "是关于一句台词的。\p"
	.string "更确切地说，如果我赢了比赛，我该\n"
	.string "说什么？$"

gText_ApprenticeWinSpeechThanks15::
	.string "{STR_VAR_1}\p"
	.string "…… …… …… …… …… …\n"
	.string "当我赢了比赛时……\p"
	.string "{STR_VAR_1}\p"
	.string "……你是认真的吗？\p"
	.string "我明白了。如果你是认真的，那好吧\n"
	.string "。感谢你抽空帮我。\p"
	.string "我希望连我也能好好利用这句台词。\p"
	.string "我似乎已经想不出还需要什么建议了\n"
	.string "。\p"
	.string "我想是时候向你告别，独自出发了。\p"
	.string "谢谢你，我的导师！我为我的怀疑向\n"
	.string "你道歉！$"
