gText_ApprenticeChallenge0::
	.string "嗯，我是{STR_VAR_1}的\n"
	.string "第{STR_VAR_2}号徒弟。\l"
	.string "抽泣……这种紧张感快压垮我了……$"

gText_ApprenticeChallenge1::
	.string "我是{STR_VAR_1}的第\n"
	.string "{STR_VAR_2}号徒弟！我\l"
	.string "们来了！$"

gText_ApprenticeChallenge2::
	.string "我是{STR_VAR_1}的第\n"
	.string "{STR_VAR_2}号徒弟！接\l"
	.string "受我的挑战吧！$"

gText_ApprenticeChallenge3::
	.string "嗯……我是{STR_VAR_1}\n"
	.string "的第{STR_VAR_2}号徒弟\l"
	.string "……你觉得像我这样的人能赢吗？$"

gText_ApprenticeChallenge4::
	.string "我是{STR_VAR_1}的第\n"
	.string "{STR_VAR_2}号徒弟！我\l"
	.string "就让你挑战我吧！$"

gText_ApprenticeChallenge5::
	.string "我忙得要命，但我碰巧也是\n"
	.string "{STR_VAR_1}的第\l"
	.string "{STR_VAR_2}号徒弟。$"

gText_ApprenticeChallenge6::
	.string "我是{STR_VAR_1}的第\n"
	.string "{STR_VAR_2}号徒弟。很\l"
	.string "高兴见到你！$"

gText_ApprenticeChallenge7::
	.string "我担任{STR_VAR_1}的第\n"
	.string "{STR_VAR_2}号徒弟。我\l"
	.string "可以开始了吗？$"

gText_ApprenticeChallenge8::
	.string "呀！我是{STR_VAR_1}的\n"
	.string "第{STR_VAR_2}号徒弟！\l"
	.string "我会尽力的！$"

gText_ApprenticeChallenge9::
	.string "哟吼！我是{STR_VAR_1}\n"
	.string "的第{STR_VAR_2}号徒弟\l"
	.string "！放马过来吧！$"

gText_ApprenticeChallenge10::
	.string "我是{STR_VAR_1}的第1\n"
	.string "000个徒弟！其实是第\l"
	.string "{STR_VAR_2}号啦！我上\l"
	.string "了！$"

gText_ApprenticeChallenge11::
	.string "没错，我是{STR_VAR_1}\n"
	.string "的第{STR_VAR_2}号徒弟\l"
	.string "！让我们摇滚起来吧！$"

gText_ApprenticeChallenge12::
	.string "哟吼哟吼！我就是人们所说的\n"
	.string "{STR_VAR_1}的第\l"
	.string "{STR_VAR_2}号徒弟！$"

gText_ApprenticeChallenge13::
	.string "咳！我是{STR_VAR_1}的\n"
	.string "第{STR_VAR_2}号徒弟。\l"
	.string "很高兴见到你！咳咳！$"

gText_ApprenticeChallenge14::
	.string "这太紧张了……我是\n"
	.string "{STR_VAR_1}的第\l"
	.string "{STR_VAR_2}号徒弟。$"

gText_ApprenticeChallenge15::
	.string "我是{STR_VAR_1}的第\n"
	.string "{STR_VAR_2}号徒弟，这\l"
	.string "可不是骗人的。$"

gText_ApprenticePleaseTeach0::
	.string "你是……{PLAYER}吗？哦！\n"
	.string "抽泣……呜咽……\p"
	.string "哦！对——对不起……我太紧张了，\n"
	.string "忍不住哭了……\p"
	.string "我是{STR_VAR_1}，我真\n"
	.string "的非常崇拜你，{PLAYER}。\p"
	.string "我……我一直梦想着有一天能见到你\n"
	.string "并向你请教关于宝可梦的事。\p"
	.string "求求你，求求你了，\n"
	.string "{PLAYER}！请务必教我关于\l"
	.string "宝可梦的知识！$"

gText_ApprenticeRejectTeaching0::
	.string "哦……可——可是……抽泣……哇啊\n"
	.string "啊啊！\p"
	.string "求你了！我求求你了，拜托！$"

gText_ApprenticeWhichLevelMode0::
	.string "哦，真的吗？你答应了？太棒了！太\n"
	.string "厉害了！嗷呜！\p"
	.string "哦……对不起……我太高兴了，又哭\n"
	.string "了……\p"
	.string "嗯……那么请告诉我！是关于对战塔\n"
	.string "的事。\p"
	.string "对我来说，Lv. 50级还是自由\n"
	.string "等级哪个更好？$"

gText_ApprenticeLevelModeThanks0::
	.string "{STR_VAR_1}？哇啊啊啊\n"
	.string "！\p"
	.string "哦！真对不起！你替我选择了级别让\n"
	.string "我很高兴，这又让我哭了……\p"
	.string "抽泣……太感谢你了！请再和我聊聊\n"
	.string "！$"

gText_ApprenticePleaseTeach1::
	.string "哇哦！你是{PLAYER}，对吧\n"
	.string "？你超强的，对吧？\p"
	.string "我是{STR_VAR_1}！我刚\n"
	.string "成为训练家！\p"
	.string "求你了，{PLAYER}！你能当\n"
	.string "我的老师，告诉我很多关于成为训练\l"
	.string "家的事吗？$"

gText_ApprenticeRejectTeaching1::
	.string "啊，为什么啊？哦，拜托？求求你了\n"
	.string "？请当我的老师吧，拜托！$"

gText_ApprenticeWhichLevelMode1::
	.string "耶！太好了！\p"
	.string "我想问你的第一件事是关于对战塔的\n"
	.string "！\p"
	.string "Lv. 50级和自由等级的房间…\n"
	.string "…哪个最适合我？$"

gText_ApprenticeLevelModeThanks1::
	.string "{STR_VAR_1}，是吧？没\n"
	.string "错！我会在那里努力的！\p"
	.string "如果我们在这里再见，请再教我点别\n"
	.string "的，老师！$"

gText_ApprenticePleaseTeach2::
	.string "嗯……你是{PLAYER}吗？我\n"
	.string "的名字是{STR_VAR_1}。\p"
	.string "我想成为一名宝可梦训练家，但我不\n"
	.string "知道该怎么办……\p"
	.string "所以我想也许可以请教你，因为你很\n"
	.string "有名。\p"
	.string "{PLAYER}，你能给我一些建\n"
	.string "议吗？$"

gText_ApprenticeRejectTeaching2::
	.string "哦，但是……\p"
	.string "我是真心想成为一名宝可梦训练家的\n"
	.string "！\p"
	.string "拜托，你能回答我的问题吗？$"

gText_ApprenticeWhichLevelMode2::
	.string "谢谢！我马上问第一个问题！\p"
	.string "对战塔有2个级别，Lv. 50级\n"
	.string "和自由等级，对吧？\p"
	.string "你觉得哪个级别更适合我？$"

gText_ApprenticeLevelModeThanks2::
	.string "哦，挑战{STR_VAR_1}？\n"
	.string "明白了！\p"
	.string "如果我有其他问题，我会回来寻求你\n"
	.string "的建议！$"

gText_ApprenticePleaseTeach3::
	.string "哦？啊？你是……不，那不可能是真\n"
	.string "的。\p"
	.string "像我这样的人不可能遇到\n"
	.string "{PLAYER}。\p"
	.string "……你真的是{PLAYER}？真\n"
	.string "不敢相信我正在和你说话！\p"
	.string "当这么好的事情发生时，我知道现在\n"
	.string "只会发生可怕的事情在我身上……\p"
	.string "……对不起……我是……\n"
	.string "{STR_VAR_1}……\p"
	.string "我没什么特别之处可以引以为豪……\p"
	.string "我甚至不应该说任何关于自己的事，\n"
	.string "因为你一定会忘记……\p"
	.string "我曾梦想着如果我能遇到你，\n"
	.string "{PLAYER}，也许我就能以训\l"
	.string "练家的身份向你寻求建议。\p"
	.string "但我觉得你不会同意那样的事。\p"
	.string "……或者你会好心地给我建议吗？$"

gText_ApprenticeRejectTeaching3::
	.string "我就知道会这样……\p"
	.string "这一定是因为我真是个无聊的小人物\n"
	.string "……\p"
	.string "但我以为也许还有机会……你不会重\n"
	.string "新考虑一下，对吧？\p"
	.string "但我不能就这样放弃。趁着我运气还\n"
	.string "在，我要问你！\p"
	.string "拜托，你能好心地给我建议吗？$"

gText_ApprenticeWhichLevelMode3::
	.string "真的吗？我不敢相信！真不敢相信你\n"
	.string "会给我建议！我……我太高兴了……\p"
	.string "我想问你的其实很琐碎，但我无法决\n"
	.string "定……\p"
	.string "在对战塔，他们让你选择Lv. 5\n"
	.string "0级或自由等级。\p"
	.string "你觉得哪个级别哪怕像我这样的人也\n"
	.string "可能有机会？$"

gText_ApprenticeLevelModeThanks3::
	.string "{STR_VAR_1}？好的！但\n"
	.string "你真的觉得像我这样的人会有机会吗\l"
	.string "？\p"
	.string "我会尽力的，尽管我不认为会成功。\p"
	.string "非常感谢你花时间陪伴像我这样的人\n"
	.string "。$"

gText_ApprenticePleaseTeach4::
	.string "哦！你是{PLAYER}\n"
	.string "{KUN}，对吧？\p"
	.string "我听说你在宝可梦方面很强！\p"
	.string "我是{STR_VAR_1}！我会\n"
	.string "成为你的朋友！\p"
	.string "你知道吗？\p"
	.string "如果你只知道训练家学校教的东西，\n"
	.string "你就无法在对战开拓区获胜。\p"
	.string "我愿意听取你的建议。你当然会同意\n"
	.string "吧？$"

gText_ApprenticeRejectTeaching4::
	.string "嗯？你为什么要拒绝我？是我在问你\n"
	.string "啊！你必须重新考虑！$"

gText_ApprenticeWhichLevelMode4::
	.string "好的，所以有件事。我想让你替我决\n"
	.string "定。\p"
	.string "你知道对战塔有Lv. 50级和自\n"
	.string "由等级的房间吧？\p"
	.string "你觉得哪个会适合我，\n"
	.string "{PLAYER}{KUN}？$"

gText_ApprenticeLevelModeThanks4::
	.string "好的，{STR_VAR_1}适合\n"
	.string "我？谢谢你！\p"
	.string "知道是你做的决定，\n"
	.string "{PLAYER}{KUN}，就算\l"
	.string "我输了也不会那么难过。\p"
	.string "好的，我会再来向你寻求建议。再见\n"
	.string "！$"

gText_ApprenticePleaseTeach5::
	.string "哦，嗨，你好！{PLAYER}\n"
	.string "{KUN}！我认识你，因为你很有\l"
	.string "名！叫我{STR_VAR_1}！\l"
	.string "很高兴见到你！\p"
	.string "我是个铁人三项选手，所以我即使在\n"
	.string "培育宝可梦时也保持健康。\p"
	.string "我还参与其他事情，比如工作、打盹\n"
	.string "、交谊舞……\p"
	.string "这么忙，对我来说要成为一个像样的\n"
	.string "训练家可不容易。\p"
	.string "所以，我有个提议！\p"
	.string "我们相遇一定有原因。所以，\n"
	.string "{PLAYER}{KUN}，不如\l"
	.string "你偶尔和我分享你的智慧？$"

gText_ApprenticeRejectTeaching5::
	.string "哦，但是，拜托？像我这样的人需要\n"
	.string "你这样的人，{PLAYER}\l"
	.string "{KUN}！\p"
	.string "老实说，我需要你的建议！$"

gText_ApprenticeWhichLevelMode5::
	.string "谢谢你！这才对嘛！那么，我们从一\n"
	.string "个简单的问题开始！\p"
	.string "你知道对战塔的2个级别，对吧？就\n"
	.string "是Lv. 50级和自由等级。\p"
	.string "像我这样的大忙人，应该为哪个做准\n"
	.string "备？$"

gText_ApprenticeLevelModeThanks5::
	.string "{STR_VAR_1}，是吧？好\n"
	.string "的，明白了。我会想办法找时间试试\l"
	.string "看的！\p"
	.string "……哎呀，我得去上班了！谢谢！回\n"
	.string "头见！$"

gText_ApprenticePleaseTeach6::
	.string "不可能！呃——呃！你该不会是真正\n"
	.string "的{PLAYER}吧？\p"
	.string "啊哈！太棒了！我是\n"
	.string "{STR_VAR_1}，很高兴见\l"
	.string "到你！\p"
	.string "{PLAYER}，你很强，对吧？\p"
	.string "大家都在谈论你！\p"
	.string "哦！我刚刚有个超棒的主意！我要向\n"
	.string "你请教，{PLAYER}！我相信\l"
	.string "这能让我变强！\p"
	.string "这不是个好主意吗？拜托，我想要你\n"
	.string "的建议！$"

gText_ApprenticeRejectTeaching6::
	.string "啊哈哈哈，你可以假装很凶，但你骗\n"
	.string "不了我！你其实是答应的意思，对吧\l"
	.string "？$"

gText_ApprenticeWhichLevelMode6::
	.string "耶！我就知道你心胸宽广，\n"
	.string "{PLAYER}！\p"
	.string "我该先问你什么呢？……哦，我想到\n"
	.string "了！\p"
	.string "请鼓掌！我的问题是……\p"
	.string "如果我要挑战对战塔，我该走哪条路\n"
	.string "？\p"
	.string "Lv. 50级还是自由等级？哪个\n"
	.string "更适合我？$"

gText_ApprenticeLevelModeThanks6::
	.string "哦——哦——哦！\n"
	.string "{STR_VAR_1}，你说！谢\l"
	.string "谢你超级酷的回答！\p"
	.string "我想今天要问你的就这些了。\p"
	.string "让我们在这里再见，好吗？谢谢！$"

gText_ApprenticePleaseTeach7::
	.string "打扰一下，请问……你是\n"
	.string "{PLAYER}吗？\p"
	.string "我是{STR_VAR_1}，很高\n"
	.string "兴认识你。\p"
	.string "我仰慕你很久了……\p"
	.string "…… … … … … …\p"
	.string "嗯……希望你觉得这个请求不会太麻\n"
	.string "烦，但是……\p"
	.string "我可以成为你的徒弟吗，\n"
	.string "{PLAYER}？$"

gText_ApprenticeRejectTeaching7::
	.string "哦……！\p"
	.string "…… … … … … …\n"
	.string "… … … … … …\p"
	.string "……我一定是震惊得晕过去了。对不\n"
	.string "起，我一定是听错了。\p"
	.string "拜托！请说你愿意收我为徒！$"

gText_ApprenticeWhichLevelMode7::
	.string "哦……我很高兴！\p"
	.string "我不想浪费你的时间，所以请在这件\n"
	.string "事上给我建议。\p"
	.string "我计划不久后参加对战塔挑战。\p"
	.string "但是，有2个级别……\p"
	.string "哪个最适合我？Lv. 50级还是\n"
	.string "自由等级？$"

gText_ApprenticeLevelModeThanks7::
	.string "{STR_VAR_1} is your choice!\n"
	.string "I see. I will do my best!\p"
	.string "Thank you, {PLAYER}.\n"
	.string "I hope I can count on you again.\l"
	.string "Please take care!$"

gText_ApprenticePleaseTeach8::
	.string "Eek! Eek! {PLAYER}!\n"
	.string "You spoke to me!\l"
	.string "I… I'm overjoyed!\p"
	.string "Me! My name is {STR_VAR_1}!\n"
	.string "I just became a TRAINER!\p"
	.string "I'm delighted I met you, {PLAYER},\n"
	.string "the big name in POKéMON circles!\p"
	.string "Oh-oh-oh, I know!\n"
	.string "May I ask a huge favor, {PLAYER}?\p"
	.string "Please take me in as your apprentice!\n"
	.string "I want to learn from you!$"

gText_ApprenticeRejectTeaching8::
	.string "哇啊啊！{PLAYER}拒绝了我\n"
	.string "……这……这是宝贵的经验！\p"
	.string "{PLAYER}，拜托！这次我想\n"
	.string "听到肯定的回答！\p"
	.string "我恳求你的指导！$"

gText_ApprenticeWhichLevelMode8::
	.string "咿耶！{PLAYER}说好！\n"
	.string "{PLAYER}说好！\p"
	.string "我今晚会睡不着觉了……太感谢你了\n"
	.string "！\p"
	.string "那么，这是我的问题！\p"
	.string "在对战塔，什么适合我，Lv. 5\n"
	.string "0级还是自由等级？$"

gText_ApprenticeLevelModeThanks8::
	.string "{STR_VAR_1}！完全明白\n"
	.string "了！我完全明白！我高兴得要发狂了\l"
	.string "！\p"
	.string "希望下次你愿意再教我一些东西。$"

gText_ApprenticePleaseTeach9::
	.string "哇！你该不会是……难道是……\n"
	.string "{PLAYER}{KUN}？！那\l"
	.string "个强大又著名的训练家？你好，我简\l"
	.string "直太幸运了！\p"
	.string "你好，我叫{STR_VAR_1}\n"
	.string "！\p"
	.string "我一直在寻找一位宝可梦老师。\p"
	.string "而你来得正是时候，\n"
	.string "{PLAYER}{KUN}！\p"
	.string "所以，就是这样，{PLAYER}\n"
	.string "{KUN}！让我拜你为师吧！$"

gText_ApprenticeRejectTeaching9::
	.string "呱啊啊啊！你真是又酷又硬派……\p"
	.string "别这样，拜托。我是在请求你！$"

gText_ApprenticeWhichLevelMode9::
	.string "哦，耶！这是坚定的回答！太棒了，\n"
	.string "我得说！\p"
	.string "那么，对战塔的第一个建议怎么样？\p"
	.string "如果我要去，哪个更好？Lv. 5\n"
	.string "0级还是自由等级？$"

gText_ApprenticeLevelModeThanks9::
	.string "嗯哼，{STR_VAR_1}是吧\n"
	.string "！好，A——OK！我会去展示我的\l"
	.string "实力，就像，酷炫！\p"
	.string "好的，我会把你当作我的导师！再见\n"
	.string "！$"

gText_ApprenticePleaseTeach10::
	.string "Oh, hey, {PLAYER}{KUN}, right?\n"
	.string "The police were looking for you!\p"
	.string "… … …\n"
	.string "Of course I'm lying!\p"
	.string "Me, I'm {STR_VAR_1}. Despite the way\n"
	.string "I look, I'm the POKéMON CHAMPION!\l"
	.string "…That's a lie, too!\p"
	.string "This is no lie, though.\n"
	.string "I'm not very good at battling.\p"
	.string "So, how about you becoming my master\n"
	.string "about all things POKéMON?$"

gText_ApprenticeRejectTeaching10::
	.string "如果你要表现得这么冷淡，我就让你\n"
	.string "看看我会做什么！\p"
	.string "哇！哇！哇！嗝！\p"
	.string "哈哈哈，那是我装的眼泪！\p"
	.string "来吧，拜托你当我的宝可梦师父好吗\n"
	.string "？$"

gText_ApprenticeWhichLevelMode10::
	.string "耶比！我会给你买艘船！\p"
	.string "当然我又在撒谎！但是……谢谢你，\n"
	.string "师父！\p"
	.string "你知道对战塔有Lv. 50级和自\n"
	.string "由等级吧？\p"
	.string "我正纠结该挑战哪个级别……\p"
	.string "师父你能替我决定吗？$"

gText_ApprenticeLevelModeThanks10::
	.string "Okay, so {STR_VAR_1} is better!\n"
	.string "I'll go to the other level, then!\p"
	.string "Just kidding!\n"
	.string "I'll obey your teaching, master!\p"
	.string "Thanks, master!\n"
	.string "I hope you'll keep teaching me!$"

gText_ApprenticePleaseTeach11::
	.string "A-H-O-Y!\n"
	.string "And that spells ahoy, and it means hi!\p"
	.string "I'm {STR_VAR_1}, the rappin' SAILOR\n"
	.string "am I!\p"
	.string "Your turn now, tell me a little about\n"
	.string "yourself, give it a try!\p"
	.string "Uh-huh, uh-huh!\n"
	.string "{PLAYER}{KUN}'s your name,\l"
	.string "and POKéMON's your game!\p"
	.string "And you're at a delicate age\n"
	.string "when all the world's your stage!\p"
	.string "Anyway, I just want to say,\n"
	.string "that you're the tenth TRAINER\l"
	.string "I've spoken to today.\p"
	.string "Let's make that a celebration!\n"
	.string "Become my mentor for commemoration!$"

gText_ApprenticeRejectTeaching11::
	.string "但是！你必须配合我！\p"
	.string "别这么逗我了！请当我的导师吧！$"

gText_ApprenticeWhichLevelMode11::
	.string "就这样！{PLAYER}，你有这\n"
	.string "个精神！\p"
	.string "所以这是我的第一个问题，需要你的\n"
	.string "建议！\p"
	.string "是关于对战塔的，这取决于我的实力\n"
	.string "！\p"
	.string "那里有Lv. 50级和自由等级，\n"
	.string "哪个才是我该选的级别？$"

gText_ApprenticeLevelModeThanks11::
	.string "好的，{STR_VAR_1}，你\n"
	.string "说！我会去的，就在路上！\p"
	.string "如果我需要建议，{PLAYER}\n"
	.string "，你的话我永远听从！$"

gText_ApprenticePleaseTeach12::
	.string "Say, hey, aren't you {PLAYER}?\n"
	.string "What should I do? Talk to you?\l"
	.string "Why not? I'm already talking to you!\p"
	.string "{PLAYER}, are you surprised at me?\n"
	.string "I'd better tell you who I happen to be!\p"
	.string "{STR_VAR_1} is what you can call me.\n"
	.string "The brightest star in guitardom,\l"
	.string "that's me!\p"
	.string "Are you receiving me?\n"
	.string "You are receiving me!\p"
	.string "My luck's at its best,\n"
	.string "I'll hit you with a request!\p"
	.string "{PLAYER}, let me be your underling!\n"
	.string "I want you to teach me everything!$"

gText_ApprenticeRejectTeaching12::
	.string "You're turning me down, then?\n"
	.string "I'll just have to ask you again!\p"
	.string "{PLAYER}, I beg to be your underling!\n"
	.string "I need you to teach me everything!$"

gText_ApprenticeWhichLevelMode12::
	.string "幸运，耶，呜呼！我该问你个问题吗\n"
	.string "？\p"
	.string "既然我们在对战塔附近，不如问个关\n"
	.string "于它实力的问题？\p"
	.string "在你能看到的选择中，哪个才是我该\n"
	.string "选的？$"

gText_ApprenticeLevelModeThanks12::
	.string "如果{STR_VAR_1}是你建\n"
	.string "议的，那它一定是最棒的！\p"
	.string "嗯，{PLAYER}，我必须自由\n"
	.string "漫游，但你别忘了我。\p"
	.string "再见了，我聪明的朋友！$"

gText_ApprenticePleaseTeach13::
	.string "Oh, hi! You there!\n"
	.string "Can I get you to massage my shoulder?\p"
	.string "…Yes, there! That's it!\n"
	.string "Ouch, ouch! Oooh, that feels great!\p"
	.string "My name's {STR_VAR_1}.\n"
	.string "I take karate training, but my body's\l"
	.string "not built to take the abuse…\p"
	.string "I decided I'll battle POKéMON and\n"
	.string "toughen myself up.\p"
	.string "You're {PLAYER}{KUN}, aren't you?\n"
	.string "The POKéMON LEAGUE CHAMP?\p"
	.string "Listen, can I get you to give me\n"
	.string "advice?$"

gText_ApprenticeRejectTeaching13::
	.string "Oh, why?\p"
	.string "I won't be a big bother, I promise!\n"
	.string "Please?$"

gText_ApprenticeWhichLevelMode13::
	.string "谢谢你。你真是太好了！……咳！咳\n"
	.string "！\p"
	.string "呃，我得快点变强……\p"
	.string "我马上就去对战塔，但对我来说哪个\n"
	.string "更好？Lv. 50级还是自由等级\l"
	.string "？$"

gText_ApprenticeLevelModeThanks13::
	.string "Hm, all right. That's {STR_VAR_1}.\n"
	.string "I'll go there right away.\p"
	.string "I hope I can keep hitting you up for\n"
	.string "help--after all, you're my mentor!$"

gText_ApprenticePleaseTeach14::
	.string "Er… Um…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "Please, don't look at me that way.\n"
	.string "You're making me all self-conscious.\p"
	.string "I… I'm {STR_VAR_1}.\p"
	.string "I'm really embarrassed to say this,\n"
	.string "but I explore ancient ruins and such.\p"
	.string "I'm even more embarrassed to admit\n"
	.string "I'm interested in the BATTLE FRONTIER.\p"
	.string "{PLAYER}{KUN}, you have a reputation as\n"
	.string "a tough TRAINER…\p"
	.string "It's hard for me to say this,\n"
	.string "but I want to ask something.\p"
	.string "Could you become my teacher and\n"
	.string "give me advice?$"

gText_ApprenticeRejectTeaching14::
	.string "Please don't brush me off like this!\n"
	.string "I can't live with the humiliation.\p"
	.string "Please become my teacher!\n"
	.string "I need your advice!$"

gText_ApprenticeWhichLevelMode14::
	.string "Th-thank you…\p"
	.string "But please don't look at me like that.\n"
	.string "It makes me all flustered.\p"
	.string "Please, answer me without looking\n"
	.string "at my eyes.\p"
	.string "At the BATTLE TOWER…\n"
	.string "Which level should I attempt?$"

gText_ApprenticeLevelModeThanks14::
	.string "Oh… Okay!\n"
	.string "I'll try my hand at that.\p"
	.string "I hope I can make a valiant challenge\n"
	.string "without getting all flustered…\p"
	.string "Thank you, {PLAYER}{KUN}.\n"
	.string "If we meet again, I hope you will be\l"
	.string "as helpful.$"

gText_ApprenticePleaseTeach15::
	.string "Hm? You appear to be {PLAYER}{KUN}…\n"
	.string "But are you really real?\p"
	.string "You may call me {STR_VAR_1}.\p"
	.string "I have been toying with the idea of\n"
	.string "apprenticing under a strong TRAINER.\p"
	.string "So, I must say I'm lucky you came along!\n"
	.string "…You really are {PLAYER}{KUN}, yes?\p"
	.string "No, no, if you are real, it's fine.\n"
	.string "I merely want you to recognize me\l"
	.string "as your apprentice.$"

gText_ApprenticeRejectTeaching15::
	.string "Oh?\n"
	.string "But what would compel you to refuse?\p"
	.string "I apologize for being skeptical about\n"
	.string "your identity.\p"
	.string "Please accept my apology and\n"
	.string "accept me as your apprentice.$"

gText_ApprenticeWhichLevelMode15::
	.string "You really are accepting me?\n"
	.string "I don't wish to celebrate prematurely.\p"
	.string "If it is true, I apologize.\n"
	.string "But now, I need your advice.\p"
	.string "If I were to enter the BATTLE TOWER,\n"
	.string "what would be worthy of me?\l"
	.string "Level 50 or Open Level?$"

gText_ApprenticeLevelModeThanks15::
	.string "{STR_VAR_1}?\n"
	.string "Are you certain?\p"
	.string "I see. If that's the case, that's fine.\n"
	.string "I thank you for your time.\p"
	.string "I realize I can annoy, but it delights\n"
	.string "me that you have accepted me.\p"
	.string "Let us meet again!$"

gText_ApprenticeWhatHeldItem0::
	.string "Sigh… Sob…\n"
	.string "Oh, {PLAYER}!\p"
	.string "I'm all tangled up in a dilemma\n"
	.string "that I can't decide.\p"
	.string "I can't decide what I should make\n"
	.string "my {STR_VAR_1} hold.\p"
	.string "Please tell me, {PLAYER}.\n"
	.string "What item should I make it hold?$"

gText_ApprenticeHoldNothing0::
	.string "哦，真的吗？我不该让我的\n"
	.string "{STR_VAR_1}携带任何东\l"
	.string "西？$"

gText_ApprenticeThanksNoHeldItem0::
	.string "哦，好的！很高兴问题解决了！太棒\n"
	.string "了！太厉害了！嗷呜！\p"
	.string "非常感谢你！$"

gText_ApprenticeThanksHeldItem0::
	.string "哦，我太高兴了……我想我也有\n"
	.string "{STR_VAR_1}呢。\p"
	.string "很高兴问题解决了！太棒了！太厉害\n"
	.string "了！嗷呜！\p"
	.string "非常感谢你！$"

gText_ApprenticeItemAlreadyRecommended0::
	.string "哇哇哇！请不要这么刻薄！\p"
	.string "道具{STR_VAR_1}之前已\n"
	.string "经有人推荐过了，呜咽……\p"
	.string "或者你是说我不该让我的\n"
	.string "{STR_VAR_2}携带任何东\l"
	.string "西？$"

gText_ApprenticeWhatHeldItem1::
	.string "耶！是{PLAYER}！太好了！\n"
	.string "我想问你点事！\p"
	.string "你会让宝可梦携带道具吗？我也想让\n"
	.string "我宝可梦携带，但是……\p"
	.string "什么道具适合\n"
	.string "{STR_VAR_1}携带呢？\p"
	.string "你觉得呢？$"

gText_ApprenticeHoldNothing1::
	.string "嗯？你是说我的\n"
	.string "{STR_VAR_1}不用携带任\l"
	.string "何东西？$"

gText_ApprenticeThanksNoHeldItem1::
	.string "哦，明白了！我会照做的！谢谢你教\n"
	.string "我！$"

gText_ApprenticeThanksHeldItem1::
	.string "哦，哇！{STR_VAR_1}，\n"
	.string "是吧？好的，我会用那个！\p"
	.string "谢谢你教我！$"

gText_ApprenticeItemAlreadyRecommended1::
	.string "Oh, uh, no, that's not what I meant.\n"
	.string "I want to know about a different item\l"
	.string "than the ones I already know.\p"
	.string "Or do you mean that my POKéMON doesn't\n"
	.string "have to hold anything this time?$"

gText_ApprenticeWhatHeldItem2::
	.string "{PLAYER}，你好！是关于我\n"
	.string "的{STR_VAR_1}……\p"
	.string "我想让它携带个好道具。什么适合它\n"
	.string "呢？$"

gText_ApprenticeHoldNothing2::
	.string "哦，那我的{STR_VAR_1}\n"
	.string "不需要携带任何东西？$"

gText_ApprenticeThanksNoHeldItem2::
	.string "好的，明白了！下次见！$"

gText_ApprenticeThanksHeldItem2::
	.string "哦，道具{STR_VAR_1}？\n"
	.string "明白了！\p"
	.string "我会尽力找一个的！下次见！$"

gText_ApprenticeItemAlreadyRecommended2::
	.string "有人已经教过我关于\n"
	.string "{STR_VAR_1}的事了。\p"
	.string "我想要我的宝可梦携带不同类型的道\n"
	.string "具。\p"
	.string "或者你觉得{STR_VAR_2}\n"
	.string "不需要携带任何东西？$"

gText_ApprenticeWhatHeldItem3::
	.string "你好，{PLAYER}……很抱歉\n"
	.string "打扰你，但我还有件事想问。\p"
	.string "我觉得自己不够强，无法独自赢比赛\n"
	.string "，所以想让我的\l"
	.string "{STR_VAR_1}携带道具。\p"
	.string "但不知道什么才好。\p"
	.string "{PLAYER}，拜托，你能替我\n"
	.string "决定吗？$"

gText_ApprenticeHoldNothing3::
	.string "像我这样的人的宝可梦不带道具更好\n"
	.string "？$"

gText_ApprenticeThanksNoHeldItem3::
	.string "我明白了……你是说我不该依赖道具\n"
	.string "。我会尽力不依赖的！\p"
	.string "非常感谢你！$"

gText_ApprenticeThanksHeldItem3::
	.string "道具{STR_VAR_1}，好的\n"
	.string "。我不确定能不能弄到一个……不！\l"
	.string "我会尽力搞到的。\p"
	.string "非常感谢你！$"

gText_ApprenticeItemAlreadyRecommended3::
	.string "哦，但是……我想我以前听说过……\p"
	.string "是不是因为我没用好道具\n"
	.string "{STR_VAR_1}？\p"
	.string "或者你是说我不该让我的\n"
	.string "{STR_VAR_2}携带任何东\l"
	.string "西？$"

gText_ApprenticeWhatHeldItem4::
	.string "哦，{PLAYER}{KUN}。\n"
	.string "有件事我想问你。\p"
	.string "你知道你之前决定了我该用哪只宝可\n"
	.string "梦吧？\p"
	.string "但我没问你它该携带什么道具。\p"
	.string "既然你已经给了我建议，不如有始有\n"
	.string "终？\p"
	.string "什么比较好？我想让我的\n"
	.string "{STR_VAR_1}带点东西。$"

gText_ApprenticeHoldNothing4::
	.string "哦！所以我的\n"
	.string "{STR_VAR_1}应该空手上\l"
	.string "阵做到最好？$"

gText_ApprenticeThanksNoHeldItem4::
	.string "如果你觉得这样最好，我会照做。\p"
	.string "知道是你做的决定，\n"
	.string "{PLAYER}{KUN}，就算\l"
	.string "我输了也不会太难过。\p"
	.string "好的，我会再来向你请教。再见！$"

gText_ApprenticeThanksHeldItem4::
	.string "道具{STR_VAR_1}，是吧\n"
	.string "？不错。我会用的！\p"
	.string "知道是你做的决定，\n"
	.string "{PLAYER}{KUN}，就算\l"
	.string "我输了也不会太难过。\p"
	.string "好的，我会再来向你请教。再见！$"

gText_ApprenticeItemAlreadyRecommended4::
	.string "嗯？你在说什么？你之前已经告诉过\n"
	.string "{STR_VAR_1}的事了。\p"
	.string "或者你是说我的\n"
	.string "{STR_VAR_2}应该空手上\l"
	.string "阵做到最好？$"

gText_ApprenticeWhatHeldItem5::
	.string "Yo, {PLAYER}{KUN}!\p"
	.string "We're both busy, but we seem to run\n"
	.string "into each other often anyway!\p"
	.string "Today I have to do some walking,\n"
	.string "cleaning, and brushing.\p"
	.string "I haven't even had the time to buy\n"
	.string "my precious {STR_VAR_1} anything.\p"
	.string "I don't have any time, so how about\n"
	.string "giving me advice on what I should make\l"
	.string "my {STR_VAR_1} hold?$"

gText_ApprenticeHoldNothing5::
	.string "哦，所以像我这样的大忙人，你说我\n"
	.string "的{STR_VAR_1}不需要任\l"
	.string "何东西？$"

gText_ApprenticeThanksNoHeldItem5::
	.string "好的，知道了。我不需要为此花时间\n"
	.string "。\p"
	.string "今天谢谢了！回头见！$"

gText_ApprenticeThanksHeldItem5::
	.string "好的，知道了。我会想办法找时间找\n"
	.string "到你推荐的{STR_VAR_1}\l"
	.string "。\p"
	.string "我很高兴遇到你这样的好导师。谢谢\n"
	.string "！回头见！$"

gText_ApprenticeItemAlreadyRecommended5::
	.string "嗯？我已经知道那个\n"
	.string "{STR_VAR_1}了。\p"
	.string "哦，对了，我懂了。所以像我这样的\n"
	.string "大忙人，你说我的\l"
	.string "{STR_VAR_2}不需要任何\l"
	.string "东西？$"

gText_ApprenticeWhatHeldItem6::
	.string "Hiya, {PLAYER}! It's me!\n"
	.string "I need to tap your mind again today.\l"
	.string "Please, I need your advice!\p"
	.string "Drum roll, please!\n"
	.string "The question I have is…\p"
	.string "If I want to make my {STR_VAR_1} hold\n"
	.string "an item, what should it be?$"

gText_ApprenticeHoldNothing6::
	.string "是吗？你是说我的\n"
	.string "{STR_VAR_1}不需要携带\l"
	.string "道具？$"

gText_ApprenticeThanksNoHeldItem6::
	.string "好的，我会照做的！\p"
	.string "我想今天要问的就这些了。\p"
	.string "让我们在这里再见，好吗？谢谢！$"

gText_ApprenticeThanksHeldItem6::
	.string "嗯哼！{STR_VAR_1}。多\n"
	.string "酷的选择！我一定会试试的！\p"
	.string "我想今天要问的就这些了。\p"
	.string "让我们在这里再见，好吗？谢谢！$"

gText_ApprenticeItemAlreadyRecommended6::
	.string "啊哈哈！真傻！你之前已经告诉过\n"
	.string "{STR_VAR_1}的事了！\p"
	.string "你还好吗，{PLAYER}？\p"
	.string "哦，等等！你是说我的\n"
	.string "{STR_VAR_2}不需要携带\l"
	.string "任何道具？$"

gText_ApprenticeWhatHeldItem7::
	.string "你好，{PLAYER}。希望你一\n"
	.string "切安好。\p"
	.string "我可以请教你吗？\p"
	.string "最近一次对战中，对手似乎让他的宝\n"
	.string "可梦携带了道具。\p"
	.string "结果，我被打败了……\p"
	.string "我不想落后。我也想让我\n"
	.string "{STR_VAR_1}携带道具。\p"
	.string "如果你能决定什么适合我的宝可梦就\n"
	.string "太好了……$"

gText_ApprenticeHoldNothing7::
	.string "换句话说……我的宝可梦不需要携带\n"
	.string "道具？$"

gText_ApprenticeThanksNoHeldItem7::
	.string "I understand clearly now!\n"
	.string "I will keep trying like this.\p"
	.string "Thank you, {PLAYER}.\n"
	.string "I hope I can count on you again.\l"
	.string "Please take care!$"

gText_ApprenticeThanksHeldItem7::
	.string "One {STR_VAR_1} it is!\n"
	.string "I will order it right away.\p"
	.string "Thank you, {PLAYER}.\n"
	.string "I hope I can count on you again.\l"
	.string "Please take care!$"

gText_ApprenticeItemAlreadyRecommended7::
	.string "你已经告诉过我了，而且我已经有了\n"
	.string "。\p"
	.string "或者你是说……我的宝可梦不需要携\n"
	.string "带道具？$"

gText_ApprenticeWhatHeldItem8::
	.string "呀！{PLAYER}！我……又见\n"
	.string "到你我太高兴了！\p"
	.string "哦——哦——哦！有件事我一定要问\n"
	.string "你，{PLAYER}！\p"
	.string "请决定我的{STR_VAR_1}\n"
	.string "该携带什么！$"

gText_ApprenticeHoldNothing8::
	.string "哦，哇！我没想到这个回答！所以，\n"
	.string "携带道具不是必须的？$"

gText_ApprenticeThanksNoHeldItem8::
	.string "完全明白了！我会继续不用道具努力\n"
	.string "的！\p"
	.string "希望下次你愿意再教我些东西。$"

gText_ApprenticeThanksHeldItem8::
	.string "{STR_VAR_1}! I'll use that!\p"
	.string "Um… Could it be, {PLAYER}, you also\n"
	.string "make your POKéMON hold that item?\p"
	.string "I'll be sure to get it!\n"
	.string "I hope you'll be willing to teach me\l"
	.string "some more another time.$"

gText_ApprenticeItemAlreadyRecommended8::
	.string "哦？你之前也推荐过\n"
	.string "{STR_VAR_1}。\p"
	.string "或者这是最好的携带物？还是说我的\n"
	.string "{STR_VAR_2}不需要携带\l"
	.string "任何东西？$"

gText_ApprenticeWhatHeldItem9::
	.string "Hola!\n"
	.string "My maestro, {PLAYER}{KUN}!\p"
	.string "I want to hit you up for advice on\n"
	.string "POKéMON tools.\p"
	.string "What do you think would be good for\n"
	.string "my {STR_VAR_1} to hold?\p"
	.string "Don't be shy now.\n"
	.string "Let's blurt it out!$"

gText_ApprenticeHoldNothing9::
	.string "哦？所以你是说我的\n"
	.string "{STR_VAR_1}不携带道具\l"
	.string "也能赢？$"

gText_ApprenticeThanksNoHeldItem9::
	.string "好的，行！我会尽力而为，就像，猛\n"
	.string "击！\p"
	.string "好了，一如既往地感谢！再见！$"

gText_ApprenticeThanksHeldItem9::
	.string "嗯哼，{STR_VAR_1}？好\n"
	.string "的，行！我会去找一个，就像，砰！\p"
	.string "好了，一如既往地感谢！再见！$"

gText_ApprenticeItemAlreadyRecommended9::
	.string "不，不！你之前已经告诉过我\n"
	.string "{STR_VAR_1}的事了。\p"
	.string "哦，现在等等……所以你是说我的\n"
	.string "{STR_VAR_2}不携带道具\l"
	.string "也能赢？$"

gText_ApprenticeWhatHeldItem10::
	.string "{PLAYER}{KUN}, something unbelievable\n"
	.string "has happened!\p"
	.string "I woke up this morning, and my POKéMON\n"
	.string "had 10 NUGGETS!\p"
	.string "Of course I'm lying!\n"
	.string "Wahahaha!\p"
	.string "This is no lie, though.\n"
	.string "I'm not very good at thinking about\l"
	.string "what items POKéMON should hold.\p"
	.string "So, how about deciding for me what\n"
	.string "my {STR_VAR_1} should hold, master?$"

gText_ApprenticeHoldNothing10::
	.string "那是什么意思？不让它带任何东西？$"

gText_ApprenticeThanksNoHeldItem10::
	.string "Okay, so it shouldn't hold anything.\n"
	.string "Then, I'd better get something for it!\p"
	.string "Just kidding!\n"
	.string "I'll obey your teaching, master!\p"
	.string "Thanks, master!\n"
	.string "I hope you'll keep teaching me!$"

gText_ApprenticeThanksHeldItem10::
	.string "Okay, so it's one {STR_VAR_1}!\n"
	.string "I'll make it hold anything but that!\p"
	.string "Just kidding!\n"
	.string "I'll obey your teaching, master!\p"
	.string "Thanks, master!\n"
	.string "I hope you'll keep teaching me!$"

gText_ApprenticeItemAlreadyRecommended10::
	.string "嗯，你之前告诉过我了，对吧？\p"
	.string "没有别的东西了吗？\p"
	.string "或者你是说，不让我的\n"
	.string "{STR_VAR_2}携带任何东\l"
	.string "西？$"

gText_ApprenticeWhatHeldItem11::
	.string "A——H——O——Y！拼出来就是\n"
	.string "Ahoy，嗨！\p"
	.string "说唱水手就是我！向你提个超酷的问\n"
	.string "题！\p"
	.string "这是个道具问题需要你的建议！\p"
	.string "我的{STR_VAR_1}需要携\n"
	.string "带道具，该带什么好，请告诉我！$"

gText_ApprenticeHoldNothing11::
	.string "是吗？我的{STR_VAR_1}\n"
	.string "不需要携带任何东西？$"

gText_ApprenticeThanksNoHeldItem11::
	.string "好的，我听到了，当然！我的宝可梦\n"
	.string "也会空手上阵！\p"
	.string "如果我需要建议，{PLAYER}\n"
	.string "，你的话我永远听从！$"

gText_ApprenticeThanksHeldItem11::
	.string "好的，{STR_VAR_1}，那\n"
	.string "就是我要用的。让你选是对的！\p"
	.string "如果我需要建议，{PLAYER}\n"
	.string "，你的话我永远听从！$"

gText_ApprenticeItemAlreadyRecommended11::
	.string "好的，{STR_VAR_1}，你\n"
	.string "说？你之前告诉过我了。我需要新点\l"
	.string "子，全新的方式。\p"
	.string "或者，什么，是吗？我的宝可梦不需\n"
	.string "要携带任何东西？$"

gText_ApprenticeWhatHeldItem12::
	.string "Say, hey, {PLAYER}!\n"
	.string "I found you again today!\p"
	.string "What should I do? Get your advice?\n"
	.string "Why not? I'm already talking to you!\p"
	.string "{PLAYER}, are you getting sick of me?\n"
	.string "Nah, no way, that can't be.\p"
	.string "Will you hear me out?\n"
	.string "I'm looking for advice--that's what\l"
	.string "I'm talking about.\p"
	.string "It's about a hold item for\n"
	.string "my {STR_VAR_1} that'd be good.\l"
	.string "My indecision is making me brood.$"

gText_ApprenticeHoldNothing12::
	.string "我的{STR_VAR_1}什么都\n"
	.string "不需要？不需要携带任何东西？$"

gText_ApprenticeThanksNoHeldItem12::
	.string "如果什么都不带是最好的，我会照你\n"
	.string "说的做！\p"
	.string "嗯，{PLAYER}，我必须自由\n"
	.string "漫游，但别忘了我。\p"
	.string "再见，我聪明的朋友！$"

gText_ApprenticeThanksHeldItem12::
	.string "如果携带{STR_VAR_1}是\n"
	.string "最好的，我会照你说的做！\p"
	.string "嗯，{PLAYER}，我必须自由\n"
	.string "漫游，但别忘了我。\p"
	.string "再见，我聪明的朋友！$"

gText_ApprenticeItemAlreadyRecommended12::
	.string "我没听说过那个\n"
	.string "{STR_VAR_1}吗？我肯定\l"
	.string "听说过，那是肯定的！\p"
	.string "我需要新东西！或者我的\n"
	.string "{STR_VAR_2}什么都不需\l"
	.string "要？不需要携带任何东西？$"

gText_ApprenticeWhatHeldItem13::
	.string "嘎！哎哟！{PLAYER}\n"
	.string "{KUN}，我的手臂断了！别碰它\l"
	.string "，拜托！\p"
	.string "一定是我在尝试不同道具和我的宝可\n"
	.string "梦伙伴们时弄断的。\p"
	.string "所以，事已至此，我需要你替我决定\n"
	.string "。\p"
	.string "{PLAYER}{KUN}，你觉\n"
	.string "得我的{STR_VAR_1}携带\l"
	.string "什么好？$"

gText_ApprenticeHoldNothing13::
	.string "哎哟……\p"
	.string "所以你的建议是我的\n"
	.string "{STR_VAR_1}不需要携带\l"
	.string "任何东西？$"

gText_ApprenticeThanksNoHeldItem13::
	.string "嗯，好的。以我现在的情况，那样更\n"
	.string "容易。\p"
	.string "我希望我能继续这样向你求助。$"

gText_ApprenticeThanksHeldItem13::
	.string "Hm, all right. That's one {STR_VAR_1}.\n"
	.string "My POKéMON's arm is fine, so I'll make\l"
	.string "it hold that item right away.\p"
	.string "I hope I can keep hitting you up\n"
	.string "for help like this.$"

gText_ApprenticeItemAlreadyRecommended13::
	.string "No, no, you told me about that\n"
	.string "{STR_VAR_1} before, remember?\p"
	.string "How about telling me something\n"
	.string "even better?\p"
	.string "Oh, wait a second.\n"
	.string "So your suggestion is my {STR_VAR_2}\l"
	.string "doesn't have to hold anything?$"

gText_ApprenticeWhatHeldItem14::
	.string "Er… Um…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "Please, don't look at me that way.\n"
	.string "My POKéMON don't have anything.\p"
	.string "I… I'm really embarrassed about this,\n"
	.string "but I really need your advice.\p"
	.string "I can't decide what hold item would\n"
	.string "make my {STR_VAR_1} strong.\p"
	.string "{PLAYER}{KUN}, what do you think would\n"
	.string "be good?$"

gText_ApprenticeHoldNothing14::
	.string "哦……那么，你觉得我的\n"
	.string "{STR_VAR_1}不带道具更\l"
	.string "好？$"

gText_ApprenticeThanksNoHeldItem14::
	.string "Oh… Okay!\n"
	.string "I'll go without an item.\p"
	.string "This is nerve-racking, though.\n"
	.string "Wouldn't it be too cool?\p"
	.string "Thank you, {PLAYER}{KUN}.\n"
	.string "If we meet again, I hope you will be\l"
	.string "as helpful.$"

gText_ApprenticeThanksHeldItem14::
	.string "Oh… Okay!\n"
	.string "I'll go with that {STR_VAR_1}.\p"
	.string "This is nerve-racking, though.\n"
	.string "Wouldn't it be too cool?\p"
	.string "Thank you, {PLAYER}{KUN}.\n"
	.string "If we meet again, I hope you will be\l"
	.string "as helpful.$"

gText_ApprenticeItemAlreadyRecommended14::
	.string "B-but I already heard about that.\p"
	.string "Please don't brush me off like this!\n"
	.string "I can't live with the humiliation.\p"
	.string "Oh… Am I jumping to conclusions?\n"
	.string "Do you think it would be better if\l"
	.string "my {STR_VAR_2} didn't have an item?$"

gText_ApprenticeWhatHeldItem15::
	.string "Hm? You appear to be {PLAYER}{KUN}…\n"
	.string "But are you really?\l"
	.string "Perhaps you're a twin?\p"
	.string "Oh, no, no, no, don't worry!\n"
	.string "If you really are {PLAYER}, please\l"
	.string "forget about my rudeness.\p"
	.string "What I would like is some more of\n"
	.string "your fine advice.\p"
	.string "I have here my {STR_VAR_1} that I wish\n"
	.string "to make hold a convenient item.\p"
	.string "What would be worthy of it?$"

gText_ApprenticeHoldNothing15::
	.string "It's better if it held nothing?\n"
	.string "Are you certain?$"

gText_ApprenticeThanksNoHeldItem15::
	.string "I see. If that's the case, that's fine.\n"
	.string "I thank you for your time.\p"
	.string "Let us meet again!$"

gText_ApprenticeThanksHeldItem15::
	.string "One {STR_VAR_1}?\n"
	.string "Are you certain?\p"
	.string "I see. If that's the case, that's fine.\n"
	.string "I thank you for your time.\p"
	.string "I do hope my POKéMON will be able to\n"
	.string "put it to good use.\p"
	.string "Let us meet again!$"

gText_ApprenticeItemAlreadyRecommended15::
	.string "No, no, wait a minute.\n"
	.string "I believe you taught me that before.\p"
	.string "I would like you to recommend\n"
	.string "something different this time.\p"
	.string "Perhaps you're suggesting that\n"
	.string "my {STR_VAR_2} should hold nothing?\l"
	.string "Are you certain?$"

gText_ApprenticeWhichMonFirst0::
	.string "呜哇，{PLAYER}！我有个两\n"
	.string "难困境，抽泣……\p"
	.string "我想开始和别人对战，但不知道该怎\n"
	.string "么办。\p"
	.string "我该如何排列我的宝可梦才能让它们\n"
	.string "最强？\p"
	.string "请告诉我，{PLAYER}。如果\n"
	.string "你是我，这些宝可梦中你会先派出哪\l"
	.string "只？$"

gText_ApprenticeMonFirstThanks0::
	.string "我的{STR_VAR_1}应该先\n"
	.string "上？哇啊啊！\p"
	.string "哦！真对不起！你替我选择首发宝可\n"
	.string "梦让我很高兴，这又让我哭了……\p"
	.string "太感谢你了！$"

gText_ApprenticeWhichMonFirst1::
	.string "耶！是{PLAYER}！太好了！\n"
	.string "我想问你点事！\p"
	.string "嗯，在我的宝可梦中，你觉得哪只应\n"
	.string "该先出场？$"

gText_ApprenticeMonFirstThanks1::
	.string "我的{STR_VAR_1}？没错\n"
	.string "。好的，我会这么做的！\p"
	.string "谢谢你教我！$"

gText_ApprenticeWhichMonFirst2::
	.string "{PLAYER}，你好！\p"
	.string "我觉得在对战中，哪只宝可梦先出场\n"
	.string "非常重要。\p"
	.string "在我拥有的宝可梦中，哪只适合先派\n"
	.string "出去？$"

gText_ApprenticeMonFirstThanks2::
	.string "我的{STR_VAR_1}先上？\n"
	.string "好的，明白了！\p"
	.string "下次见！$"

gText_ApprenticeWhichMonFirst3::
	.string "你好，{PLAYER}……很抱歉\n"
	.string "又打扰你问另一个问题。\p"
	.string "我太没自信了，没有你\n"
	.string "{PLAYER}我都不知道该怎么\l"
	.string "办。\p"
	.string "可能我连担心都是浪费时间，但我就\n"
	.string "是无法决定一件事……\p"
	.string "我的宝可梦中哪只应该在对战中先出\n"
	.string "场？$"

gText_ApprenticeMonFirstThanks3::
	.string "我的{STR_VAR_1}？明白\n"
	.string "了！\p"
	.string "真不敢相信你会经常费心回答我的问\n"
	.string "题！\p"
	.string "我很感激你甚至愿意和我说话……谢\n"
	.string "谢你！$"

gText_ApprenticeWhichMonFirst4::
	.string "哦，{PLAYER}{KUN}！\n"
	.string "是我！很高兴见到你，因为我有个小\l"
	.string "问题。\p"
	.string "我无法决定我的宝可梦该如何排列。\n"
	.string "你能替我决定吗？\p"
	.string "哦，你现在不需要决定整个队伍。\p"
	.string "不如先替我决定首发宝可梦？$"

gText_ApprenticeMonFirstThanks4::
	.string "我的{STR_VAR_1}？太好\n"
	.string "了！\p"
	.string "知道是你做的决定，\n"
	.string "{PLAYER}{KUN}，就算\l"
	.string "我输了也不会太难过。\p"
	.string "好的，我会再来向你请教。再见！$"

gText_ApprenticeWhichMonFirst5::
	.string "嗨，我的老师{PLAYER}\n"
	.string "{KUN}！我今天又很忙！\p"
	.string "我得做些骑车、购物和哼歌的事。\p"
	.string "我甚至没时间决定如何排列我的宝可\n"
	.string "梦队伍。\p"
	.string "所以，不如看看我的队伍？哪只应该\n"
	.string "先出场？$"

gText_ApprenticeMonFirstThanks5::
	.string "Okay, gotcha.\n"
	.string "I have enough time at least to put\l"
	.string "my {STR_VAR_1} at the head of the line!\p"
	.string "Whoops, my girlfriend's waiting!\n"
	.string "Thanks! See you around!$"

gText_ApprenticeWhichMonFirst6::
	.string "哟嚯！嗨，{PLAYER}！你走\n"
	.string "路总是看起来很酷！\p"
	.string "听着，我又需要你帮忙了！老样子！\p"
	.string "请鼓掌！我的问题是关于我的队伍。\p"
	.string "我的宝可梦中哪只应该在对战中先出\n"
	.string "场？$"

gText_ApprenticeMonFirstThanks6::
	.string "嗯哼！你说我的\n"
	.string "{STR_VAR_1}！感谢这个\l"
	.string "超酷的回答！\p"
	.string "我想今天要问的就这些了。\p"
	.string "让我们在这里再见，好吗？谢谢！$"

gText_ApprenticeWhichMonFirst7::
	.string "非常感谢你停下来和我聊天，\n"
	.string "{PLAYER}。\p"
	.string "我知道我在利用你的善良，但能请教\n"
	.string "一下吗？\p"
	.string "我想让你决定我的宝可梦队伍的顺序\n"
	.string "。\p"
	.string "如果你能决定哪只宝可梦应该先出场\n"
	.string "就太好了。$"

gText_ApprenticeMonFirstThanks7::
	.string "My {STR_VAR_1} it is!\n"
	.string "I will put it first right away!\p"
	.string "Thank you, {PLAYER}.\n"
	.string "I hope I can count on you again.\l"
	.string "Please take care!$"

gText_ApprenticeWhichMonFirst8::
	.string "呀！我发现了{PLAYER}！我\n"
	.string "……又见到你我太高兴了！\p"
	.string "我的宝可梦变得强多了！\p"
	.string "但我并不总是赢。似乎取决于哪只宝\n"
	.string "可梦先出场。\p"
	.string "{PLAYER}，拜托，我需要你\n"
	.string "的帮助！\p"
	.string "请决定我的宝可梦中哪只应该先出场\n"
	.string "！$"

gText_ApprenticeMonFirstThanks8::
	.string "呼……我幸福得要晕过去了……\p"
	.string "能让你替我决定就像做梦一样，\n"
	.string "{PLAYER}。\p"
	.string "但完全明白了！我会让我的\n"
	.string "{STR_VAR_1}先上！\p"
	.string "希望下次你愿意再教我些东西。$"

gText_ApprenticeWhichMonFirst9::
	.string "Hello, hello!\n"
	.string "My mentor, {PLAYER}{KUN}!\l"
	.string "Hit me with your sage advice today!\p"
	.string "You see, I pulled together a team of\n"
	.string "three POKéMON. So far so good.\p"
	.string "But the team's battling order's not\n"
	.string "settled yet.\p"
	.string "This is where you come in, {PLAYER}{KUN}!\n"
	.string "You decide which POKéMON leads off!\p"
	.string "Don't be shy now.\n"
	.string "Let's blurt it out!$"

gText_ApprenticeMonFirstThanks9::
	.string "嗯哼，我的{STR_VAR_1}\n"
	.string "打头阵！OK，A——OK！我会重\l"
	.string "新排序队伍，就像，砰！\p"
	.string "好了，一如既往地感谢！再见！$"

gText_ApprenticeWhichMonFirst10::
	.string "{PLAYER}{KUN}, listen!\n"
	.string "It's a crisis!\p"
	.string "My POKéMON, all three of them, go into\n"
	.string "battle at once!\p"
	.string "Of course that's impossible!\n"
	.string "Wahahaha!\p"
	.string "This is no lie, though.\n"
	.string "I'm not very good at thinking about\l"
	.string "how I should line up my POKéMON.\p"
	.string "So, how about deciding for me which\n"
	.string "POKéMON should go first, master?$"

gText_ApprenticeMonFirstThanks10::
	.string "Okay, so it's my {STR_VAR_1} you chose?\n"
	.string "I'll let any but that one go first!\p"
	.string "Just kidding!\n"
	.string "I'll obey your teaching, master!\p"
	.string "Thanks, master!\n"
	.string "I hope you'll keep teaching me!$"

gText_ApprenticeWhichMonFirst11::
	.string "A——H——O——Y！拼出来就是\n"
	.string "Ahoy，嗨！\p"
	.string "说唱水手就是我！向你提个超酷的问\n"
	.string "题！\p"
	.string "这是个队伍排序问题需要你的建议！\p"
	.string "这些宝可梦中，哪只应该首先出场？$"

gText_ApprenticeMonFirstThanks11::
	.string "好的，我听到了，当然！我会调整它\n"
	.string "们的位置，就这么办！\p"
	.string "如果我需要建议，{PLAYER}\n"
	.string "，你的话我永远听从！$"

gText_ApprenticeWhichMonFirst12::
	.string "哟嚯，{PLAYER}！你好吗？\p"
	.string "我该怎么办？直接问？嗯哼，我有事\n"
	.string "要问！你收到我的信号了吗？你收到\l"
	.string "了！\p"
	.string "你必须决定，我的宝可梦中哪只是第\n"
	.string "1个上场的！我是说进入战斗！$"

gText_ApprenticeMonFirstThanks12::
	.string "我的{STR_VAR_1}？是的\n"
	.string "！这样就行，没有烦恼！\p"
	.string "嗯，{PLAYER}，我必须自由\n"
	.string "漂泊，但别忘了我。\p"
	.string "再见，我聪明的朋友！$"

gText_ApprenticeWhichMonFirst13::
	.string "……呼……哎哟……\n"
	.string "{PLAYER}{KUN}……我\l"
	.string "的肚子突然好痛……\p"
	.string "……现在好些了……\p"
	.string "一定是我绞尽脑汁思考如何排列我的\n"
	.string "宝可梦伙伴时把自己愁坏了。\p"
	.string "所以，事已至此，我需要你替我决定\n"
	.string "。\p"
	.string "{PLAYER}{KUN}，我的\n"
	.string "宝可梦中哪只应该先上场？我是说，\l"
	.string "才更可能赢。$"

gText_ApprenticeMonFirstThanks13::
	.string "嗯，好的。我的\n"
	.string "{STR_VAR_1}先上。\p"
	.string "等我吃完晚饭就按那样调整顺序。\p"
	.string "我希望我能继续这样向你求助。$"

gText_ApprenticeWhichMonFirst14::
	.string "Er… Um…\n"
	.string "{PLAYER}{KUN}?\p"
	.string "Please, don't look at me that way.\n"
	.string "You're making me feel all flustered.\p"
	.string "Um…\n"
	.string "I really need your advice.\p"
	.string "It makes me bashful to say this,\n"
	.string "but I chose my 3-POKéMON team.\l"
	.string "I can't decide on the order, though.\p"
	.string "Which POKéMON should I send out first\n"
	.string "so I at least look capable?$"

gText_ApprenticeMonFirstThanks14::
	.string "Oh… Okay!\n"
	.string "I'll lead with my {STR_VAR_1}.\p"
	.string "I hope I can do my best without\n"
	.string "getting all flustered.\p"
	.string "Thank you, {PLAYER}{KUN}.\n"
	.string "If we meet again, I hope you will be\l"
	.string "as helpful.$"

gText_ApprenticeWhichMonFirst15::
	.string "Hm? You appear to be {PLAYER}{KUN}…\n"
	.string "But are you really?\l"
	.string "Perhaps you're a clever look-alike?\p"
	.string "Oh, no, no, no, don't worry!\n"
	.string "If you really are {PLAYER}, please\l"
	.string "forget about my rudeness.\p"
	.string "What I would like is your fine advice.\p"
	.string "I have here my POKéMON team.\n"
	.string "I would like you to tell me which one\l"
	.string "should go first in a battle.$"

gText_ApprenticeMonFirstThanks15::
	.string "My {STR_VAR_1}…\n"
	.string "You aren't pulling my leg?\p"
	.string "I see. If that's the case, that's fine.\n"
	.string "I thank you for your time.\p"
	.string "I am as you see, but I shall do\n"
	.string "my best.\p"
	.string "Let us meet again!$"

gText_ApprenticeWhichMon0::
	.string "抽泣……哦，{PLAYER}！\p"
	.string "来得正是时候！有件事我实在拿不定\n"
	.string "主意……\p"
	.string "我无法决定该用哪只宝可梦。\p"
	.string "在{STR_VAR_1}和\n"
	.string "{STR_VAR_2}之间犹豫不\l"
	.string "决……\p"
	.string "{PLAYER}，你觉得哪只能让\n"
	.string "我也有机会获胜？$"

gText_ApprenticeMonThanks0::
	.string "抽泣……我…我明白了！哦！真对不\n"
	.string "起！你让我太开心，我又哭了……\p"
	.string "我会努力去抓一只\n"
	.string "{STR_VAR_1}！\p"
	.string "太感谢你了！$"

gText_ApprenticeWhichMon1::
	.string "耶！是{PLAYER}！来得正好\n"
	.string "！我又需要你的建议了！\p"
	.string "嗯，我完全搞混了——该用我的\n"
	.string "{STR_VAR_1}还是\l"
	.string "{STR_VAR_2}……\p"
	.string "{PLAYER}，你觉得我该培育\n"
	.string "哪只？$"

gText_ApprenticeMonThanks1::
	.string "哦，所以我的\n"
	.string "{STR_VAR_1}更好！好的\l"
	.string "，就这么办！\p"
	.string "谢谢你的教导！$"

gText_ApprenticeWhichMon2::
	.string "{PLAYER}，你好！有个问题\n"
	.string "想请教。\p"
	.string "我在纠结该培育\n"
	.string "{STR_VAR_1}还是\l"
	.string "{STR_VAR_2}。\p"
	.string "你觉得哪只宝可梦会更强？$"

gText_ApprenticeMonThanks2::
	.string "你选了{STR_VAR_1}？好\n"
	.string "的，明白了！\p"
	.string "我这就去抓只厉害的\n"
	.string "{STR_VAR_1}！\p"
	.string "下次见！$"

gText_ApprenticeWhichMon3::
	.string "你好，{PLAYER}……\p"
	.string "嗯，你可能已经忘记我这样的人了…\n"
	.string "…\p"
	.string "……但如果你能给我建议那也没关系\n"
	.string "……\p"
	.string "我无法决定该培育哪种宝可梦……\p"
	.string "范围缩小到了\n"
	.string "{STR_VAR_1}和\l"
	.string "{STR_VAR_2}，但就在这\l"
	.string "卡住了……\p"
	.string "{PLAYER}，你可能不想费心\n"
	.string "，但请替我决定吧。$"

gText_ApprenticeMonThanks3::
	.string "但野生的{STR_VAR_1}会\n"
	.string "理我吗？\p"
	.string "我会试试的！\p"
	.string "但我能抓到吗……不！我会尽力的！\p"
	.string "谢谢你！$"

gText_ApprenticeWhichMon4::
	.string "哦，{PLAYER}{KUN}！\n"
	.string "见到你真高兴！我正要去找你呢！\p"
	.string "你能决定我该用哪种宝可梦吗？\p"
	.string "比如……{STR_VAR_1}和\n"
	.string "{STR_VAR_2}怎么样？\p"
	.string "你觉得哪只更适合我？$"

gText_ApprenticeMonThanks4::
	.string "{STR_VAR_1}？太棒了！\p"
	.string "只要是你的决定，{PLAYER}\n"
	.string "{KUN}，就算输了我也没那么难\l"
	.string "过。\p"
	.string "好的，下次再向你请教。再见！$"

gText_ApprenticeWhichMon5::
	.string "这不是{PLAYER}{KUN}\n"
	.string "吗！最近怎样？我还是老样子忙得很\l"
	.string "！\p"
	.string "我也想用好宝可梦，但一直没决定该\n"
	.string "用哪只。\p"
	.string "你看{STR_VAR_1}好像很\n"
	.string "强？但{STR_VAR_2}也不\l"
	.string "容忽视。\p"
	.string "{PLAYER}{KUN}，给我\n"
	.string "点好建议！哪只适合我？$"

gText_ApprenticeMonThanks5::
	.string "好的，明白了。我会想办法抓一只你\n"
	.string "推荐的{STR_VAR_1}。\p"
	.string "真高兴遇到你这样的好导师。谢谢！\n"
	.string "回头见！$"

gText_ApprenticeWhichMon6::
	.string "哦！是{PLAYER}！\p"
	.string "我立刻就跟朋友们炫耀遇到你的事！\p"
	.string "今天又要借用你的智慧了。对你来说\n"
	.string "很简单！\p"
	.string "请击鼓助兴！我的问题是……\p"
	.string "如果要培育宝可梦，选\n"
	.string "{STR_VAR_1}还是\l"
	.string "{STR_VAR_2}？$"

gText_ApprenticeMonThanks6::
	.string "啊啊！你说{STR_VAR_1}\n"
	.string "！感谢这超酷的答案！\p"
	.string "今天想问的就这些了。\p"
	.string "我们下次在这里再见，好吗？谢谢！$"

gText_ApprenticeWhichMon7::
	.string "哦，是你吗{PLAYER}？真高\n"
	.string "兴又见到你！\p"
	.string "自从成为你的学徒，我的信心越来越\n"
	.string "强了。\p"
	.string "我觉得准备好培育自己的宝可梦了！\p"
	.string "{PLAYER}，能麻烦你帮我选\n"
	.string "该培育哪只宝可梦吗？\p"
	.string "选项是{STR_VAR_1}或\n"
	.string "{STR_VAR_2}……哪只适\l"
	.string "合我？$"

gText_ApprenticeMonThanks7::
	.string "One {STR_VAR_1} it is!\n"
	.string "I will find one right away!\p"
	.string "Thank you, {PLAYER}.\n"
	.string "I hope I can count on you again.\l"
	.string "Please take care!$"

gText_ApprenticeWhichMon8::
	.string "Eek! {PLAYER}! I met you again!\n"
	.string "I… I'm overjoyed!\p"
	.string "Oh-oh-oh, I know!\n"
	.string "I shouldn't pass up this opportunity!\p"
	.string "May I ask a huge favor, {PLAYER}?\n"
	.string "Please choose a POKéMON for me!\p"
	.string "Please decide which would be better,\n"
	.string "{STR_VAR_1} or {STR_VAR_2}!$"

gText_ApprenticeMonThanks8::
	.string "哇！你替我决定了！我会全力培育这\n"
	.string "只{STR_VAR_1}！\p"
	.string "希望下次你还能多教我一些。$"

gText_ApprenticeWhichMon9::
	.string "嘿，嘿！我的导师{PLAYER}\n"
	.string "{KUN}！\p"
	.string "你好，我一直在找你想再听听你的睿\n"
	.string "智建议！\p"
	.string "哪种宝可梦适合我，\n"
	.string "{STR_VAR_1}还是\l"
	.string "{STR_VAR_2}？\p"
	.string "别害羞，直接说出来吧！$"

gText_ApprenticeMonThanks9::
	.string "嗯哼，就选{STR_VAR_1}\n"
	.string "！OK，没问题！我会用精灵球抓一\l"
	.string "只，就像塞进去！\p"
	.string "好的，一如既往地感谢！再见！$"

gText_ApprenticeWhichMon10::
	.string "{PLAYER}{KUN}，听着\n"
	.string "！大新闻！我抓到了幻影宝可梦！\p"
	.string "当然是骗你的！哇哈哈哈！\p"
	.string "不过这不是骗人的。我不太擅长抓宝\n"
	.string "可梦。\p"
	.string "所以，不如替我决定该抓哪种宝可梦\n"
	.string "吧，师父？\p"
	.string "哪只更好？{STR_VAR_1}\n"
	.string "还是{STR_VAR_2}？$"

gText_ApprenticeMonThanks10::
	.string "Okay, so it's {STR_VAR_1} you chose?\n"
	.string "I'll grab the other kind, then!\p"
	.string "Just kidding!\n"
	.string "I'll obey your teaching, master!\p"
	.string "Thanks, master!\n"
	.string "I hope you'll keep teaching me!$"

gText_ApprenticeWhichMon11::
	.string "A——H——O——Y！就是Aho\n"
	.string "y的拼法！\p"
	.string "我就是那个说唱水手！你肯定记得我\n"
	.string "是谁吧？\p"
	.string "今天有个宝可梦问题需要你的建议！\p"
	.string "我可以在{STR_VAR_1}和\n"
	.string "{STR_VAR_2}之间选择，\l"
	.string "哪只适合抓来陪我？$"

gText_ApprenticeMonThanks11::
	.string "你说{STR_VAR_1}，嘿，\n"
	.string "嘿！我这就去抓一只！\p"
	.string "如果需要建议，{PLAYER}，\n"
	.string "你的话我永远牢记！$"

gText_ApprenticeWhichMon12::
	.string "Oh, wow, if it isn't {PLAYER}!\p"
	.string "What should I do? Get your advice?\n"
	.string "Why not? I'm already talking to you!\p"
	.string "It's been a long time. Let me break\n"
	.string "the ice. I'm also looking for advice!\l"
	.string "Are you receiving me?\l"
	.string "You are receiving me!\p"
	.string "My POKéMON--which should I use?\n"
	.string "It's either {STR_VAR_1} or {STR_VAR_2}.\l"
	.string "Which do you choose?$"

gText_ApprenticeMonThanks12::
	.string "如果{STR_VAR_1}最棒，\n"
	.string "我就照你说的办！\p"
	.string "嗯，{PLAYER}，我得自由闯\n"
	.string "荡，但你可别忘了我。\p"
	.string "再见，我聪明的朋友！$"

gText_ApprenticeWhichMon13::
	.string "哦，嗨，{PLAYER}\n"
	.string "{KUN}……我头疼得厉害……\p"
	.string "肯定是因为太纠结该培育哪种宝可梦\n"
	.string "了。\p"
	.string "所以，情况就是这样，需要你替我决\n"
	.string "定。\p"
	.string "{PLAYER}{KUN}，如果\n"
	.string "必须在{STR_VAR_1}和\l"
	.string "{STR_VAR_2}之间选择，\l"
	.string "该选哪只？$"

gText_ApprenticeMonThanks13::
	.string "嗯，就选{STR_VAR_1}吧\n"
	.string "。等我好些了就去找一只。\p"
	.string "希望能继续这样向你求助。$"

gText_ApprenticeWhichMon14::
	.string "呃……嗯…{PLAYER}\n"
	.string "{KUN}……？\p"
	.string "拜托别那样看我。我都慌乱了……我\n"
	.string "……我需要你的建议。\p"
	.string "我……我真的很不好意思，但无法决\n"
	.string "定该用哪只宝可梦。\p"
	.string "如果选项是{STR_VAR_1}\n"
	.string "或{STR_VAR_2}，哪只更\l"
	.string "好？$"

gText_ApprenticeMonThanks14::
	.string "Oh… Okay!\n"
	.string "I'll do my best with one {STR_VAR_1}.\p"
	.string "I hope I can do my best without\n"
	.string "getting all flustered.\p"
	.string "Thank you, {PLAYER}{KUN}.\n"
	.string "If we meet again, I hope you will be\l"
	.string "as helpful.$"

gText_ApprenticeWhichMon15::
	.string "Hm? You appear to be {PLAYER}{KUN}…\n"
	.string "But are you really real?\p"
	.string "No, no, if you are real, it's fine.\n"
	.string "Incidentally, I would like to obtain\l"
	.string "your advice.\p"
	.string "It's about the POKéMON I am to use.\p"
	.string "If the choices are the POKéMON\n"
	.string "{STR_VAR_1} and {STR_VAR_2}, which is\l"
	.string "more worthy of me?$"

gText_ApprenticeMonThanks15::
	.string "{STR_VAR_1}?\n"
	.string "Are you certain?\p"
	.string "I see. If that's the case, that's fine.\n"
	.string "I thank you for your time.\p"
	.string "I do hope it is something even I can\n"
	.string "handle with aplomb.\p"
	.string "Let us meet again!$"

gText_ApprenticeWhichMove0::
	.string "Waaah! Oh, {PLAYER}!\n"
	.string "Snivel… Hiccup…\p"
	.string "I have a dilemma!\n"
	.string "I can't decide on a move for\l"
	.string "my {STR_VAR_1}…\p"
	.string "Please, please, {PLAYER}.\n"
	.string "Can you decide for me?\p"
	.string "For my {STR_VAR_1}, which move would\n"
	.string "be the better choice: {STR_VAR_2}\l"
	.string "or {STR_VAR_3}?$"

gText_ApprenticeMoveThanks0::
	.string "{STR_VAR_1}?\n"
	.string "Waaaaah!\p"
	.string "Oh! I'm so sorry, {PLAYER}!\n"
	.string "You've made me so happy by deciding\l"
	.string "the move, I'm crying…\p"
	.string "Snivel…\n"
	.string "Thank you so much!$"

gText_ApprenticeWhichMove1::
	.string "Yay! Hi, {PLAYER}!\n"
	.string "I need your advice again!\p"
	.string "I want to teach my {STR_VAR_1}\n"
	.string "a cool move.\p"
	.string "I like either of the moves\n"
	.string "{STR_VAR_2} or {STR_VAR_3}.\l"
	.string "What's your recommendation?$"

gText_ApprenticeMoveThanks1::
	.string "{STR_VAR_1}更好？我想\n"
	.string "是的！好的，我就用那个！\p"
	.string "如果我们在这里再见，请再教我点别\n"
	.string "的，老师！$"

gText_ApprenticeWhichMove2::
	.string "{PLAYER}, hello!\n"
	.string "It's about my {STR_VAR_1}, but I'm\l"
	.string "worried about its moves.\p"
	.string "You see, it's the moves {STR_VAR_2}\n"
	.string "and {STR_VAR_3}.\p"
	.string "Which is stronger and better for\n"
	.string "my {STR_VAR_1}?$"

gText_ApprenticeMoveThanks2::
	.string "{STR_VAR_1}是你的选择\n"
	.string "？好的，明白了！\p"
	.string "我马上去教我的宝可梦\n"
	.string "{STR_VAR_1}！\p"
	.string "下次见！$"

gText_ApprenticeWhichMove3::
	.string "Ohhh, {PLAYER}…\n"
	.string "I'm hopeless, no, really!\p"
	.string "I've decided to raise a POKéMON,\n"
	.string "but now I can't even decide what\l"
	.string "move I should let it learn…\p"
	.string "I know that it doesn't mean anything\n"
	.string "to you, {PLAYER}.\p"
	.string "But it means a lot to me…\p"
	.string "Please, {PLAYER}, could you choose\n"
	.string "a move for my {STR_VAR_1}?\p"
	.string "If you could even choose between\n"
	.string "{STR_VAR_2} and {STR_VAR_3}…$"

gText_ApprenticeMoveThanks3::
	.string "我明白了！\p"
	.string "但它会愿意为我学\n"
	.string "{STR_VAR_1}吗……不！\l"
	.string "我会尽力的！\p"
	.string "谢谢你！$"

gText_ApprenticeWhichMove4::
	.string "Oh, {PLAYER}{KUN}!\n"
	.string "I was just hoping to see you, too!\p"
	.string "I was wondering what move would\n"
	.string "be suitable for my {STR_VAR_1}.\p"
	.string "I can't decide, so can you decide\n"
	.string "for me instead?\p"
	.string "For instance… How about the moves\n"
	.string "{STR_VAR_2} and {STR_VAR_3}?\l"
	.string "Which one would be better?$"

gText_ApprenticeMoveThanks4::
	.string "{STR_VAR_1}？太棒了！\p"
	.string "知道是你做的决定，\n"
	.string "{PLAYER}{KUN}，就算\l"
	.string "我输了也不会太难过。\p"
	.string "好的，我会再来向你请教。再见！$"

gText_ApprenticeWhichMove5::
	.string "How could things be this busy?\n"
	.string "Hey, if it isn't {PLAYER}{KUN}!\l"
	.string "How's it going?\p"
	.string "Since I got up this morning, I've done\n"
	.string "my jogging, swimming, and cooking!\p"
	.string "You wouldn't believe how busy I am!\p"
	.string "I can't even decide what move\n"
	.string "my {STR_VAR_1} should learn!\p"
	.string "{STR_VAR_2} looks good, huh?\n"
	.string "But {STR_VAR_3}'s also decent.\p"
	.string "{PLAYER}{KUN}, give me some of your good\n"
	.string "advice! Which move'd be good for me?$"

gText_ApprenticeMoveThanks5::
	.string "Okay, gotcha.\n"
	.string "I'll make room in my schedule and\l"
	.string "teach that move.\p"
	.string "I'm glad I met a good mentor in you.\n"
	.string "Thanks! See you around!$"

gText_ApprenticeWhichMove6::
	.string "Oh! Lucky!\n"
	.string "I met you again, {PLAYER}!\l"
	.string "I need to tap your mind again today.\p"
	.string "Drum roll, please!\n"
	.string "The question I have is…\p"
	.string "For my {STR_VAR_1}, which is the move\n"
	.string "best suited, {STR_VAR_2} or\l"
	.string "{STR_VAR_3}?$"

gText_ApprenticeMoveThanks6::
	.string "啊！{STR_VAR_1}，你说\n"
	.string "！感谢这个超酷的回答！\p"
	.string "我想今天要问的就这些了。\p"
	.string "让我们在这里再见，好吗？谢谢！$"

gText_ApprenticeWhichMove7::
	.string "Oh, hello, {PLAYER}.\n"
	.string "I trust you've been well?\p"
	.string "I have to seek your advice again.\n"
	.string "It's about my dearest {STR_VAR_1}.\p"
	.string "What would be the ideal move for\n"
	.string "my lovable {STR_VAR_1}?\l"
	.string "{STR_VAR_2} or {STR_VAR_3}?$"

gText_ApprenticeMoveThanks7::
	.string "{STR_VAR_1} it is!\n"
	.string "I will teach that right away!\p"
	.string "Thank you, {PLAYER}.\n"
	.string "I hope I can count on you again.\l"
	.string "Please take care!$"

gText_ApprenticeWhichMove8::
	.string "Eek! {PLAYER}! I met you again!\n"
	.string "I… I'm overjoyed!\p"
	.string "Whenever I'm in need, you're always\n"
	.string "there for me, {PLAYER}!\p"
	.string "Today, I want you to recommend\n"
	.string "a move for me!\p"
	.string "Please choose a move for\n"
	.string "my {STR_VAR_1}!\p"
	.string "Which move would be better,\n"
	.string "{STR_VAR_2} or {STR_VAR_3}?$"

gText_ApprenticeMoveThanks8::
	.string "Oh-oh-oh! Thank you!\n"
	.string "{STR_VAR_1} is it!\l"
	.string "Perfectly understood!\p"
	.string "I hope you'll be willing to teach me\n"
	.string "some more another time.$"

gText_ApprenticeWhichMove9::
	.string "Hola, {PLAYER}{KUN}, bueno!\n"
	.string "I'm hoping for some more of\l"
	.string "your sage advice today!\p"
	.string "What would be the best move for\n"
	.string "my {STR_VAR_1}?\p"
	.string "It should be something that'll\n"
	.string "let me win just like that!\p"
	.string "Would it be {STR_VAR_2}?\n"
	.string "Or {STR_VAR_3}?$"

gText_ApprenticeMoveThanks9::
	.string "嗯哼，{STR_VAR_1}！好\n"
	.string "的，行！我会教它，就像，砰！\p"
	.string "好了，一如既往地感谢！再见！$"

gText_ApprenticeWhichMove10::
	.string "{PLAYER}{KUN}, it's completely wild!\p"
	.string "My POKéMON!\n"
	.string "It learned six moves!\p"
	.string "Of course I'm lying!\n"
	.string "Wahahaha!\p"
	.string "This is no lie, though.\n"
	.string "I'm not very good at choosing moves\l"
	.string "for my POKéMON.\p"
	.string "So, how about deciding for me which\n"
	.string "kind of move I should teach?\p"
	.string "{STR_VAR_2} or {STR_VAR_3}--which\n"
	.string "would go with my {STR_VAR_1} best?$"

gText_ApprenticeMoveThanks10::
	.string "Okay, so it's {STR_VAR_1} you chose?\n"
	.string "I'll choose another move, then!\p"
	.string "Just kidding!\n"
	.string "I'll obey your teaching, master!\p"
	.string "Thanks, master!\n"
	.string "I hope you'll keep teaching me!$"

gText_ApprenticeWhichMove11::
	.string "A-H-O-Y!\n"
	.string "And that spells ahoy!\p"
	.string "The rappin' SAILOR am I!\n"
	.string "I'm always with it, don't ask me why.\p"
	.string "Today, I have a move question\n"
	.string "that begs your suggestion!\p"
	.string "{STR_VAR_2} and {STR_VAR_3} are\n"
	.string "the moves. What would be the best\l"
	.string "for my {STR_VAR_1} so it grooves?$"

gText_ApprenticeMoveThanks11::
	.string "{STR_VAR_1}，你说，嘿\n"
	.string "，嘿！我马上去教那招！\p"
	.string "如果我需要建议，{PLAYER}\n"
	.string "，你的话我永远听从！$"

gText_ApprenticeWhichMove12::
	.string "Oh, yeahah, if it isn't {PLAYER}!\p"
	.string "What should I do? Get your advice?\n"
	.string "Why not? I'm already talking to you!\p"
	.string "{PLAYER}, are you surprised by me?\n"
	.string "I want your advice, can't you see?\p"
	.string "Are you receiving me?\n"
	.string "You are receiving me!\p"
	.string "My {STR_VAR_1}--what should it use?\n"
	.string "It's {STR_VAR_2} or {STR_VAR_3},\l"
	.string "what do you choose?$"

gText_ApprenticeMoveThanks12::
	.string "如果{STR_VAR_1}是最好\n"
	.string "的，我会照你说的做！\p"
	.string "嗯，{PLAYER}，我必须自由\n"
	.string "漫游，但别忘了我。\p"
	.string "再见，我聪明的朋友！$"

gText_ApprenticeWhichMove13::
	.string "Gahack! Gaah! Oh, {PLAYER}{KUN}…\n"
	.string "I have this lousy cold, I do…\p"
	.string "I want to pick a move for my POKéMON,\n"
	.string "but I'm not up to it…\p"
	.string "So, things being this way,\n"
	.string "I need you to decide for me.\p"
	.string "{PLAYER}{KUN}, if I had to choose between\n"
	.string "{STR_VAR_2} and {STR_VAR_3} for\l"
	.string "my {STR_VAR_1}, which would it be?$"

gText_ApprenticeMoveThanks13::
	.string "Hm, {STR_VAR_1}, all right. Cough!\n"
	.string "I'll go teach it when I get better.\p"
	.string "I hope I can keep hitting you up\n"
	.string "for help like this.$"

gText_ApprenticeWhichMove14::
	.string "Er… Um…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "Please, don't look at me that way.\n"
	.string "I'm getting all flustered…\l"
	.string "I… I need your advice.\p"
	.string "I… I'm really embarrassed, but I can't\n"
	.string "decide what move I should teach\l"
	.string "my POKéMON.\p"
	.string "It's for my {STR_VAR_1}.\n"
	.string "If the choices were {STR_VAR_2} or\l"
	.string "{STR_VAR_3}, which would be better?$"

gText_ApprenticeMoveThanks14::
	.string "Oh… Okay!\n"
	.string "I'll try that {STR_VAR_1}.\p"
	.string "I hope I can teach that move…\n"
	.string "This is so nerve-racking…\p"
	.string "Thank you, {PLAYER}{KUN}.\n"
	.string "If we meet again, I hope you will be\l"
	.string "as helpful.$"

gText_ApprenticeWhichMove15::
	.string "Hm? You appear to be {PLAYER}{KUN}…\n"
	.string "But are you really real?\p"
	.string "Perhaps you're one of those popular\n"
	.string "mimics?\p"
	.string "No, no, if you are real, it's fine.\n"
	.string "No need to be upset, I assure you!\p"
	.string "Incidentally, I would like to obtain\n"
	.string "your advice.\p"
	.string "It's about my {STR_VAR_1}.\p"
	.string "Which move would be better for it to\n"
	.string "use, {STR_VAR_2} or {STR_VAR_3}?$"

gText_ApprenticeMoveThanks15::
	.string "{STR_VAR_1}?\n"
	.string "There's no question about that?\p"
	.string "I see. If that's the case, that's fine.\n"
	.string "I thank you for your time.\p"
	.string "I do hope it is something even\n"
	.string "my POKéMON can learn.\p"
	.string "Let us meet again!$"

gText_ApprenticePickWinSpeech0::
	.string "哦… {PLAYER}？是\n"
	.string "{PLAYER}啊！哦！抽泣……\l"
	.string "呜咽… 请听我说！\p"
	.string "我… 在对战时，我会紧张得不得了\n"
	.string "，就算赢了也忍不住哭出来……\p"
	.string "我真希望赢的时候能说点帅气的话…\n"
	.string "…\p"
	.string "求求你，{PLAYER}！能不能\n"
	.string "教我一句赢了之后说的酷酷的话，这\l"
	.string "样我就不会哭了？$"

gText_ApprenticeWinSpeechThanks0::
	.string "{STR_VAR_1}\p"
	.string "太棒了！帅呆了！呜哦哦！这真的很\n"
	.string "酷！\p"
	.string "哦……对不起……我太高兴了，又哭\n"
	.string "了……\p"
	.string "抽鼻子… {PLAYER}！真的\n"
	.string "非常感谢你为我做的一切！\p"
	.string "为了你，{PLAYER}，我会尽\n"
	.string "我所能去战斗的！\p"
	.string "{PLAYER}……下次… 我们\n"
	.string "来对战吧！$"

gText_ApprenticePickWinSpeech1::
	.string "Yay! It's {PLAYER}! Hello!\n"
	.string "I wanted to ask you something!\p"
	.string "I want to say something cool when\n"
	.string "I win a match.\p"
	.string "Do you have a cool saying that\n"
	.string "you could recommend?$"

gText_ApprenticeWinSpeechThanks1::
	.string "{STR_VAR_1}\p"
	.string "哦，哇！这太酷了！好的，我就说这\n"
	.string "句了！\p"
	.string "谢谢你一直以来的教导！从今以后，\n"
	.string "无论走到哪里，我都会全力以赴的！\p"
	.string "等我们再见面时，就来一场对战吧！$"

gText_ApprenticePickWinSpeech2::
	.string "{PLAYER}，你好！\p"
	.string "我和我的宝可梦已经准备好迎接任何\n"
	.string "挑战了，除了一件事。\p"
	.string "我觉得如果我赢了之后能喊点什么就\n"
	.string "好了。\p"
	.string "你能帮我想一句适合说的话吗？$"

gText_ApprenticeWinSpeechThanks2::
	.string "{STR_VAR_1}\p"
	.string "……酷！我就用这句了！\p"
	.string "我要去各地旅行战斗了。\p"
	.string "说不定有一天，我还能和你对战呢，\n"
	.string "{PLAYER}。\p"
	.string "下次，我们在对战之地再见吧！$"

gText_ApprenticePickWinSpeech3::
	.string "你好，{PLAYER}……抱歉打\n"
	.string "扰你，但我真是没救了……\p"
	.string "即使是……即使我赢了，我也说不出\n"
	.string "什么特别的话来……\p"
	.string "我知道这对你来说可能不算什么，\n"
	.string "{PLAYER}。\p"
	.string "但对我来说意义重大……\p"
	.string "求你了，{PLAYER}，如果我\n"
	.string "赢了比赛，该说什么好呢？$"

gText_ApprenticeWinSpeechThanks3::
	.string "{STR_VAR_1}\p"
	.string "这话真有水平……\p"
	.string "呃……像我这样的人说这个真的合适\n"
	.string "吗？\p"
	.string "不！我会努力的！\p"
	.string "{PLAYER}，真的非常感谢你\n"
	.string "一直这么包容我……\p"
	.string "我保证从现在开始会尽最大努力。\p"
	.string "我知道你大概很快就会忘掉我这样的\n"
	.string "人，但我们一定要在某个地方再见面\l"
	.string "！$"

gText_ApprenticePickWinSpeech4::
	.string "哦，{PLAYER}{KUN}。\n"
	.string "有件事想请你听听。\p"
	.string "我知道我说话有时听起来不太友善或\n"
	.string "礼貌……\p"
	.string "赢了比赛时，我觉得自己显得有点傲\n"
	.string "慢。\p"
	.string "我不想让人讨厌，所以我想对被我打\n"
	.string "败的人说点好话。\p"
	.string "但我就是想不出什么好词！你能帮我\n"
	.string "想一句吗？$"

gText_ApprenticeWinSpeechThanks4::
	.string "{STR_VAR_1}\p"
	.string "不错嘛！嗯，我就用这句了！\p"
	.string "我要踏上旅程，把从你那里学到的东\n"
	.string "西记在脑海里、放在心里，尽我所能\l"
	.string "去做。\p"
	.string "很抱歉我一直对你这么缠人！\p"
	.string "下次，我们来对战吧，好吗？再见！$"

gText_ApprenticePickWinSpeech5::
	.string "Oh, I can't get over how busy I am!\n"
	.string "Oh, hey, I was looking for you, {PLAYER}{KUN}.\p"
	.string "Are you well as usual?\n"
	.string "Things haven't changed for me at all.\p"
	.string "I've got running, fighting, and mapping\n"
	.string "to do. Why am I so busy?\p"
	.string "But even though I'm busy, it'd be rude\n"
	.string "to just turn on my heels and walk away\l"
	.string "from a win without saying a word.\p"
	.string "So, what would be a cool saying to\n"
	.string "underline my coolness when I'm done\l"
	.string "and walking away? {PLAYER}{KUN}, help me!$"

gText_ApprenticeWinSpeechThanks5::
	.string "{STR_VAR_1}\p"
	.string "好的，明白了。我总能挤出时间说这\n"
	.string "句的！\p"
	.string "说实话，能遇到你这样的好导师真是\n"
	.string "太好了。\p"
	.string "我会想办法挤出时间去好好对战的。\p"
	.string "谢谢你做的一切，{PLAYER}\n"
	.string "{KUN}！总有一天，我们一定要\l"
	.string "对战一场！$"

gText_ApprenticePickWinSpeech6::
	.string "我又走运了！{PLAYER}！见\n"
	.string "到你太高兴了！和往常一样，我需要\l"
	.string "你的建议！\p"
	.string "请击鼓助兴！我要问的最后一个问题\n"
	.string "是……\p"
	.string "如果我赢了比赛，想用一句酷炫的结\n"
	.string "束语收尾，我该说什么？$"

gText_ApprenticeWinSpeechThanks6::
	.string "{STR_VAR_1}\p"
	.string "这句……这句太棒了！既体面又帅气\n"
	.string "！我宣布这句归我了！\p"
	.string "……听着，我觉得我现在还挺像样的\n"
	.string "了，对吧？\p"
	.string "所以，我打算从现在开始挑战其他训\n"
	.string "练家了。\p"
	.string "{PLAYER}，你的建议真的帮\n"
	.string "了我大忙。\p"
	.string "也许有一天，就是我们交手的时候了\n"
	.string "！\p"
	.string "感谢你所做的一切！$"

gText_ApprenticePickWinSpeech7::
	.string "哦，{PLAYER}。真高兴能遇\n"
	.string "见你！\p"
	.string "关于我的宝可梦，我已经没有任何顾\n"
	.string "虑了。\p"
	.string "让我担心的是我自己……\p"
	.string "你知道训练家赢了比赛后会说些什么\n"
	.string "吗？\p"
	.string "毫无疑问，我也希望能那样做！\p"
	.string "求你了，赢了比赛后我该说什么好呢\n"
	.string "？$"

gText_ApprenticeWinSpeechThanks7::
	.string "{STR_VAR_1}\p"
	.string "啊！这句话！它让我神清气爽，仿佛\n"
	.string "重获新生！\p"
	.string "我必须马上就用上这句！\p"
	.string "那么现在，我必须告辞了，\n"
	.string "{PLAYER}……\p"
	.string "我会去和很多人对战，但永远不会忘\n"
	.string "记你的教导。\p"
	.string "也许有一天……再会了！$"

gText_ApprenticePickWinSpeech8::
	.string "呀！我看到{PLAYER}了！我\n"
	.string "……我见到你太高兴了！\p"
	.string "哦——哦——哦！有件事我非问你不\n"
	.string "可！\p"
	.string "不久前，我赢了一场对战。那部分让\n"
	.string "我飘飘然！\p"
	.string "但它让我太高兴了，我激动得说不出\n"
	.string "话来！\p"
	.string "所以现在，{PLAYER}，拜托\n"
	.string "了，我想让你帮我想一句赢了之后退\l"
	.string "场的台词！$"

gText_ApprenticeWinSpeechThanks8::
	.string "{STR_VAR_1}\p"
	.string "哇啊啊啊！我要说这句？！我……我\n"
	.string "高兴得快疯了！\p"
	.string "谢——谢——谢谢你！我现在没有遗\n"
	.string "憾了！\p"
	.string "我现在要去旅行了，要和各种各样的\n"
	.string "人对战。\p"
	.string "这一切，都归功于你，\n"
	.string "{PLAYER}。真的，真的，谢\l"
	.string "谢你！\p"
	.string "我得走了，但总有一天我们要在战场\n"
	.string "上见！$"

gText_ApprenticePickWinSpeech9::
	.string "喂，你好！{PLAYER}\n"
	.string "{KUN}！\p"
	.string "你知道吗，我有点想去各地旅行对战\n"
	.string "了。\p"
	.string "但在那之前，我还想再请教你一次，\n"
	.string "拜托了！\p"
	.string "如果我赢了比赛，有什么好的炫耀词\n"
	.string "可以对战败的训练家对手说呢？$"

gText_ApprenticeWinSpeechThanks9::
	.string "{STR_VAR_1}\p"
	.string "嗯哼，这话真棒！Si, buen\n"
	.string "o！嗯哼，我会试着这么说，就像，\l"
	.string "火腿！\p"
	.string "那么，是时候说再见了！感谢你为我\n"
	.string "做的一切！\p"
	.string "改天和我对战一场，好吗？再见！$"

gText_ApprenticePickWinSpeech10::
	.string "{PLAYER}{KUN}，出大\n"
	.string "麻烦了！\p"
	.string "我赢了比赛后，至少要吹嘘一个小时\n"
	.string "！\p"
	.string "当然我是骗你的！哇哈哈哈！\p"
	.string "不过这不是骗人的。我不太擅长聊天\n"
	.string "。\p"
	.string "所以，不如你替我决定一下赢了比赛\n"
	.string "后该说什么吧，师父？$"

gText_ApprenticeWinSpeechThanks10::
	.string "{STR_VAR_1}\p"
	.string "这就是我该说的，是吗？那么，我会\n"
	.string "远离那句的！\p"
	.string "开个玩笑啦！我会遵从您的教诲的，\n"
	.string "师父！\p"
	.string "谢谢您一直以来的教导，师父！\p"
	.string "我终于开始明白身为训练家意味着什\n"
	.string "么了。\p"
	.string "我要出去和任何训练家对战并赢得胜\n"
	.string "利。\p"
	.string "也许有一天会是你，师父！\p"
	.string "就这样吧！再见了，我的师父！$"

gText_ApprenticePickWinSpeech11::
	.string "A——H——O——Y！就是Aho\n"
	.string "y，嗨的拼法！\p"
	.string "我就是那个说唱水手！这将是我最后\n"
	.string "的问题，你可别哭！\p"
	.string "这是个寻求你建议的台词问题！\p"
	.string "如果我赢了比赛，该怎么说才显得超\n"
	.string "酷？$"

gText_ApprenticeWinSpeechThanks11::
	.string "{STR_VAR_1}\p"
	.string "完美！我就用这句了。让你选果然是\n"
	.string "对的！\p"
	.string "那么现在，我想是时候让我展翅高飞\n"
	.string "了！\p"
	.string "谢谢你教会我的一切。我要出发去大\n"
	.string "干一场了！\p"
	.string "B——O——N——V——O——Y\n"
	.string "——A——G——E！就是Bon \l"
	.string "voyage的拼法，以此向你致敬\l"
	.string "！$"

gText_ApprenticePickWinSpeech12::
	.string "哦，耶，{PLAYER}！今天又\n"
	.string "找到你了！\p"
	.string "我该怎么办？再问你一次？为什么不\n"
	.string "呢？反正我都在问了！\p"
	.string "总之，{PLAYER}……你收到\n"
	.string "我的信号了吗？你收到了！我需要再\l"
	.string "要点建议！\p"
	.string "是关于我该喊什么的。战斗顺利结束\n"
	.string "时该喊点什么酷酷的话。\p"
	.string "来吧，我想听你说出来！$"

gText_ApprenticeWinSpeechThanks12::
	.string "{STR_VAR_1}\p"
	.string "好极了，好极了！我就用这句了，因\n"
	.string "为它太赞了！\p"
	.string "我已经没东西问你了。只剩下挥手告\n"
	.string "别了。\p"
	.string "但也许有一天我们会相遇，其中一人\n"
	.string "注定要败北。\p"
	.string "不过，真的该说再见了。\p"
	.string "嗯，{PLAYER}，我得自由闯\n"
	.string "荡了，但你可别忘了我！\p"
	.string "保重，{PLAYER}！爱你哟！$"

gText_ApprenticePickWinSpeech13::
	.string "{PLAYER}{KUN}，我完\n"
	.string "了……我的鼻涕止不住地流……\p"
	.string "我刚才在努力想赢了比赛时该说的酷\n"
	.string "酷台词。\p"
	.string "它太让我激动了，我哭了，现在我的\n"
	.string "鼻涕就停不下来……\p"
	.string "所以，情况就是这样，我需要你帮我\n"
	.string "决定，{PLAYER}{KUN}\l"
	.string "。\p"
	.string "我赢了比赛后，该说什么呢？$"

gText_ApprenticeWinSpeechThanks13::
	.string "{STR_VAR_1}\p"
	.string "… … …That's good.\n"
	.string "No, it's awe inspiring!\l"
	.string "It's bringing fresh tears to my eyes!\p"
	.string "But in spite of my tears and runny\n"
	.string "nose, I will use that saying!\p"
	.string "I'm plumb out of things to ask you,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "From now on, we're rivals!\n"
	.string "Thanks for everything!$"

gText_ApprenticePickWinSpeech14::
	.string "呃……嗯…{PLAYER}\n"
	.string "{KUN}……\p"
	.string "拜托，别那样看着我。你让我好紧张\n"
	.string "。\p"
	.string "我……我又需要你的建议了。不过这\n"
	.string "是最后一次了……\p"
	.string "问这个真的很不好意思，但如果我赢\n"
	.string "了比赛呢？我该说什么？$"

gText_ApprenticeWinSpeechThanks14::
	.string "{STR_VAR_1}\p"
	.string "哦……好的！我会试着说这句的！我\n"
	.string "可能会紧张得说不出来……\p"
	.string "谢谢你，{PLAYER}\n"
	.string "{KUN}。我现在得说再见了。\p"
	.string "我会遵从你教给我的一切，\n"
	.string "{PLAYER}{KUN}，尽我\l"
	.string "所能做到最好。$"

gText_ApprenticePickWinSpeech15::
	.string "嗯？你好像是{PLAYER}\n"
	.string "{KUN}……但你真的是吗？或许\l"
	.string "是个聪明的{PLAYER}人偶？\p"
	.string "哦，不不不，别担心！如果你是真的\n"
	.string "，请忘了我的无礼吧。\p"
	.string "没必要这么生气。我所希望的只是更\n"
	.string "多你宝贵的建议。\p"
	.string "是关于一句台词的。\p"
	.string "更确切地说，如果我赢了比赛，我该\n"
	.string "说什么？$"

gText_ApprenticeWinSpeechThanks15::
	.string "{STR_VAR_1}\p"
	.string "…… …… …… …… …… …\n"
	.string "当我赢了比赛时……\p"
	.string "{STR_VAR_1}\p"
	.string "……你是认真的吗？\p"
	.string "我明白了。如果你是认真的，那好吧\n"
	.string "。感谢你抽空帮我。\p"
	.string "我希望连我也能好好利用这句台词。\p"
	.string "我似乎已经想不出还需要什么建议了\n"
	.string "。\p"
	.string "我想是时候向你告别，独自出发了。\p"
	.string "谢谢你，我的导师！我为我的怀疑向\n"
	.string "你道歉！$"
