
#if IS_HNS
FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "I welcome you to the BATTLE TENT!\p"
	.string "I am your guide to the Set KO Tourney!$"
#else
FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "I welcome you to the BATTLE TENT\n"
	.string "FALLARBOR SITE!\p"
	.string "I am your guide to the Set KO Tourney!$"
#endif

FallarborTown_BattleTentLobby_Text_TakeChallenge:
	.string "要挑战三回合定胜负锦标赛吗？$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge:
	.string "随时恭候您再次挑战！$"

FallarborTown_BattleTentLobby_Text_ExplainFallarborTent:
#if IS_HNS
	.string "In the ARENA BATTLE TENT,\n"
#else
	.string "In the FALLARBOR BATTLE TENT,\n"
#endif
	.string "we undertake the Set KO Tourney.\p"
	.string "All participants enter with a team of\n"
	.string "three POKéMON.\p"
	.string "The three POKéMON must be lined up\n"
	.string "in the order that they are to appear in.\p"
	.string "During battle, the POKéMON will appear\n"
	.string "one at a time in the preset order.\p"
	.string "Once a POKéMON enters battle, it must\n"
	.string "remain out until the match is decided.\p"
	.string "If a match remains undecided in\n"
	.string "three turns, it goes to judging.\p"
	.string "If you wish to interrupt your challenge,\n"
	.string "please save the game.\p"
	.string "If you don't save, you will not be able\n"
	.string "to continue with your challenge.\p"
	.string "If you pull off the feat of beating\n"
	.string "three TRAINERS in succession,\l"
	.string "we will present you with a fine prize.$"

FallarborTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "在挑战对战帐篷之前要先写入记录，\n"
	.string "可以吗？$"

@ Unused
FallarborTown_BattleTentLobby_Text_WhichLevelMode:
	.string "我们提供2个级别的比赛，Lv. \n"
	.string "50级和自由等级您要参加哪个？$"

FallarborTown_BattleTentLobby_Text_SelectThreeMons:
	.string "好的，请选择3只宝可梦。$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "My dear challenger!\p"
	.string "You do not have the three POKéMON\n"
	.string "required for entry.\p"
	.string "They also must not hold the same\n"
	.string "kinds of items.\p"
	.string "EGGS{STR_VAR_1} ineligible.\p"
	.string "When you have made your preparations,\n"
	.string "please do return.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "这位客人！\p"
	.string "您能够参加对战的宝可梦不满3只。\p"
	.string "您需要准备3只不同种类的宝可梦，\p"
	.string "且让它们分别携带不同道具才可参加\n"
	.string "对战。\p"
	.string "此外，蛋{STR_VAR_1}无\n"
	.string "法参加对战！\p"
	.string "请在准备就绪之后，再来参加吧！$"

FallarborTown_BattleTentLobby_Text_GuideYouToBattleTent:
	.string "我现在带您进入对战帐篷。$"

FallarborTown_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "这位客人！\p"
	.string "您在上次结束时没有写入记录吧？\p"
	.string "非常遗憾，没有写入记录的挑战我们\n"
	.string "将视其为无效。\p"
	.string "当然，您可以随时开始一次新的挑战\n"
	.string "。$"

FallarborTown_BattleTentLobby_Text_BeatThreeTrainers:
	.string "太棒了！您连续打败了3位训练家！$"

FallarborTown_BattleTentLobby_Text_WaitWhileSaveGame:
	.string "正在写入记录……请稍候。$"

FallarborTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "为纪念您取得3连胜，特此为您颁发\n"
	.string "这份奖品。$"

FallarborTown_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER}得到了\n"
	.string "{STR_VAR_1}。$"

FallarborTown_BattleTentLobby_Text_BagFullReturnForPrize:
	.string "哎？包包已经满了。\p"
	.string "请把包包整理好之后再来领取吧。$"

FallarborTown_BattleTentLobby_Text_ThankYouWaitWhileSaving:
	.string "辛苦了！\p"
	.string "正在写入记录……请稍候。$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge2:
	.string "随时恭候您再次挑战！$"

FallarborTown_BattleTentLobby_Text_LookingForwardToArrival:
	.string "我们一直恭候您的到来。\p"
	.string "在带您进入对战帐篷之前，需要先写\n"
	.string "入记录。请稍候。$"

#if IS_HNS
VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "I welcome you to the BATTLE TENT!\p"
	.string "Here, the TRAINER's trust toward\n"
	.string "POKéMON is tested.$"
#else
VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "I welcome you to the BATTLE TENT\n"
	.string "VERDANTURF SITE!\p"
	.string "Here, the TRAINER's trust toward\n"
	.string "POKéMON is tested.$"
#endif
VerdanturfTown_BattleTentLobby_Text_TakeChallenge:
#if IS_HNS
	.string "Do you wish to take the PALACE\n"
#else
	.string "Do you wish to take the VERDANTURF\n"
#endif
	.string "BATTLE TENT challenge?$"

VerdanturfTown_BattleTentLobby_Text_ExplainVerdanturfTent:
#if IS_HNS
	.string "In the PALACE BATTLE TENT,\n"
#else
	.string "In the VERDANTURF BATTLE TENT,\n"
#endif
	.string "there is one crucial rule that must\l"
	.string "be obeyed.\p"
	.string "TRAINERS are permitted only to switch\n"
	.string "their POKéMON in and out.\p"
	.string "TRAINERS are otherwise forbidden to\n"
	.string "command their POKéMON.\p"
	.string "The POKéMON are to behave according\n"
	.string "to their nature and battle on their own.\p"
	.string "You must put your trust in your\n"
	.string "POKéMON and watch over them.\p"
	.string "If you achieve the honor of beating\n"
	.string "three TRAINERS in succession,\l"
	.string "we will present you with a prize.\p"
	.string "If you want to interrupt your\n"
	.string "challenge, please save the game.\p"
	.string "If you don't save before interrupting,\n"
	.string "you will be disqualified.$"

VerdanturfTown_BattleTentLobby_Text_ReturnFortified:
	.string "当您的心灵与您的宝可梦都变得更强\n"
	.string "的时候，再回到这里来吧。$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_WhichLevelMode:
	.string "有2个级别，Lv. 50级和自由\n"
	.string "等级。您要挑战哪个？$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "唉……\p"
	.string "您能够参加对战的宝可梦不满3只。\p"
	.string "您需要准备3只不同种类的宝可梦，\p"
	.string "且让它们分别携带不同道具才可参加\n"
	.string "对战。\p"
	.string "此外，蛋{STR_VAR_1}无\n"
	.string "法参加对战！\p"
	.string "请在准备就绪之后，再来参加吧！$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "唉……\p"
	.string "您能够参加对战的宝可梦不满3只。\p"
	.string "您需要准备3只不同种类的宝可梦，\p"
	.string "且让它们分别携带不同道具才可参加\n"
	.string "对战。\p"
	.string "此外，蛋{STR_VAR_1}无\n"
	.string "法参加对战！\p"
	.string "请在准备就绪之后，再来参加吧！$"

VerdanturfTown_BattleTentLobby_Text_SelectThreeMons:
	.string "好的。现在请您选择3只宝可梦。$"

VerdanturfTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "在进入对战帐篷之前需要先写入记录\n"
	.string "，可以吗？$"

VerdanturfTown_BattleTentLobby_Text_NowFollowMe:
	.string "很好。那么，请随我来。$"

VerdanturfTown_BattleTentLobby_Text_ResultsWillBeRecorded:
	.string "很荣幸能观赏到您的宝可梦的英姿。\p"
	.string "正在记录比赛成绩，请稍候。$"

VerdanturfTown_BattleTentLobby_Text_AchievedThreeWinStreak:
	.string "您达成了3连胜……\p"
	.string "看来您的心灵与宝可梦之间的牵绊已\n"
	.string "经坚不可摧。$"

VerdanturfTown_BattleTentLobby_Text_FeatWillBeRecorded:
	.string "正在记录比赛成绩，请稍候。$"

VerdanturfTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "为纪念您取得3连胜，特此为您颁发\n"
	.string "这份奖品。$"


#if IS_HNS
SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Welcome to the BATTLE TENT!\p"
	.string "I am your guide to the Battle Swap\n"
	.string "Tournament.$"
#else
SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Welcome to the BATTLE TENT\n"
	.string "SLATEPORT SITE!\p"
	.string "I am your guide to the Battle Swap\n"
	.string "Tournament.$"
#endif


SlateportCity_BattleTentLobby_Text_TakeChallenge:
	.string "要挑战交换式对战锦标赛吗？$"

SlateportCity_BattleTentLobby_Text_ExplainSlateportTent:
#if IS_HNS
	.string "Here at the FACTORY BATTLE TENT,\n"
#else
	.string "Here at the SLATEPORT BATTLE TENT,\n"
#endif
	.string "we hold Battle Swap events\l"
	.string "using rental POKéMON.\p"
	.string "First, you will be loaned three\n"
	.string "POKéMON specifically for this event.\p"
	.string "Using the supplied rental POKéMON,\n"
	.string "you must conduct a SINGLE BATTLE.\p"
	.string "If you win, you are permitted to trade\n"
	.string "one of your rental POKéMON.\p"
	.string "Repeat this cycle of battling and\n"
	.string "trading--if you win three times in\l"
	.string "a row, you will earn a fine prize.\p"
	.string "If you want to interrupt your\n"
	.string "challenge, please save the game.\p"
	.string "If you don't save before interrupting,\n"
	.string "you will be disqualified.$"

SlateportCity_BattleTentLobby_Text_LookForwardToNextVisit:
	.string "我们期待您的再次光临。$"

@ Unused
SlateportCity_BattleTentLobby_Text_WhichLevelMode:
	.string "您要挑战哪个等级？Lv. 50级\n"
	.string "还是100级？$"

SlateportCity_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "在挑战前需要先写入记录，可以吗？$"

@ Unused
SlateportCity_BattleTentLobby_Text_HoldMonsForSafekeeping:
	.string "好的，我会替您保管宝可梦。$"

SlateportCity_BattleTentLobby_Text_StepThisWay:
	.string "这边请。$"

SlateportCity_BattleTentLobby_Text_ReturnRentalMonsSaveResults:
	.string "辛苦了！\p"
	.string "我将把您的宝可梦还给您并换回租借\n"
	.string "宝可梦。\p"
	.string "并且需要写入对战记录。请稍等。$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnMonsExchangeRentals:
	.string "我要将您的宝可梦还给您并且收回我\n"
	.string "们借给您的宝可梦。$"

SlateportCity_BattleTentLobby_Text_WonThreeMatchesReturnMons:
	.string "恭喜您！您获得了3连胜！\p"
	.string "我将把您的宝可梦还给您并换回租借\n"
	.string "宝可梦。\p"
	.string "并且需要写入对战记录。请稍等。$"

SlateportCity_BattleTentLobby_Text_AwardYouThisPrize:
	.string "为纪念您取得3连胜，特此为您颁发\n"
	.string "这份奖品。$"

SlateportCity_BattleTentLobby_Text_NoRoomInBagMakeRoom:
	.string "哎？包包已经满了。\p"
	.string "请把包包整理好之后再来领取吧。$"

SlateportCity_BattleTentLobby_Text_BeenWaitingForYou:
	.string "我们已经恭候多时了！\p"
	.string "在您继续战斗之前，需要先写入记录\n"
	.string "。$"

SlateportCity_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "I'm sorry to say this, but you didn't\n"
	.string "save before you quit playing last time.\p"
	.string "As a result, you have been disqualified\n"
	.string "from your challenge.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnPersonalMons:
	.string "我们将归还您的宝可梦。$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER}得到奖品\n"
	.string "{STR_VAR_1}。$"

@ Unused
SlateportCity_BattleTentLobby_Text_RulesAreListed:
	.string "交换式对战规则已经列出。$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReadWhichHeading:
	.string "要读哪一部分的说明？$"

SlateportCity_BattleTentLobby_Text_ExplainBasicRules:
	.string "在交换式对战中，您只能用3只宝可\n"
	.string "梦。\p"
	.string "无论是租借还是交换得到的，您的队\n"
	.string "伍中不能出现2只或以上相同种类的\l"
	.string "宝可梦。$"

SlateportCity_BattleTentLobby_Text_ExplainSwapPartnerRules:
	.string "您只能与刚击败过的训练家交换宝可\n"
	.string "梦。\p"
	.string "您只能交换到该训练家所使用的宝可\n"
	.string "梦。$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNumberRules:
	.string "每获胜1场战斗后，您可以选择交换\n"
	.string "对手的1只宝可梦。\p"
	.string "第3位训练家不可进行交换。$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNotes:
	.string "在交换宝可梦时有2个需要注意的地\n"
	.string "方。\p"
	.string "第一，交换时您无法查看目标宝可梦\n"
	.string "的具体能力。\p"
	.string "第二，队伍中的宝可梦的排列顺序按\n"
	.string "租用时的顺序固定。\p"
	.string "交换后该顺序仍保持不变。$"

SlateportCity_BattleTentLobby_Text_ExplainMonRules:
	.string "在凯那市对战帐篷中使用的宝可梦都\n"
	.string "是租借的。\p"
	.string "所有租借的宝可梦等级均为30。$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_RulesAreListed2:
	.string "绿茵镇对战帐篷的规则已经列出$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ReadWhichHeading:
	.string "要读哪一部分的说明？$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainBasicRules:
	.string "在绿茵镇对战帐篷，宝可梦需要独立\n"
	.string "思考并战斗。\p"
	.string "不像在野外，宝可梦和人类一起生存\n"
	.string "由于自然环境不同行为也不同。$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainNatureRules:
	.string "由于它所处自然环境，宝可梦可能会\n"
	.string "不知原因的攻击。\p"
	.string "另外的宝可梦可能会保护自己免受伤\n"
	.string "害。\p"
	.string "有的还喜欢干扰和迷惑自己的敌人。\p"
	.string "由于它所处的自然环境，宝可梦可能\n"
	.string "有它所最喜欢的招式并且可以熟练使\l"
	.string "用。\p"
	.string "它也有可能存在不喜欢的招式于是不\n"
	.string "擅长使用。$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainMoveRules:
	.string "有攻击招式可以对敌人造成直接伤害\n"
	.string "。\p"
	.string "有防守招式用来防御敌人的攻击或用\n"
	.string "来恢复HP等等。\p"
	.string "也有一些有点怪异的招式可以使得敌\n"
	.string "人变得无力和带来其他问题，例如中\l"
	.string "毒和麻痹。\p"
	.string "宝可梦可能会考虑在这3种招式中选\n"
	.string "择使用。$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainUnderpoweredRules:
	.string "当没有听从训练家的命令时宝可梦可\n"
	.string "能不会有效的使用特定招式。\p"
	.string "宝可梦不擅长使用任何它不喜欢的招\n"
	.string "式。\p"
	.string "如果宝可梦仅仅知道些不符合其性格\n"
	.string "的招式，那么它就不会展示它的潜能\l"
	.string "。$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainWhenInDangerRules:
	.string "根据其性格，当陷入麻烦时，宝可梦\n"
	.string "可能会开始使用一些并不符合性格的\l"
	.string "招式。\p"
	.string "如果宝可梦开始变得行为怪异，您就\n"
	.string "有必要仔细查看了。$"

BattleTentLobby_Text_ExplainLevelRules:
	.string "在对战帐篷中，对手的宝可梦等级会\n"
	.string "根据您的宝可梦等级进行调整。\p"
	.string "但是，训练家所持有的宝可梦最低不\n"
	.string "会低于等级30。$"

VerdanturfTown_BattleTentLobby_Text_RulesAreListed:
	.string "上面列出了绿茵镇对战帐篷的规则。$"

BattleTentLobby_Text_EarnedBattlePoints:
	.string "You've earned {STR_VAR_1} Battle Points!$"

