PetalburgCity_Gym_Text_GiveEnigmaBerry:
	.string "爸爸：嘿，{PLAYER}！\p"
	.string "我刚刚得到了一种稀有树果，给你拿\n"
	.string "着吧。$"

Route104_Text_PlantBerriesInSoilTakeThis:
	.string "你可以随意取走生长在松软的土壤里\n"
	.string "的树果，\p"
	.string "但记住离开之前一定要在同一个地方\n"
	.string "种下一枚树果，这是约定俗成的习\l"
	.string "惯。\p"
	.string "这个给你吧。$"

Route104_Text_TrainersOftenMakeMonHoldBerries:
	.string "看上去……你一定是训练家吧？\p"
	.string "训练家经常会给他们的宝可梦携带树\n"
	.string "果。\p"
	.string "当然，得到树果后是种植还是使用都\n"
	.string "取决于你自己。$"

Route111_Text_WateredPlantsEveryDayTakeBerry:
	.string "我每天都给植物浇水，开出了好多好\n"
	.string "多花呢。\p"
	.string "而且结出了好多树果哦。\p"
	.string "这个给你！送给你啦！$"

Route111_Text_GoingToTryToMakeDifferentColorBerries:
	.string "我要努力种出不同颜色的树果。\p"
	.string "你也要努力啊！$"

Route111_Text_WhatColorBerriesToLookForToday:
	.string "今天去找什么颜色的树果呢？$"

Route114_Text_LoveUsingBerryCrushShareBerry:
	.string "我喜欢玩树果粉碎，所以我收集了各\n"
	.string "种各样的树果。\p"
	.string "这个给你怎么样？$"

Route114_Text_TryBerryCrushWithFriends:
	.string "我建议你和你的朋友一起玩树果粉\n"
	.string "碎。$"

Route114_Text_FunToThinkAboutBerries:
	.string "该种什么树果？得到的树果是使用还\n"
	.string "是收藏起来？\p"
	.string "考虑这些事情也是乐趣啊。$"

Route120_Text_BerriesExpressionOfLoveIsntIt:
	.string "树果吸收了阳光，渐渐成长，\p"
	.string "而我们要经常给它们浇水，帮助它们\n"
	.string "长大。\p"
	.string "这大概就是爱的表现吧？$"

Route120_Text_YesYouUnderstand:
	.string "啊，没错，没错，看来你明白我说的\n"
	.string "话了。\p"
	.string "这个给你吧。$"

Route120_Text_MakeYourOwnImpressions:
	.string "啊……也对，有自己的想法才是最重要\n"
	.string "的……\p"
	.string "这个给你吧。$"

Route120_Text_BerryIsRareRaiseItWithCare:
	.string "这可是个很少见的树果，希望你能用\n"
	.string "你的爱去照顾它成长。$"

Route120_Text_IllGetMoreBerriesFromBerryMaster:
	.string "我会从树果名人那儿得到更多树果。$"

LilycoveCity_Text_BerrySuitsYou:
	.string "要怎么说呢……\p"
	.string "就像我适合穿西装，海风适合在海边\n"
	.string "吹一样，\p"
	.string "你适合拥有树果……\p"
	.string "为什么呢？$"

LilycoveCity_Text_BecauseYoureTrainer:
	.string "要怎么说呢……\p"
	.string "就因为你是训练家！$"

LilycoveCity_Text_PokeblocksSuitPokemon:
	.string "说到底……\p"
	.string "正如端庄素雅非常适合我一样，\n"
	.string "{POKEBLOCK}也同样完美\l"
	.string "适合宝可梦。$"

Route123_BerryMastersHouse_Text_YoureDeservingOfBerry:
	.string "你可以叫我树果名人。\p"
	.string "我始终梦想着让鲜花开满世界各地，\n"
	.string "所以我种植树果并把它们交托给遇见\l"
	.string "的每一个人。\p"
	.string "收下这个吧！$"

Route123_BerryMastersHouse_Text_WhyBeStingyTakeAnother:
	.string "不用客气，这个也给你！$"

Route123_BerryMastersHouse_Text_VisitPrettyPetalFlowerShop:
	.string "记得一定要去卡那兹市附近的花店圣\n"
	.string "橙华看看。\p"
	.string "愿鲜花开满世界！$"

Route123_BerryMastersHouse_Text_DoneForToday:
	.string "今天就这些了，以后再来吧。\p"
	.string "愿鲜花开满世界！$"

Route123_BerryMastersHouse_Text_HeardAGoodSayingLately:
	.string "我家老头子是世界上最擅长种树果的\n"
	.string "人。\p"
	.string "呵呵，这是我最自豪的事情。\p"
	.string "话说回来，孩子，你听说过最近一句\n"
	.string "流行的谚语吗？$"

Route123_BerryMastersHouse_Text_InspirationalTakeThis:
	.string "啊！多棒的谚语！真令人感动！\p"
	.string "这个送给你吧。$"

Route123_BerryMastersHouse_Text_GoodSayingTakeThis:
	.string "啊！很好的谚语。真是了不起。\p"
	.string "这个送给你吧。$"

Route123_BerryMastersHouse_Text_JoyNeverGoesOutOfMyLife:
	.string "我们的四个孙子肯定会比老头子干得\n"
	.string "更好的。\p"
	.string "我的生活里始终都充满了快乐！$"

Route123_BerryMastersHouse_Text_Ah:
	.string "啊……$"

Route104_PrettyPetalFlowerShop_Text_ThisIsPrettyPetalFlowerShop:
	.string "欢迎！\p"
	.string "这里是花店。我们的目标是让鲜花开\n"
	.string "满全世界！$"

Route104_PrettyPetalFlowerShop_Text_LearnAboutBerries:
	.string "{PLAYER}{KUN}，想知\n"
	.string "道关于树果的事情吗？$"

Route104_PrettyPetalFlowerShop_Text_IntroLearnAboutBerries:
	.string "你的名字是？\p"
	.string "{PLAYER}{KUN}。好名\n"
	.string "字。\p"
	.string "{PLAYER}{KUN}，想知\n"
	.string "道关于树果的事情吗？$"

Route104_PrettyPetalFlowerShop_Text_BerriesExplanation:
	.string "树果只有在松软的土壤中才能健康生\n"
	.string "长。\p"
	.string "如果你摘了树果，请记得在土壤中再\n"
	.string "种下一颗。\p"
	.string "种下的树果很快会发芽，长出枝叶，\n"
	.string "开出美丽的花，最后又结出树果。\p"
	.string "真希望能看到整个世界都布满了美丽\n"
	.string "的花啊。这可一直是我的梦想。\p"
	.string "来帮我们吧，{PLAYER}\n"
	.string "{KUN}，多种些树果，让世界上\l"
	.string "开出更多鲜花吧。$"

Route104_PrettyPetalFlowerShop_Text_FlowersBringHappiness:
	.string "鲜花会使人们得到幸福。$"

Route104_PrettyPetalFlowerShop_Text_YouCanHaveThis:
	.string "欢迎！\p"
	.string "你越是细心地照顾花朵，花朵就会绽\n"
	.string "放得越艳丽。\p"
	.string "看上去你很喜欢照顾花儿，这个送给\n"
	.string "你吧。$"

Route104_PrettyPetalFlowerShop_Text_WailmerPailExplanation:
	.string "树果渐渐长大的时候，就用吼吼鲸喷\n"
	.string "壶给它们浇水吧。\p"
	.string "啊，对了，\p"
	.string "如果一段时间里你没摘下树果，它们\n"
	.string "会掉进土里，不过很快它们又会发芽\l"
	.string "的。\p"
	.string "挺不错的吧？就好像它们自己也盼望\n"
	.string "着成长一样。$"

Route104_PrettyPetalFlowerShop_Text_ImGrowingFlowers:
	.string "我正在向姐姐们学习种花，总有一\n"
	.string "天，我也会像她们那样优秀！\p"
	.string "给！这个送你！$"

Route104_PrettyPetalFlowerShop_Text_MachineMixesBerries:
	.string "你可以把树果种到土里让它长大，也\n"
	.string "可以让宝可梦携带它，\p"
	.string "现在还有另一种选择，用一种特别的\n"
	.string "机器混合树果为宝可梦制作糖果。\p"
	.string "我也想要些糖果啊。$"

SootopolisCity_Text_NameIsKiriHaveOneOfThese:
	.string "你叫什么名字啊？\p"
	.string "…… …… …… …… ……嗯，真是个好名字\p"
	.string "我叫小桐。\p"
	.string "爸爸妈妈希望我健康长大且热心助\n"
	.string "人，所以给我起了这个名字。\p"
	.string "这个给你一个吧。$"

SootopolisCity_Text_GiveYouThisBerryToo:
	.string "小桐也会给你这种树果的！我真的很\n"
	.string "喜欢它！$"

SootopolisCity_Text_WhatKindOfWishInYourName:
	.string "你的名字里会包含了什么样的期望\n"
	.string "呢？$"

SootopolisCity_Text_LikeSeasonBornIn:
	.string "春，夏，秋，冬……\p"
	.string "春天出生的人喜欢春天冬天出生的人\n"
	.string "喜欢冬天吗？$"

SootopolisCity_Text_ThenILoveAutumn:
	.string "那么，小桐是秋天出生的，所以一定\n"
	.string "喜欢秋天！\p"
	.string "你喜欢什么季节？$"

SootopolisCity_Text_OhDoesntMatter:
	.string "啊……算了，没关系......\p"
	.string "我想要了解的事情还有好多好多呢.\n"
	.string ".....$"
