gText_Birch_Welcome::
	.string "哎呀——让你久等啦！\p"
	.string "欢迎来到宝可梦的世界！\p"
	.string "我的名字是小田卷。\p"
	.string "不过大家都叫我宝可梦博士。\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "这个世界上叫做宝可梦的生物随处可\n"
	.string "见。\p"
	.string "人们和宝可梦友好相处、共同生活，\n"
	.string "有时作为玩伴一起玩耍，有时作为同\l"
	.string "伴协力工作。\p"
	.string "也有时候，我们指挥宝可梦并肩而战\n"
	.string "，与其他人彼此对战切磋。\p"
	.string "尽管如此亲密，我们仍未了解宝可梦\n"
	.string "的一切。\p"
	.string "事实上，宝可梦身上的秘密依然数不\n"
	.string "胜数！\p"
	.string "为了揭开宝可梦的秘密，我倾注了毕\n"
	.string "生心血进行研究。这就是我一直在做\l"
	.string "的事。\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "对了，你是……$"

gText_Birch_BoyOrGirl::
	.string "男孩？还是女孩？$"

gText_Birch_WhatsYourName::
	.string "好的。能告诉我你的名字吗？$"

gText_Birch_SoItsPlayer::
	.string "是{PLAYER}{KUN}吗？$"

gText_Birch_YourePlayer::
	.string "……原来如此！\p"
	.string "你就是即将搬到未白镇来的\n"
	.string "{PLAYER}{KUN}啊！我\l"
	.string "知道了！\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "好，准备好了吗？\p"
	.string "只属于你的冒险即将展开！\p"
	.string "鼓起勇气，迈进充满梦想、冒险与邂\n"
	.string "逅的宝可梦世界吧！\p"
	.string "之后在研究所见吧！我在那里等着你\n"
	.string "！\p"
	.string "$"
