BerryBlender_Text_BlendWithTheBlendMaster:
	.string "混合名人：没错！我就是传说中的混\n"
	.string "合名人！\p"
	.string "与我共舞吧，你将亲眼见证我登峰造\n"
	.string "极的混合技艺！$"

BerryBlender_Text_SeeMyMasteryInAction:
	.string "混合名人：嗯！你想亲眼见识我的独\n"
	.string "门技艺？$"

BerryBlender_Text_TooBusyNowIsee:
	.string "嗯！\p"
	.string "看来你现在很忙啊！\p"
	.string "不过别担心！我会在这里待一整天！\n"
	.string "快去快回吧！$"

BerryBlender_Text_BlendMasterNoBerries:
	.string "嗯！\p"
	.string "你连一颗树果都没有！\p"
	.string "我会在这里待一整天！快去摘些树果\n"
	.string "回来！$"

BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks:
	.string "Of course!\n"
	.string "Of course!\p"
	.string "Incidentally…\n"
	.string "You do know how to blend {POKEBLOCK}S\l"
	.string "from BERRIES?$"

BerryBlender_Text_BlendMasterExplainBerryBlending:
	.string "嗯！\p"
	.string "其实过程很简单！\p"
	.string "当混合器的箭头转到你的标记时，按\n"
	.string "下A键就行。\p"
	.string "就这么简单。\p"
	.string "等你见识到我精准按下A键的功力，\n"
	.string "就会明白其中奥妙了。$"

BerryBlender_Text_BlendMasterLetsBerryBlender:
	.string "很好！\p"
	.string "那我们就开始吧！\p"
	.string "与混合名人一起，开始树果混合吧！$"

BerryBlender_Text_BlendMasterNoPokeblockCase:
	.string "Hmmm!\p"
	.string "You don't appear to have gotten\n"
	.string "the {POKEBLOCK} CASE!\p"
	.string "I shall be here all day!\n"
	.string "Obtain the {POKEBLOCK} CASE and hurry back!$"

BerryBlender_Text_BlendMasterPokeblockCaseFull:
	.string "Hmmm!\p"
	.string "Your {POKEBLOCK} CASE appears to be full!\p"
	.string "I shall be here all day!\n"
	.string "Use some {POKEBLOCK}S and hurry back!$"

BerryBlender_Text_WhoaAwesome:
	.string "Whoa!\n"
	.string "Awesome!$"

BerryBlender_Text_WickedlyFast:
	.string "真是快得惊人！$"

BerryBlender_Text_WhatAnExpert:
	.string "真是专家啊！$"

BerryBlender_Text_MadeAmazingPokeblocksWithMaster:
	.string "When I blended with the MASTER,\n"
	.string "we made amazing {POKEBLOCK}S!$"

BerryBlender_Text_QualitiesOfBlendMaster:
	.string "如机器般精准追踪箭头的双眼……\p"
	.string "如钟表般精确按下A键的巧手……\p"
	.string "拥有这些特质，才成就了真正的混合\n"
	.string "名人。$"

BerryBlender_Text_MasterWorksOnSkillsInMountains:
	.string "据说混合名人常年在深山中磨练他的\n"
	.string "技艺。\p"
	.string "有时他会来到水静市，混合树果一整\n"
	.string "天。$"
