CableClub_Text_WelcomeWhichCableClubService:
	.string "欢迎来到宝可梦联机俱乐部，\p"
	.string "请问您需要使用哪项服务？$"

CableClub_Text_WhichService:
	.string "请问您需要使用哪项服务？$"

CableClub_Text_TradeUsingLinkCable::
	.string "通过GBA连接线与其他玩家交换宝\n"
	.string "可梦。$"

CableClub_Text_BattleUsingLinkCable::
	.string "通过GBA连接线与其他训练家进行\n"
	.string "对战。$"

CableClub_Text_RecordCornerUsingLinkCable::
	.string "通过GBA连接线与其他人使用记录\n"
	.string "角功能。$"

@ Unused
CableClub_Text_CloseThisMenu:
	.string "关闭菜单。$"

CableClub_Text_NeedTwoMonsForDoubleBattle:
	.string "要进行双打对战的话，至少要携带2\n"
	.string "只宝可梦。$"

CableClub_Text_NeedTwoMonsToTrade:
	.string "要进行交换的话，至少要携带2只宝\n"
	.string "可梦。$"

CableClub_Text_CantTradeEnigmaBerry:
	.string "带有{STR_VAR_1}树果的\n"
	.string "宝可梦无法进行交换。$"

gText_PleaseWaitForLink::
	.string "正在等待连接………… B键：取消$"

gText_ConfirmLinkWhenPlayersReady::
	.string "等待所有玩家准备完毕……A键：确\n"
	.string "认B键：取消$"

gText_ConfirmStartLinkWithXPlayers::
	.string "开始与{STR_VAR_1}名玩\n"
	.string "家进行连接。A键：确认B键：取消$"

gText_AwaitingLinkup::
	.string "正在等待连接………… B键：取消$"

@ Unused
CableClub_Text_OkayToSaveProgress::
	.string "连接前必须先写入记录，可以吗？$"

CableClub_Text_PleaseEnter:
	.string "请进。$"

CableClub_Text_DirectYouToYourRoom:
	.string "请让我带您前往您的房间。$"

Text_SomeoneIsNotReadyToLink:
	.string "有玩家尚未准备好连接。\p"
	.string "请待所有人准备就绪之后再来。$"

Text_LinkErrorPleaseReset:
	.string "对不起，连接发生错误……请重启之\n"
	.string "后再试。$"

Text_PlayersMadeDifferentSelections:
	.string "连接伙伴的选择似乎不一致。$"

CableClub_Text_PleaseVisitAgain:
	.string "欢迎再次光临。$"

CableClub_Text_IncorrectNumberOfParticipants:
	.string "参与人数不正确。$"

CableClub_Text_CantSingleBattleWithXPlayers:
	.string "单打模式无法由\n"
	.string "{STR_VAR_1}名玩家进行\l"
	.string "。$"

CableClub_Text_CantDoubleBattleWithXPlayers:
	.string "双打模式无法由\n"
	.string "{STR_VAR_1}名玩家进行\l"
	.string "。$"

CableClub_Text_NeedFourPlayers:
	.string "此对战模式需要4位玩家参与。$"

CableClub_Text_PleaseConfirmNumberAndRestart:
	.string "请确认玩家数量后重新开始。$"

Text_TerminateLinkConfirmation:
	.string "如果离开房间，连接将会中止。可以\n"
	.string "吗？$"

Text_TerminateLinkPleaseWait:
	.string "正在中止连接……将由向导带您离开\n"
	.string "房间，请稍候。$"

CableClub_Text_TooBusyToNotice:
	.string "这个训练家太忙，没空注意……$"

CableClub_Text_GotToLookAtTrainerCard:
	.string "成功查看了{STR_VAR_1}\n"
	.string "的训练家卡！$"

CableClub_Text_GotToLookAtColoredTrainerCard:
	.string "成功查看了{STR_VAR_1}\n"
	.string "的训练家卡！\p"
	.string "是一张{STR_VAR_2}色的\n"
	.string "训练家卡！$"

BattleColosseum_2P_Text_TakePlaceStartBattle:
	.string "请就位，准备开始对战。$"

TradeCenter_Text_TakeSeatStartTrade:
	.string "请就位，准备开始交换。$"

RecordCorner_Text_ThanksForComing:
	.string "感谢参与。$"

CableClub_Text_TrainerCardDataOverwritten:
	.string "训练家卡数据将被覆盖。$"

CableClub_Text_HopeToSeeYouAgain:
	.string "期待再次相见！$"

CableClub_Text_NotSetUpForFarAwayRegion:
	.string "非常抱歉！\p"
	.string "我们目前尚未开放与其它地区的训练\n"
	.string "家进行连接的功能……$"

CableClub_Text_OtherTrainerNotReady:
	.string "其他训练家尚未准备好。$"

CableClub_Text_YouHaveAMonThatCantBeTaken:
	.string "您带有无法携带的宝可梦。$"

RecordCorner_Text_TakeSeatAndWait:
	.string "请您在座位上等候。$"

RecordCorner_Text_PlayerSentOverOneX:
	.string "{STR_VAR_1}送出了1个\n"
	.string "{STR_VAR_2}。$"

CableClub_Text_CantMixWithJapaneseGame:
	.string "对不起，连接错误。\p"
	.string "无法与日版红/蓝宝石混合记录。\p"
	.string "此外，也无法同时与日版绿宝石和海\n"
	.string "外版红/蓝宝石混合记录。$"

CableClub_Text_AdapterNotConnected:
	.string "无线适配器没有正确连接。$"

CableClub_Text_ParticipantsStepUpToCounter:
	.string "参加者请到接待处。$"

@ Unused
CableClub_Text_Hello:
	.string "您好！$"

@ Unused
CableClub_Text_PleaseWait:
	.string "请稍候。$"

CableClub_Text_YouMayTradeHere::
	.string "在这里您可以与其他训练家交换宝可\n"
	.string "梦。$"

CableClub_Text_YouMayBattleHere::
	.string "在这里您可以与朋友进行对战。$"

CableClub_Text_CanMakeBerryPowder::
	.string "可以与2到5个训练家一起制作树果\n"
	.string "粉末。$"

CableClub_Text_CanMixRecords::
	.string "这里可以将2到4个玩家的记录混合\n"
	.string "在一起。$"

@ Unused
CableClub_Text_GuideToVariousServices:
	.string "无线俱乐部的导游提供各种服务。$"

CableClub_Text_CancelSelectedItem::
	.string "取消选定的菜单项目。$"

@ Unused
CableClub_Text_WhichBattleMode:
	.string "您喜欢哪种对战模式？$"

@ Unused
CableClub_Text_ReturnsToPreviousStep:
	.string "回到上一步。$"

CableClub_Text_NeedBerryForBerryCrush:
	.string "要使用树果粉碎，您至少要有1个树\n"
	.string "果。$"

CableClub_Text_NeedTwoMonsForUnionRoom:
	.string "要进入联盟交谊厅，您至少要带有2\n"
	.string "只宝可梦。$"

CableClub_Text_NoEnigmaBerryInUnionRoom:
	.string "带有{STR_VAR_1}树果的\n"
	.string "宝可梦无法进入联盟交谊厅。$"

CableClub_Text_UnionRoomAdapterNotConnected:
	.string "这里是宝可梦无线俱乐部联盟交谊厅\n"
	.string "，\p"
	.string "很抱歉，您的无线适配器没有正确连\n"
	.string "接，\p"
	.string "请下次再来。$"

@ Unused
CableClub_Text_OhExcuseMe:
	.string "哦……打扰了！$"

CableClub_Text_PlayerIsWaiting:
	.string "看来{STR_VAR_1}已经准\n"
	.string "备好了。加油！$"

MossdeepCity_GameCorner_1F_Text_DescribeWhichGame:
	.string "需要的话，我可以向您解说对战规则\n"
	.string "。\p"
	.string "需要解说哪一项？$"

MossdeepCity_GameCorner_1F_Text_PokemonJumpInfo:
	.string "“宝可梦跳绳”\p"
	.string "用A键让您的宝可梦跳过藤鞭。\p"
	.string "只有60厘米以下的小型宝可梦可以\n"
	.string "参加，\p"
	.string "而且，只会游泳、挖掘、飞行的宝可\n"
	.string "梦并不擅长跳跃，\p"
	.string "因此，这些宝可梦也无法参加。\p"
	.string "如果大家都及时跳起，会有好事情发\n"
	.string "生。$"

MossdeepCity_GameCorner_1F_Text_DodrioBerryPickingInfo:
	.string "“嘟嘟摘树果”\p"
	.string "指挥嘟嘟的三颗头\n"
	.string "接住掉落的树果。\p"
	.string "按十字键的右、上、左，\n"
	.string "即可操控三颗头。\p"
	.string "要玩这个游戏，\n"
	.string "你必须拥有一只嘟嘟。$"

MossdeepCity_GameCorner_1F_Text_TalkToOldManToPlay:
	.string "如果您想玩游戏，就告诉我后面的老\n"
	.string "人。$"

MossdeepCity_GameCorner_1F_Text_WelcomeCanYouWait:
	.string "嗨，欢迎！您是想用无线连接玩游戏\n"
	.string "吗？\p"
	.string "请稍等一下好吗？$"

MossdeepCity_GameCorner_1F_Text_ComeAgain:
	.string "好，再来啊！$"

MossdeepCity_GameCorner_1F_Text_AdapterNotConnected:
	.string "无线适配器没有连接。连接好之后再\n"
	.string "回来吧！$"

MossdeepCity_GameCorner_1F_Text_PlayWhichGame:
	.string "好的，要玩哪个游戏？$"

MossdeepCity_GameCorner_1F_Text_EnterWhichPokemon:
	.string "要让哪只宝可梦参加？$"

MossdeepCity_GameCorner_1F_Text_AllGoodToGo:
	.string "好的，一切就绪，一定要赢！$"

@ Unused
MossdeepCity_GameCorner_1F_Text_LeavingDoComeAgain:
	.string "现在离开吗？要再来哟！$"

MossdeepCity_GameCorner_1F_Text_ExplainRequiredMon:
	.string "看来您并没有可以参加的宝可梦……\p"
	.string "需要我为您解释一下什么样的宝可梦\n"
	.string "可以参加吗？$"

MossdeepCity_GameCorner_1F_Text_ShortJumpingPokemonAllowed:
	.string "参加“宝可梦跳绳”的宝可梦必须在\n"
	.string "60厘米以下，\p"
	.string "此外，不会跳跃的宝可梦也无法参加\n"
	.string "，\p"
	.string "比如说，只会游泳、挖掘、飞行的宝\n"
	.string "可梦。\p"
	.string "知道这些就够了。$"

MossdeepCity_GameCorner_1F_Text_OnlyDodrioAllowed:
	.string "只有嘟嘟利可以参加嘟嘟利摘树果。$"

@ Unused
MossdeepCity_GameCorner_1F_Text_RetryPlease:
	.string "要再次从头挑战吗？$"

CableClub_Text_WelcomeWhichDirectCornerRoom:
	.string "欢迎来到宝可梦无线俱乐部直接连接\n"
	.string "室，\p"
	.string "在这里您可以与您的朋友直接进行连\n"
	.string "接。\p"
	.string "您要进入哪个房间？$"

CableClub_Text_TradePokemon:
	.string "要交换宝可梦吗？$"

CableClub_Text_PlayWhichBattleMode:
	.string "要参加哪个对战模式？$"

CableClub_Text_AccessRecordCorner:
	.string "要进入记录角吗？$"

CableClub_Text_UseBerryCrush:
	.string "要使用树果粉碎系统吗？$"

CableClub_Text_ExplainBattleModes:
	.string "一共有3种不同的对战模式。\p"
	.string "单打模式中每位选手至少带上1只宝\n"
	.string "可梦。\p"
	.string "对战开始时每位选手同时派出1只宝\n"
	.string "可梦。\p"
	.string "双打模式中2位选手各自至少带上2\n"
	.string "只宝可梦。\p"
	.string "对战开始时2位选手同时派出2只宝\n"
	.string "可梦。\p"
	.string "混战模式中4位选手各自至少带上1\n"
	.string "只宝可梦。\p"
	.string "对战开始时每位选手同时派出1只宝\n"
	.string "可梦。$"

CableClub_Text_ChooseGroupLeaderOfTwo:
	.string "请协商并选出一人做群组的组长。\p"
	.string "其他人请选择“加入群组。”$"

CableClub_Text_ChooseGroupLeaderOfFour:
	.string "请协商并选出一人做群组的组长。\p"
	.string "其他人请选择“加入群组。”$"

CableClub_Text_ChooseGroupLeader:
	.string "请协商并选出一人做群组的组长。\p"
	.string "其他人请选择“加入群组。”$"

CableClub_Text_WelcomeUnionRoomEnter:
	.string "欢迎来到宝可梦无线连接俱乐部联盟\n"
	.string "交谊厅。\p"
	.string "在这里你可以直接与其他训练家互动\n"
	.string "，甚至包括一些您不认识的人。\p"
	.string "要进入房间吗？$"

CableClub_Text_UnionRoomInfo:
	.string "联盟交谊厅的训练家都是在您周围并\n"
	.string "且也进入了联盟交谊厅的玩家。\p"
	.string "你可以在这里做各种事情，比如互相\n"
	.string "问候。\p"
	.string "您可以拿出2只等级30的宝可梦进\n"
	.string "行1对1的对战。\p"
	.string "您也可以和2到5个人在这里进行聊\n"
	.string "天。\p"
	.string "或者您也可以登记宝可梦进行交换。\p"
	.string "要进入房间吗？$"

CableClub_Text_EnjoyUnionRoom:
	.string "希望您能在联盟交谊厅度过愉快的时\n"
	.string "光。$"

CableClub_Text_FirstTimeRightThisWay:
	.string "您好！我是青名。\p"
	.string "您应该是第一次到这里来吧。\p"
	.string "由我来向您介绍无线连接系统的使用\n"
	.string "方法吧。\p"
	.string "首先需要带您参观一下宝可梦中心的\n"
	.string "这一层。\p"
	.string "这边请。$"

CableClub_Text_ExplainWirelessClubFirstTime:
	.string "在这层有2个房间。\p"
	.string "首先是左边的房间，这是联盟交谊厅\n"
	.string "。\p"
	.string "您能够和那些在您周围并且也进入该\n"
	.string "房间的训练家进行连接。\p"
	.string "您可以和他们一起进行聊天、对战或\n"
	.string "交换。\p"
	.string "其次是右边的房间，叫做直接连接室\n"
	.string "。\p"
	.string "您可以和他们进行交换或对战。\p"
	.string "如果无线适配器没有连接，您仍然可\n"
	.string "以使用GBA连接线进行连接。\p"
	.string "这种情况下，您就需要进入直接连接\n"
	.string "室。\p"
	.string "希望您能享受无线连接系统的乐趣。$"

CableClub_Text_AskAboutLinking:
	.string "您好，{PLAYER}！\p"
	.string "我是青名，宝可梦中心2楼的服务员\n"
	.string "。\p"
	.string "您想了解关于连接的事情吗？$"

CableClub_Text_ExplainWirelessClub:
	.string "请让我为您介绍宝可梦无线俱乐部的\n"
	.string "功能。\p"
	.string "在最顶层的这一层，一共有两个房\n"
	.string "间。\p"
	.string "首先是左手边的房间，那里是“联谊\n"
	.string "厅”。\p"
	.string "您可以与周围同样进入了联谊厅的训\n"
	.string "练家进行连接。\p"
	.string "您可以与他们一起聊天、进行对战或\n"
	.string "是交换。\p"
	.string "其次是右手边的房间，那里是“直接\n"
	.string "角”。\p"
	.string "您可以在这个房间里与朋友交换宝可\n"
	.string "梦或进行对战。\p"
	.string "有时，您可能无法在联谊厅或直接角\n"
	.string "找到您的朋友。\p"
	.string "遇到这种情况时，请尽量靠近您的朋\n"
	.string "友。\p"
	.string "如果没有连接无线适配器，您仍然可\n"
	.string "以使用GBA通信线进行连接。\p"
	.string "如果是那样的话，请前往直接角。\p"
	.string "祝您享受无线通信系统的乐趣。$"

CableClub_Text_HopeYouEnjoyWirelessSystem:
	.string "希望您能享受无线连接系统的乐趣。$"
