@ Same as Hoenn's day-care text, used by the Four Island Day-Care. Unused text translated in Emerald

DayCare_Text_ImDaycareManSpeakToMyWife::
	.string "我是培育屋爷爷。\p"
	.string "我负责帮训练家照料他们宝贵的宝可\n"
	.string "梦。\p"
	.string "如果你想寄放宝可梦的话，请跟我老\n"
	.string "伴说吧。$"

DayCare_Text_DoYouWantEgg::
	.string "啊，是你啊！\p"
	.string "我们帮你照顾宝可梦的时候，哎呀，\n"
	.string "真是吓了一跳！\p"
	.string "你的宝可梦竟然带着一颗蛋！\p"
	.string "虽然不知道是怎么来的，但确实是在\n"
	.string "你的宝可梦身边的。\p"
	.string "你想要收下它，对吧？$"

DayCare_Text_YourMonIsDoingFine::
	.string "哎呀，是你啊！见到你真高兴。你的\n"
	.string "{STR_VAR_1}精神得很\l"
	.string "呢。$"

DayCare_Text_IllKeepIt::
	.string "这样啊，那我就自己留着了。谢谢你\n"
	.string "啦！$"

DayCare_Text_YouHaveNoRoomForIt::
	.string "你的同行宝可梦已经满了......腾出\n"
	.string "空位后再来吧。$"

DayCare_Text_ReceivedEgg::
	.string "{PLAYER}从培育屋爷爷那里\n"
	.string "收到了蛋！$"

DayCare_Text_TakeGoodCareOfIt::
	.string "要好好照顾它哦。$"

DayCare_Text_SeeWifeIfYouWantToPickUpMon::
	.string "想要领回宝可梦的时候，就去跟我老\n"
	.string "伴说吧。$"

DayCare_Text_YourMonsAreDoingFine::
	.string "哎呀，是你啊！你的\n"
	.string "{STR_VAR_1}和\l"
	.string "{STR_VAR_2}都精神得很\l"
	.string "呢。$"

DayCare_Text_IWillKeepDoYouWantIt::
	.string "我真的会自己留着的哦。你其实还是\n"
	.string "想要的，对吧？$"

DayCare_Text_WouldYouLikeUsToRaiseMon::
	.string "我是培育屋的奶奶。\p"
	.string "我们能替你照顾宝可梦。\p"
	.string "你想寄放宝可梦吗？$"

DayCare_Text_WhichMonShouldWeRaise::
	.string "要把哪只宝可梦寄放在这里呢？$"

DayCare_Text_WellRaiseYourMon::
	.string "好的，我们会替你照顾\n"
	.string "{STR_VAR_1}一阵子的。\p"
	.string "过段时间再来领吧。$"

DayCare_Text_WeCanRaiseOneMore::
	.string "我们可以帮你照料两只宝可梦。\p"
	.string "你还要再寄放一只宝可梦吗？$"

DayCare_Text_HusbandWasLookingForYou::
	.string "我老伴刚才在找你呢。$"

DayCare_Text_FineThenComeAgain::
	.string "哎呀，这样啊。欢迎下次再来。$"

DayCare_Text_NotEnoughMoney::
	.string "你的钱不够呢......$"

DayCare_Text_TakeOtherOneBackToo::
	.string "另一只也要一起领回去吗？$"

DayCare_Text_ComeAgain::
	.string "好嘞。欢迎下次再来。$"

DayCare_Text_GoodToSeeYou::
	.string "啊，是你啊！见到你真高兴。\p"
	.string "你的宝可梦精神得很呢！$"

DayCare_Text_YourMonHasGrownXLevels::
	.string "按等级来看，你的\n"
	.string "{STR_VAR_1}提升了\l"
	.string "{STR_VAR_2}级。$"

DayCare_Text_YourPartyIsFull::
	.string "你的同行宝可梦已经满了。空出位置\n"
	.string "后再来找我吧。$"

DayCare_Text_TakeBackWhichMon::
	.string "你想领回哪只宝可梦？$"

DayCare_Text_ItWillCostX::
	.string "如果想领回你的\n"
	.string "{STR_VAR_1}，费用是¥\l"
	.string "{STR_VAR_2}。$"

DayCare_Text_HeresYourMon::
	.string "好的！这是你的宝可梦。$"

DayCare_Text_TookBackMon::
	.string "{PLAYER}从培育屋婆婆那里\n"
	.string "领回了{STR_VAR_1}。$"

DayCare_Text_YouHaveJustOneMon::
	.string "哎呀？可是你身上只有一只宝可梦\n"
	.string "呀。\p"
	.string "下次再来吧。$"

DayCare_Text_TakeYourMonBack::
	.string "要领回你的宝可梦吗？$"

DayCare_Text_WhatWillYouBattleWith::
	.string "要是把这只宝可梦留在我这儿，你拿\n"
	.string "什么去对战呢？\p"
	.string "下次再来吧。$"

DayCare_Text_Huh::
	.string "咦？$"
