EventTicket_Text_OldSeaMapTooFar:
	.string "你说什么，年轻人？\p"
	.string "什么，就是你拥有破烂的古老地图？\p"
	.string "让我看看。…… …… ……\p"
	.string "好家伙……这简直是遥不可及。我恐\n"
	.string "怕帮不了你……$"

EventTicket_Text_BrineyHoldOnASecond:
	.string "哈奇：喂！\p"
	.string "竟敢拒绝我恩人的请求这叫怎么一回\n"
	.string "事儿啊！$"

EventTicket_Text_BrineyLetsSail:
	.string "{PLAYER}{KUN}，真不\n"
	.string "好意思。\p"
	.string "你特意来这找我帮忙，可是我们差点\n"
	.string "把你拒之门外。\p"
	.string "让我来弥补这个错误吧。\p"
	.string "我们这就启航！\p"
	.string "让我们去找古航海图上的小岛吧！$"

EventTicket_Text_OddTicketGetOnBoard:
	.string "你带着船票了吗？\p"
	.string "你要去的小岛在很远很远的地方。\p"
	.string "没人知道那里会有什么等着我们……\p"
	.string "光是想想就让我这个老水手热血沸腾\n"
	.string "！\p"
	.string "上船吧，年轻人！$"

FarawayIsland_Entrance_Text_SailorReturn:
	.string "CAPT. BRINEY can be so maddeningly\n"
	.string "fickle…\p"
#if IS_HNS
	.string "Do you want to return to OLIVINE?$"
#else
	.string "Do you want to return to LILYCOVE?$"
#endif

BirthIsland_Harbor_Text_SailorReturn:
	.string "What an oddly shaped island, eh?\n"
#if IS_HNS
	.string "Do you want to return to OLIVINE?$"
#else
	.string "Do you want to return to LILYCOVE?$"
#endif

EventTicket_Text_OddTicketsWhereTo:
	.string "你带着船票了吗？\p"
	.string "…… ……唔。\p"
	.string "这些船票能带你去往很远很远的小岛\n"
	.string "。\p"
	.string "没人知道那里会有什么等着我们，抑\n"
	.string "或是可能会发生什么。\p"
	.string "光是想想就让我这个老水手热血沸腾\n"
	.string "！\p"
	.string "上船吧，年轻人！我们先去哪？$"

NavelRock_Harbor_Text_SailorReturn:
	.string "你听……听到了吗？从深处传出的低\n"
	.string "吼。\p"
	.string "你确定这里安全吗？我们要不要离开\n"
	.string "这儿？$"

FarawayIsland_Entrance_Text_Sign:
	.string "字迹已经模糊不清仿佛已经写了很久\n"
	.string "很久了……\p"
	.string "“……月6日在踏进这里的……类面\n"
	.string "前再次……身的话希望他心地……良\l"
	.string "在……里写下这样的愿望后我离开了\l"
	.string "这个…………士”$"

FarawayIsland_Interior_Text_Mew:
	.string "咪呦……$"
