EventTicket_Text_ShowOldSeaMap:
	.string "去凯那市的渡轮……\p"
	.string "嗯？什么？要去地图上的这个地方\n"
	.string "吗？\p"
	.string "我认得一个人，也许能帮上你。请稍\n"
	.string "等。$"

EventTicket_Text_ThatPass:
	.string "去凯那市的渡轮……\p"
	.string "哦？那张船票……$"

EventTicket_Text_ShowEonTicket:
	.string "嘿，伙计，拿着那张奇怪的船票的人\n"
	.string "就是你吗？\p"
	.string "我说，那可是南方非常远的一个小\n"
	.string "岛，\p"
	.string "而且谁也不知道到那儿之后会碰上什\n"
	.string "么东西，想想就激动啊！\p"
	.string "上船了！$"

#if IS_HNS
EventTicket_Text_SouthernIslandSailBack:
	.string "嘿，伙计，这座不起眼的小岛\n"
	.string "没什么可看可玩的了。\p"
	.string "咱们回浅葱市去，怎么样？$"
#else
EventTicket_Text_SouthernIslandSailBack:
	.string "嘿，伙计，这座不起眼的小岛\n"
	.string "没什么可看可玩的了。\p"
	.string "咱们回凯那市去，怎么样？$"
#endif 


EventTicket_Text_SailHome:
	.string "好的！出海，回家去了！$"

EventTicket_Text_AsYouLike:
	.string "好的，你随意吧。$"

SouthernIsland_Interior_Text_Sign:
	.string "“所有的梦境都只是另一个现实。永\n"
	.string "远不要忘记……”$"

SouthernIsland_Exterior_Text_Sign:
	.string "“那些似已逝去的记忆，人们会将其\n"
	.string "镌刻在心的最深处……”$"
