gFameCheckerFlavorText_ProfOak0:: @ 0x81AD106
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "这个人是做什么的？\p"
	.string "{COLOR DARK_GRAY}\n"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "大木宝可梦研究所$"

gFameCheckerFlavorText_ProfOak1:: @ 0x81AD145
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "这个人怎么样？\p"
	.string "{FONT_MALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "完成一本记载着世界上所有宝可梦的\l"
	.string "图鉴......\p"
	.string "那是我的梦想！$"

gFameCheckerFlavorText_ProfOak2:: @ 0x81AD1BB
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "这个人怎么样？\p"
	.string "{FONT_FEMALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "大木博士看起来平平无奇，但他可是\l"
	.string "宝可梦研究的权威。\p"
	.string "很多宝可梦训练家都对他非常崇敬。$"

gFameCheckerFlavorText_ProfOak3:: @ 0x81AD258
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "家人与朋友？\p"
	.string "{COLOR DARK_GRAY}\n"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "据说大木博士和他的孙子孙女奈奈美\l"
	.string "以及{RIVAL}住在一起。$"

gFameCheckerFlavorText_ProfOak4:: @ 0x81AD2B9
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "家人与朋友？\p"
	.string "{FONT_FEMALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "听说大木那家伙对你很感兴趣啊，孩\l"
	.string "子。\p"
	.string "那个老骨头当年可是又强壮又英俊呢\n"
	.string "。\p"
	.string "不过那是几十年前的事了。现在已经\n"
	.string "完全没有当年的风采喽。$"

gFameCheckerFlavorText_ProfOak5:: @ 0x81AD377
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PROF. OAK is going to have his own\n"
	.string "radio show soon.\p"
	.string "The program will be called PROF.\n"
	.string "OAK'S POKéMON SEMINAR.$"

gFameCheckerFlavorText_Daisy0:: @ 0x81AD40C
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "这个人是做什么的？\p"
	.string "{FONT_MALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "如果你把宝可梦给奈奈美看，她能看\l"
	.string "出它有多喜欢你。\p"
	.string "偶尔，她甚至还会帮你给宝可梦做美\n"
	.string "容呢。$"

gFameCheckerFlavorText_Daisy1:: @ 0x81AD4AE
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "这个人是什么样的人？\p"
	.string "{FONT_FEMALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "不过要说最受宝可梦喜爱的，我想还\l"
	.string "是奈奈美吧。$"

gFameCheckerFlavorText_Daisy2:: @ 0x81AD516
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "这个人是什么样的人？\p"
	.string "{FONT_MALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "她温柔地给宝可梦梳理毛发....\l"
	.string "..简直就像个小天使。\p"
	.string "那个小女孩的名字......好像\n"
	.string "是叫奈奈美吧。$"

gFameCheckerFlavorText_Daisy3:: @ 0x81AD5A7
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "家人与朋友？\p"
	.string "{COLOR DARK_GRAY}\n"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "据说大木博士和他的孙子孙女奈奈美\l"
	.string "以及{RIVAL}住在一起。$"

gFameCheckerFlavorText_Daisy4:: @ 0x81AD608
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "这个人是什么样的人？\p"
	.string "{FONT_FEMALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "真新镇的女孩奈奈美，每天都很喜欢\l"
	.string "喝茶。\p"
	.string "她常常去玉虹百货大楼买茶叶呢。$"

gFameCheckerFlavorText_Daisy5:: @ 0x81AD69F
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "有个传闻......\p"
	.string "{COLOR DARK_GRAY}\n"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "春季宝可梦华丽大赛的总冠军是真新\l"
	.string "镇的大木奈奈美！$"

gFameCheckerFlavorText_Brock0:: @ 0x81AD705
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "这个人是做什么的？\p"
	.string "{COLOR DARK_GRAY}\n"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "深灰市宝可梦道馆馆主：小刚坚如磐\l"
	.string "石的宝可梦训练家！$"

gFameCheckerFlavorText_Brock1:: @ 0x81AD771
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "喜欢的宝可梦类型？\p"
	.string "{FONT_MALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "我那坚如磐石的意志，在我的宝可梦\l"
	.string "身上也清晰可见。\p"
	.string "我的宝可梦全都坚如磐石，而且拥有\n"
	.string "坚韧不拔的毅力。\p"
	.string "没错--我的宝可梦全部都是岩石属\n"
	.string "性！$"

gFameCheckerFlavorText_Brock2:: @ 0x81AD840
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "这个人是什么样的人？\p"
	.string "{FONT_MALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "这里认真的宝可梦训练家可不多。\p"
	.string "他们大多像捕虫少年一样，你知道的\n"
	.string "，纯粹是当成爱好。\p"
	.string "但深灰道馆的小刚可绝不是那样，一\n"
	.string "点儿也不像。$"

gFameCheckerFlavorText_Brock3:: @ 0x81AD908
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "这个人是什么样的人？\p"
	.string "{FONT_MALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "小刚很酷，他可不只是实力强悍。大\l"
	.string "家都喜欢而且敬佩他。\p"
	.string "我也想成为一名像他那样的道馆馆主\n"
	.string "。$"

gFameCheckerFlavorText_Brock4:: @ 0x81AD99A
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "这个人是做什么的？\p"
	.string "{FONT_MALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "你好，我正在月见山地下发掘化石呢\l"
	.string "。\p"
	.string "有时候，深灰道馆的小刚也会来帮我\n"
	.string "的忙。$"

gFameCheckerFlavorText_Brock5:: @ 0x81ADA27
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "这个人是什么样的人？\p"
	.string "{COLOR DARK_GRAY}\n"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "小刚平时很少笑，但据说一旦笑起来\l"
	.string "就停不下来。$"

gFameCheckerFlavorText_Misty0:: @ 0x81ADA91
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "这个人是做什么的？\p"
	.string "{COLOR DARK_GRAY}\n"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "华蓝市宝可梦道馆馆主：小霞调皮俏\l"
	.string "人鱼！$"

gFameCheckerFlavorText_Misty1:: @ 0x81ADAF6
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "喜欢的宝可梦类型？\p"
	.string "{FONT_FEMALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "我的方针就是用水属性宝可梦展开全\l"
	.string "面猛攻！$"

gFameCheckerFlavorText_Misty2:: @ 0x81ADB5A
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "这个人是什么样的人？\p"
	.string "{FONT_MALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "小霞可是会不断进步的训练家。\p"
	.string "她才不会输给你这种人呢！$"

gFameCheckerFlavorText_Misty3:: @ 0x81ADBD9
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "有个传闻......\p"
	.string "{FONT_MALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "这一带经常能见到强劲的训练家和水\l"
	.string "属性宝可梦。\p"
	.string "据说华蓝道馆的小霞也在这里修行呢\n"
	.string "。$"

gFameCheckerFlavorText_Misty4:: @ 0x81ADC72
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "有个传闻......\p"
	.string "{FONT_FEMALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "这个海角可是著名的约会胜地。\p"
	.string "道馆馆主小霞似乎对这里充满了期待\n"
	.string "呢。$"

gFameCheckerFlavorText_Misty5:: @ 0x81ADCEB
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "有个传闻......\p"
	.string "{COLOR DARK_GRAY}\n"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "据说小霞非常崇拜四天王中的科拿。$"

gFameCheckerFlavorText_LtSurge0:: @ 0x81ADD3C
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "这个人是做什么的？\p"
	.string "{COLOR DARK_GRAY}\n"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "枯叶市宝可梦道馆馆主：马志士闪电\l"
	.string "般的美国人！$"

gFameCheckerFlavorText_LtSurge1:: @ 0x81ADDA7
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "喜欢的宝可梦类型？\p"
	.string "{FONT_MALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "我告诉你，小子，在战争时期可是电\l"
	.string "属性宝可梦救了我的命！$"

gFameCheckerFlavorText_LtSurge2:: @ 0x81ADE0B
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "这个人是什么样的人？\p"
	.string "{FONT_MALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "我在陆军服役的时候，马志士少校就\l"
	.string "是我严厉的长官。\p"
	.string "他对人要求可是出了名的严格。$"

gFameCheckerFlavorText_LtSurge3:: @ 0x81ADE82
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "这个人是什么样的人？\p"
	.string "{FONT_MALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "马志士在军队里一直因其谨慎的性格\l"
	.string "而闻名。$"

gFameCheckerFlavorText_LtSurge4:: @ 0x81ADEEC
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "这个人是什么样的人？\p"
	.string "{FONT_MALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "道馆里的机关都是马志士亲自装的。\p"
	.string "到处都设置了双重电子锁。$"

gFameCheckerFlavorText_LtSurge5:: @ 0x81ADF6A
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "有个传闻......\p"
	.string "{COLOR DARK_GRAY}\n"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "据传闻，马志士在美国老家时曾经是\l"
	.string "一名飞行员。\p"
	.string "他利用宝可梦产生的电力来驱动自己\n"
	.string "的飞机。$"

gFameCheckerFlavorText_Erika0:: @ 0x81AE009
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "这个人是做什么的？\p"
	.string "{COLOR DARK_GRAY}\n"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "玉虹市宝可梦道馆馆主：莉佳喜爱自\l"
	.string "然的大小姐！$"

gFameCheckerFlavorText_Erika1:: @ 0x81AE072
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "喜欢的宝可梦类型？\p"
	.string "{FONT_FEMALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "我是插花艺术的修习者。\p"
	.string "我的宝可梦全部都是草属性的。$"

gFameCheckerFlavorText_Erika2:: @ 0x81AE0F3
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "这个人性格怎么样？\p"
	.string "{FONT_FEMALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "我们的馆主莉佳虽然文静，但在这带\l"
	.string "可是很有名的。$"

gFameCheckerFlavorText_Erika3:: @ 0x81AE15B
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "这个人性格怎么样？\p"
	.string "{FONT_FEMALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "我们道馆只使用草属性宝可梦。\p"
	.string "至于原因嘛......因为我们还\n"
	.string "会用它们来插花呢！$"

gFameCheckerFlavorText_Erika4:: @ 0x81AE1E5
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "喜欢什么样的宝可梦？\p"
	.string "{FONT_FEMALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "如果不是好看的宝可梦，我才不会收\l"
	.string "服呢。$"

gFameCheckerFlavorText_Erika5:: @ 0x81AE247
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "有传闻说......\p"
	.string "{COLOR DARK_GRAY}\n"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "有传闻说，要是悄悄往玉虹道馆里面\l"
	.string "看，经常能看到莉佳在打瞌睡。$"

gFameCheckerFlavorText_Koga0:: @ 0x81AE2B6
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "这个人是做什么的？\p"
	.string "{COLOR DARK_GRAY}\n"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "浅红市宝可梦道馆馆主：阿桔剧毒忍\l"
	.string "者掌门人$"

gFameCheckerFlavorText_Koga1:: @ 0x81AE31D
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "喜欢什么样的宝可梦？\p"
	.string "{FONT_MALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "在毒属性宝可梦那悄然逼近的恐怖面\l"
	.string "前绝望吧！$"

gFameCheckerFlavorText_Koga2:: @ 0x81AE37D
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "这个人性格怎么样？\p"
	.string "{FONT_MALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "就算输了，我也要遵循我师父忍者阿\l"
	.string "桔的教导，继续修行。$"

gFameCheckerFlavorText_Koga3:: @ 0x81AE407
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "家人与朋友？\p"
	.string "{FONT_FEMALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "我的父亲是这个城镇的道馆馆主。\p"
	.string "我也在修行，希望能像父亲那样熟练\n"
	.string "指挥毒属性宝可梦。$"

gFameCheckerFlavorText_Koga4:: @ 0x81AE48D
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "有传闻说......\p"
	.string "{COLOR DARK_GRAY}\n"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "据说阿桔对医药极有研究。\p"
	.string "他甚至会亲自调配秘药来为他的宝可\n"
	.string "梦疗伤。$"

gFameCheckerFlavorText_Koga5:: @ 0x81AE51B
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "这个人是做什么的？\p"
	.string "{FONT_MALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "野生原野区很大对吧？\p"
	.string "浅红道馆的馆主阿桔经常会在这里巡\n"
	.string "逻。\p"
	.string "多亏了他，我们才能放心地在这儿游\n"
	.string "玩。$"

gFameCheckerFlavorText_Sabrina0:: @ 0x81AE5E8
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "这个人是做什么的？\p"
	.string "{COLOR DARK_GRAY}\n"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "金黄市宝可梦道馆馆主：娜姿操纵超\l"
	.string "能力宝可梦的高手！$"

gFameCheckerFlavorText_Sabrina1:: @ 0x81AE656
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "喜欢什么样的宝可梦？\p"
	.string "{FONT_MALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "你知道金黄市的那位年轻女馆主吗？\p"
	.string "她使用的是超能力属性宝可梦，对吧\n"
	.string "？$"

gFameCheckerFlavorText_Sabrina2:: @ 0x81AE6D7
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "这个人性格怎么样？\p"
	.string "{FONT_FEMALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "我从小就拥有超能力。\p"
	.string "最初是无意间扔出去的勺子居然自己\n"
	.string "弯曲了。$"

gFameCheckerFlavorText_Sabrina3:: @ 0x81AE762
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "这个人性格怎么样？\p"
	.string "{FONT_FEMALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "虽然我不喜欢对战，但如果你坚持，\l"
	.string "我就让你见识一下我的力量！$"

gFameCheckerFlavorText_Sabrina4:: @ 0x81AE7CB
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "有传闻说......\p"
	.string "{COLOR DARK_GRAY}\n"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "有人说娜姿在对战时，不用开口就能\l"
	.string "与宝可梦进行心灵感应。$"

gFameCheckerFlavorText_Sabrina5:: @ 0x81AE841
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "这个人性格怎么样？\p"
	.string "{FONT_MALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "娜姿刚才把隔壁格斗道场的空手道大\l"
	.string "王彻底打垮了。$"

gFameCheckerFlavorText_Blaine0:: @ 0x81AE89E
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "这个人是做什么的？\p"
	.string "{COLOR DARK_GRAY}\n"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "红莲岛宝可梦道馆馆主：夏伯热血猜\l"
	.string "谜大师！$"

gFameCheckerFlavorText_Blaine1:: @ 0x81AE90A
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "喜欢什么样的宝可梦？\p"
	.string "{FONT_MALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "我的火属性宝可梦个个威猛十足，散\l"
	.string "发着滚烫的热气！\p"
	.string "它们会把所有挑战者都烧成灰烬！$"

gFameCheckerFlavorText_Blaine2:: @ 0x81AE990
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "喜欢什么样的宝可梦？\p"
	.string "{FONT_MALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "我们的馆主夏伯曾经在山里彻底迷失\l"
	.string "了方向。\p"
	.string "夜幕降临时，一只全身燃烧着烈火的\n"
	.string "鸟宝可梦出现了。\p"
	.string "多亏了它的光芒，夏伯才得以平安走\n"
	.string "下山来。$"

gFameCheckerFlavorText_Blaine3:: @ 0x81AEA59
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "这个人性格怎么样？\p"
	.string "{FONT_FEMALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "红莲道馆的夏伯是个古怪的老头。\p"
	.string "早在研究所建起之前，他就一直住在\n"
	.string "这个岛上了。$"

gFameCheckerFlavorText_Blaine4:: @ 0x81AEAEE
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "家人与朋友？\p"
	.string "{COLOR DARK_GRAY}\n"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "这是一张夏伯和富士老人的合影。\p"
	.string "他们俩勾肩搭背，脸上挂着灿烂的笑\n"
	.string "容。$"

gFameCheckerFlavorText_Blaine5:: @ 0x81AEB69
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "有传闻说......\p"
	.string "{COLOR DARK_GRAY}\n"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "据说夏伯只有在构思新的问答题时，\l"
	.string "才会摘下他的墨镜。$"

gFameCheckerFlavorText_Lorelei0:: @ 0x81AEBDF
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "这个人是做什么的？\p"
	.string "{FONT_FEMALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "我是四天王之一的科拿。$"

gFameCheckerFlavorText_Lorelei1:: @ 0x81AEC28
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "喜欢什么样的宝可梦？\p"
	.string "{FONT_FEMALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "论冰属性宝可梦，没有人比我更强。$"

gFameCheckerFlavorText_Lorelei2:: @ 0x81AEC82
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "出生地在哪里？\p"
	.string "{FONT_MALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "在这座岛上长大了一位非常了不起的\l"
	.string "强大训练家。\p"
	.string "我敢说连你也认识她，那就是四天王\n"
	.string "之一的科拿！$"

gFameCheckerFlavorText_Lorelei3:: @ 0x81AED27
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "那个人是个怎样的人？\p"
	.string "{COLOR DARK_GRAY}\n"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "科拿以冷静、有条理且深思熟虑的对\l"
	.string "战风格著称，不过她还有一个惊人的\l"
	.string "秘密！$"

gFameCheckerFlavorText_Lorelei4:: @ 0x81AEDAA
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "那个人是个怎样的人？\p"
	.string "{FONT_FEMALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "你知道科拿有好多好多的毛绒玩偶吗\l"
	.string "？\p"
	.string "她每次回4之岛的时候，收藏的玩偶\n"
	.string "就会变得更多呢！$"

gFameCheckerFlavorText_Lorelei5:: @ 0x81AEE51
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "喜欢什么类型的宝可梦？\p"
	.string "{FONT_FEMALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "她身边的拉普拉斯，我想大概是她小\l"
	.string "时候遇到的那只吧。\p"
	.string "如果我没记错的话，应该是在冻瀑洞\n"
	.string "窟里收服的。\p"
	.string "也许从那时候起，那只宝可梦就一直\n"
	.string "陪伴着她了。$"

gFameCheckerFlavorText_Bruno0:: @ 0x81AEF25
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "那个人是做什么的？\p"
	.string "{FONT_MALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "我是四天王之一的希巴！$"

gFameCheckerFlavorText_Bruno1:: @ 0x81AEF6C
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "喜欢什么类型的宝可梦？\p"
	.string "{FONT_MALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "我一直与格斗宝可梦朝夕相处、共同\l"
	.string "修行！$"

gFameCheckerFlavorText_Bruno2:: @ 0x81AEFC6
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "那个人是个怎样的人？\p"
	.string "{COLOR DARK_GRAY}\n"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "希巴为了能和最强的训练家交手，凭\l"
	.string "着满腔的热忱加入了四天王。$"

gFameCheckerFlavorText_Bruno3:: @ 0x81AF04C
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "那个人是个怎样的人？\p"
	.string "{FONT_MALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "希巴是我的前辈，他偶尔会来温泉这\l"
	.string "里。\p"
	.string "他是来给自己和宝可梦疗伤的。$"

gFameCheckerFlavorText_Bruno4:: @ 0x81AF0F0
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "传闻......\p"
	.string "{FONT_FEMALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "他是四天王之一，叫希巴。\p"
	.string "听说愤怒之馒头卖光了之后，他满脸\n"
	.string "失落地离开了。$"

gFameCheckerFlavorText_Bruno5:: @ 0x81AF19A
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "家人与朋友？\p"
	.string "{FONT_MALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "即使是强如希巴......从前也\l"
	.string "曾和一个叫藤树的家伙一起修行过呢\l"
	.string "。$"

gFameCheckerFlavorText_Agatha0:: @ 0x81AF200
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "那个人是做什么的？\p"
	.string "{FONT_FEMALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "老身是四天王之一的菊子。$"

gFameCheckerFlavorText_Agatha1:: @ 0x81AF248
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "喜欢什么类型的宝可梦？\p"
	.string "{FONT_MALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "菊子的幽灵属性宝可梦，实力强得让\l"
	.string "人毛骨悚然。$"

gFameCheckerFlavorText_Agatha2:: @ 0x81AF2B7
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "那个人是个怎样的人？\p"
	.string "{FONT_MALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "那个老太太的脾气可火爆了。\p"
	.string "哪怕是一点点小事，都能让那个可怕\n"
	.string "的老太太大发雷霆。$"

gFameCheckerFlavorText_Agatha3:: @ 0x81AF34E
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "传闻......\p"
	.string "{COLOR DARK_GRAY}\n"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "菊子年轻时曾和大木博士作为竞争对\l"
	.string "手，在训练家之路上争夺过顶峰。$"

gFameCheckerFlavorText_Agatha4:: @ 0x81AF3BE
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "家人与朋友？\p"
	.string "{FONT_FEMALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "听说大木那家伙对你很感兴趣啊，孩\l"
	.string "子。\p"
	.string "那个老骨头当年可是又强壮又英俊呢\n"
	.string "。\p"
	.string "不过那是几十年前的事了。现在已经\n"
	.string "完全没有当年的风采喽。$"

gFameCheckerFlavorText_Agatha5:: @ 0x81AF47C
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "那个人是个怎样的人？\p"
	.string "{FONT_FEMALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "就拿菊子来说吧。\p"
	.string "她创下了历任四天王中最高龄的纪录\n"
	.string "呢。$"

gFameCheckerFlavorText_Lance0:: @ 0x81AF4FD
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "那个人是做什么的？\p"
	.string "{FONT_MALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "我是四天王之首。\p"
	.string "你可以叫我龙使者阿渡。$"

gFameCheckerFlavorText_Lance1:: @ 0x81AF567
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "喜欢什么类型的宝可梦？\p"
	.string "{FONT_MALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "你应该知道，龙宝可梦是神圣的传说\l"
	.string "宝可梦。\p"
	.string "它们难以捕捉，也难以培育，但实力\n"
	.string "却是出类拔萃的。\p"
	.string "它们几乎无懈可击，耍小聪明对它们\n"
	.string "可不管用。$"

gFameCheckerFlavorText_Lance2:: @ 0x81AF641
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "那个人是个怎样的人？\p"
	.string "{FONT_FEMALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "他坚守着正义！既帅气又充满热情！\l"
	.string "阿渡大人是最棒的！$"

gFameCheckerFlavorText_Lance3:: @ 0x81AF6BA
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "传闻......\p"
	.string "{FONT_FEMALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "有位常客名叫阿渡，偶尔会来这里。\p"
	.string "他每次都只买披风。\p"
	.string "我很好奇......他家里是不是\n"
	.string "有一堆一模一样的披风呢？$"

gFameCheckerFlavorText_Lance4:: @ 0x81AF758
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "家人与朋友？\p"
	.string "{COLOR DARK_GRAY}\n"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "阿渡的祖父据说是某个著名龙使一族\l"
	.string "的长老。$"

gFameCheckerFlavorText_Lance5:: @ 0x81AF7CB
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "家人与朋友？\p"
	.string "{FONT_MALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "据我所知，阿渡在很遥远的地方有一\l"
	.string "个当道馆馆主的表妹。$"

gFameCheckerFlavorText_Bill0:: @ 0x81AF83E
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "那个人是做什么的？\p"
	.string "{FONT_MALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "正辉可是举世闻名的宝可梦狂呢。\p"
	.string "电脑上的宝可梦储存系统也是他发明\n"
	.string "出来的。$"

gFameCheckerFlavorText_Bill1:: @ 0x81AF8CA
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "喜欢什么类型的宝可梦？\p"
	.string "{FONT_MALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "正辉有好多宝可梦！他连稀有的宝可\l"
	.string "梦也收集！$"

gFameCheckerFlavorText_Bill2:: @ 0x81AF929
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "那个人是个怎样的人？\p"
	.string "{FONT_MALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "他是我孙子！\p"
	.string "从小时候起，他就特别喜欢收集各种\n"
	.string "东西！$"

gFameCheckerFlavorText_Bill3:: @ 0x81AF998
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "喜欢什么类型的宝可梦？\p"
	.string "{FONT_MALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "正辉是个宝可梦狂，所以所有宝可梦\l"
	.string "他都喜欢。\p"
	.string "听说他收服的第一只宝可梦是一只凯\n"
	.string "西。$"

gFameCheckerFlavorText_Bill4:: @ 0x81AFA20
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "家人与朋友？\p"
	.string "{FONT_MALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "正辉的老家在满金市，他的家人现在\l"
	.string "还住在那里。\p"
	.string "听说那是一座相当热闹繁华的大都市\n"
	.string "呢。$"

gFameCheckerFlavorText_Bill5:: @ 0x81AFAB9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Apparently, BILL simply can't\n"
	.string "stomach milk at all.$"

gFameCheckerFlavorText_MrFuji0:: @ 0x81AFB0C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}He's really kind.\p"
	.string "He looks after abandoned and\n"
	.string "orphaned POKéMON.$"

gFameCheckerFlavorText_MrFuji1:: @ 0x81AFB76
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}This old guy marched right up to\n"
	.string "our HIDEOUT.\p"
	.string "Then, he starts ranting about how\n"
	.string "TEAM ROCKET's abusing POKéMON.\p"
	.string "So, we're just talking it over as\n"
	.string "adults.$"

gFameCheckerFlavorText_MrFuji2:: @ 0x81AFC38
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}POKéMON FAN MAGAZINE\n"
	.string "Monthly Grand Prize Drawing!\p"
	.string "The application form is…\p"
	.string "Gone! It's been clipped out.\n"
	.string "Someone must have applied already.$"

gFameCheckerFlavorText_MrFuji3:: @ 0x81AFCE9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I hear that MR. FUJI's not from\n"
	.string "these parts originally, either.$"

gFameCheckerFlavorText_MrFuji4:: @ 0x81AFD49
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "家人与朋友？\p"
	.string "{COLOR DARK_GRAY}\n"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "这是一张夏伯和富士老人的合影。\p"
	.string "他们俩勾肩搭背，脸上挂着灿烂的笑\n"
	.string "容。$"

gFameCheckerFlavorText_MrFuji5:: @ 0x81AFDC4
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Editor: The shy MR. FUJI turned\n"
	.string "down our interview requests.\p"
	.string "He is a kindly man who is adored\n"
	.string "and respected in LAVENDER TOWN.$"

gFameCheckerFlavorText_Giovanni0:: @ 0x81AFE68
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}TEAM ROCKET captures POKéMON from\n"
	.string "around the world.\p"
	.string "They're important tools for keeping\n"
	.string "our criminal enterprise going.\p"
	.string "I am the leader, GIOVANNI!$"

gFameCheckerFlavorText_Giovanni1:: @ 0x81AFF23
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Those thugs that took over our\n"
	.string "building…\p"
	.string "Their BOSS said he was looking for\n"
	.string "strong POKéMON.$"

gFameCheckerFlavorText_Giovanni2:: @ 0x81AFFA8
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}TEAM ROCKET's BOSS is terribly\n"
	.string "cruel!\p"
	.string "To him, POKéMON are just tools to\n"
	.string "be used.$"

gFameCheckerFlavorText_Giovanni3:: @ 0x81B0022
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Welcome to my hideout!\p"
	.string "It shall be so until I can restore\n"
	.string "TEAM ROCKET to its former glory.$"

gFameCheckerFlavorText_Giovanni4:: @ 0x81B00A6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Blow me away! GIOVANNI was the\n"
	.string "GYM LEADER of VIRIDIAN?$"

gFameCheckerFlavorText_Giovanni5:: @ 0x81B0106
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}You… You're not GIOVANNI's kid,\n"
	.string "are you?\p"
	.string "No, that can't be right.\n"
	.string "GIOVANNI's kid has red hair.$"


gFameCheckerPersonName_ProfOak:: @ 0x81B0188
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "大木博士$"

gFameCheckerPersonQuote_ProfOak:: @ 0x81B0198
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: PROF. OAK\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Why do POKéMON compete and battle\n"
	.string "so hard for you?\p"
	.string "They do so because they can see\n"
	.string "the love and trust you have\l"
	.string "towards POKéMON.\p"
	.string "Never forget that.$"

gFameCheckerPersonName_Daisy:: @ 0x81B0251
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "奈奈美$"

gFameCheckerPersonQuote_Daisy:: @ 0x81B025D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: DAISY\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}While I was comfortably enjoying\n"
	.string "my tea breaks, you've grown very\l"
	.string "skilled and powerful.\p"
	.string "I hope you'll remain a good rival\n"
	.string "to my little brother.$"

gFameCheckerPersonName_Brock:: @ 0x81B030F
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "小刚$"

gFameCheckerPersonQuote_Brock:: @ 0x81B031B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: BROCK\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}In this big world of ours, there\n"
	.string "must be many tough TRAINERS.\p"
	.string "Let's both keep training and\n"
	.string "making ourselves stronger!$"

gFameCheckerPersonName_Misty:: @ 0x81B03B3
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "小霞$"

gFameCheckerPersonQuote_Misty:: @ 0x81B03BF
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: MISTY\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I'm going to keep training here at\n"
	.string "this GYM.\p"
	.string "When I get better, I'd love to hit\n"
	.string "the road and travel.$"

gFameCheckerPersonName_LtSurge:: @ 0x81B0446
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "马志士$"

gFameCheckerPersonQuote_LtSurge:: @ 0x81B0456
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: LT. SURGE\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Hey, kid!\n"
	.string "You electrified me in our battle!\p"
	.string "I didn't know that there were\n"
	.string "gutsy TRAINERS like you.\p"
	.string "It made me change my mind about\n"
	.string "you!$"

gFameCheckerPersonName_Erika:: @ 0x81B0504
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "莉佳$"

gFameCheckerPersonQuote_Erika:: @ 0x81B0510
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: ERIKA\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I am so glad that there are strong\n"
	.string "TRAINERS like you.\p"
	.string "That awareness alone inspires and\n"
	.string "motivates me to try harder.\p"
	.string "Please visit me again.\n"
	.string "Zzz…$"

gFameCheckerPersonName_Koga:: @ 0x81B05C2
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "阿桔$"

gFameCheckerPersonQuote_Koga:: @ 0x81B05CD
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "寄件人：阿桔收件人：\l"
	.string "{PLAYER}\p"
	.string "{FONT_MALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "你我二人，都必须放眼更高之处，迎\l"
	.string "面接受新的挑战。\p"
	.string "那么，我该去修行并指导小女了。$"

gFameCheckerPersonName_Sabrina:: @ 0x81B0667
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "娜姿$"

gFameCheckerPersonQuote_Sabrina:: @ 0x81B0675
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "寄件人：娜姿收件人：\l"
	.string "{PLAYER}\p"
	.string "{FONT_FEMALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "你对宝可梦倾注的爱意......\p"
	.string "那是连我的超能力也无法战胜的力量\n"
	.string "。$"

gFameCheckerPersonName_Blaine:: @ 0x81B06FB
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "夏伯$"

gFameCheckerPersonQuote_Blaine:: @ 0x81B0708
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "寄件人：夏伯收件人：\l"
	.string "{PLAYER}\p"
	.string "{FONT_MALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "我的火属性宝可梦！它们还会变得更\l"
	.string "加强大！\p"
	.string "那么现在出个问答题：火属性的宝可\n"
	.string "梦到底有多少种呢？$"

gFameCheckerPersonName_Lorelei:: @ 0x81B079F
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "科拿$"

gFameCheckerPersonQuote_Lorelei:: @ 0x81B07AD
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "寄件人：科拿收件人：\l"
	.string "{PLAYER}\p"
	.string "{FONT_FEMALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "之前承蒙你的相助，在此向你道谢。\p"
	.string "不过，那和对战可完全是两码事。\p"
	.string "下次见面可要小心了哦！$"

gFameCheckerPersonName_Bruno:: @ 0x81B0845
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "希巴$"

gFameCheckerPersonQuote_Bruno:: @ 0x81B0851
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "寄件人：希巴收件人：\l"
	.string "{PLAYER}\p"
	.string "{FONT_MALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "你与宝可梦的超强力量，我已经亲身\l"
	.string "体会到了。\p"
	.string "下次，也许我该教教你如何锻炼自己\n"
	.string "的体魄了。$"

gFameCheckerPersonName_Agatha:: @ 0x81B08EE
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "菊子$"

gFameCheckerPersonQuote_Agatha:: @ 0x81B08FB
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "寄件人：菊子收件人：\l"
	.string "{PLAYER}\p"
	.string "{FONT_FEMALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "等你上了年纪，可千万别像大木那个\l"
	.string "老顽固一样变得心慈手软！\p"
	.string "要像我一样，把战斗一直进行到底！$"

gFameCheckerPersonName_Lance:: @ 0x81B097F
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "阿渡$"

gFameCheckerPersonQuote_Lance:: @ 0x81B098B
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "寄件人：阿渡收件人：\l"
	.string "{PLAYER}\p"
	.string "{FONT_MALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "我正在考虑回一趟故乡。\p"
	.string "我想重新磨炼我的龙属性宝可梦，让\n"
	.string "它们变得更加强大。\p"
	.string "总有一天，我想邀请你去我的故乡看\n"
	.string "看。$"

gFameCheckerPersonName_Bill:: @ 0x81B0A45
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "正辉$"

gFameCheckerPersonQuote_Bill:: @ 0x81B0A50
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "寄件人：正辉收件人：\l"
	.string "{PLAYER}\p"
	.string "{FONT_MALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "哟！锦辉那家伙把你夸上了天呢。\p"
	.string "听得我也跟着高兴起来了。\p"
	.string "要是抓到了稀有的宝可梦，可要拿来\n"
	.string "给我瞧瞧哦？说好了！$"

gFameCheckerPersonName_MrFuji:: @ 0x81B0AFF
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "富士老人$"

gFameCheckerPersonQuote_MrFuji:: @ 0x81B0B0E
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "寄件人：富士老人收件人：\l"
	.string "{PLAYER}\p"
	.string "{FONT_MALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "与其仅祈愿你自己的宝可梦获得幸福\l"
	.string "......\p"
	.string "......老夫能否拜托你，祈愿\n"
	.string "所有宝可梦都能得到幸福呢？$"

gFameCheckerPersonName_Giovanni:: @ 0x81B0BA6
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "坂木$"

gFameCheckerPersonQuote_Giovanni:: @ 0x81B0BB5
	.string "{COLOR BLUE}\n"
	.string "{SHADOW LIGHT_BLUE}\l"
	.string "寄件人：坂木收件人：\l"
	.string "{PLAYER}\p"
	.string "{FONT_MALE}\n"
	.string "{COLOR DARK_GRAY}\l"
	.string "{SHADOW LIGHT_GRAY}\l"
	.string "我跟你之间已无话可说。\p"
	.string "我唯有潜心磨砺自身，仅此而已。$"

gFameCheckerFlavorTextOriginLocation_ProfOak0:: @ 0x81B0C45
	.string "真新镇$"

gFameCheckerFlavorTextOriginLocation_ProfOak1::
	.string "研究所$"

gFameCheckerFlavorTextOriginLocation_ProfOak2::
	.string "研究所$"

gFameCheckerFlavorTextOriginLocation_ProfOak3::
	.string "常青市$"

gFameCheckerFlavorTextOriginLocation_ProfOak4::
	.string "宝可梦联盟$"

gFameCheckerFlavorTextOriginLocation_ProfOak5::
	.string "研究所$"

gFameCheckerFlavorTextOriginLocation_Daisy0::
	.string "研究所$"

gFameCheckerFlavorTextOriginLocation_Daisy1::
	.string "枯叶市$"

gFameCheckerFlavorTextOriginLocation_Daisy2::
	.string "水之迷宫$"

gFameCheckerFlavorTextOriginLocation_Daisy3::
	.string "常青市$"

gFameCheckerFlavorTextOriginLocation_Daisy4::
	.string "玉虹大厦$"

gFameCheckerFlavorTextOriginLocation_Daisy5::
	.string "4之岛$"

gFameCheckerFlavorTextOriginLocation_Brock0::
	.string "深灰市$"

gFameCheckerFlavorTextOriginLocation_Brock1::
	.string "深灰道馆$"

gFameCheckerFlavorTextOriginLocation_Brock2::
	.string "深灰市$"

gFameCheckerFlavorTextOriginLocation_Brock3::
	.string "4号道路$"

gFameCheckerFlavorTextOriginLocation_Brock4::
	.string "月见山$"

gFameCheckerFlavorTextOriginLocation_Brock5::
	.string "深灰科学博物馆$"

gFameCheckerFlavorTextOriginLocation_Misty0::
	.string "华蓝市$"

gFameCheckerFlavorTextOriginLocation_Misty1::
	.string "华蓝道馆$"

gFameCheckerFlavorTextOriginLocation_Misty2::
	.string "华蓝道馆$"

gFameCheckerFlavorTextOriginLocation_Misty3::
	.string "双子岛$"

gFameCheckerFlavorTextOriginLocation_Misty4::
	.string "华蓝海角$"

gFameCheckerFlavorTextOriginLocation_Misty5::
	.string "华蓝市$"

gFameCheckerFlavorTextOriginLocation_LtSurge0::
	.string "枯叶市$"

gFameCheckerFlavorTextOriginLocation_LtSurge1::
	.string "枯叶道馆$"

gFameCheckerFlavorTextOriginLocation_LtSurge2::
	.string "枯叶道馆$"

gFameCheckerFlavorTextOriginLocation_LtSurge3::
	.string "枯叶道馆$"

gFameCheckerFlavorTextOriginLocation_LtSurge4::
	.string "枯叶道馆$"

gFameCheckerFlavorTextOriginLocation_LtSurge5::
	.string "枯叶市$"

gFameCheckerFlavorTextOriginLocation_Erika0::
	.string "玉虹市$"

gFameCheckerFlavorTextOriginLocation_Erika1::
	.string "玉虹道馆$"

gFameCheckerFlavorTextOriginLocation_Erika2::
	.string "玉虹道馆$"

gFameCheckerFlavorTextOriginLocation_Erika3::
	.string "玉虹道馆$"

gFameCheckerFlavorTextOriginLocation_Erika4::
	.string "玉虹道馆$"

gFameCheckerFlavorTextOriginLocation_Erika5::
	.string "玉虹大厦$"

gFameCheckerFlavorTextOriginLocation_Koga0::
	.string "浅红市$"

gFameCheckerFlavorTextOriginLocation_Koga1::
	.string "浅红道馆$"

gFameCheckerFlavorTextOriginLocation_Koga2::
	.string "浅红道馆$"

gFameCheckerFlavorTextOriginLocation_Koga3::
	.string "浅红市$"

gFameCheckerFlavorTextOriginLocation_Koga4::
	.string "浅红市$"

gFameCheckerFlavorTextOriginLocation_Koga5::
	.string "狩猎地带$"

gFameCheckerFlavorTextOriginLocation_Sabrina0::
	.string "金黄市$"

gFameCheckerFlavorTextOriginLocation_Sabrina1::
	.string "3之岛$"

gFameCheckerFlavorTextOriginLocation_Sabrina2::
	.string "金黄道馆$"

gFameCheckerFlavorTextOriginLocation_Sabrina3::
	.string "金黄道馆$"

gFameCheckerFlavorTextOriginLocation_Sabrina4::
	.string "金黄市$"

gFameCheckerFlavorTextOriginLocation_Sabrina5::
	.string "金黄道馆$"

gFameCheckerFlavorTextOriginLocation_Blaine0::
	.string "红莲岛$"

gFameCheckerFlavorTextOriginLocation_Blaine1::
	.string "红莲道馆$"

gFameCheckerFlavorTextOriginLocation_Blaine2::
	.string "红莲道馆$"

gFameCheckerFlavorTextOriginLocation_Blaine3::
	.string "红莲岛$"

gFameCheckerFlavorTextOriginLocation_Blaine4::
	.string "红莲道馆$"

gFameCheckerFlavorTextOriginLocation_Blaine5::
	.string "豪华度假村$"

gFameCheckerFlavorTextOriginLocation_Lorelei0::
	.string "宝可梦联盟$"

gFameCheckerFlavorTextOriginLocation_Lorelei1::
	.string "宝可梦联盟$"

gFameCheckerFlavorTextOriginLocation_Lorelei2::
	.string "4之岛$"

gFameCheckerFlavorTextOriginLocation_Lorelei3::
	.string "5之岛$"

gFameCheckerFlavorTextOriginLocation_Lorelei4::
	.string "4之岛$"

gFameCheckerFlavorTextOriginLocation_Lorelei5::
	.string "4之岛$"

gFameCheckerFlavorTextOriginLocation_Bruno0::
	.string "宝可梦联盟$"

gFameCheckerFlavorTextOriginLocation_Bruno1::
	.string "宝可梦联盟$"

gFameCheckerFlavorTextOriginLocation_Bruno2::
	.string "金黄市$"

gFameCheckerFlavorTextOriginLocation_Bruno3::
	.string "灯火温泉$"

gFameCheckerFlavorTextOriginLocation_Bruno4::
	.string "2之岛$"

gFameCheckerFlavorTextOriginLocation_Bruno5::
	.string "七宝峡谷$"

gFameCheckerFlavorTextOriginLocation_Agatha0::
	.string "宝可梦联盟$"

gFameCheckerFlavorTextOriginLocation_Agatha1::
	.string "石英高原$"

gFameCheckerFlavorTextOriginLocation_Agatha2::
	.string "石英高原$"

gFameCheckerFlavorTextOriginLocation_Agatha3::
	.string "第7岛$"

gFameCheckerFlavorTextOriginLocation_Agatha4::
	.string "宝可梦联盟$"

gFameCheckerFlavorTextOriginLocation_Agatha5::
	.string "第6岛$"

gFameCheckerFlavorTextOriginLocation_Lance0::
	.string "宝可梦联盟$"

gFameCheckerFlavorTextOriginLocation_Lance1::
	.string "宝可梦联盟$"

gFameCheckerFlavorTextOriginLocation_Lance2::
	.string "金黄市$"

gFameCheckerFlavorTextOriginLocation_Lance3::
	.string "玉虹百货公司$"

gFameCheckerFlavorTextOriginLocation_Lance4::
	.string "石英高原$"

gFameCheckerFlavorTextOriginLocation_Lance5::
	.string "石英高原$"

gFameCheckerFlavorTextOriginLocation_Bill0::
	.string "华蓝市$"

gFameCheckerFlavorTextOriginLocation_Bill1::
	.string "华蓝市$"

gFameCheckerFlavorTextOriginLocation_Bill2::
	.string "浅红市$"

gFameCheckerFlavorTextOriginLocation_Bill3::
	.string "第1岛$"

gFameCheckerFlavorTextOriginLocation_Bill4::
	.string "第1岛$"

gFameCheckerFlavorTextOriginLocation_Bill5::
	.string "第1岛$"

gFameCheckerFlavorTextOriginLocation_MrFuji0::
	.string "紫苑镇$"

gFameCheckerFlavorTextOriginLocation_MrFuji1::
	.string "宝可梦塔$"

gFameCheckerFlavorTextOriginLocation_MrFuji2::
	.string "紫苑镇$"

gFameCheckerFlavorTextOriginLocation_MrFuji3::
	.string "紫苑镇$"

gFameCheckerFlavorTextOriginLocation_MrFuji4::
	.string "红莲道馆$"

gFameCheckerFlavorTextOriginLocation_MrFuji5::
	.string "红莲岛$"

gFameCheckerFlavorTextOriginLocation_Giovanni0::
	.string "火箭队基地$"

gFameCheckerFlavorTextOriginLocation_Giovanni1::
	.string "西尔佛公司$"

gFameCheckerFlavorTextOriginLocation_Giovanni2::
	.string "西尔佛公司$"

gFameCheckerFlavorTextOriginLocation_Giovanni3::
	.string "常青道馆$"

gFameCheckerFlavorTextOriginLocation_Giovanni4::
	.string "常青道馆$"

gFameCheckerFlavorTextOriginLocation_Giovanni5::
	.string "火箭队仓库$"

gFameCheckerFlavorTextOriginObjectName_ProfOak0::
	.string "告示牌$"

gFameCheckerFlavorTextOriginObjectName_ProfOak1::
	.string "大木博士$"

gFameCheckerFlavorTextOriginObjectName_ProfOak2::
	.string "助手$"

gFameCheckerFlavorTextOriginObjectName_ProfOak3::
	.string "宝可梦周刊$"

gFameCheckerFlavorTextOriginObjectName_ProfOak4::
	.string "菊子$"

gFameCheckerFlavorTextOriginObjectName_ProfOak5::
	.string "助手$"

gFameCheckerFlavorTextOriginObjectName_Daisy0::
	.string "助手$"

gFameCheckerFlavorTextOriginObjectName_Daisy1::
	.string "女性$"

gFameCheckerFlavorTextOriginObjectName_Daisy2::
	.string "男性$"

gFameCheckerFlavorTextOriginObjectName_Daisy3::
	.string "宝可梦周刊$"

gFameCheckerFlavorTextOriginObjectName_Daisy4::
	.string "老奶奶$"

gFameCheckerFlavorTextOriginObjectName_Daisy5::
	.string "宝可梦周刊$"

gFameCheckerFlavorTextOriginObjectName_Brock0::
	.string "告示牌$"

gFameCheckerFlavorTextOriginObjectName_Brock1::
	.string "小刚$"

gFameCheckerFlavorTextOriginObjectName_Brock2::
	.string "青年$"

gFameCheckerFlavorTextOriginObjectName_Brock3::
	.string "男孩$"

gFameCheckerFlavorTextOriginObjectName_Brock4::
	.string "男性$"

gFameCheckerFlavorTextOriginObjectName_Brock5::
	.string "宝可梦周刊$"

gFameCheckerFlavorTextOriginObjectName_Misty0::
	.string "告示牌$"

gFameCheckerFlavorTextOriginObjectName_Misty1::
	.string "小霞$"

gFameCheckerFlavorTextOriginObjectName_Misty2::
	.string "路易斯$"

gFameCheckerFlavorTextOriginObjectName_Misty3::
	.string "青年$"

gFameCheckerFlavorTextOriginObjectName_Misty4::
	.string "贵妇人$"

gFameCheckerFlavorTextOriginObjectName_Misty5::
	.string "宝可梦周刊$"

gFameCheckerFlavorTextOriginObjectName_LtSurge0::
	.string "告示牌$"

gFameCheckerFlavorTextOriginObjectName_LtSurge1::
	.string "马志士$"

gFameCheckerFlavorTextOriginObjectName_LtSurge2::
	.string "达克$"

gFameCheckerFlavorTextOriginObjectName_LtSurge3::
	.string "达克$"

gFameCheckerFlavorTextOriginObjectName_LtSurge4::
	.string "德韦恩$"

gFameCheckerFlavorTextOriginObjectName_LtSurge5::
	.string "宝可梦周刊$"

gFameCheckerFlavorTextOriginObjectName_Erika0::
	.string "告示牌$"

gFameCheckerFlavorTextOriginObjectName_Erika1::
	.string "莉佳$"

gFameCheckerFlavorTextOriginObjectName_Erika2::
	.string "罗拉$"

gFameCheckerFlavorTextOriginObjectName_Erika3::
	.string "塔米娅$"

gFameCheckerFlavorTextOriginObjectName_Erika4::
	.string "莉佳$"

gFameCheckerFlavorTextOriginObjectName_Erika5::
	.string "宝可梦周刊$"

gFameCheckerFlavorTextOriginObjectName_Koga0::
	.string "告示牌$"

gFameCheckerFlavorTextOriginObjectName_Koga1::
	.string "阿桔$"

gFameCheckerFlavorTextOriginObjectName_Koga2::
	.string "柯克$"

gFameCheckerFlavorTextOriginObjectName_Koga3::
	.string "查琳$"

gFameCheckerFlavorTextOriginObjectName_Koga4::
	.string "宝可梦周刊$"

gFameCheckerFlavorTextOriginObjectName_Koga5::
	.string "男性$"

gFameCheckerFlavorTextOriginObjectName_Sabrina0::
	.string "告示牌$"

gFameCheckerFlavorTextOriginObjectName_Sabrina1::
	.string "青年$"

gFameCheckerFlavorTextOriginObjectName_Sabrina2::
	.string "娜姿$"

gFameCheckerFlavorTextOriginObjectName_Sabrina3::
	.string "娜姿$"

gFameCheckerFlavorTextOriginObjectName_Sabrina4::
	.string "宝可梦周刊$"

gFameCheckerFlavorTextOriginObjectName_Sabrina5::
	.string "泰隆$"

gFameCheckerFlavorTextOriginObjectName_Blaine0::
	.string "告示牌$"

gFameCheckerFlavorTextOriginObjectName_Blaine1::
	.string "夏伯$"

gFameCheckerFlavorTextOriginObjectName_Blaine2::
	.string "德里克$"

gFameCheckerFlavorTextOriginObjectName_Blaine3::
	.string "女性$"

gFameCheckerFlavorTextOriginObjectName_Blaine4::
	.string "照片$"

gFameCheckerFlavorTextOriginObjectName_Blaine5::
	.string "宝可梦周刊$"

gFameCheckerFlavorTextOriginObjectName_Lorelei0::
	.string "科拿$"

gFameCheckerFlavorTextOriginObjectName_Lorelei1::
	.string "科拿$"

gFameCheckerFlavorTextOriginObjectName_Lorelei2::
	.string "老爷爷$"

gFameCheckerFlavorTextOriginObjectName_Lorelei3::
	.string "宝可梦周刊$"

gFameCheckerFlavorTextOriginObjectName_Lorelei4::
	.string "小女孩$"

gFameCheckerFlavorTextOriginObjectName_Lorelei5::
	.string "老奶奶$"

gFameCheckerFlavorTextOriginObjectName_Bruno0::
	.string "希巴$"

gFameCheckerFlavorTextOriginObjectName_Bruno1::
	.string "希巴$"

gFameCheckerFlavorTextOriginObjectName_Bruno2::
	.string "宝可梦周刊$"

gFameCheckerFlavorTextOriginObjectName_Bruno3::
	.string "破坏者$"

gFameCheckerFlavorTextOriginObjectName_Bruno4::
	.string "女性$"

gFameCheckerFlavorTextOriginObjectName_Bruno5::
	.string "破坏者$"

gFameCheckerFlavorTextOriginObjectName_Agatha0::
	.string "菊子$"

gFameCheckerFlavorTextOriginObjectName_Agatha1::
	.string "破坏者$"

gFameCheckerFlavorTextOriginObjectName_Agatha2::
	.string "破坏者$"

gFameCheckerFlavorTextOriginObjectName_Agatha3::
	.string "宝可梦周刊$"

gFameCheckerFlavorTextOriginObjectName_Agatha4::
	.string "菊子$"

gFameCheckerFlavorTextOriginObjectName_Agatha5::
	.string "老奶奶$"

gFameCheckerFlavorTextOriginObjectName_Lance0::
	.string "阿渡$"

gFameCheckerFlavorTextOriginObjectName_Lance1::
	.string "阿渡$"

gFameCheckerFlavorTextOriginObjectName_Lance2::
	.string "女性$"

gFameCheckerFlavorTextOriginObjectName_Lance3::
	.string "小女孩$"

gFameCheckerFlavorTextOriginObjectName_Lance4::
	.string "宝可梦周刊$"

gFameCheckerFlavorTextOriginObjectName_Lance5::
	.string "青年$"

gFameCheckerFlavorTextOriginObjectName_Bill0::
	.string "{RIVAL}$"

gFameCheckerFlavorTextOriginObjectName_Bill1::
	.string "小男孩$"

gFameCheckerFlavorTextOriginObjectName_Bill2::
	.string "老爷爷$"

gFameCheckerFlavorTextOriginObjectName_Bill3::
	.string "锦辉$"

gFameCheckerFlavorTextOriginObjectName_Bill4::
	.string "锦辉$"

gFameCheckerFlavorTextOriginObjectName_Bill5::
	.string "锦辉$"

gFameCheckerFlavorTextOriginObjectName_MrFuji0::
	.string "小女孩$"

gFameCheckerFlavorTextOriginObjectName_MrFuji1::
	.string "火箭队$"

gFameCheckerFlavorTextOriginObjectName_MrFuji2::
	.string "杂志$"

gFameCheckerFlavorTextOriginObjectName_MrFuji3::
	.string "男性$"

gFameCheckerFlavorTextOriginObjectName_MrFuji4::
	.string "照片$"

gFameCheckerFlavorTextOriginObjectName_MrFuji5::
	.string "宝可梦周刊$"

gFameCheckerFlavorTextOriginObjectName_Giovanni0::
	.string "坂木$"

gFameCheckerFlavorTextOriginObjectName_Giovanni1::
	.string "研究员$"

gFameCheckerFlavorTextOriginObjectName_Giovanni2::
	.string "研究员$"

gFameCheckerFlavorTextOriginObjectName_Giovanni3::
	.string "坂木$"

gFameCheckerFlavorTextOriginObjectName_Giovanni4::
	.string "男性$"

gFameCheckerFlavorTextOriginObjectName_Giovanni5::
	.string "技男$"

PokemonJournal_Text_SpecialFeatureBrock::
	.string "《宝可梦周刊》\p"
	.string "深灰道馆馆主小刚特辑！\p"
	.string "平时不苟言笑的小刚，据说一笑起来\n"
	.string "就停不下来。$"

PokemonJournal_Text_SpecialFeatureMisty::
	.string "《宝可梦周刊》\p"
	.string "华蓝道馆馆主小霞特辑！\p"
	.string "据说小霞十分崇拜四天王中的科拿。$"

PokemonJournal_Text_SpecialFeatureLtSurge::
	.string "《宝可梦周刊》\p"
	.string "枯叶道馆馆主马志士特辑！\p"
	.string "传闻马志士还在美国老家时曾是一名\n"
	.string "飞行员。\p"
	.string "他曾利用宝可梦产生的电力来驱动他\n"
	.string "的飞机。$"

PokemonJournal_Text_SpecialFeatureErika::
	.string "《宝可梦周刊》\p"
	.string "玉虹道馆馆主莉佳特辑！\p"
	.string "传闻只要朝玉虹道馆里偷瞄，就经常\n"
	.string "能看到莉佳在打瞌睡。$"

PokemonJournal_Text_SpecialFeatureKoga::
	.string "《宝可梦周刊》\p"
	.string "浅红道馆馆主阿桔特辑！\p"
	.string "据说阿桔对医药有着极为深厚的造诣\n"
	.string "。\p"
	.string "他甚至会亲自配药来为自己的宝可梦\n"
	.string "调理身体。$"

PokemonJournal_Text_SpecialFeatureSabrina::
	.string "《宝可梦周刊》\p"
	.string "金黄道馆馆主娜姿特辑！\p"
	.string "大家都说娜姿在对战时即使不开口，\n"
	.string "也能与宝可梦心意相通。$"

PokemonJournal_Text_SpecialFeatureBlaine::
	.string "《宝可梦周刊》\p"
	.string "红莲道馆馆主夏伯特辑！\p"
	.string "据说夏伯只有在构思新的谜题时，才\n"
	.string "会摘下他的深色墨镜。$"

PokemonJournal_Text_SpecialFeatureLorelei::
	.string "《宝可梦周刊》\p"
	.string "四天王科拿特辑！\p"
	.string "以沉着冷静、精于算计的对战风格闻\n"
	.string "名的科拿，其实有着令人意外的秘密\l"
	.string "！$"

PokemonJournal_Text_SpecialFeatureBruno::
	.string "《宝可梦周刊》\p"
	.string "四天王希巴特辑！\p"
	.string "希巴之所以加入四天王，据说是为了\n"
	.string "能与最顶尖的训练家交手而燃起了熊\l"
	.string "熊斗志。$"

PokemonJournal_Text_SpecialFeatureAgatha::
	.string "《宝可梦周刊》\p"
	.string "四天王菊子特辑！\p"
	.string "菊子在年轻时曾与大木博士为了争夺\n"
	.string "最强训练家之名而针锋相对。$"

PokemonJournal_Text_SpecialFeatureLance::
	.string "《宝可梦周刊》\p"
	.string "四天王阿渡特辑！\p"
	.string "据说阿渡的祖父是名扬四海的驯龙一\n"
	.string "族长老。$"

PokemonJournal_Text_SpecialFeatureProfOak::
	.string "《宝可梦周刊》\p"
	.string "宝可梦研究巨擘--大木博士特辑！\p"
	.string "据报道，大木博士如今与孙女奈奈美\n"
	.string "以及孙子{RIVAL}生活在一起\l"
	.string "。$"

PokemonJournal_Text_SpecialFeatureDaisyOak::
	.string "这是一份很多年前的《宝可梦周刊》\n"
	.string "......\p"
	.string "《宝可梦周刊》华丽大赛特辑！\p"
	.string "春季宝可梦华丽大赛的总冠军是来自\n"
	.string "真新镇的大木奈奈美！$"

PokemonJournal_Text_SpecialFeatureMrFuji::
	.string "《宝可梦周刊》\p"
	.string "宝可梦之家的富士老人特辑！\p"
	.string "主编注：生性害羞的富士老人回绝了\n"
	.string "我们的采访请求。\p"
	.string "他是一位慈祥的老人，在紫苑镇深受\n"
	.string "居民们的爱戴与尊敬。$"
