Trade_Text_LookingForMonWannaTradeForMon::
	.string "我正在寻找宝可梦\n"
	.string "{STR_VAR_1}！\p"
	.string "能用我的{STR_VAR_2}来\n"
	.string "和你交换一只吗？$"

Trade_Text_AwwOhWell::
	.string "啊......好吧......$"

Trade_Text_WhatThatsNoMon::
	.string "哎？这可不是\n"
	.string "{STR_VAR_1}啊！$"

Trade_Text_HeyThanks::
	.string "嘿，太感谢啦！$"

Trade_Text_IsntMyOldMonGreat::
	.string "我之前的那只\n"
	.string "{STR_VAR_2}很棒吧？$"

Trade_Text_DoYouHaveMonWouldYouTradeForMon::
	.string "你好呀！你身上刚好有\n"
	.string "{STR_VAR_1}吗？\p"
	.string "愿意用它来交换我的\n"
	.string "{STR_VAR_2}吗？$"

Trade_Text_WellIfYouDontWantTo::
	.string "好吧，不想换就算啦......$"

Trade_Text_ThisIsntMon::
	.string "嗯？这可不是\n"
	.string "{STR_VAR_1}呀。\p"
	.string "要是抓到的话，可千万要想着我哦。$"

Trade_Text_Thanks::
	.string "谢谢！$"

Trade_Text_HasTradedMonGrownStronger::
	.string "我换给你的{STR_VAR_2}\n"
	.string "，有变得更强了吗？$"

Trade_Text_DoYouHaveMonWantToTradeForMon::
	.string "你好！你有{STR_VAR_1}\n"
	.string "吗？\p"
	.string "想不想用它来交换我的\n"
	.string "{STR_VAR_2}？$"

Trade_Text_ThatsTooBad::
	.string "真遗憾。$"

Trade_Text_ThisIsNoMon::
	.string "......这不是\n"
	.string "{STR_VAR_1}啊。\p"
	.string "如果你收服到了，一定要和我交换哦\n"
	.string "。$"

Trade_Text_ThanksYoureAPal::
	.string "谢谢你，你真是个好伙伴！$"

Trade_Text_HowIsMyOldMon::
	.string "之前换给你的\n"
	.string "{STR_VAR_2}怎么样了？\l"
	.string "我的{STR_VAR_1}精神得\l"
	.string "很呢！$"
