LilycoveCity_DepartmentStore_1F_Text_LotteryCornerDrawTicket:
	.string "这里是宝可梦奖券角。\p"
	.string "莅临本百货商场的顾客都可以抽取一\n"
	.string "张宝可梦彩票。\p"
	.string "如果彩票号码与你的宝可梦中任何一\n"
	.string "只的ID完全吻合，就能获得豪华大奖\l"
	.string "哦。\p"
	.string "你想抽取一张宝可梦彩票吗？$"

LilycoveCity_DepartmentStore_1F_Text_ComeBackTomorrow:
	.string "请明天再来。$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain:
	.string "欢迎下次再来。$"

LilycoveCity_DepartmentStore_1F_Text_PleasePickTicket:
	.string "请选一张彩票吧。......\n"
	.string "{PAUSE 0x0F}\l"
	.string "{PAUSE 0x0F}\l"
	.string "{PAUSE 0x0F}\l"
	.string "{PAUSE 0x0F}......\l"
	.string "{PAUSE 0x0F}\l"
	.string "{PAUSE 0x0F}\l"
	.string "{PAUSE 0x0F}\l"
	.string "{PAUSE 0x0F}......\l"
	.string "{PAUSE 0x0F}\l"
	.string "{PAUSE 0x0F}\l"
	.string "{PAUSE 0x0F}\l"
	.string "{PAUSE 0x0F}$"

LilycoveCity_DepartmentStore_1F_Text_TicketNumberIsXPleaseWait:
	.string "彩票的号码是\n"
	.string "{STR_VAR_1}，\p"
	.string "我需要对照一下您的宝可梦的ID，请\n"
	.string "稍候。$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPartyMon:
	.string "恭喜！\p"
	.string "您携带的{STR_VAR_1}的\n"
	.string "ID与彩票号码相同！$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPCMon:
	.string "恭喜！\p"
	.string "您盒子里的{STR_VAR_1}\n"
	.string "的ID与彩票号码相同！$"

LilycoveCity_DepartmentStore_1F_Text_NoNumbersMatched:
	.string "很遗憾，没有找到相符的号码。$"

LilycoveCity_DepartmentStore_1F_Text_TwoDigitsMatched:
	.string "有2个数字相同，恭喜您获得三等\n"
	.string "奖！奖品是\l"
	.string "{STR_VAR_1}！$"

LilycoveCity_DepartmentStore_1F_Text_ThreeDigitsMatched:
	.string "有3个数字相同，恭喜您获得二等\n"
	.string "奖！奖品是\l"
	.string "{STR_VAR_1}！$"

LilycoveCity_DepartmentStore_1F_Text_FourDigitsMatched:
	.string "有4个数字相同，恭喜您获得一等\n"
	.string "奖！奖品是\l"
	.string "{STR_VAR_1}！$"

LilycoveCity_DepartmentStore_1F_Text_AllFiveDigitsMatched:
	.string "啊，天哪，5个数字完全相同！\p"
	.string "恭喜您获得特等奖！奖品是\n"
	.string "{STR_VAR_1}！$"

LilycoveCity_DepartmentStore_1F_Text_NoRoomForThis:
	.string "哎？好像您没有放奖品的地方了，\p"
	.string "等您的背包里腾出空间之后，请再来\n"
	.string "找我。$"

LilycoveCity_DepartmentStore_1F_Text_PrizeWeveBeenHolding:
	.string "{PLAYER}对吧？好的，我正\n"
	.string "等您呢。\p"
	.string "这是为您保管的奖品。$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain2:
	.string "欢迎下次再来。$"
