LilycoveCity_DepartmentStore_1F_Text_LotteryCornerDrawTicket:
	.string "This is the POKéMON LOTTERY CORNER.\p"
	.string "All shoppers at our DEPARTMENT STORE\n"
	.string "get to draw a POKéMON LOTO TICKET.\p"
	.string "If the LOTO TICKET's number matches\n"
	.string "the ID number of any of your POKéMON,\l"
	.string "you will receive a fabulous gift.\p"
	.string "Would you like to draw a POKéMON\n"
	.string "LOTO TICKET?$"

LilycoveCity_DepartmentStore_1F_Text_ComeBackTomorrow:
	.string "请明天再来。$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain:
	.string "欢迎下次再来。$"

LilycoveCity_DepartmentStore_1F_Text_PleasePickTicket:
	.string "Please pick a LOTO TICKET.\n"
	.string "…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

LilycoveCity_DepartmentStore_1F_Text_TicketNumberIsXPleaseWait:
	.string "彩票的号码是\n"
	.string "{STR_VAR_1}，\p"
	.string "我需要对照一下您的宝可梦的ID，\n"
	.string "请稍候。$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPartyMon:
	.string "恭喜！\p"
	.string "您携带的{STR_VAR_1}的\n"
	.string "ID与彩票号码相同！$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPCMon:
	.string "恭喜！\p"
	.string "您盒子里的{STR_VAR_1}\n"
	.string "的ID与彩票号码相同！$"

LilycoveCity_DepartmentStore_1F_Text_NoNumbersMatched:
	.string "很遗憾，没有找到相符的号码。$"

LilycoveCity_DepartmentStore_1F_Text_TwoDigitsMatched:
	.string "有2个数字相同，恭喜您获得三等奖\n"
	.string "！奖品是{STR_VAR_1}！$"

LilycoveCity_DepartmentStore_1F_Text_ThreeDigitsMatched:
	.string "有3个数字相同，恭喜您获得二等奖\n"
	.string "！奖品是{STR_VAR_1}！$"

LilycoveCity_DepartmentStore_1F_Text_FourDigitsMatched:
	.string "有4个数字相同，恭喜您获得一等奖\n"
	.string "！奖品是{STR_VAR_1}！$"

LilycoveCity_DepartmentStore_1F_Text_AllFiveDigitsMatched:
	.string "啊，天哪，5个数字完全相同！\p"
	.string "恭喜您获得特等奖！奖品是\n"
	.string "{STR_VAR_1}！$"

LilycoveCity_DepartmentStore_1F_Text_NoRoomForThis:
	.string "哎？好像您没有放奖品的地方了，\p"
	.string "等您的包包里腾出空间之后，请再来\n"
	.string "找我。$"

LilycoveCity_DepartmentStore_1F_Text_PrizeWeveBeenHolding:
	.string "{PLAYER}?\n"
	.string "Yes, I've been expecting you.\p"
	.string "This is the prize we've been holding\n"
	.string "for you.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain2:
	.string "欢迎下次再来。$"
