MatchCall_WildBattleText1::
	.string "嗨！{PLAYER}{KUN}，\n"
	.string "你好！我是{STR_VAR_1}\l"
	.string "。\p"
	.string "刚才我遇到了\n"
	.string "{STR_VAR_2}！但是没能\l"
	.string "捉到它。\p"
	.string "就差一点点！好了，下次见！$"

MatchCall_WildBattleText2::
	.string "你好，{PLAYER}{KUN}\n"
	.string "。我是{STR_VAR_1}。\p"
	.string "不久前我试着捕捉一只很棒的\n"
	.string "{STR_VAR_2}。\p"
	.string "但它还是跑掉了。真的好失望啊！\p"
	.string "好了，再见！$"

MatchCall_WildBattleText3::
	.string "你好啊，{PLAYER}！是我呀\n"
	.string "，{STR_VAR_1}。\p"
	.string "我刚才试着捕捉这只\n"
	.string "{STR_VAR_2}，但是给它\l"
	.string "逃掉了。\p"
	.string "差一点就成功了！\p"
	.string "今天算是倒霉……好了，下次见！$"

MatchCall_WildBattleText4::
	.string "嗨，{PLAYER}{KUN}。\n"
	.string "是我，{STR_VAR_1}。\p"
	.string "你知道宝可梦\n"
	.string "{STR_VAR_2}吗？我差点\l"
	.string "就捕捉到一只。\p"
	.string "就在刚才，我以为已经捕捉到了，但\n"
	.string "它还是跑了。\p"
	.string "如果再让我看见它，一定要捕捉到！\p"
	.string "好，回头见。$"

MatchCall_WildBattleText5::
	.string "你好，{PLAYER}{KUN}\n"
	.string "！我是{STR_VAR_1}。最\l"
	.string "近捕捉到什么宝可梦了吗？\p"
	.string "刚才我差一点捕捉到一只，但是它逃\n"
	.string "掉了。\p"
	.string "好，多保重！$"

MatchCall_WildBattleText6::
	.string "嘿，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。最近\l"
	.string "有捕捉到什么宝可梦吗？\p"
	.string "前几天我差点捕捉到了一只。但是不\n"
	.string "知怎么它跑掉了。\p"
	.string "多保重。$"

MatchCall_WildBattleText7::
	.string "……嗯，{PLAYER}\n"
	.string "{KUN}？是我，\l"
	.string "{STR_VAR_1}。\p"
	.string "哦，等等！等等！我能捕捉到这只\n"
	.string "{STR_VAR_2}……\p"
	.string "啊啊！给他逃了！只差一点点啊！$"

MatchCall_WildBattleText8::
	.string "哦，{PLAYER}{KUN}，\n"
	.string "最近如何？我是\l"
	.string "{STR_VAR_1}。\p"
	.string "你捕捉宝可梦还顺利吗？\p"
	.string "不久前我差点抓到一只。但目标还是\n"
	.string "逃掉了。\p"
	.string "我还得再加把劲啊！下次见！$"

MatchCall_WildBattleText9::
	.string "哦，{PLAYER}{KUN}，\n"
	.string "你好！我是{STR_VAR_1}\l"
	.string "！\p"
	.string "怎么样？有捕捉到更多宝可梦吗？\p"
	.string "我最近好倒霉，它们全都逃走了！\p"
	.string "再见！$"

MatchCall_WildBattleText10::
	.string "哦，{PLAYER}{KUN}，\n"
	.string "你好……我是\l"
	.string "{STR_VAR_1}。\p"
	.string "听着，我几乎马上就能捉到这只\n"
	.string "{STR_VAR_2}了……\p"
	.string "但是，它还是溜掉了……\p"
	.string "我得再加把劲。回头见。$"

MatchCall_WildBattleText11::
	.string "啊，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。最近\l"
	.string "怎么样？\p"
	.string "我刚才想捕捉只野生的\n"
	.string "{STR_VAR_2}，但是它成\l"
	.string "功逃走了。\p"
	.string "感觉好失败……$"

MatchCall_WildBattleText12::
	.string "你好，{PLAYER}{KUN}\n"
	.string "。是我，{STR_VAR_1}。\l"
	.string "你还在捕捉宝可梦吗？\p"
	.string "我自己也在试着捕捉。但是真的好不\n"
	.string "容易呀。\p"
	.string "宝可梦的世界真是深奥啊！$"

MatchCall_WildBattleText13::
	.string "啊，你好，{PLAYER}\n"
	.string "{KUN}！我是\l"
	.string "{STR_VAR_1}！你捕捉到\l"
	.string "宝可梦了吗？\p"
	.string "我自己也努力试着捕捉，但没什么成\n"
	.string "果。\p"
	.string "宝可梦的世界真是深奥啊！$"

MatchCall_WildBattleText14::
	.string "哦嗨，{PLAYER}{KUN}\n"
	.string "，你好吗？我是\l"
	.string "{STR_VAR_1}。\p"
	.string "刚才我试着捕捉一只可爱的\n"
	.string "{STR_VAR_2}。\p"
	.string "但它还是逃走了！哦，我真是失望极\n"
	.string "了！\p"
	.string "再见！$"

MatchCall_WildBattleText15::
	.string "嘿，{PLAYER}！我是\n"
	.string "{STR_VAR_1}！\p"
	.string "我正在考虑捕捉一两只宝可梦。\p"
	.string "但一只都找不到。这真是个难题啊！\p"
	.string "我完全想不到办法！以后再见！$"

MatchCall_NegativeBattleText1::
	.string "嗨！{PLAYER}{KUN}，\n"
	.string "好啊！我是{STR_VAR_1}\l"
	.string "。\p"
	.string "我试着挑战了另一个训练家，但是我\n"
	.string "输了。\p"
	.string "好失望。好了，以后再聊！$"

MatchCall_NegativeBattleText2::
	.string "你好，{PLAYER}{KUN}\n"
	.string "。我是{STR_VAR_1}。\p"
	.string "在我们对战后，我又挑战了别人。\p"
	.string "我差点就赢了，但是最后还是输了。\n"
	.string "唉，算了！$"

MatchCall_NegativeBattleText3::
	.string "嘿你好，{PLAYER}！是我，\n"
	.string "{STR_VAR_1}。\p"
	.string "我刚刚在对战中惨败。\p"
	.string "看来我得再训练一下我的队伍！$"

MatchCall_NegativeBattleText4::
	.string "嘿，{PLAYER}。是我，\n"
	.string "{STR_VAR_1}。\p"
	.string "我昨天又对战了一场，可还是没能赢\n"
	.string "。\p"
	.string "我的队伍还需要再练练。OK，以后\n"
	.string "再聊。$"

MatchCall_NegativeBattleText5::
	.string "嘿嘿，{PLAYER}！我是\n"
	.string "{STR_VAR_1}。\p"
	.string "最近怎么样？\p"
	.string "我一直在对战，但很少能赢。\p"
	.string "完全找不到感觉。好了，保重！$"

MatchCall_NegativeBattleText6::
	.string "嘿，{PLAYER}。我是\n"
	.string "{STR_VAR_1}呢。\p"
	.string "最近还好吗？\p"
	.string "我最近拼命对战，但没什么成果。\p"
	.string "完全找不到节奏。你多保重！$"

MatchCall_NegativeBattleText7::
	.string "{STR_VAR_1}。最近还顺\n"
	.string "利吗？\p"
	.string "我昨天又输了，一直在想这件事。\p"
	.string "我得想个对策……再见。$"

MatchCall_NegativeBattleText8::
	.string "喂，{PLAYER}{KUN}，\n"
	.string "你好吗？我是\l"
	.string "{STR_VAR_1}呀。\p"
	.string "你的宝可梦怎么样？前几天我又输了\n"
	.string "一场对战。\p"
	.string "我要更努力些！再见！$"

MatchCall_NegativeBattleText9::
	.string "喂，{PLAYER}{KUN}，\n"
	.string "你好啊！我是\l"
	.string "{STR_VAR_1}！\p"
	.string "听着，听着，你一定要听听这个！\p"
	.string "我刚才来了场宝可梦对战，我在最后\n"
	.string "一秒的时候被打败了。\p"
	.string "哦哦，气死我了！$"

MatchCall_NegativeBattleText10::
	.string "喂，{PLAYER}{KUN}，\n"
	.string "你好……我是\l"
	.string "{STR_VAR_1}。\p"
	.string "不久前，我打了一场对战。结果我输\n"
	.string "了。\p"
	.string "我得在继续训练我的宝可梦。再见。$"

MatchCall_NegativeBattleText11::
	.string "啊，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。你的\l"
	.string "宝可梦怎么样？\p"
	.string "我又输掉了一场对战。\p"
	.string "哦，再见！$"

MatchCall_NegativeBattleText12::
	.string "你好，{PLAYER}{KUN}\n"
	.string "。是我，{STR_VAR_1}。\l"
	.string "你还在努力对战吗？\p"
	.string "我的话，最近刚输了一场，所以我重\n"
	.string "新训练我的队伍。\p"
	.string "下次见吧！$"

MatchCall_NegativeBattleText13::
	.string "喂，你好啊，{PLAYER}\n"
	.string "{KUN}！我是\l"
	.string "{STR_VAR_1}！\p"
	.string "我希望你一切顺利。\p"
	.string "我刚刚结束了一场对战。\p"
	.string "{PLAYER}{KUN}，要像\n"
	.string "我这样活跃哦！再见！$"

MatchCall_NegativeBattleText14::
	.string "喂，你好，{PLAYER}\n"
	.string "{KUN}。我是\l"
	.string "{STR_VAR_1}。\p"
	.string "最近还好吗？\p"
	.string "不过要记得常回家看看哦。\p"
	.string "再见！$"

MatchCall_PositiveBattleText1::
	.string "嗨！{PLAYER}{KUN}，\n"
	.string "你好！我是{STR_VAR_1}\l"
	.string "！\p"
	.string "我和其他训练家来了场对战。我赢啦\n"
	.string "！赢啦！\p"
	.string "我的{STR_VAR_2}真的干\n"
	.string "得很漂亮！太棒了！$"

MatchCall_PositiveBattleText2::
	.string "你好，{PLAYER}{KUN}\n"
	.string "！我是{STR_VAR_1}！\p"
	.string "我昨天对战了一场，而且赢了！太棒\n"
	.string "了！$"

MatchCall_PositiveBattleText3::
	.string "你好，{PLAYER}！我是\n"
	.string "{STR_VAR_1}！你战况如\l"
	.string "何？\p"
	.string "我前些天对战了一场，我的\n"
	.string "{STR_VAR_2}表现超级棒\l"
	.string "！\p"
	.string "下次再遇到你，{PLAYER}，\n"
	.string "输的就不是我了！$"

MatchCall_PositiveBattleText4::
	.string "嘿，{PLAYER}。是我\n"
	.string "{STR_VAR_1}。\p"
	.string "刚刚我有一场对战。我尽全力取胜了\n"
	.string "，但其实很险。\p"
	.string "我的{STR_VAR_2}可真是\n"
	.string "上演了一出好戏。$"

MatchCall_PositiveBattleText5::
	.string "嘿呀，{PLAYER}{KUN}\n"
	.string "！我是{STR_VAR_1}。\p"
	.string "最近怎么样？战绩如何？\p"
	.string "我刚刚赢了一场！我的\n"
	.string "{STR_VAR_2}太出色了！\p"
	.string "等着瞧，我一定会打败你的！好啦，\n"
	.string "保重！$"

MatchCall_PositiveBattleText6::
	.string "嘿，{PLAYER}{KUN}。\n"
	.string "是我{STR_VAR_1}。\p"
	.string "一切顺利吗？\p"
	.string "我最近势头正猛！我刚刚可就赢了一\n"
	.string "场对战。\p"
	.string "等我们下次交手时，我肯定不会输了\n"
	.string "！$"

MatchCall_PositiveBattleText7::
	.string "{PLAYER}{KUN}？是我\n"
	.string "{STR_VAR_1}。\p"
	.string "我的{STR_VAR_2}超级厉\n"
	.string "害的！我刚刚又赢了一场！\p"
	.string "我真想现在就和你再比试一场。$"

MatchCall_PositiveBattleText8::
	.string "哦，{PLAYER}{KUN}，\n"
	.string "你好吗？我是\l"
	.string "{STR_VAR_1}呀。\p"
	.string "我希望你一切都好。我想告诉你我刚\n"
	.string "刚赢了。\p"
	.string "我的{STR_VAR_2}为了赢\n"
	.string "得对战，表现得非常努力！\p"
	.string "下次见！$"

MatchCall_PositiveBattleText9::
	.string "哦，{PLAYER}{KUN}，\n"
	.string "好啊！我是{STR_VAR_1}\l"
	.string "！\p"
	.string "你的宝可梦最近怎样？我刚刚赢了一\n"
	.string "场！\p"
	.string "不得不说我的\n"
	.string "{STR_VAR_2}真的是太出\l"
	.string "色了！\p"
	.string "我希望你也能看看！以后见！$"

MatchCall_PositiveBattleText10::
	.string "哦，{PLAYER}{KUN}，\n"
	.string "好啊……我是\l"
	.string "{STR_VAR_1}。\p"
	.string "最近过得好吗？\p"
	.string "我的宝可梦现在充满了力量。\p"
	.string "我刚刚与它们一同获得了胜利。以后\n"
	.string "见。$"

MatchCall_PositiveBattleText11::
	.string "啊，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。\p"
	.string "最近有在对战吗？我今天又战胜了一\n"
	.string "个！\p"
	.string "势不可挡！哈哈哈哈！好了，回见！$"

MatchCall_PositiveBattleText12::
	.string "你好，{PLAYER}{KUN}\n"
	.string "。是我，{STR_VAR_1}。\p"
	.string "你过得还好吧？我依然充满了活力！\p"
	.string "刚刚又赢了一场。我可不会轻易输给\n"
	.string "你们年轻人！！$"

MatchCall_PositiveBattleText13::
	.string "啊，好啊，{PLAYER}\n"
	.string "{KUN}！我是\l"
	.string "{STR_VAR_1}！\p"
	.string "希望你一切安好。我依然精力充沛！\p"
	.string "刚才又赢了一场。我可不会轻易输给\n"
	.string "年轻人呢！\p"
	.string "再见！$"

MatchCall_PositiveBattleText14::
	.string "哦，嗨，{PLAYER}\n"
	.string "{KUN}。我是\l"
	.string "{STR_VAR_1}。\p"
	.string "我最近在对战时，我的\n"
	.string "{STR_VAR_2}表现超群！\p"
	.string "真希望你能看到呢，\n"
	.string "{PLAYER}{KUN}。再见\l"
	.string "！$"

MatchCall_SameRouteBattleRequestText1::
	.string "嗨！{PLAYER}，你好！这里\n"
	.string "是{STR_VAR_1}。\p"
	.string "嗯？等一下，你在\n"
	.string "{STR_VAR_2}附近？\p"
	.string "哇哦，那我们得来场对战！我等着你\n"
	.string "！待会见！$"

MatchCall_SameRouteBattleRequestText2::
	.string "你好，{PLAYER}！我是\n"
	.string "{STR_VAR_1}。\p"
	.string "啊？你说正在\n"
	.string "{STR_VAR_2}这里？\p"
	.string "我们来对战一场好吗？我等你啊！待\n"
	.string "会见！$"

MatchCall_SameRouteBattleRequestText3::
	.string "嗨你好，{PLAYER}！是我，\n"
	.string "{STR_VAR_1}。\p"
	.string "哦，嘿，你就在\n"
	.string "{STR_VAR_2}这里？\p"
	.string "我们现在来对战一场怎么样？\p"
	.string "我不会再输了！我等你！快来吧！$"

MatchCall_SameRouteBattleRequestText4::
	.string "嘿，{PLAYER}{KUN}。\n"
	.string "是我{STR_VAR_1}。\p"
	.string "你在哪里？啥？\n"
	.string "{STR_VAR_2}？\p"
	.string "现在要和我对战吗？我等你。待会见\n"
	.string "！$"

MatchCall_SameRouteBattleRequestText5::
	.string "嘿呀，{PLAYER}{KUN}\n"
	.string "！我是{STR_VAR_1}。最\l"
	.string "近如何？\p"
	.string "你在哪里？{STR_VAR_2}\n"
	.string "？\p"
	.string "那我们现在立刻再战一场如何？\p"
	.string "我会留意你的。马上见！$"

MatchCall_SameRouteBattleRequestText6::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\l"
	.string "How are your POKéMON keeping?\p"
	.string "Oh, is that right? You're around\n"
	.string "{STR_VAR_2}?\p"
	.string "Well, then, we'd better have\n"
	.string "a rematch.\p"
	.string "I can wait, sure.\n"
	.string "See you!$"

MatchCall_SameRouteBattleRequestText7::
	.string "……呃，{PLAYER}\n"
	.string "{KUN}？是我\l"
	.string "{STR_VAR_1}……\p"
	.string "哦，你正好在\n"
	.string "{STR_VAR_2}附近？\p"
	.string "那么，来对战吧。我是说，现在。\p"
	.string "我会给你看看我的宝可梦。我等着你\n"
	.string "。$"

MatchCall_SameRouteBattleRequestText8::
	.string "哦，{PLAYER}{KUN}，\n"
	.string "你还好吗？我是\l"
	.string "{STR_VAR_1}呀。\p"
	.string "希望你一切都好。哦，你就在\n"
	.string "{STR_VAR_2}这里啊。\p"
	.string "那么，你想来跟我来一场对战吗？\p"
	.string "我等着你。等下见！$"

MatchCall_SameRouteBattleRequestText9::
	.string "嗯，{PLAYER}{KUN}，\n"
	.string "你好啊！我是\l"
	.string "{STR_VAR_1}！\p"
	.string "一切都好吗？哦，你就在\n"
	.string "{STR_VAR_2}附近？\p"
	.string "哦，那你不觉得应该与我来一场对战\n"
	.string "吗？\p"
	.string "别让我久等！$"

MatchCall_SameRouteBattleRequestText10::
	.string "哦，{PLAYER}{KUN}，\n"
	.string "你好……这里是\l"
	.string "{STR_VAR_1}。\p"
	.string "过得顺利吗？哦，你就在\n"
	.string "{STR_VAR_2}这里。\p"
	.string "那么我们应该来场对战。\p"
	.string "我已经准备好了。快点过来！$"

MatchCall_SameRouteBattleRequestText11::
	.string "啊，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。\p"
	.string "啊，你现在正在\n"
	.string "{STR_VAR_2}？\p"
	.string "既然如此，我们之间一定得来一场对\n"
	.string "战，不是吗？\p"
	.string "我在这里等你！马上见！$"

MatchCall_SameRouteBattleRequestText12::
	.string "喂，{PLAYER}{KUN}。\n"
	.string "是我，{STR_VAR_1}。你\l"
	.string "现在在哪儿呢？\p"
	.string "{STR_VAR_2}？离我很近\n"
	.string "啊！\p"
	.string "你说我们现在来一场对战如何？\p"
	.string "我会等你的。等会见！$"

MatchCall_SameRouteBattleRequestText13::
	.string "啊，你好，{PLAYER}\n"
	.string "{KUN}！我是\l"
	.string "{STR_VAR_1}！\p"
	.string "希望你一切顺利。哦，你在\n"
	.string "{STR_VAR_2}附近？\p"
	.string "既然离得不远，来和我对战一场吧。\p"
	.string "我等你，先这样吧。$"

MatchCall_SameRouteBattleRequestText14::
	.string "哦，嗨，{PLAYER}\n"
	.string "{KUN}。我是\l"
	.string "{STR_VAR_1}。\p"
	.string "你在哪儿？……\n"
	.string "{STR_VAR_2}？那很近啊\l"
	.string "。\p"
	.string "你不觉得我们应该来一场对战吗？\p"
	.string "我会等你的！拜拜！$"

MatchCall_DifferentRouteBattleRequestText1::
	.string "嗨！{PLAYER}，你好！我是\n"
	.string "{STR_VAR_1}。\p"
	.string "想和我对战一场吗？\p"
	.string "我就在{STR_VAR_2}等你\n"
	.string "！$"

MatchCall_DifferentRouteBattleRequestText2::
	.string "你好啊，{PLAYER}！我是\n"
	.string "{STR_VAR_1}。\p"
	.string "你想不想再和我比试一场？\p"
	.string "你能在{STR_VAR_2}这边\n"
	.string "找到我。我等着你！$"

MatchCall_DifferentRouteBattleRequestText3::
	.string "你好啊，{PLAYER}！是我，\n"
	.string "{STR_VAR_1}。\p"
	.string "我的宝可梦比起之前成长了许多。\p"
	.string "我想看看它们和你的宝可梦比起来谁\n"
	.string "更强，{PLAYER}。\p"
	.string "我们对战吧！\p"
	.string "我就在{STR_VAR_2}这里\n"
	.string "等你。$"

MatchCall_DifferentRouteBattleRequestText4::
	.string "嘿，{PLAYER}{KUN}。\n"
	.string "是我{STR_VAR_1}。你还\l"
	.string "好吗？\p"
	.string "我的宝可梦最近变得很厉害了。\p"
	.string "嘿，你想再和我来一场对战吗？\p"
	.string "我们在{STR_VAR_2}见面\n"
	.string "，好吗？$"

MatchCall_DifferentRouteBattleRequestText5::
	.string "嘿，{PLAYER}{KUN}！\n"
	.string "我是{STR_VAR_1}。\p"
	.string "我的宝可梦这些天成长了不少。\p"
	.string "真的好想和你再对战一次。\p"
	.string "我会在{STR_VAR_2}这里\n"
	.string "等你！回头见！$"

MatchCall_DifferentRouteBattleRequestText6::
	.string "嘿，{PLAYER}{KUN}。\n"
	.string "是我{STR_VAR_1}。希望\l"
	.string "你一切顺利。\p"
	.string "我想能和你再来一场对战。你觉得呢\n"
	.string "？\p"
	.string "如果你想就来\n"
	.string "{STR_VAR_2}这里吧。\p"
	.string "再见！$"

MatchCall_DifferentRouteBattleRequestText7::
	.string "……呃，{PLAYER}\n"
	.string "{KUN}？是我\l"
	.string "{STR_VAR_1}……所以，\l"
	.string "你的宝可梦成长了吗？\p"
	.string "我的肯定变强了。想给你看一看。\p"
	.string "我会在{STR_VAR_2}附近\n"
	.string "。来找我对战吧。\p"
	.string "以后见。$"

MatchCall_DifferentRouteBattleRequestText8::
	.string "哦，{PLAYER}{KUN}，\n"
	.string "你好吗？我是\l"
	.string "{STR_VAR_1}。\p"
	.string "希望你一切都好。我的宝可梦十分活\n"
	.string "跃。\p"
	.string "如果你在附近的话，和我再对战一次\n"
	.string "吧。\p"
	.string "我就在{STR_VAR_2}。不\n"
	.string "见不散，再见！$"

MatchCall_DifferentRouteBattleRequestText9::
	.string "哦，{PLAYER}{KUN}，\n"
	.string "你好啊！我是\l"
	.string "{STR_VAR_1}！你的宝可\l"
	.string "梦还好吗？\p"
	.string "我的宝可梦越来越强了。想让你见识\n"
	.string "一下，{PLAYER}{KUN}\l"
	.string "。\p"
	.string "我现在就在{STR_VAR_2}\n"
	.string "这里，如果你在附近的话，那么我们\l"
	.string "就来场对战吧。\p"
	.string "希望很快能见到你！$"

MatchCall_DifferentRouteBattleRequestText10::
	.string "哦，{PLAYER}{KUN}，\n"
	.string "你好……我是\l"
	.string "{STR_VAR_1}。啊，最近\l"
	.string "还好吗？\p"
	.string "我的宝可梦可是比以前要强得多了。\p"
	.string "我很想和你再对战一次，\n"
	.string "{PLAYER}{KUN}。\p"
	.string "现在我在{STR_VAR_2}。\n"
	.string "如果方便的话就来吧。$"

MatchCall_DifferentRouteBattleRequestText11::
	.string "啊，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。你现\l"
	.string "在会在哪里呢？\p"
	.string "我的宝可梦现在充满活力。它们好像\n"
	.string "很想再见一见你的宝可梦，\l"
	.string "{PLAYER}{KUN}。\p"
	.string "我现在就在{STR_VAR_2}\n"
	.string "这里。希望你能来找我们。$"

MatchCall_DifferentRouteBattleRequestText12::
	.string "喂，{PLAYER}{KUN}。\n"
	.string "是我，{STR_VAR_1}。\p"
	.string "我想告诉你，我的宝可梦已经成长了\n"
	.string "很多很多。\p"
	.string "想看看它们和你对战的表现，\n"
	.string "{PLAYER}{KUN}。\p"
	.string "我们会在{STR_VAR_2}附\n"
	.string "近。随时欢迎来找我们！$"

MatchCall_DifferentRouteBattleRequestText13::
	.string "啊，你好，{PLAYER}\n"
	.string "{KUN}！我是\l"
	.string "{STR_VAR_1}！你的宝可\l"
	.string "梦都好吗？\p"
	.string "我的宝可梦非常健康，看起来不会输\n"
	.string "给你！\p"
	.string "我很想再和你对战一场。\p"
	.string "如果你在{STR_VAR_2}附\n"
	.string "近，一定要来找我们。$"

MatchCall_DifferentRouteBattleRequestText14::
	.string "哦，好，{PLAYER}\n"
	.string "{KUN}。我是\l"
	.string "{STR_VAR_1}。一切都好\l"
	.string "吧。\p"
	.string "哦，对了！我的宝可梦已经比以前强\n"
	.string "大了不少。\p"
	.string "你不觉得我们应该再战一场吗，\n"
	.string "{PLAYER}{KUN}？\p"
	.string "我会在{STR_VAR_2}等着\n"
	.string "你的。\p"
	.string "随时来找我们，好吗？$"

MatchCall_PersonalizedText1::
	.string "是我啊，热爱大山的\n"
	.string "{STR_VAR_1}！\p"
	.string "那个，上次见过以后，你是不是也开\n"
	.string "始喜欢群山了呢？\p"
	.string "我很少在山里看见你呀……\p"
	.string "下一次，让我们在\n"
	.string "{STR_VAR_2}碰头吧。$"

MatchCall_PersonalizedText2::
	.string "我是{STR_VAR_1}。你好\n"
	.string "。\p"
	.string "我刚刚告诉了一个新人训练家有关你\n"
	.string "的事。\p"
	.string "我告诉她有一个强大的训练家用爱心\n"
	.string "培育他的宝可梦。\p"
	.string "我希望你能成为一个人人称赞的训练\n"
	.string "家。\p"
	.string "希望能再见到你！$"

MatchCall_PersonalizedText3::
	.string "你好！我是{STR_VAR_1}\n"
	.string "。\p"
	.string "我爱上我所在的地方了。多么怡人的\n"
	.string "芳香！\p"
	.string "我想有人种下了些树果，它们正在开\n"
	.string "花。\p"
	.string "再见！$"

MatchCall_PersonalizedText4::
	.string "你好！具有30年经验的探险家，\n"
	.string "{STR_VAR_1}为你服务！\p"
	.string "看上去你正在充满干劲的走东闯西呢\n"
	.string "。\p"
	.string "你发现了什么新的遗迹吗？如果有的\n"
	.string "话要告诉我！\p"
	.string "现在恕我失陪，我还要去探索遗迹。$"

MatchCall_PersonalizedText5::
	.string "我是{STR_VAR_1}！\p"
	.string "知道我正在做什么吗？我正在海边看\n"
	.string "海浪！\p"
	.string "啊……海浪闪闪发光。这里真是看海\n"
	.string "的好地方啊。我有点饿了，再见了！$"

MatchCall_PersonalizedText6::
	.string "嗯嗯……哦，嗨，我是\n"
	.string "{STR_VAR_1}。我喜欢在\l"
	.string "海滩上吃东西。\p"
	.string "我的宝可梦和我都好得很。我们充满\n"
	.string "活力！我要去游个泳了。再见！$"

MatchCall_PersonalizedText7::
	.string "你好，我是{STR_VAR_1}\n"
	.string "……\p"
	.string "最近对“精英训练家”这个头衔有点\n"
	.string "厌倦了……\p"
	.string "每个人都认为我是完美的训练家，因\n"
	.string "此我不得不按照别人期望而活。\p"
	.string "不过这可能就是精英训练家的宿命吧\n"
	.string "。\p"
	.string "我得继续咬牙坚持……微笑着承受一\n"
	.string "切。\p"
	.string "这些话我只对你一个人说。\p"
	.string "但下次见面时别担心，我不会抱怨的\n"
	.string "！$"

MatchCall_PersonalizedText8::
	.string "哟吼，我是{STR_VAR_1}\n"
	.string "！你好吗？\p"
	.string "我现在正在训练我的宝可梦，你是我\n"
	.string "的目标哦。\p"
	.string "下次遇见你的时候我不会再输了。\p"
	.string "有个训练家朋友可真好啊！再见啦！$"

MatchCall_PersonalizedText9::
	.string "我是{STR_VAR_1}……现\n"
	.string "在，在你的身后……不觉得那里有东\l"
	.string "西吗……？\p"
	.string "那是沉睡在送神山的宝可梦之大能…\n"
	.string "…\p"
	.string "它正向我诉说你的一切……\p"
	.string "赶快离开这里，而且千万不要回头…\n"
	.string "…\p"
	.string "嘻嘻……再见……$"

MatchCall_PersonalizedText10::
	.string "我是{STR_VAR_1}。最近\n"
	.string "好吗？\p"
	.string "能够远距离通话真是方便呢！\p"
	.string "之前如果我想和谁聊聊的话，只能叫\n"
	.string "我爸开车载我去……\p"
	.string "差不多该挂啦。很高兴和你聊天。$"

MatchCall_PersonalizedText11::
	.string "我是{STR_VAR_1}！听我\n"
	.string "说个事！\p"
	.string "我很喜欢狩猎地带，但每次去都会迷\n"
	.string "路！\p"
	.string "到处是高高的杂草！而且地方也太大\n"
	.string "了！\p"
	.string "说出来舒服多啦！\p"
	.string "我要再次向狩猎地带出发了！回见！$"

MatchCall_PersonalizedText12::
	.string "你好，是我{STR_VAR_1}\n"
	.string "。嗯，没错，我还是那么有钱。\p"
	.string "我要告诉你，我的财富在上次见面后\n"
	.string "又增加了不少。\p"
	.string "而且，我的宝可梦也变得更强了。\p"
	.string "我不得不开始怀疑地球是围着我转的\n"
	.string "！\p"
	.string "哦，无需多言！事实就在眼前！\p"
	.string "哦，抱歉要先失陪了，我得去参加一\n"
	.string "场重要的晚宴了。$"

MatchCall_PersonalizedText13::
	.string "呼呼呼……是我，\n"
	.string "{STR_VAR_1}……\p"
	.string "能猜到我在看什么吗？一对\n"
	.string "{STR_VAR_2}正在打架。\p"
	.string "也许我应把胜利者捕捉了……呼呼呼\n"
	.string "……\p"
	.string "我……要去忙了。我走了。$"

MatchCall_PersonalizedText14::
	.string "哦，我是{STR_VAR_1}！\p"
	.string "我已经开始觉得呆在被遗弃的海船里\n"
	.string "有些无聊了。\p"
	.string "但既然我来了，而且还想赢你一次，\n"
	.string "那就再多呆一会吧。\p"
	.string "有兴趣的话，不妨来找我？\p"
	.string "我想今天终于可以和隔壁的大叔来场\n"
	.string "对战了。\p"
	.string "再见！$"

MatchCall_PersonalizedText15::
	.string "我是{STR_VAR_1}！大海\n"
	.string "的男儿！\p"
	.string "你知道我在想啥吗？\p"
	.string "从大海中来的训练家才是强者中的强\n"
	.string "者呀！\p"
	.string "你应该向我学着在大海中修炼……\p"
	.string "哦哦，有巨浪涌起！\p"
	.string "这是多么好的训练机会啊！抱歉，我\n"
	.string "先闪了！$"

MatchCall_PersonalizedText16::
	.string "在下是{STR_VAR_1}！听\n"
	.string "着，我一直在传授空手道给我的宝可\l"
	.string "梦。\p"
	.string "它们现在已经比我厉害了！我一直在\n"
	.string "输给它们！\p"
	.string "但就算输给了宝可梦，我也绝不会输\n"
	.string "给训练家的！\p"
	.string "我们再战一场吧！呜哇！$"

MatchCall_PersonalizedText17::
	.string "是我，{STR_VAR_1}。旅\n"
	.string "行还顺利吗？\p"
	.string "……哇，真的？听起来超刺激啊！\p"
	.string "我想我都能把你的故事写成歌了。\p"
	.string "……哦，灵感来了。我的脑海里已经\n"
	.string "有旋律了。\p"
	.string "我得赶紧把曲子记下来，嗯，得走了\n"
	.string "！下次见！$"

MatchCall_PersonalizedText18::
	.string "我是{STR_VAR_1}……听\n"
	.string "听我的新歌吧。\p"
	.string "啦啦啦，{STR_VAR_2}，\n"
	.string "{STR_VAR_2}！为什么你\l"
	.string "是{STR_VAR_2}？为什么\l"
	.string "我不能成为你，\l"
	.string "{STR_VAR_2}？啦啦，\l"
	.string "{STR_VAR_2}和\l"
	.string "{STR_VAR_1}，\l"
	.string "{STR_VAR_1}和\l"
	.string "{STR_VAR_2}……\p"
	.string "重复副歌，淡出……$"

MatchCall_PersonalizedText19::
	.string "我是{STR_VAR_1}，你知\n"
	.string "道的，野营专家！\p"
	.string "上次对战输给你很正常。\p"
	.string "毕竟我的专长是露营。\p"
	.string "无论结果如何，我都喜欢在露营时对\n"
	.string "战。\p"
	.string "再来对战吧，怎么样？一起去露营也\n"
	.string "行哦！$"

MatchCall_PersonalizedText20::
	.string "是我呀，我，\n"
	.string "{STR_VAR_1}！\p"
	.string "说实话，我想去爬其他的山。\p"
	.string "但是我不确定其他山的美女会不会像\n"
	.string "烟囱山里的一样多。\p"
	.string "如果你知道哪座山美女多的话，记得\n"
	.string "告诉我！\p"
	.string "哎嘿嘿，回见啦！$"

MatchCall_PersonalizedText21::
	.string "…… …… ………… …… ……\n"
	.string "我是{STR_VAR_1}……\p"
	.string "…… …… ………… …… ……\n"
	.string "今天就这样……$"

MatchCall_PersonalizedText22::
	.string "我是{STR_VAR_1}。今天\n"
	.string "有预感会和你通话。\p"
	.string "想打败你的心情与日俱增。\p"
	.string "你也有这样的劲敌吧？希望那个人是\n"
	.string "我……\p"
	.string "很高兴你能听我说这些。再见！$"

MatchCall_PersonalizedText23::
	.string "我是{STR_VAR_1}。\p"
	.string "附近有强大训练家时，我总能感应到\n"
	.string "。\p"
	.string "刚才是你经过吗，{PLAYER}\n"
	.string "{KUN}？说不定就是你呢。\p"
	.string "期待你的来访。再见！$"

MatchCall_PersonalizedText24::
	.string "你好，我是{STR_VAR_1}\n"
	.string "。听起来你还不错，\l"
	.string "{PLAYER}{KUN}。\p"
	.string "虽然周游了世界，但我特别喜欢这个\n"
	.string "地区。\p"
	.string "我打算多待一阵子。也许我们应该再\n"
	.string "见一见？\p"
	.string "我还记得你精彩的对战技巧。\p"
	.string "我真的希望能再切磋一次。$"

MatchCall_PersonalizedText25::
	.string "呜咽……我是……\n"
	.string "{STR_VAR_1}…………吸\l"
	.string "……\p"
	.string "今天在课上被杜娟训了。\p"
	.string "但是我并讨厌她。\p"
	.string "杜娟直接指出了我的错误，这样我能\n"
	.string "吃一堑长一智。\p"
	.string "明天我绝对还要去训练师学校！\p"
	.string "回头见！$"

MatchCall_PersonalizedText26::
	.string "我是{STR_VAR_1}！\p"
	.string "昨天，杜娟答应和我对战了。\p"
	.string "结果吗……不用问也知道很惨。\p"
	.string "但能挑战她我就超开心！\p"
	.string "我现在更崇拜她了！\p"
	.string "我会加倍努力的！先走啦！$"

MatchCall_PersonalizedText27::
	.string "嗨，我是美穗！我今天还是和我的后\n"
	.string "辈搭档里子在一起。\p"
	.string "我超喜欢照顾里子和宝可梦。它们太\n"
	.string "可爱了！\p"
	.string "真希望我可以像对待弟弟妹妹一样宠\n"
	.string "它们！\p"
	.string "——哦，里子！面包买到了吗？\p"
	.string "什么？没有，才没有把你当成私家仆\n"
	.string "人使唤！\p"
	.string "你输了对战，所以就要罚你跑腿帮我\n"
	.string "买面包！\p"
	.string "我不会把你当作私家仆人的，里子对\n"
	.string "我可是特别的存在！\p"
	.string "现在得走啦，点心时间到！$"

MatchCall_PersonalizedText28::
	.string "I love POKéMON!\n"
	.string "It's {STR_VAR_1} from the FAN CLUB!\p"
	.string "You have to hear this!\n"
	.string "My sweet POKéMON…\p"
	.string "Snort! Wahaha!\n"
	.string "I can't say any more! It's a secret!\l"
	.string "It's just too cute for words!\p"
	.string "Oh, my sweet {STR_VAR_2} is begging\n"
	.string "for a {POKEBLOCK}!\p"
	.string "It's the picture of cuteness!\p"
	.string "Sorry, but I can't talk now!\n"
	.string "You'll have to hear this next time!$"

MatchCall_PersonalizedText29::
	.string "哦吼吼！\p"
	.string "我是{STR_VAR_1}！迫不\n"
	.string "及待想分享我家可爱宝可梦的趣事！\p"
	.string "拜托了，一定要听我说。是关于我亲\n"
	.string "爱的{STR_VAR_2}。\p"
	.string "只要被人抱起来，它就会立刻跳回我\n"
	.string "怀里！\p"
	.string "哦……哦……还有比这更幸福的感觉\n"
	.string "吗？\p"
	.string "啊，我仿佛身处天堂！\p"
	.string "很高兴能和你分享这份快乐！\p"
	.string "现在得走啦，拜拜！$"

MatchCall_PersonalizedText30::
	.string "我是……{STR_VAR_1}。\n"
	.string "尽管人们都叫我达人。\p"
	.string "但是我清楚一件事——我无法仅凭一\n"
	.string "己之力成为达人。\p"
	.string "只有与宝可梦同心协力，训练家方能\n"
	.string "成为达人。\p"
	.string "哼！可能我说得有些过于深奥了！\p"
	.string "我应该给你留份好心情的！$"

MatchCall_PersonalizedText31::
	.string "我是{STR_VAR_1}。很高\n"
	.string "兴和你聊天！\p"
	.string "泡在温泉里的我现在神清气爽。\p"
	.string "自上次我们交手以后，我又和不少年\n"
	.string "轻的训练家对战过，但是你仍是他们\l"
	.string "之中的佼佼者。\p"
	.string "我能想象等你到了我这个岁数也会成\n"
	.string "为一个达人的！呵呵呵……$"

MatchCall_PersonalizedText32::
	.string "耶！我是{STR_VAR_1}！\n"
	.string "猜怎么着？\p"
	.string "不知道是不是错觉，每次打赢对战，\n"
	.string "我的短裤材质好像都会变得更高级，\p"
	.string "那是什么意思？有点难以形容，怎么\n"
	.string "说呢……？好像触感更丝滑了！\p"
	.string "但是和你对战的时候，\n"
	.string "{PLAYER}{KUN}，短裤\l"
	.string "触感就会变得糙糙的。\p"
	.string "…… …… ……你不会当真吧？哎\n"
	.string "嘿嘿，就这样吧！拜拜！$"

MatchCall_PersonalizedText33::
	.string "咳咳！是我{STR_VAR_1}\n"
	.string "！\p"
	.string "和平常一样，正疯狂钓鱼中！\p"
	.string "除了大海和河流，还有其他地方能捕\n"
	.string "鱼吗？\p"
	.string "我现在无论看哪里都好想甩上一竿！\p"
	.string "哦，糟糕，见鬼！我的线缠住了！\p"
	.string "我走了！记得帮我找新钓点啊！$"

MatchCall_PersonalizedText34::
	.string "嘿，你好！我是\n"
	.string "{STR_VAR_1}。最近过得\l"
	.string "悠闲吗？\p"
	.string "从我还是个孩子开始，要知道，我都\n"
	.string "生活得都很平静，是吧？\p"
	.string "我那时从来没有遇到过巨大的压力和\n"
	.string "刺激的事情。\p"
	.string "但是你不知道吧，我现在是个铁人三\n"
	.string "项选手了。\p"
	.string "你无法预见命运会把你带到哪里，如\n"
	.string "果你像我一样漂泊的话。\p"
	.string "你目前是个训练家，但是谁知道未来\n"
	.string "会怎样呢，是吧？\p"
	.string "想想看自己将成为一个导师，或是一\n"
	.string "个艺术家。酷，是吧？\p"
	.string "但是，嘿，冷静点。放轻松。再见了\n"
	.string "。$"

MatchCall_PersonalizedText35::
	.string "我是{STR_VAR_1}！我在\n"
	.string "骑自行车呢。\p"
	.string "我喜欢游泳和跑步，但是自行车是我\n"
	.string "的最爱！\p"
	.string "我感觉整个人好像都和风融为一体了\n"
	.string "。\p"
	.string "好像随风飞行一样，感觉太棒了！\p"
	.string "好了！今天，我要创造一个自行车公\n"
	.string "路赛的新纪录！\p"
	.string "你也可以来挑战一下！再见！$"

MatchCall_PersonalizedText36::
	.string "哟，我是{STR_VAR_1}！\n"
	.string "正在铁人三项赛中！\p"
	.string "不过，嘿，总有时间聊天的！\p"
	.string "和宝可梦一起训练超棒！\p"
	.string "无需言语就能心灵同步。\p"
	.string "多美妙啊！\p"
	.string "呃……边跑边聊……上气不接下气了\n"
	.string "……呼……我……必须……挂了……$"

MatchCall_PersonalizedText37::
	.string "嗨，我是{STR_VAR_1}。\n"
	.string "如果你想增强耐力，那么就来参加高\l"
	.string "原训练！\p"
	.string "来山顶上跑步吧。你可能马上就喘不\n"
	.string "上气了！\p"
	.string "我也感到有点缺氧了！再见！$"

MatchCall_PersonalizedText38::
	.string "哦，我是{STR_VAR_1}，\n"
	.string "你好。\p"
	.string "我已经游了很久了，可看起来还是到\n"
	.string "不了彩悠市。\p"
	.string "我不会在兜圈子吧。\p"
	.string "不，那绝对不可能啦。哇哈哈哈。保\n"
	.string "重！$"

MatchCall_PersonalizedText39::
	.string "Hey, it's {STR_VAR_1}…\n"
	.string "Whoops!\p"
	.string "Splash!\p"
	.string "Blug-blug-blug-blug…\p"
	.string "Sploosh!\p"
	.string "Whiff-whiff! Whiff-whiff!\p"
	.string "Hey! Sorry about that!\n"
	.string "I just put on some suntan oil.\p"
	.string "So my POKéNAV went whoopsy\n"
	.string "out of my hand into the water!\p"
	.string "But, boy, DEVON's POKéNAV is built\n"
	.string "tough. It survived that dunking!\p"
	.string "Anyways, I'm busy sunbathing,\n"
	.string "so let's chat another time.$"

MatchCall_PersonalizedText40::
	.string "你好，我是{STR_VAR_1}\n"
	.string "。\p"
	.string "铁人三项赛里面，我最喜欢游泳了。\p"
	.string "但要是泡海里太久，皮肤会不会皱成\n"
	.string "梅干啊？\p"
	.string "哦，铁人三项赛真是对人类耐力的严\n"
	.string "酷考验啊！再见！$"

MatchCall_PersonalizedText41::
	.string "你好，{PLAYER}{KUN}\n"
	.string "。是我{STR_VAR_1}。\p"
	.string "你的宝可梦还好吗？\p"
	.string "我的龙宝可梦看起来状态绝佳。先这\n"
	.string "样吧。$"

MatchCall_PersonalizedText42::
	.string "是我{STR_VAR_1}。\p"
	.string "我的{STR_VAR_2}可是要\n"
	.string "比上一次的时候强多了。\p"
	.string "我绝不会再输给你了。等着瞧吧！\p"
	.string "再见了！$"

MatchCall_PersonalizedText43::
	.string "我是{STR_VAR_1}。\p"
	.string "我一直在继续钻研精进隐匿之术。\p"
	.string "但似乎太成功了——现在根本没人能\n"
	.string "找到我了。成功的代价是孤独啊……\p"
	.string "我如烟般消散吧！告辞！$"

MatchCall_PersonalizedText44::
	.string "我是{STR_VAR_1}。上次\n"
	.string "见面以后我一直在修炼。\p"
	.string "我的{STR_VAR_2}变得很\n"
	.string "厉害了。\p"
	.string "海滩特训果然有效，和预料中的一样\n"
	.string "。再见！$"

MatchCall_PersonalizedText45::
	.string "你好吗？我是\n"
	.string "{STR_VAR_1}。\p"
	.string "我在想这烦人的火山灰要下到什么时\n"
	.string "候？\p"
	.string "如果再这样下去，我遮阳伞上的图案\n"
	.string "都要被盖住了……\p"
	.string "约好下次再见啦！$"

MatchCall_PersonalizedText46::
	.string "嗨，是我{STR_VAR_1}。\p"
	.string "你知道吗？浮在海水里比浮在泳池里\n"
	.string "简单很多呢。\p"
	.string "只要放松躺着，你的身体会自己飘起\n"
	.string "来。\p"
	.string "但如果你漂浮的时间太长，要注意别\n"
	.string "被海流冲得太远啊。\p"
	.string "……呃我现在是到哪了？我得挂了！$"

MatchCall_PersonalizedText47::
	.string "喂，{PLAYER}{KUN}，\n"
	.string "好啊！我是{STR_VAR_1}\l"
	.string "。我正在山上呢。\p"
	.string "但这地面一点也不平整。我不能在这\n"
	.string "里搭帐篷……\p"
	.string "哦，灵光一闪！\p"
	.string "也许我能用宝可梦来踏平地面！\p"
	.string "这就去试试看！再见！$"

MatchCall_PersonalizedText48::
	.string "喂，嗨，嗨，我是\n"
	.string "{STR_VAR_1}！\p"
	.string "我正在和留美一起培育宝可梦！我们\n"
	.string "超努力的！\p"
	.string "如果我们再努力些，会成为第一吗？\n"
	.string "再见！$"

MatchCall_PersonalizedText49::
	.string "我是{STR_VAR_1}！\p"
	.string "尽管是个水手，但是现在并不在船上\n"
	.string "。\p"
	.string "我很好奇应该如何称呼一个在陆地上\n"
	.string "的水手呢？\p"
	.string "这就是我经常在远航时常常在想的问\n"
	.string "题。\p"
	.string "好了，下次见！$"

MatchCall_PersonalizedText50::
	.string "我是{STR_VAR_1}。捕捉\n"
	.string "新的宝可梦了吗？\p"
	.string "如果捕捉到了，你一定要来给我看看\n"
	.string "。\p"
	.string "保证不缠着你要，说到做到。我等着\n"
	.string "你，会见！$"

MatchCall_PersonalizedText51::
	.string "这里是{STR_VAR_1}。\p"
	.string "你有在用最优方式培育宝可梦吗？\p"
	.string "我这里的空气超清新，对于培育宝可\n"
	.string "梦来说简直是完美环境。\p"
	.string "要专注培育宝可梦的话，强烈推荐来\n"
	.string "{STR_VAR_2}。多保重啦\l"
	.string "！$"

MatchCall_PersonalizedText52::
	.string "Hi, this is {STR_VAR_1}.\p"
	.string "I gave a {POKEBLOCK} to my {STR_VAR_2}.\n"
	.string "It seemed to enjoy it very much.\p"
	.string "It looks like POKéMON have their\n"
	.string "likes and dislikes with {POKEBLOCK}S.\p"
	.string "I find that quite fascinating.\n"
	.string "Please do take care.$"

MatchCall_PersonalizedText53::
	.string "我是{STR_VAR_1}。\p"
	.string "只要和宝可梦协作，野外生活也能很\n"
	.string "舒适。\p"
	.string "真希望更多人明白这点，多多和宝可\n"
	.string "梦合作啊。\p"
	.string "我真的这么想！\p"
	.string "我觉得你做得就很好！改天见！$"

MatchCall_PersonalizedText54::
	.string "嗨，我是时刻准备的训练家\n"
	.string "{STR_VAR_1}！\p"
	.string "{PLAYER}{KUN}，带够\n"
	.string "道具了吗？宝可梦状态如何？\p"
	.string "随时保持万全准备才是保持长久冒险\n"
	.string "的秘诀！\p"
	.string "我也得去检查行李了，时刻留意！$"

MatchCall_PersonalizedText55::
	.string "我是{STR_VAR_1}！我是\n"
	.string "{STR_VAR_1}！\p"
	.string "{STR_VAR_2}是交通要道\n"
	.string "，所以我每天都能挑战到各种训练家\l"
	.string "。\p"
	.string "我今天5胜3败！\p"
	.string "你的战绩呢？下次告诉我吧，好吗？$"

MatchCall_PersonalizedText56::
	.string "是我，{STR_VAR_1}。\p"
	.string "我是因为虫系宝可梦多才受关注的对\n"
	.string "吧？\p"
	.string "今天我带了一堆最爱的虫宝可梦去学\n"
	.string "校。\p"
	.string "结果我喜欢的女孩子被吓哭了！你想\n"
	.string "笑就笑吧。\p"
	.string "我得想办法让她明白虫系宝可梦的魅\n"
	.string "力！\p"
	.string "呜呜……再见！$"

MatchCall_PersonalizedText57::
	.string "呼！呼！呼！呼！\p"
	.string "嗨！我是{STR_VAR_1}！\n"
	.string "呼！呼！\p"
	.string "尝试……登山的时候聊天……是多么\n"
	.string "困难的训练啊……呼！呼！\p"
	.string "哇！呜……山峰真陡峭……我们要改\n"
	.string "日……再谈了……呼！呼！哇！$"

MatchCall_PersonalizedText58::
	.string "哦，嗨！\p"
	.string "我依然和夏一起寻找财宝！\p"
	.string "也许这里其实什么财宝都没有……\p"
	.string "但是对我来说和夏一起搜索才重要。\p"
	.string "哦嘿，夏！为……为什么那么生气？\p"
	.string "我没有忽略你，宝贝！你就是我的唯\n"
	.string "一！\p"
	.string "……{PLAYER}，我得挂了，\n"
	.string "再见！$"

MatchCall_PersonalizedText59::
	.string "我是{STR_VAR_1}！\p"
	.string "我又去武斗镇的道馆训练了。\p"
	.string "道馆馆主藤树，看上去更强大了。\p"
	.string "看起来巨浪的确能磨炼人……\p"
	.string "说来他还一如既往地帅气。女粉丝们\n"
	.string "可崇拜他了！说实话，真让人羡慕啊\l"
	.string "。\p"
	.string "我很好奇……他的朋友希巴会是个和\n"
	.string "藤树差不多的人吗？\p"
	.string "你知道的，浑身汗味，还喜欢叫别人\n"
	.string "“巨浪”之类的。\p"
	.string "不过这种嫉妒心理是不是不太好啊？\p"
	.string "就当我什么都没说吧，怎么样？再见\n"
	.string "啦！$"

MatchCall_PersonalizedText60::
	.string "我很高兴能和你这样的年轻训练家交\n"
	.string "流。\p"
	.string "我想无论你多大年纪都会继续享受宝\n"
	.string "可梦的乐趣。\p"
	.string "如果你能像我们这样拥有伴侣不是很\n"
	.string "好吗？\p"
	.string "当然，{PLAYER}{KUN}\n"
	.string "，你现在已经拥有了宝可梦的信任与\l"
	.string "陪伴。\p"
	.string "你已经具备建立长久关系的基础了！\p"
	.string "哈哈哈！永远不要气馁！$"

MatchCall_PersonalizedText61::
	.string "嗨，我是{STR_VAR_1}！\n"
	.string "我们刚刚赢了一场对战！\p"
	.string "尽管不是经常能赢，但对手是个很帅\n"
	.string "气的泳裤小伙子。\p"
	.string "我姐姐气坏了！\p"
	.string "她本来想假装弱小来博取关注！\p"
	.string "无论输赢，她都要数落我一顿！\p"
	.string "{PLAYER}{KUN}，下次\n"
	.string "你能帮我说说她吗？\p"
	.string "好了，再见！$"

MatchCall_PersonalizedText62::
	.string "我是{STR_VAR_1}，对。\n"
	.string "昨天我出海去了。\p"
	.string "我本希望能发现一个新的遗迹。\p"
	.string "但是，海流不知怎么把我又带回我出\n"
	.string "发的地方了。\p"
	.string "我的对战水平也还很弱……尽管笑我\n"
	.string "吧……但是我不会放弃。\p"
	.string "终有一天我会发现新遗迹的！\p"
	.string "就说这么多了！先告辞了！$"

MatchCall_PersonalizedText63::
	.string "喂，那啥！是我，\n"
	.string "{STR_VAR_1}！我现在正\l"
	.string "在108号水路上！简而言之还是在\l"
	.string "老地方！\p"
	.string "今天，有位超级美丽的比基尼姐姐从\n"
	.string "我身旁游过！\p"
	.string "我就大喊一声吓了她一跳！\p"
	.string "结果她狠狠瞪了我一眼！\p"
	.string "以上都发生在108号水路！由\n"
	.string "{STR_VAR_1}为你报道！$"

MatchCall_PersonalizedText64::
	.string "我是{STR_VAR_1}！\p"
	.string "虽然有点忙，但觉得应该告诉你，我\n"
	.string "今天又打败了五个训练家。\p"
	.string "如果保持这种势头，下次大概就能赢\n"
	.string "你了。\p"
	.string "我想，你和我，会成为好对手的，再\n"
	.string "见了！$"

MatchCall_BattleFrontierStreakText1::
	.string "嗨！我是{STR_VAR_1}。\n"
	.string "听说消息了！\p"
	.string "他们说你在{STR_VAR_2}\n"
	.string "表现超棒。\p"
	.string "一下子就连赢了\n"
	.string "{STR_VAR_3}场？真了不\l"
	.string "起！再见！$"

MatchCall_BattleFrontierStreakText2::
	.string "你好，我是{STR_VAR_1}\n"
	.string "！听说你的事了！\p"
	.string "他们说你在{STR_VAR_2}\n"
	.string "一下子取得了\l"
	.string "{STR_VAR_3}连胜。\p"
	.string "太厉害了！我也要努力！再见！$"

MatchCall_BattleFrontierStreakText3::
	.string "喂你好，{PLAYER}！是我，\n"
	.string "{STR_VAR_1}。\p"
	.string "我听说你在{STR_VAR_2}\n"
	.string "势不可挡！\p"
	.string "一个漂亮的{STR_VAR_3}\n"
	.string "连胜……这是个新纪录，对吧？\p"
	.string "我也要努力了！以后联系！$"

MatchCall_BattleFrontierStreakText4::
	.string "喂，{PLAYER}{KUN}。\n"
	.string "是我{STR_VAR_1}，最近\l"
	.string "怎样？\p"
	.string "有传言说你在\n"
	.string "{STR_VAR_2}取得了\l"
	.string "{STR_VAR_3}连胜。\p"
	.string "我也要加油啊。再见！$"

MatchCall_BattleFrontierStreakText5::
	.string "喂，{PLAYER}{KUN}！\n"
	.string "我是{STR_VAR_1}。\p"
	.string "你在{STR_VAR_2}取得\n"
	.string "{STR_VAR_3}连胜？真厉\l"
	.string "害啊！\p"
	.string "我也要多加训练宝可梦了。回见！$"

MatchCall_BattleFrontierStreakText6::
	.string "喂，{PLAYER}{KUN}。\n"
	.string "是我{STR_VAR_1}。你好\l"
	.string "吗？\p"
	.string "对了，我听说你在\n"
	.string "{STR_VAR_2}完成了\l"
	.string "{STR_VAR_3}场连胜的壮\l"
	.string "举。\p"
	.string "这激励我要更专注于培养队伍了。$"

MatchCall_BattleFrontierStreakText7::
	.string "……呃，{PLAYER}\n"
	.string "{KUN}？是我\l"
	.string "{STR_VAR_1}……\p"
	.string "哦对了，你之前在\n"
	.string "{STR_VAR_2}，对吧？\p"
	.string "并且还取得了\n"
	.string "{STR_VAR_3}连胜。\p"
	.string "哎呀，这里有只稀有的宝可梦！我要\n"
	.string "走了！$"

MatchCall_BattleFrontierStreakText8::
	.string "喂，{PLAYER}{KUN}，\n"
	.string "你好吗？我是\l"
	.string "{STR_VAR_1}。希望你一\l"
	.string "切顺利。\p"
	.string "不过你好像的确很顺利。我听说你在\n"
	.string "{STR_VAR_2}取得了\l"
	.string "{STR_VAR_3}连胜。\p"
	.string "真是让人震惊！祝你继续保持成功。$"

MatchCall_BattleFrontierStreakText9::
	.string "哦，{PLAYER}{KUN}，\n"
	.string "你好啊！我是\l"
	.string "{STR_VAR_1}！\p"
	.string "我听说了！你在\n"
	.string "{STR_VAR_2}取得了\l"
	.string "{STR_VAR_3}连胜！\p"
	.string "太酷了！我也要加油！$"

MatchCall_BattleFrontierStreakText10::
	.string "喂，{PLAYER}{KUN}，\n"
	.string "你好……我是\l"
	.string "{STR_VAR_1}。\p"
	.string "你在{STR_VAR_2}取得了\n"
	.string "{STR_VAR_3}连胜？\p"
	.string "真是了不起的成就。我要努力了。$"

MatchCall_BattleFrontierStreakText11::
	.string "啊，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。\p"
	.string "听说你在{STR_VAR_2}所\n"
	.string "向披靡？\p"
	.string "你取得了，多少，\n"
	.string "{STR_VAR_3}连胜？\p"
	.string "你真厉害啊你。不知道我能赢几场？$"

MatchCall_BattleFrontierStreakText12::
	.string "你好，{PLAYER}{KUN}\n"
	.string "。是我，{STR_VAR_1}。\l"
	.string "你还好吗？\p"
	.string "有些人在谈论你。说你在\n"
	.string "{STR_VAR_2}连胜了\l"
	.string "{STR_VAR_3}场？\p"
	.string "真是精彩的故事。回见！$"

MatchCall_BattleFrontierStreakText13::
	.string "啊，你好，{PLAYER}\n"
	.string "{KUN}！我是\l"
	.string "{STR_VAR_1}！希望你一\l"
	.string "切都好。\p"
	.string "他们说你在{STR_VAR_2}\n"
	.string "取得了{STR_VAR_3}连胜\l"
	.string "。\p"
	.string "真佩服你的活力！再见了。$"

MatchCall_BattleFrontierStreakText14::
	.string "喂，嗨，{PLAYER}\n"
	.string "{KUN}。我是\l"
	.string "{STR_VAR_1}。\p"
	.string "我听说你的事了！你是不是刚在\n"
	.string "{STR_VAR_2}取得了\l"
	.string "{STR_VAR_3}连胜？\p"
	.string "真是鼓舞人心！再见！$"

MatchCall_BattleFrontierRecordStreakText1::
	.string "嗨！我是{STR_VAR_1}。\n"
	.string "听说消息了！\p"
	.string "他们说你在{STR_VAR_2}\n"
	.string "表现超棒。\p"
	.string "一下子就连赢了\n"
	.string "{STR_VAR_3}场？真了不\l"
	.string "起！再见！$"

MatchCall_BattleFrontierRecordStreakText2::
	.string "你好，我是{STR_VAR_1}\n"
	.string "！听说你的事了！\p"
	.string "他们说你在{STR_VAR_2}\n"
	.string "一下子取得了\l"
	.string "{STR_VAR_3}连胜。\p"
	.string "太厉害了！我也要努力！再见！$"

MatchCall_BattleFrontierRecordStreakText3::
	.string "喂你好，{PLAYER}！是我，\n"
	.string "{STR_VAR_1}。\p"
	.string "我听说你在{STR_VAR_2}\n"
	.string "势不可挡！\p"
	.string "一个漂亮的{STR_VAR_3}\n"
	.string "连胜……这是个新纪录，对吧？\p"
	.string "我也要努力了！以后联系！$"

MatchCall_BattleFrontierRecordStreakText4::
	.string "喂，{PLAYER}{KUN}。\n"
	.string "是我{STR_VAR_1}，最近\l"
	.string "怎样？\p"
	.string "有传言说你在\n"
	.string "{STR_VAR_2}取得了\l"
	.string "{STR_VAR_3}连胜。\p"
	.string "我也要加油啊。再见！$"

MatchCall_BattleFrontierRecordStreakText5::
	.string "喂，{PLAYER}{KUN}！\n"
	.string "我是{STR_VAR_1}。\p"
	.string "你在{STR_VAR_2}取得\n"
	.string "{STR_VAR_3}连胜？真厉\l"
	.string "害啊！\p"
	.string "我也要多加训练宝可梦了。回见！$"

MatchCall_BattleFrontierRecordStreakText6::
	.string "喂，{PLAYER}{KUN}。\n"
	.string "是我{STR_VAR_1}。你好\l"
	.string "吗？\p"
	.string "对了，我听说你在\n"
	.string "{STR_VAR_2}完成了\l"
	.string "{STR_VAR_3}场连胜的壮\l"
	.string "举。\p"
	.string "这激励我要更专注于培养队伍了。$"

MatchCall_BattleFrontierRecordStreakText7::
	.string "……呃，{PLAYER}\n"
	.string "{KUN}？是我\l"
	.string "{STR_VAR_1}……\p"
	.string "哦对了，你之前在\n"
	.string "{STR_VAR_2}，对吧？\p"
	.string "并且还取得了\n"
	.string "{STR_VAR_3}连胜。\p"
	.string "哎呀，这里有只稀有的宝可梦！我要\n"
	.string "走了！$"

MatchCall_BattleFrontierRecordStreakText8::
	.string "喂，{PLAYER}{KUN}，\n"
	.string "你好吗？我是\l"
	.string "{STR_VAR_1}。希望你一\l"
	.string "切顺利。\p"
	.string "不过你好像的确很顺利。我听说你在\n"
	.string "{STR_VAR_2}取得了\l"
	.string "{STR_VAR_3}连胜。\p"
	.string "真是让人震惊！祝你继续保持成功。$"

MatchCall_BattleFrontierRecordStreakText9::
	.string "哦，{PLAYER}{KUN}，\n"
	.string "你好啊！我是\l"
	.string "{STR_VAR_1}！\p"
	.string "我听说了！你在\n"
	.string "{STR_VAR_2}取得了\l"
	.string "{STR_VAR_3}连胜！\p"
	.string "太酷了！我也要加油！$"

MatchCall_BattleFrontierRecordStreakText10::
	.string "喂，{PLAYER}{KUN}，\n"
	.string "你好……我是\l"
	.string "{STR_VAR_1}。\p"
	.string "你在{STR_VAR_2}取得了\n"
	.string "{STR_VAR_3}连胜？\p"
	.string "真是了不起的成就。我要努力了。$"

MatchCall_BattleFrontierRecordStreakText11::
	.string "啊，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。\p"
	.string "听说你在{STR_VAR_2}所\n"
	.string "向披靡？\p"
	.string "你取得了，多少，\n"
	.string "{STR_VAR_3}连胜？\p"
	.string "你真厉害啊你。不知道我能赢几场？$"

MatchCall_BattleFrontierRecordStreakText12::
	.string "你好，{PLAYER}{KUN}\n"
	.string "。是我，{STR_VAR_1}。\l"
	.string "你还好吗？\p"
	.string "有些人在谈论你。说你在\n"
	.string "{STR_VAR_2}连胜了\l"
	.string "{STR_VAR_3}场？\p"
	.string "真是精彩的故事。回见！$"

MatchCall_BattleFrontierRecordStreakText13::
	.string "啊，你好，{PLAYER}\n"
	.string "{KUN}！我是\l"
	.string "{STR_VAR_1}！希望你一\l"
	.string "切都好。\p"
	.string "他们说你在{STR_VAR_2}\n"
	.string "取得了{STR_VAR_3}连胜\l"
	.string "。\p"
	.string "真佩服你的活力！再见了。$"

MatchCall_BattleFrontierRecordStreakText14::
	.string "喂，嗨，{PLAYER}\n"
	.string "{KUN}。我是\l"
	.string "{STR_VAR_1}。\p"
	.string "我听说你的事了！你是不是刚在\n"
	.string "{STR_VAR_2}取得了\l"
	.string "{STR_VAR_3}连胜？\p"
	.string "真是鼓舞人心！再见！$"

MatchCall_BattleDomeText1::
	.string "嗨！{PLAYER}？你好，我是\n"
	.string "{STR_VAR_1}！我听说你\l"
	.string "了！\p"
	.string "你在{STR_VAR_2}达成了\n"
	.string "{STR_VAR_3}连冠？\p"
	.string "太棒了！我也得加把劲！再见啦！$"

MatchCall_BattleDomeText2::
	.string "你好，我是{STR_VAR_1}\n"
	.string "！我听说了你的事！\p"
	.string "他们说你在{STR_VAR_2}\n"
	.string "取得了{STR_VAR_3}连冠\l"
	.string "。\p"
	.string "真厉害！我在想自己能不能也成为冠\n"
	.string "军呢？$"

MatchCall_BattleDomeText3::
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "How's it going?\p"
	.string "I heard you won events {STR_VAR_3} times\n"
	.string "at the {STR_VAR_2}!\p"
	.string "Make it one more next time!\n"
	.string "Catch you soon!$"

MatchCall_BattleDomeText4::
	.string "嘿，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。\p"
	.string "听说你在{STR_VAR_2}获\n"
	.string "得了{STR_VAR_3}连冠？\p"
	.string "看来你很努力啊。我也得跟上你的步\n"
	.string "伐！$"

MatchCall_BattleDomeText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "I heard you won {STR_VAR_3} times\n"
	.string "outright at the {STR_VAR_2}.\p"
	.string "I'd better get with it, too!\n"
	.string "See you soon!$"

MatchCall_BattleDomeText6::
	.string "Hey, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here. How are you?\p"
	.string "By the way, I heard you became\n"
	.string "the champion {STR_VAR_3} times at\l"
	.string "the {STR_VAR_2}.\p"
	.string "I'd better raise my POKéMON before\n"
	.string "you pull farther ahead.$"

MatchCall_BattleDomeText7::
	.string "{PLAYER}{KUN}？我是\n"
	.string "{STR_VAR_1}。\p"
	.string "你在{STR_VAR_2}取得了\n"
	.string "{STR_VAR_3}连冠？\p"
	.string "真不得了啊。对了，你有捕捉到稀有\n"
	.string "的宝可梦吗？\p"
	.string "哦，这样啊。好，再见。$"

MatchCall_BattleDomeText8::
	.string "喂，{PLAYER}{KUN}，\n"
	.string "你好吗？我是\l"
	.string "{STR_VAR_1}。希望你一\l"
	.string "切顺利。\p"
	.string "不过你好像的确很顺利。我听说你在\n"
	.string "{STR_VAR_2}取得了\l"
	.string "{STR_VAR_3}连冠。\p"
	.string "我也得像你一样训练我的宝可梦。下\n"
	.string "次见！$"

MatchCall_BattleDomeText9::
	.string "喂，{PLAYER}{KUN}，\n"
	.string "你好啊！我是\l"
	.string "{STR_VAR_1}！\p"
	.string "我听说了！你在\n"
	.string "{STR_VAR_2}取得了\l"
	.string "{STR_VAR_3}连冠！\p"
	.string "太酷了！我也要努力了！$"

MatchCall_BattleDomeText10::
	.string "哦，{PLAYER}{KUN}，\n"
	.string "你好。我是{STR_VAR_1}\l"
	.string "。\p"
	.string "你在{STR_VAR_2}取得了\n"
	.string "{STR_VAR_3}连冠？\p"
	.string "真是了不起啊。我也要努力了。$"

MatchCall_BattleDomeText11::
	.string "哦，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。\p"
	.string "听说你在{STR_VAR_2}所\n"
	.string "向披靡？\p"
	.string "你现在已经实现\n"
	.string "{STR_VAR_3}连冠了？\p"
	.string "我在想自己能不能……也成为冠军？\p"
	.string "……大概不可能吧？好吧，再见！$"

MatchCall_BattleDomeText12::
	.string "你好，{PLAYER}{KUN}\n"
	.string "。是我，{STR_VAR_1}。\l"
	.string "最近还好吗？\p"
	.string "你在{STR_VAR_2}取得了\n"
	.string "{STR_VAR_3}连冠？\p"
	.string "真是传奇啊。再见！$"

MatchCall_BattleDomeText13::
	.string "喂，你好，{PLAYER}\n"
	.string "{KUN}！我是\l"
	.string "{STR_VAR_1}！希望你一\l"
	.string "切都好。\p"
	.string "据说你在{STR_VAR_2}取\n"
	.string "得了{STR_VAR_3}连冠？\p"
	.string "真是精彩的故事！再见！$"

MatchCall_BattleDomeText14::
	.string "喂，你好，{PLAYER}\n"
	.string "{KUN}。我是\l"
	.string "{STR_VAR_1}。我听说你\l"
	.string "的事了！\p"
	.string "你不是在{STR_VAR_2}取\n"
	.string "得了{STR_VAR_3}连冠吗\l"
	.string "？\p"
	.string "真了不起啊！再见！$"

MatchCall_BattlePikeText1::
	.string "嗨！{PLAYER}？你好，我是\n"
	.string "{STR_VAR_1}！我听说了\l"
	.string "！\p"
	.string "你是不是在{STR_VAR_2}\n"
	.string "连续通过了{STR_VAR_3}\l"
	.string "个房间？\p"
	.string "太惊人了！再见！$"

MatchCall_BattlePikeText2::
	.string "你好，我是{STR_VAR_1}\n"
	.string "！听说你的事了！\p"
	.string "他们说你在{STR_VAR_2}\n"
	.string "连续通过了{STR_VAR_3}\l"
	.string "个房间！\p"
	.string "我也要加油啊！再见！$"

MatchCall_BattlePikeText3::
	.string "嘿你好，{PLAYER}！是我，\n"
	.string "{STR_VAR_1}。一切还好\l"
	.string "吗？\p"
	.string "我听说你在{STR_VAR_2}\n"
	.string "连续通过了{STR_VAR_3}\l"
	.string "个房间！\p"
	.string "下次争取更好成绩啊！以后再见！$"

MatchCall_BattlePikeText4::
	.string "嘿，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。\p"
	.string "我听说你在{STR_VAR_2}\n"
	.string "连续横扫了{STR_VAR_3}\l"
	.string "个房间。\p"
	.string "。我也得好好训练宝可梦才能跟上你\n"
	.string "！$"

MatchCall_BattlePikeText5::
	.string "你好，{PLAYER}{KUN}\n"
	.string "！我是{STR_VAR_1}。\p"
	.string "我听说你在{STR_VAR_2}\n"
	.string "连续闯过了{STR_VAR_3}\l"
	.string "个房间。\p"
	.string "我也要多多努力！回见！$"

MatchCall_BattlePikeText6::
	.string "喂，{PLAYER}{KUN}？\n"
	.string "我是{STR_VAR_1}。你好\l"
	.string "吗？\p"
	.string "对了，我听说你在\n"
	.string "{STR_VAR_2}连续通过了\l"
	.string "{STR_VAR_3}个房间。\p"
	.string "我也得好好训练宝可梦才能跟上你！$"

MatchCall_BattlePikeText7::
	.string "{PLAYER}{KUN}？是我\n"
	.string "{STR_VAR_1}。\p"
	.string "我听说你在{STR_VAR_2}\n"
	.string "连续通过了{STR_VAR_3}\l"
	.string "个房间？\p"
	.string "真是太厉害了。\p"
	.string "哦，那边有只稀有的宝可梦！好了，\n"
	.string "再见！$"

MatchCall_BattlePikeText8::
	.string "喂，{PLAYER}{KUN}，\n"
	.string "你好吗？我是\l"
	.string "{STR_VAR_1}。希望你一\l"
	.string "切顺利。啊，看来你确实顺利啊。\p"
	.string "我听说你在{STR_VAR_2}\n"
	.string "连续通过了{STR_VAR_3}\l"
	.string "个房间。\p"
	.string "真是让人震惊！我也要像你一样训练\n"
	.string "宝可梦了。再见。$"

MatchCall_BattlePikeText9::
	.string "喂，{PLAYER}{KUN}，\n"
	.string "你好！我是{STR_VAR_1}\l"
	.string "！\p"
	.string "我听说了！你在\n"
	.string "{STR_VAR_2}连续通过了\l"
	.string "{STR_VAR_3}个房间。\p"
	.string "太酷了！我也要努力！$"

MatchCall_BattlePikeText10::
	.string "喂，{PLAYER}{KUN}，\n"
	.string "你好。我是{STR_VAR_1}\l"
	.string "。\p"
	.string "你在{STR_VAR_2}连续通\n"
	.string "过了{STR_VAR_3}个房间\l"
	.string "？\p"
	.string "真是了不起啊。我也要加油了。$"

MatchCall_BattlePikeText11::
	.string "喂，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。\p"
	.string "听说你在{STR_VAR_2}所\n"
	.string "向披靡？\p"
	.string "你通过了，多少，\n"
	.string "{STR_VAR_3}个房间？真\l"
	.string "是不得了啊。\p"
	.string "我想知道我也能成为冠军吗？\p"
	.string "……不可能吗？好吧，再见！$"

MatchCall_BattlePikeText12::
	.string "喂，{PLAYER}{KUN}。\n"
	.string "是我，{STR_VAR_1}。最\l"
	.string "近好吗？\p"
	.string "你在{STR_VAR_2}连续通\n"
	.string "过了{STR_VAR_3}个房间\l"
	.string "？\p"
	.string "真是个精彩的故事。再见！$"

MatchCall_BattlePikeText13::
	.string "啊，你好，{PLAYER}\n"
	.string "{KUN}！我是\l"
	.string "{STR_VAR_1}！希望你一\l"
	.string "切都好。\p"
	.string "据说你在{STR_VAR_2}连\n"
	.string "续通过了{STR_VAR_3}个\l"
	.string "房间？\p"
	.string "真佩服你的精力！再见。$"

MatchCall_BattlePikeText14::
	.string "喂，嗨，{PLAYER}\n"
	.string "{KUN}。我是\l"
	.string "{STR_VAR_1}。听说你的\l"
	.string "事了！\p"
	.string "你不是在{STR_VAR_2}连\n"
	.string "续通过了{STR_VAR_3}个\l"
	.string "房间吗？\p"
	.string "真是了不起！再见！$"

MatchCall_BattlePyramidText1::
	.string "喂！{PLAYER}？你好，我是\n"
	.string "{STR_VAR_1}！我听说了\l"
	.string "！\p"
	.string "你在{STR_VAR_2}里登上\n"
	.string "了{STR_VAR_3}层对吧？\p"
	.string "真是厉害啊！我也该试着挑战一下。$"

MatchCall_BattlePyramidText2::
	.string "你好，我是{STR_VAR_1}\n"
	.string "！听说你的消息了！\p"
	.string "他们说你在{STR_VAR_2}\n"
	.string "里一共登上了\l"
	.string "{STR_VAR_3}层？\p"
	.string "真不可思议！我也要去训练我的宝可\n"
	.string "梦了！$"

MatchCall_BattlePyramidText3::
	.string "嘿你好，{PLAYER}！是我，\n"
	.string "{STR_VAR_1}。最近怎么\l"
	.string "样？\p"
	.string "我听说你在{STR_VAR_2}\n"
	.string "里登上了{STR_VAR_3}层\l"
	.string "？\p"
	.string "下次争取做得更好啊！再见！$"

MatchCall_BattlePyramidText4::
	.string "嘿，{PLAYER}{KUN}。\n"
	.string "是我{STR_VAR_1}。\p"
	.string "说你在{STR_VAR_2}里征\n"
	.string "服了{STR_VAR_3}层？\p"
	.string "我也得努力训练才能跟上你的步伐！$"

MatchCall_BattlePyramidText5::
	.string "喂，{PLAYER}{KUN}！\n"
	.string "我是{STR_VAR_1}。\p"
	.string "听说你在{STR_VAR_2}里\n"
	.string "登上了{STR_VAR_3}层？\p"
	.string "我也得加把劲了！再见！$"

MatchCall_BattlePyramidText6::
	.string "喂，{PLAYER}{KUN}？\n"
	.string "是我{STR_VAR_1}。最近\l"
	.string "好吗？\p"
	.string "对了，听说你在\n"
	.string "{STR_VAR_2}里征服了\l"
	.string "{STR_VAR_3}层。\p"
	.string "我也要去训练宝可梦，否则要被你甩\n"
	.string "开了。$"

MatchCall_BattlePyramidText7::
	.string "{PLAYER}{KUN}？是我\n"
	.string "{STR_VAR_1}。\p"
	.string "你在{STR_VAR_2}里征服\n"
	.string "了{STR_VAR_3}层？\p"
	.string "厉害啊！那里有稀有的宝可梦吗？\p"
	.string "哦，没有吗？好的，再见。$"

MatchCall_BattlePyramidText8::
	.string "哦，{PLAYER}{KUN}，\n"
	.string "你好吗？我是\l"
	.string "{STR_VAR_1}。希望你一\l"
	.string "切顺利。噢，看来你确实很顺利啊。\p"
	.string "听说你在{STR_VAR_2}里\n"
	.string "通过了{STR_VAR_3}层？\p"
	.string "真是不得了啊！我也要像你一样培育\n"
	.string "我的宝可梦。再见。$"

MatchCall_BattlePyramidText9::
	.string "哦，{PLAYER}{KUN}，\n"
	.string "你好！我是{STR_VAR_1}\l"
	.string "！\p"
	.string "我听说了！你在\n"
	.string "{STR_VAR_2}里闯过了\l"
	.string "{STR_VAR_3}层！\p"
	.string "太酷了！我也要努力！$"

MatchCall_BattlePyramidText10::
	.string "哦，{PLAYER}{KUN}，\n"
	.string "你好。我是{STR_VAR_1}\l"
	.string "。\p"
	.string "你在{STR_VAR_2}里征服\n"
	.string "了{STR_VAR_3}层？\p"
	.string "真是了不起。我也要加油了。$"

MatchCall_BattlePyramidText11::
	.string "喂，{PLAYER}{KUN}。\n"
	.string "我是{STR_VAR_1}。\p"
	.string "听说你在{STR_VAR_2}所\n"
	.string "向披靡？\p"
	.string "你登上了，多少，\n"
	.string "{STR_VAR_3}层？这真是\l"
	.string "了不起啊。\p"
	.string "不知道我能不能也成为冠军？\p"
	.string "……基本不可能？好，再见！$"

MatchCall_BattlePyramidText12::
	.string "你好，{PLAYER}{KUN}\n"
	.string "。是我，{STR_VAR_1}。\l"
	.string "你还好吗？\p"
	.string "你在{STR_VAR_2}里闯过\n"
	.string "了{STR_VAR_3}层？\p"
	.string "真是个精彩的故事。再见！$"

MatchCall_BattlePyramidText13::
	.string "喂，你好，{PLAYER}\n"
	.string "{KUN}！我是\l"
	.string "{STR_VAR_1}！希望你一\l"
	.string "切都好。\p"
	.string "你在{STR_VAR_2}里征服\n"
	.string "了{STR_VAR_3}层？\p"
	.string "真佩服你的精力！再见了。$"

MatchCall_BattlePyramidText14::
	.string "喂，你好，{PLAYER}\n"
	.string "{KUN}。我是\l"
	.string "{STR_VAR_1}。听说你的\l"
	.string "事了！\p"
	.string "你不是在{STR_VAR_2}里\n"
	.string "征服了{STR_VAR_3}层吗\l"
	.string "？\p"
	.string "你真是我的偶像！再见了！$"

MatchCall_Text_Mom1::
	.string "妈妈：你们父子两个……大家都被宝\n"
	.string "可梦迷住了。\p"
	.string "宝可梦到底有什么魅力呢？\p"
	.string "我吗？我喜欢那些能帮忙做家务的宝\n"
	.string "可梦。$"

MatchCall_Text_Mom2::
	.string "妈妈：嗨，{PLAYER}！你爸\n"
	.string "爸整天把自己关在橙华市道馆里。\p"
	.string "他偶尔也会回家一趟。但是每次他吃\n"
	.string "光所有东西之后，就又立刻回道馆去\l"
	.string "了。\p"
	.string "我猜输给你这件事对他的自尊心是一\n"
	.string "个很大的打击！$"

MatchCall_Text_Mom3::
	.string "妈妈：{PLAYER}……别为我\n"
	.string "和家里担心。\p"
	.string "穿着这双跑步鞋直到它们彻底磨破吧\n"
	.string "！$"

MatchCall_Text_Baoba1::
	.string "BAOBA: {PLAYER}!\n"
	.string "The SAFARI ZONE is nearly ready!\p"
	.string "I'll call you first thing when\n"
	.string "it's finished!$"

MatchCall_Text_Baoba2::
	.string "BAOBA: {PLAYER}!\n"
	.string "The SAFARI ZONE is open! Come\p"
	.string "anytime!$"

MatchCall_Text_Roxanne1::
	.string "ROXANNE: Oh, hello, {PLAYER}!\p"
	.string "I've been hard at work retraining\n"
	.string "since we met.\p"
	.string "I will still need some more time\n"
	.string "before I can reopen the GYM.\p"
	.string "But when I do, please visit my GYM\n"
	.string "for a rematch!$"

MatchCall_Text_Roxanne2::
	.string "ROXANNE: Is this {PLAYER}?\n"
	.string "Congratulations!\l"
	.string "I've been hearing about you!\p"
	.string "As for me, I need some more time\n"
	.string "before I can reopen the GYM.\p"
	.string "But when I do, please visit my GYM\n"
	.string "for a rematch!$"

MatchCall_Text_Roxanne3::
	.string "ROXANNE: {PLAYER}!\n"
	.string "My GYM is ready!\p"
	.string "Please visit RUSTBORO whenever\n"
	.string "you can!$"

MatchCall_Text_Roxanne4::
	.string "ROXANNE: At the RUSTBORO GYM,\n"
	.string "the fact that we battled, {PLAYER},\l"
	.string "is a matter of pride.$"

MatchCall_Text_Brawly1::
	.string "BRAWLY: Hey, there, {PLAYER}{KUN}!\p"
	.string "I learned a lot from the battle we\n"
	.string "had together.\p"
	.string "I intend to do my training over,\n"
	.string "then reopen the GYM.\p"
	.string "It's going to take some time before\n"
	.string "I'm ready to run the GYM again.\p"
	.string "But if I can reopen the GYM,\n"
	.string "I want you to challenge us again.$"

MatchCall_Text_Brawly2::
	.string "BRAWLY: Hey, {PLAYER}{KUN}!\n"
	.string "Congratulations!\p"
	.string "Word about your exploits arrived\n"
	.string "on tidal winds!\p"
	.string "It appears as if I need to work on\n"
	.string "my training some more.\p"
	.string "It's going to take some time before\n"
	.string "I'm ready to run the GYM again.\p"
	.string "But if I can reopen the GYM,\n"
	.string "I want you to challenge us again.$"

MatchCall_Text_Brawly3::
	.string "BRAWLY: Hey, {PLAYER}{KUN}!\n"
	.string "My GYM's ready for action!\p"
	.string "Come back to DEWFORD anytime\n"
	.string "for another challenge!$"

MatchCall_Text_Brawly4::
	.string "BRAWLY: {PLAYER}{KUN}, I don't think\n"
	.string "I'll ever get bored of battling you!$"

MatchCall_Text_Wattson1::
	.string "WATTSON: Oh, it's you!\p"
	.string "After you left, I've been redoing\n"
	.string "my training from scratch.\p"
	.string "I'd say I could use a wee bit more\n"
	.string "time to reopen my GYM.\p"
	.string "You'll have to wait till then!\n"
	.string "Wahahahaha!$"

MatchCall_Text_Wattson2::
	.string "WATTSON: Wahahahaha!\p"
	.string "You've really done it, haven't you?\n"
	.string "I've been getting word about you!\p"
	.string "It seems I need to retrain some\n"
	.string "more still.\p"
	.string "I'd say I could use a wee bit more\n"
	.string "time to reopen my GYM.\p"
	.string "You'll have to wait till then!\n"
	.string "Wahahahaha!$"

MatchCall_Text_Wattson3::
	.string "WATTSON: Oh, it's you!\n"
	.string "My GYM's ready!\p"
	.string "Visit MAUVILLE anytime!\n"
	.string "Wahahahaha!$"

MatchCall_Text_Wattson4::
	.string "WATTSON: Wahahaha!\p"
	.string "A battle with you is always charged\n"
	.string "with shocking power!$"

MatchCall_Text_Flannery1::
	.string "FLANNERY: {PLAYER}…\p"
	.string "When we battled, I learned exactly\n"
	.string "how immature I was.\p"
	.string "But I'm not done yet!\p"
	.string "I'm going to redo my training and\n"
	.string "reopen the GYM.\p"
	.string "When the time comes, {PLAYER},\n"
	.string "please challenge us again.$"

MatchCall_Text_Flannery2::
	.string "FLANNERY: Hello, {PLAYER}?\n"
	.string "Congratulations!\p"
	.string "Word of your success has reached\n"
	.string "us like the heat of a volcano!\p"
	.string "Our training is coming along very\n"
	.string "well here.\p"
	.string "When the GYM's ready, a mark will\n"
	.string "appear beside my name in the\l"
	.string "MATCH CALL list.$"

MatchCall_Text_Flannery3::
	.string "FLANNERY: Oh, {PLAYER}?\n"
	.string "Our GYM's ready!\p"
	.string "Come to LAVARIDGE for a soak\n"
	.string "in the hot spring and a challenge!$"

MatchCall_Text_Flannery4::
	.string "FLANNERY: {PLAYER}…\n"
	.string "I'm positive that you keep getting\l"
	.string "better at training every time.$"

MatchCall_Text_Winona1::
	.string "WINONA: Hello, {PLAYER}!\p"
	.string "Thanks to our battle, I've come\n"
	.string "to understand my weak points!\p"
	.string "When I reopen the GYM, I won't go\n"
	.string "down in defeat again!$"

MatchCall_Text_Winona2::
	.string "WINONA: You've done it, {PLAYER}!\p"
	.string "News about the new CHAMPION\n"
	.string "has reached us in FORTREE!\p"
	.string "But… The next time we battle,\n"
	.string "it's not going to end the same way.$"

MatchCall_Text_Winona3::
	.string "WINONA: Is this {PLAYER}?\n"
	.string "Our GYM is back in operation!\p"
	.string "We're waiting for you in FORTREE!$"

MatchCall_Text_Winona4::
	.string "WINONA: {PLAYER}…\n"
	.string "Though I have lost, my wings will\l"
	.string "never break.\p"
	.string "Yes, in exactly the same way that\n"
	.string "you never lost sight of your dream.$"

MatchCall_Text_TateLiza1::
	.string "TATE: Oh! You're…\n"
	.string "LIZA: {PLAYER}!\p"
	.string "TATE: We're in training again…\n"
	.string "LIZA: So we can reopen our GYM!\p"
	.string "TATE: When our GYM is ready…\n"
	.string "LIZA: When our GYM is ready…\p"
	.string "TATE: A mark'll appear by our name…\n"
	.string "LIZA: On the MATCH CALL list.$"

MatchCall_Text_TateLiza2::
	.string "TATE: {PLAYER}, congratulations!\n"
	.string "LIZA: {PLAYER}, congratulations!\p"
	.string "TATE: The two of us are…\n"
	.string "LIZA: Still in training!\p"
	.string "TATE: We need some more time, but…\n"
	.string "LIZA: When our GYM is ready…\p"
	.string "TATE: A mark'll appear by our name…\n"
	.string "LIZA: On the MATCH CALL list.$"

MatchCall_Text_TateLiza3::
	.string "TATE: {PLAYER}!\n"
	.string "LIZA: {PLAYER}!\p"
	.string "TATE: Our GYM is ready!\n"
	.string "LIZA: Our GYM is ready!\p"
	.string "TATE: Please come visit…\n"
	.string "LIZA: MOSSDEEP anytime!$"

MatchCall_Text_TateLiza4::
	.string "TATE: {PLAYER}, the battle we had…\n"
	.string "LIZA: Is an invaluable experience.\p"
	.string "TATE: It would be nice if…\n"
	.string "LIZA: We could all battle again!$"

MatchCall_Text_Juan1::
	.string "JUAN: Hmm…\n"
	.string "{PLAYER}{KUN}… Was it?\p"
	.string "Our battle together--it brought\n"
	.string "to me memories of when I first\l"
	.string "encountered WALLACE.\p"
	.string "Perhaps you are a genius who may\n"
	.string "yet surpass WALLACE!$"

MatchCall_Text_Juan2::
	.string "JUAN: Fufu… {PLAYER}{KUN}…\n"
	.string "You've finally achieved your goal.\p"
	.string "My eye for appraising talent wasn't\n"
	.string "mistaken…\p"
	.string "I wish for another chance to meet\n"
	.string "you, for you have scaled the peak\l"
	.string "of power and prestige.$"

MatchCall_Text_Juan3::
	.string "JUAN: Hoho… {PLAYER}{KUN}…\p"
	.string "Our SOOTOPOLIS GYM has finally\n"
	.string "reopened.\p"
	.string "If you wish to see me, you are\n"
	.string "welcome to visit anytime.$"

MatchCall_Text_Juan4::
	.string "JUAN: {PLAYER}{KUN}…\p"
	.string "Like the finest music, the battles\n"
	.string "we wage together strike chords\l"
	.string "of inspiration in my heart…\p"
	.string "When I close my eyes, I see visions\n"
	.string "of you soaring with the melody…$"

MatchCall_Text_Sidney::
	.string "花月：哟，{PLAYER}！\p"
	.string "如果你想跟我再战一场，你可以随时\n"
	.string "来宝可梦联盟找我。\p"
	.string "我会等你的！等你来战！$"

MatchCall_Text_Phoebe::
	.string "芙蓉：嗨，{PLAYER}！\p"
	.string "要不要抽空再来这儿看看？\p"
	.string "我想看看你和宝可梦的牵绊是否变得\n"
	.string "更加深厚了。$"

MatchCall_Text_Glacia::
	.string "波妮：您好，{PLAYER}。\p"
	.string "我相信您没有因实力强大而懈怠吧？\p"
	.string "如果想稍稍冷却一下激情，随时欢迎\n"
	.string "来宝可梦联盟……$"

MatchCall_Text_Drake::
	.string "源治：这个声音……\n"
	.string "{PLAYER}，是你吗？听起来\l"
	.string "状态不错……\p"
	.string "听说有个叫对战开拓区的设施，专门\n"
	.string "考验训练家的实力。\p"
	.string "但若追求真正的对战，宝可梦联盟才\n"
	.string "是最佳的选择！\p"
	.string "你说是吧，{PLAYER}？$"

MatchCall_Text_Wallace::
	.string "米可利：哈喽，{PLAYER}\n"
	.string "{KUN}。你见过大吾吗？\p"
	.string "他这个人啊……明明实力无比强大。\p"
	.string "但是他不常与人宝可梦对战，反而总\n"
	.string "是在找稀有的石头。\p"
	.string "是个奇特的人呢。\p"
	.string "我敢保证，他肯定正在某个山洞或者\n"
	.string "峭壁附近挖掘呢。\p"
	.string "不过什么石头才称得上珍稀呢？我能\n"
	.string "想到的也只有陨石了……$"

MatchCall_Text_MayRayquazaCall:
	.string "…… …… ………… …… ……\n"
	.string "嘟嘟！\p"
	.string "小遥：嗨，{PLAYER}\n"
	.string "{KUN}！\p"
	.string "我刚才在暮水镇附近呢。\p"
	.string "我看见一个巨大的绿色宝可梦在高空\n"
	.string "翱翔。\p"
	.string "我……我从没见过这样的东西。\p"
	.string "真好奇它是什么？这是不是个重大发\n"
	.string "现？\p"
	.string "…… …… ………… …… ……\n"
	.string "咔嚓！$"

MatchCall_Text_BrendanRayquazaCall:
	.string "…… …… ………… …… ……\n"
	.string "嘟嘟！\p"
	.string "小悠：嗨，{PLAYER}！我刚\n"
	.string "才在暮水镇附近。\p"
	.string "我看见一个巨大的绿色宝可梦划过了\n"
	.string "天际。\p"
	.string "我从没见过这么震撼的东西……\p"
	.string "要是你也能看到就好了，\n"
	.string "{PLAYER}。\p"
	.string "…… …… ………… …… ……\n"
	.string "咔嚓！$"

MatchCall_Text_May1::
	.string "小遥：嗨，{PLAYER}\n"
	.string "{KUN}！\p"
	.string "哈奇老人从水手的岗位上退休了，但\n"
	.string "是我常常见到他和宠物小皮一起出海\l"
	.string "。\p"
	.string "他果然还热爱着大海呢。$"

MatchCall_Text_May2::
	.string "小遥：嗨，{PLAYER}\n"
	.string "{KUN}！\p"
	.string "你知道有些小城镇，比如橙华市和武\n"
	.string "斗镇都设有道馆？\p"
	.string "而不知道为什么，像凯那市这样的大\n"
	.string "港口反而没有。\p"
	.string "等那里建好道馆之后，我也许去申请\n"
	.string "当个馆主！$"

MatchCall_Text_May3::
	.string "小遥：嗨，{PLAYER}\n"
	.string "{KUN}！\p"
	.string "你还记得叫卡那兹市里那个叫居合劈\n"
	.string "大叔的人吗？他在那里有幢小房子，\l"
	.string "有印象吗？\p"
	.string "我发现他的弟弟住在紫堇市。\p"
	.string "你猜猜看他的外号？\p"
	.string "…… …… ……\n"
	.string "…… …… ……\p"
	.string "是碎岩大叔啦！$"

MatchCall_Text_May4::
	.string "小遥：{PLAYER}{KUN}\n"
	.string "？\p"
	.string "卡绿隧道……这个名字取自它连接的\n"
	.string "卡那兹市和绿茵镇。$"

MatchCall_Text_May5::
	.string "小遥：{PLAYER}{KUN}\n"
	.string "，还好吗？\p"
	.string "我正在111号道路呢。\p"
	.string "我准备在一个老婆婆家里休息一下。\p"
	.string "她就住在沙漠的北边。$"

MatchCall_Text_May6::
	.string "小遥：嗨，{PLAYER}\n"
	.string "{KUN}！\p"
	.string "你知道沙漠里有座幻影之塔吗？\p"
	.string "据说它会像海市蜃楼一样忽隐忽现。\p"
	.string "好想亲眼看看啊！$"

MatchCall_Text_May7::
	.string "小遥：{PLAYER}{KUN}\n"
	.string "，呀呼！我正在119号道路上呢。\p"
	.string "这里有条大河，还经常下雨。\p"
	.string "我都被淋透了！$"

MatchCall_Text_May8::
	.string "小遥：{PLAYER}{KUN}\n"
	.string "，嗨。\p"
	.string "送神山是用来纪念逝去宝可梦的地方\n"
	.string "。\p"
	.string "或许是因为这个，里面有很多幽灵属\n"
	.string "性的宝可梦呢！$"

MatchCall_Text_May9::
	.string "小遥：嗨，{PLAYER}\n"
	.string "{KUN}！\p"
	.string "我本来想去釜炎镇泡一泡温泉。\p"
	.string "但是在凹凸山道上，我碰到一群看着\n"
	.string "不怀好意的家伙。一下子兴致全无！$"

MatchCall_Text_May10::
	.string "小遥：嗨，{PLAYER}\n"
	.string "{KUN}！看到新闻了吗？\p"
	.string "说是楠木馆长在水下勘探中发现了海\n"
	.string "底洞窟呢！$"

MatchCall_Text_May11::
	.string "小遥：嗨，{PLAYER}\n"
	.string "{KUN}！你不觉得这很棒吗？\p"
	.string "就算没有船，你也能用宝可梦的招式\n"
	.string "横渡大海。\p"
	.string "还有更厉害的呢——\p"
	.string "有个宝可梦招式甚至能潜到海底哦！$"

MatchCall_Text_May12::
	.string "小遥：嗨，{PLAYER}\n"
	.string "{KUN}！希望一切顺利！\p"
	.string "你在海上时有没有遇到过被挡住去路\n"
	.string "的情况？\p"
	.string "试试潜到水下深处，沿着海沟前进。\p"
	.string "到达另一边后再浮上来。很简单吧！$"

MatchCall_Text_May13::
	.string "小遥：嗨，{PLAYER}\n"
	.string "{KUN}！\p"
	.string "最近怎么样？还在完成宝可梦图鉴吗\n"
	.string "？\p"
	.string "我听说了超古代宝可梦的传闻。而且\n"
	.string "一共有3只呢！\p"
	.string "要是能亲眼见到哪怕就1只也好啊…\n"
	.string "…$"

MatchCall_Text_May14::
	.string "小遥：{PLAYER}{KUN}\n"
	.string "！我听说了！\p"
	.string "你击败了琉璃市的道馆馆主？\p"
	.string "也就是说，你的目标已经近在咫尺了\n"
	.string "？$"

MatchCall_Text_May15::
	.string "小遥：现在整个丰缘地区没有哪个训\n"
	.string "练家不认识你了，{PLAYER}\l"
	.string "{KUN}！\p"
	.string "当我说和你是朋友时，\n"
	.string "{PLAYER}{KUN}，大家\l"
	.string "都大吃一惊呢！$"

MatchCall_Text_Brendan1::
	.string "小悠：嘿，{PLAYER}！\p"
	.string "哈奇老人从水手的岗位上退休了，但\n"
	.string "是我常常见到他和宠物小皮一起出海\l"
	.string "。\p"
	.string "看来他依然还热爱着大海啊。$"

MatchCall_Text_Brendan2::
	.string "小悠：嘿，{PLAYER}！\p"
	.string "我不明白为什么橙华市和武斗镇这样\n"
	.string "的小镇都有道馆。\p"
	.string "而像凯那市这样的大港口却没有道馆\n"
	.string "。\p"
	.string "等建好道馆之后，我应该去申请当个\n"
	.string "馆主。$"

MatchCall_Text_Brendan3::
	.string "小悠：哟，{PLAYER}！\p"
	.string "还记得那个住在卡那兹市的叫居合劈\n"
	.string "大叔的人吗？在那里有幢小房子的那\l"
	.string "个？\p"
	.string "原来他的弟弟就住在紫堇市。\p"
	.string "猜猜他叫什么？\p"
	.string "…… …… ……\n"
	.string "…… …… ……\p"
	.string "叫碎岩大叔！$"

MatchCall_Text_Brendan4::
	.string "小悠：这声音……是\n"
	.string "{PLAYER}吗？\p"
	.string "卡绿隧道名字的由来是因为它连接了\n"
	.string "卡那兹市和绿茵镇。\p"
	.string "你知道吗？$"

MatchCall_Text_Brendan5::
	.string "小悠：{PLAYER}，最近怎样\n"
	.string "？\p"
	.string "我正在111号道路呢。\p"
	.string "我打算在一个老婆婆家里稍作休息，\n"
	.string "她家就在沙漠的北边。\p"
	.string "你要是路过，也应该来看看她。$"

MatchCall_Text_Brendan6::
	.string "小悠：嘿，{PLAYER}！\p"
	.string "你知道沙漠里的幻影之塔吗？\p"
	.string "据说它像海市蜃楼一样时隐时现。\p"
	.string "真想亲眼看看！$"

MatchCall_Text_Brendan7::
	.string "小悠：谁啊？哦，{PLAYER}\n"
	.string "？你猜怎么着？我正在119号道路\l"
	.string "呢。\p"
	.string "这里有条大河，而且天天下雨。\p"
	.string "我都被彻底淋透了！$"

MatchCall_Text_Brendan8::
	.string "小悠：{PLAYER}！\p"
	.string "送神山是纪念逝去的宝可梦的地方。\p"
	.string "说不定正是因为这样，里面才有很多\n"
	.string "幽灵属性宝可梦出没！$"

MatchCall_Text_Brendan9::
	.string "小悠：你好，{PLAYER}。\p"
	.string "我本来想去釜炎镇泡温泉的。\p"
	.string "但是在凹凸山道，我撞上了一帮不怀\n"
	.string "好意的家伙。\p"
	.string "这群家伙……我想他们是熔岩队。$"

MatchCall_Text_Brendan10::
	.string "小悠：嗨，{PLAYER}！看新\n"
	.string "闻了吗？\p"
	.string "听说楠木馆长在水下勘探中发现了海\n"
	.string "底洞窟。$"

MatchCall_Text_Brendan11::
	.string "小悠：你好，{PLAYER}！不\n"
	.string "觉得这很棒吗？\p"
	.string "即使没有船，你也能利用宝可梦招式\n"
	.string "来渡过大海。\p"
	.string "有种宝可梦招式甚至还能让你潜入海\n"
	.string "底呢。\p"
	.string "宝可真是梦无所不能啊！$"

MatchCall_Text_Brendan12::
	.string "小悠：嗨，{PLAYER}！最近\n"
	.string "还好吗？\p"
	.string "在海上有遇到过被挡住去路的情况吗\n"
	.string "？\p"
	.string "试试看潜到水下深处，沿着海底的沟\n"
	.string "壑前进。\p"
	.string "到达另一边后，再浮上水面。简单吧\n"
	.string "！$"

MatchCall_Text_Brendan13::
	.string "小悠：你好啊，{PLAYER}！\p"
	.string "最近怎么样？还在完成宝可梦图鉴吗\n"
	.string "？\p"
	.string "我听说有关于超古代、n宝可梦的传\n"
	.string "闻。而且不止1只——是3只！\p"
	.string "我好想捕获哪怕1只……$"

MatchCall_Text_Brendan14::
	.string "小悠：{PLAYER}！我听说了\n"
	.string "！\p"
	.string "你打倒了琉璃市道馆的馆主？真厉害\n"
	.string "！\p"
	.string "只有一步之遥了！$"

MatchCall_Text_Brendan15::
	.string "小悠：现在整个丰缘地区没有训练家\n"
	.string "不认识你了，{PLAYER}！\p"
	.string "我和大家说你是我的朋友时，\n"
	.string "{PLAYER}，他们都羡慕坏了\l"
	.string "！$"

MatchCall_Text_Wally1::
	.string "满充：哦，{PLAYER}！\p"
	.string "我变得更健康了，体能也在变好。\p"
	.string "我希望能早日成为你这样的训练家，\n"
	.string "{PLAYER}！$"

MatchCall_Text_Wally2::
	.string "满充：{PLAYER}，你好！\p"
	.string "自从卡绿隧道打通之后，满盈姐开心\n"
	.string "多了！$"

MatchCall_Text_Wally3::
	.string "满充：哦，{PLAYER}！\p"
	.string "我没告诉任何人就离开了绿茵镇的叔\n"
	.string "叔家。\p"
	.string "不知道他会不会很生气呢……\p"
	.string "{PLAYER}，你能理解我的心\n"
	.string "情吧？$"

MatchCall_Text_Wally4::
	.string "满充：{PLAYER}？是我呀，\n"
	.string "满充！\p"
	.string "训练家的世界太棒了！\p"
	.string "当我带着宝可梦旅行时，会有各种人\n"
	.string "向我打招呼！\p"
	.string "好像大家都被宝可梦联系在一起了！$"

MatchCall_Text_Wally5::
	.string "满充：{PLAYER}？太不可思\n"
	.string "议了！还记得我们一起捕捉的拉鲁拉\l"
	.string "丝吗？它进化了，{PLAYER}\l"
	.string "！\p"
	.string "我或许有些天赋……\p"
	.string "啊，我不该得意忘形！\p"
	.string "毕竟被称赞的应该是宝可梦才对！$"

MatchCall_Text_Wally6::
	.string "…… …… ……\n"
	.string "…… …… ……\p"
	.string "满充似乎不在宝可导航的服务区内…\n"
	.string "…$"

MatchCall_Text_Wally7::
	.string "满充：哦，{PLAYER}！\p"
	.string "在遇见你之前，我几乎从不出门……\p"
	.string "但现在，我正在和自己的宝可梦一起\n"
	.string "冒险呢……\p"
	.string "{PLAYER}……谢谢你……$"

MatchCall_Text_Scott1::
	.string "亚希达：嗨，{PLAYER}\n"
	.string "{KUN}！\p"
	.string "你知道宝可梦无处不在吗？\p"
	.string "在山里，海里，在草丛里？\p"
	.string "像宝可梦一样，训练家也是满地都是\n"
	.string "。\p"
	.string "我也只好到处奔波了。忙得很啊！$"

MatchCall_Text_Scott2::
	.string "亚希达：我正在119号道路上呢。\n"
	.string "这里到处都是训练家！\p"
	.string "这里也到处都是草丛，长得特别茂密\n"
	.string "。\p"
	.string "穿短裤在这里走，草挠得腿好痒啊！$"

MatchCall_Text_Scott3::
	.string "亚希达：嗨，嗨，{PLAYER}\n"
	.string "{KUN}！\p"
	.string "你有没有登上过送神山？\p"
	.string "那是为了纪念逝去的宝可梦的地方。\p"
	.string "每个训练家都至少应该登上去一次。$"

MatchCall_Text_Scott4::
	.string "SCOTT: Hi, {PLAYER}{KUN}!\p"
	.string "I've been hearing about these odd\n"
	.string "gangs being a nuisance.\p"
	.string "TEAM MAGMA and TEAM AQUA,\n"
	.string "I think they were.\p"
	.string "I would think there'd be some\n"
	.string "skilled TRAINERS among them.\p"
	.string "…But if they're thugs…$"

MatchCall_Text_Scott5::
	.string "亚希达：哦，嗨，{PLAYER}\n"
	.string "{KUN}。\p"
	.string "在海底可能会有强大的训练家吗？\p"
	.string "我不能亲自一探究竟。首先我不会游\n"
	.string "泳。再说我也不培育宝可梦啊……$"

MatchCall_Text_Scott6::
	.string "SCOTT: Hi, hi, {PLAYER}{KUN}!\p"
	.string "You know that you can challenge\n"
	.string "the POKéMON LEAGUE when you've\l"
	.string "collected all the GYM BADGES?\p"
	.string "With your talent, becoming the\n"
	.string "CHAMPION isn't a pipe dream.\p"
	.string "But did you know?\n"
	.string "There's somewhere even better.\p"
	.string "But, that's all I'm willing to say\n"
	.string "for the time being.\p"
	.string "It's something you can look\n"
	.string "forward to.\p"
	.string "When you've won your way through\n"
	.string "the POKéMON LEAGUE into the HALL\l"
	.string "OF FAME!$"

MatchCall_Text_Scott7::
	.string "…… …… ……\n"
	.string "…… …… ……\p"
	.string "亚希达似乎不在宝可导航的服务区内\n"
	.string "……$"

MatchCall_Text_Norman1::
	.string "爸爸：在卡那兹市，有一个被称作“\n"
	.string "居合劈大叔”的人。\p"
	.string "如果你在那一带，应该去拜访一下。$"

MatchCall_Text_Norman2::
	.string "爸爸：嗯……尽管不知不觉，但毫无\n"
	.string "疑问你成长得越来越强大了，\l"
	.string "{PLAYER}。\p"
	.string "而越长大，你也就会飞得离我和你妈\n"
	.string "妈越远……\p"
	.string "这种心情真是难以言表。$"

MatchCall_Text_Norman3::
	.string "爸爸：知道了……你已经收集了4个\n"
	.string "道馆徽章……\p"
	.string "看起来是时候兑现之前我们的对战约\n"
	.string "定了。\p"
	.string "随时来吧！我们都会一直等你！$"

MatchCall_Text_Norman4::
	.string "爸爸：{PLAYER}！常回去看\n"
	.string "看妈妈。\p"
	.string "我会留在这里再继续加倍训练。\p"
	.string "战斗之道，深邃而无情！$"

MatchCall_Text_Norman5::
	.string "爸爸：哦，{PLAYER}！\p"
	.string "什么？熔岩标志？我不清楚那是什么\n"
	.string "。\p"
	.string "但是从名字来看，可能和火山有关！$"

MatchCall_Text_Norman6::
	.string "DAD: Hiyah! Haah! Dwah!\p"
	.string "…Oh? {PLAYER}!\p"
	.string "You caught me right in the middle\n"
	.string "of a POKéMON training session!$"

MatchCall_Text_Norman7::
	.string "DAD: {PLAYER}!\p"
	.string "Who would've thought you'd become\n"
	.string "the POKéMON LEAGUE CHAMPION…\p"
	.string "Okay!\n"
	.string "I won't be left behind!$"

MatchCall_Text_Norman8::
	.string "DAD: Hm? {PLAYER}?\n"
	.string "What good timing!\p"
	.string "This time, I'm going to challenge\n"
	.string "you to battle.\p"
	.string "I'm waiting in the PETALBURG GYM.\n"
	.string "Accept my challenge anytime!$"

MatchCall_Text_Norman9::
	.string "DAD: …You amaze me, {PLAYER}.\n"
	.string "How much higher will you soar?$"

MatchCall_Text_Steven1::
	.string "大吾：嗨，{PLAYER}\n"
	.string "{KUN}！\p"
	.string "你去过紫堇市了吗？\p"
	.string "记得去自行车商店弄一辆音速自行车\n"
	.string "。\p"
	.string "然后去彻底探索一下石之洞窟吧。\p"
	.string "你在那里会有新发现的。$"

MatchCall_Text_Steven2::
	.string "大吾：嗨，{PLAYER}\n"
	.string "{KUN}！\p"
	.string "至今为止我遇到过各种各样的训练家\n"
	.string "。\p"
	.string "但你是独一无二的。$"

MatchCall_Text_Steven3::
	.string "大吾：嗨，{PLAYER}\n"
	.string "{KUN}！\p"
	.string "和宝可梦一起冒险时，你在想些什么\n"
	.string "呢？\p"
	.string "会把它们看作强大的伙伴吗？\p"
	.string "还是会看作有趣的旅伴呢？\p"
	.string "你不同的想法，会让旅途变得截然不\n"
	.string "同。$"

MatchCall_Text_Steven4::
	.string "大吾：喂？{PLAYER}\n"
	.string "{KUN}？\p"
	.string "我在宇宙中心里遇到点麻烦。\p"
	.string "抱歉现在不方便说话，再见！$"

MatchCall_Text_Steven5::
	.string "大吾：啊！{PLAYER}\n"
	.string "{KUN}！\p"
	.string "事已至此，无需多言了。\p"
	.string "相信自己，做正确的事吧。$"

MatchCall_Text_Steven6::
	.string "…… …… ……\p"
	.string "大吾似乎没有接电话……$"

MatchCall_Text_Steven7::
	.string "大吾：{PLAYER}{KUN}\n"
	.string "……恭喜你登入名人堂。\p"
	.string "…… …… ……\n"
	.string "…… …… ……\p"
	.string "希望我们后会有期！$"

MatchCall_Text_BirchRegisterCall:
	.string "小田卷博士：哦，{PLAYER}\n"
	.string "{KUN}！我已经听说了！\p"
	.string "你的宝可导航已经升级了对战寻呼功\n"
	.string "能对吧？\p"
	.string "我也来登记一下！\p"
	.string "这样你在外面时我也可以检查你的宝\n"
	.string "可梦图鉴进度了！\p"
	.string "…… …… ……$"

MatchCall_Text_RegisteredBirch:
	.string "将小田卷博士的信息登录进宝可导航\n"
	.string "。$"

MatchCall_Text_UnusedProfBirch:
	.string "小田卷博士：同时拥有宝可梦图鉴和\n"
	.string "宝可导航的话，研究宝可梦会更有趣\l"
	.string "吧？$"

MatchCall_Text_MrStone1::
	.string "兹伏奇：哦？{PLAYER}\n"
	.string "{KUN}！\p"
	.string "既然你给我打电话，那说明宝可导航\n"
	.string "正常工作！\p"
	.string "其他人的信息也可以登录，试着联系\n"
	.string "他们吧！\p"
	.string "好！好！你看上去很开心嘛！\p"
	.string "嗯……我是怎么知道的？\p"
	.string "因为我正从办公室的窗户里往外看着\n"
	.string "你呢！\p"
	.string "哇哈哈哈！回头见！$"

MatchCall_Text_MrStone2::
	.string "兹伏奇：哦？{PLAYER}\n"
	.string "{KUN}！\p"
	.string "怎么了？难道忘记我拜托你的事了吗\n"
	.string "？\p"
	.string "我想请你帮我送信给武斗镇的大吾那\n"
	.string "里。\p"
	.string "之后再把那个包裹送给凯那市的楠木\n"
	.string "馆长。\p"
	.string "还记得吧？\p"
	.string "身为忙碌的社长，我得先挂了！再见\n"
	.string "！$"

MatchCall_Text_MrStone3::
	.string "兹伏奇：哦！{PLAYER}\n"
	.string "{KUN}！\p"
	.string "你已经见过大吾了吧！我得给你报酬\n"
	.string "才行！\p"
	.string "等你下次再来卡那兹市时，记得来我\n"
	.string "的办公室找我。\p"
	.string "我等着你！$"

MatchCall_Text_MrStone4::
	.string "兹伏奇：哦！{PLAYER}\n"
	.string "{KUN}！\p"
	.string "你知道得文正在挖掘卡绿隧道的事吗\n"
	.string "？\p"
	.string "但为了保护那里的宝可梦，我们停止\n"
	.string "了工程。\p"
	.string "这是理所当然的。\p"
	.string "比起人类的便利，宝可梦能安稳地生\n"
	.string "活更为重要。$"

MatchCall_Text_MrStone5::
	.string "兹伏奇：你好，{PLAYER}\n"
	.string "{KUN}！\p"
	.string "我听从橙华市来的人说你是千里的孩\n"
	.string "子！\p"
	.string "果然是虎父无犬子！$"

MatchCall_Text_MrStone6::
	.string "兹伏奇：什么？\p"
	.string "你和自己的父亲对战并获得了胜利？\p"
	.string "太了不起了！\p"
	.string "我从没想到能交到像你这样特别的朋\n"
	.string "友！哇哈哈！$"

MatchCall_Text_MrStone7::
	.string "您好！这里是得文公司……哦，你好\n"
	.string "，{PLAYER}！\p"
	.string "我们社长刚刚还在这里，但是现在外\n"
	.string "出了。\p"
	.string "我们社长是很忙的，不过你好像也一\n"
	.string "样忙啊，{PLAYER}。$"

MatchCall_Text_MrStone8::
	.string "……啊？……什么？\p"
	.string "固拉……什么？……多？\p"
	.string "断断续续的…………听不清……\p"
	.string "沙沙沙……$"

MatchCall_Text_MrStone9::
	.string "……啊？……怎么了？\p"
	.string "海底……是吗？……洞窟……？\p"
	.string "怎么断断续续的…………听不见……\p"
	.string "嘶嘶嘶嘶……$"

MatchCall_Text_MrStone10::
	.string "兹伏奇：{PLAYER}\n"
	.string "{KUN}！是我！\p"
	.string "听说你经历了许多事，但我太忙了，\n"
	.string "很多详情都不清楚！\p"
	.string "无论如何，我希望你坚持自己相信的\n"
	.string "道路。\p"
	.string "我会永远支持你！保重！$"

MatchCall_Text_MrStone11::
	.string "兹伏奇：…… …… ……是\n"
	.string "{PLAYER}{KUN}吗？\p"
	.string "你的声音充满了自信，我一时都没听\n"
	.string "出来！\p"
	.string "嗯！有空一定要再来得文做客啊！$"
