@ Only contains the text for the Mauville Man named Giddy. The rest is in scripts/mauville_man.inc
GiddyText_SoPretty::
	.string " 非常漂亮！$"

GiddyText_SoDarling::
	.string " 太迷人了！$"

GiddyText_SoRelaxed::
	.string " 太悠闲了！$"

GiddyText_SoSunny::
	.string " 太愉快了！$"

GiddyText_SoDesirable::
	.string " 太合意的了！$"

GiddyText_SoExciting::
	.string " 太令人激动！$"

GiddyText_SoAmusing::
	.string " 太有意思了！$"

GiddyText_SoMagical::
	.string " 太不可思议！$"

GiddyText_Is::
	.string " 是$"

GiddyText_DontYouAgree::
	.string "你同意吗？$"

GiddyText_ISoWantToGoOnAVacation::
	.string "我很想去旅行。你知道什么好去处\n"
	.string "吗？$"

GiddyText_IBoughtCrayonsWith120Colors::
	.string "我买了一套120色的蜡笔！你不觉得\n"
	.string "很棒吗？$"

GiddyText_WouldntItBeNiceIfWeCouldFloat::
	.string "你不觉得，漂浮在一片泡泡云上很舒\n"
	.string "服吗？$"

GiddyText_WhenYouWriteOnASandyBeach::
	.string "你在沙滩上写好字，不久就会被冲掉\n"
	.string "的。真扫兴。$"

GiddyText_WhatsTheBottomOfTheSeaLike::
	.string "海底是个什么样子？我真想去一次，\n"
	.string "一次就好！$"

GiddyText_WhenYouSeeTheSettingSunDoesIt::
	.string "当你看到夕阳的时候，是不是会想回\n"
	.string "家？$"

GiddyText_LyingBackInTheGreenGrass::
	.string "往草地上这么一躺……哦，太，太棒\n"
	.string "了！$"

GiddyText_SecretBasesAreSoWonderful::
	.string "秘密基地真是太棒了！你不觉得刺激\n"
	.string "吗？$"
