MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
	.string "这个招式只能教你1次，这样可以吗\n"
	.string "？$"

MoveTutor_Text_SwaggerTeach:
	.string "嗨！看我的宝可梦多完美！它比所有\n"
	.string "其它宝可梦都酷！\p"
	.string "我总是像这样虚张声势，结果被会长\n"
	.string "训了一顿。\p"
	.string "现在我没法虚张声势了。\p"
	.string "如果你愿意，我会教你的1只宝可梦\n"
	.string "学习虚张声势。$"

MoveTutor_Text_SwaggerDeclined:
	.string "什么？不行？你就不能配合一下？$"

MoveTutor_Text_SwaggerWhichMon:
	.string "很好，想让哪只宝可梦学习虚张声势\n"
	.string "？$"

MoveTutor_Text_SwaggerTaught:
	.string "我今后不会再虚张声势地培育我的宝\n"
	.string "可梦了。$"

MoveTutor_Text_RolloutTeach:
	.string "你知道怎样从这儿朝着一个方向不变\n"
	.string "地走出去很远吗？\p"
	.string "我说不定可以滚动着走完这段路呢。\p"
	.string "你觉得你的宝可梦也很想滚动，对吗\n"
	.string "？\p"
	.string "如果你想学滚动我可以教你。$"

MoveTutor_Text_RolloutDeclined:
	.string "你不要害羞嘛。让我们滚起来！$"

MoveTutor_Text_RolloutWhichMon:
	.string "哦呵呵，当然！你的宝可梦变得像我\n"
	.string "一样就好了。$"

MoveTutor_Text_RolloutTaught:
	.string "在草里打滚使我非常快乐。来吧，让\n"
	.string "我们滚起来！$"

MoveTutor_Text_FuryCutterTeach:
	.string "这是一个你连续使用就会变得更强大\n"
	.string "的招式。\p"
	.string "这是一个虫属性的招式，并且是很酷\n"
	.string "的招式。\p"
	.string "这个招式叫做连斩。想让我教你的宝\n"
	.string "可梦吗？$"

MoveTutor_Text_FuryCutterDeclined:
	.string "我们合不来。$"

MoveTutor_Text_FuryCutterWhichMon:
	.string "耶！把要学习的宝可梦交给我。$"

MoveTutor_Text_FuryCutterTaught:
	.string "当我连续击中对手时就会觉得很兴奋\n"
	.string "！$"

MoveTutor_MimicTeach:
	.string "啊，孩子！\p"
	.string "我也是个小孩子，但我在这个模仿这\n"
	.string "个镇子里的大人们的言谈举止。\p"
	.string "你说什么，小朋友？如果我能教你模\n"
	.string "仿你就能承认我？$"

MoveTutor_MimicDeclined:
	.string "嘘！我要让你的宝可梦学会模仿！$"

MoveTutor_Text_MimicWhichMon:
	.string "噗噗！我当然能！让我看看你想要学\n"
	.string "会招式的宝可梦。$"

MoveTutor_Text_MimicTaught:
	.string "模仿是个伟大而深奥的招式。\p"
	.string "你能像我一样运用自如吗……？$"

MoveTutor_Text_MetronomeTeach:
	.string "我什么东西都想要！但是我把钱都花\n"
	.string "光了……\p"
	.string "如果要是有个能够让你一挥指就会出\n"
	.string "现钱的魔法岂不美哉？\p"
	.string "如果你想，我能让你的宝可梦学会挥\n"
	.string "指。\p"
	.string "钱不会出现，但你的宝可梦将会摇动\n"
	.string "手指。好吗？$"

MoveTutor_Text_MetronomeDeclined:
	.string "好的。等你改变主意了再来找我。$"

MoveTutor_Text_MetronomeWhichMon:
	.string "好的！我来教你！想让哪只宝可梦学\n"
	.string "习？$"

MoveTutor_Text_MetronomeTaught:
	.string "当宝可梦使用挥指时，各种各样的好\n"
	.string "事情都会发生。\p"
	.string "我们使用它不是也很棒吗？$"

MoveTutor_Text_SleepTalkTeach:
	.string "嗯！我老伴依靠觉醒力量来保持清醒\n"
	.string "。\p"
	.string "她明明可以像我一样打个盹，然后说\n"
	.string "梦话的。\p"
	.string "我能让你的宝可梦学会梦话。有兴趣\n"
	.string "吗？$"

MoveTutor_Text_SleepTalkDeclined:
	.string "哦，好吧……你也想用觉醒力量来保\n"
	.string "持清醒……$"

MoveTutor_Text_SleepTalkWhichMon:
	.string "啊，多有眼光的孩子呀！你想让我教\n"
	.string "哪只宝可梦？$"

MoveTutor_Text_SleepTalkTaught:
	.string "我从来都猜不对我老伴的硬币把戏。\p"
	.string "要是我能在梦话里说中了感觉也挺不\n"
	.string "错的。$"

MoveTutor_Text_SubstituteTeach:
	.string "当我在屋顶上看着这广阔的世界时…\n"
	.string "…\p"
	.string "我在想如果这个世界如果有不止一个\n"
	.string "自己该多有趣啊，那样我就能体验各\l"
	.string "种各样的人生了。\p"
	.string "当然这是不可能的。嘿嘿……\p"
	.string "明白了！不如让你的宝可梦学习替身\n"
	.string "吧？$"

MoveTutor_Text_SubstituteDeclined:
	.string "噢，不？\p"
	.string "宝可梦可是能用这个招式再复制出一\n"
	.string "个自己的。$"

MoveTutor_Text_SubstituteWhichMon:
	.string "嘿嘿……你想让哪只宝可梦学会替身\n"
	.string "？$"

MoveTutor_Text_SubstituteTaught:
	.string "我们人类更应该尽情享受我们自己的\n"
	.string "人生！\p"
	.string "我希望你能够如此！$"

MoveTutor_Text_DynamicPunchTeach:
	.string "我没办法继续！\p"
	.string "这一点用也没有！\p"
	.string "我是一名格斗属性训练家，所以无论\n"
	.string "我怎么努力尝试也不能在绿岭市道馆\l"
	.string "获胜！\p"
	.string "啊啊啊啊！打！打！打！打！打！打\n"
	.string "！\p"
	.string "什么，别那样看我！我只是在打地面\n"
	.string "！\p"
	.string "还是说你想让我教你的宝可梦学习爆\n"
	.string "裂拳？$"

MoveTutor_Text_DynamicPunchDeclined:
	.string "可恶！你也来取笑我吗？打！打！打\n"
	.string "！$"

MoveTutor_Text_DynamicPunchWhichMon:
	.string "什么？你想学？你真是个好人啊！想\n"
	.string "要我教哪只宝可梦？$"

MoveTutor_Text_DynamicPunchTaught:
	.string "我希望你能用爆裂拳在绿岭市道馆获\n"
	.string "胜！$"

MoveTutor_Text_DoubleEdgeTeach:
	.string "唉……\p"
	.string "琉璃市道馆馆主可真是太让人敬爱不\n"
	.string "已了。\p"
	.string "但这也意味着会有很多同样被他吸引\n"
	.string "的人做我的竞争对手。\p"
	.string "他的魅力就像舍身冲撞一样有利有弊\n"
	.string "。他根本都注意不到我。\p"
	.string "那么，让我教你的宝可梦学习舍身冲\n"
	.string "撞！$"

MoveTutor_Text_DoubleEdgeDeclined:
	.string "噢……连你都拒绝我……$"

MoveTutor_Text_DoubleEdgeWhichMon:
	.string "好的，你希望哪只宝可梦能学会舍身\n"
	.string "冲撞？$"

MoveTutor_Text_DoubleEdgeTaught:
	.string "我不再为爱而活着！我要更加坚强！$"

MoveTutor_Text_ExplosionTeach:
	.string "我可没打算一直呆在这乡下一事无成\n"
	.string "。\p"
	.string "等着瞧吧，总有一天我会闯进大城市\n"
	.string "成为大明星。\p"
	.string "说真的，我绝对会引发一场流行大爆\n"
	.string "炸！\p"
	.string "既然你听到了，我就破例教你的宝可\n"
	.string "梦学会大爆炸吧！$"

MoveTutor_Text_ExplosionDeclined:
	.string "怎么？你拒绝我是因为我住在乡下？$"

MoveTutor_Text_ExplosionWhichMon:
	.string "好的！这就是大爆炸！哪只宝可梦要\n"
	.string "学？$"

MoveTutor_Text_ExplosionTaught:
	.string "长时间以来，我一直在教宝可梦如何\n"
	.string "使用大爆炸，但是我自己还没能引发\l"
	.string "大爆炸……\p"
	.string "也许内心深处，我更想留在这儿……$"

MoveTutor_Text_HeadbuttTeach:
	.string "What am I doing?\p"
	.string "I'm shaking trees using HEADBUTT.\p"
	.string "Do you think your POKéMON will\n"
	.string "want to HEADBUTT, too?\p"
	.string "I can teach one the move HEADBUTT\n"
	.string "if you'd like. It's fun!$"
	
MoveTutor_Text_HeadbuttWhichMon:
	.string "嘿嘿，好嘞！要是那只宝可梦长得像\n"
	.string "我那就更棒了。$"

MoveTutor_Text_HeadbuttDeclined:
	.string "不用那么害羞嘛。一起来用头撞吧！$"

MoveTutor_Text_HeadbuttTaught:
	.string "用头锤摇晃树木吧。有时候睡着的宝\n"
	.string "可梦会掉下来哦。$"
