MoveRelearner_Text_WouldLearnNewMoves:
	.string "你好，我是招式回忆狂。想让宝可梦\n"
	.string "回忆起招式吗？$"

MoveRelearner_Text_LevelUpMoves:
	.string "升级招式$"

MoveRelearner_Text_EggMoves:
	.string "蛋招式$"

MoveRelearner_Text_TMMoves:
	.string "学习器招式$"

MoveRelearner_Text_TutormoveMoves:
	.string "教授招式$"

MoveRelearner_Text_SeeYa:
	.string "再见！$"

MoveRelearner_Text_AnythingElse:
	.string "还有其他要做的事吗？$"

MoveRelearner_Text_ChoosePkmn:
	.string "要选择哪只宝可梦？$"

MoveRelearner_Text_HaveNoPkmn:
	.string "你没有同行的宝可梦！$"

MoveRelearner_Text_CantTeachMoveToEgg:
	.string "抱歉……但是蛋是没法学会招式的。$"

MoveRelearner_Text_CantTeachMoveToPkmn:
	.string "抱歉……\p"
	.string "我看来没有能够教给这只宝可梦的招\n"
	.string "式。$"

MoveRelearner_Text_LevelUpMoveLWR::
	.string "升级招式$"

MoveRelearner_Text_EggMoveLWR::
	.string "蛋招式$"

MoveRelearner_Text_TMMoveLWR::
	.string "学习器招式$"

MoveRelearner_Text_TutorMoveLWR::
	.string "教授招式$"

MoveRelearner_Text_MoveLWR::
	.string "招式$"

MoveRelearner_Text_WhichXmoveShouldTeach:
	.string "要学习哪个\n"
	.string "{STR_VAR_3}？$"

MoveRelearner_Text_ThankYouComeAgain:
	.string "想让宝可梦学习招式时再过来吧。$"
