gOtherText_NewName::
	.string "输入名字$"

gNameChoice_Green::
	.string "青绿$"

gNameChoice_Red::
	.string "赤红$"

gNameChoice_Leaf::
	.string "叶子$"

gNameChoice_Fire::
	.string "火红$"

gNameChoice_Gary::
	.string "小茂$"

gNameChoice_Kaz::
	.string "阿和$"

gNameChoice_Toru::
	.string "阿彻$"

gNameChoice_Ash::
	.string "小智$"

gNameChoice_Kene::
	.string "阿健$"

gNameChoice_Geki::
	.string "阿激$"

gNameChoice_Jak::
	.string "杰克$"

gNameChoice_Janne::
	.string "珍妮$"

gNameChoice_Jonn::
	.string "约翰$"

gNameChoice_Kamon::
	.string "卡蒙$"

gNameChoice_Karl::
	.string "卡尔$"

gNameChoice_Taylor::
	.string "泰勒$"

gNameChoice_Oscar::
	.string "奥斯卡$"

gNameChoice_Hiro::
	.string "广$"

gNameChoice_Max::
	.string "麦克斯$"

gNameChoice_Jon::
	.string "乔恩$"

gNameChoice_Ralph::
	.string "拉尔夫$"

gNameChoice_Kay::
	.string "凯$"

gNameChoice_Tosh::
	.string "托什$"

gNameChoice_Roak::
	.string "罗克$"

gNameChoice_Omi::
	.string "奥米$"

gNameChoice_Jodi::
	.string "乔迪$"

gNameChoice_Amanda::
	.string "阿曼达$"

gNameChoice_Hillary::
	.string "希拉里$"

gNameChoice_Makey::
	.string "麦基$"

gNameChoice_Michi::
	.string "美智$"

gNameChoice_Paula::
	.string "宝拉$"

gNameChoice_June::
	.string "琼$"

gNameChoice_Cassie::
	.string "凯茜$"

gNameChoice_Rey::
	.string "雷$"

gNameChoice_Seda::
	.string "塞达$"

gNameChoice_Kiko::
	.string "纪子$"

gNameChoice_Mina::
	.string "米娜$"

gNameChoice_Norie::
	.string "典枝$"

gNameChoice_Sai::
	.string "彩衣$"

gNameChoice_Momo::
	.string "小桃$"

gNameChoice_Suzi::
	.string "苏茜$"

gControlsGuide_Text_Intro::
	.string "接下来将按照重要程度依次说明各个\n"
	.string "按键的功能。$"

gControlsGuide_Text_DPad::
	.string "用于控制主角移动。也可以用来选择\n"
	.string "各项数据与菜单选项。$"

gControlsGuide_Text_AButton::
	.string "用于确认选择、调查物品、对话以及\n"
	.string "翻页文本。$"

gControlsGuide_Text_BButton::
	.string "用于退出、取消选择以及取消当前模\n"
	.string "式。$"

gControlsGuide_Text_StartButton::
	.string "按下此键可以打开菜单。$"

gControlsGuide_Text_SelectButton::
	.string "用于调换道具位置，以及使用登记的\n"
	.string "快捷道具。$"

gControlsGuide_Text_LRButtons::
	.string "在游戏中遇到疑问，或想了解操作方\n"
	.string "法时，请按下L键或R键。$"

gOakSpeech_Text_AskPlayerGender::
	.string "那么告诉我。你是男孩子？还是女孩\n"
	.string "子呢？$"

gPikachuIntro_Text_Page1::
	.string "在你即将踏入的这个世界里，你将作\n"
	.string "为主角展开一场宏大的冒险。不论是\l"
	.string "在城镇、道路还是洞穴，多去和人交\l"
	.string "谈，调查周围的事物吧。从各处收集\l"
	.string "有用的情报和线索。$"

gPikachuIntro_Text_Page2::
	.string "通过帮助遇到困难的人、克服难关，\n"
	.string "以及解开重重谜团，新的道路将为你\l"
	.string "敞开。有时你会被他人发起挑战，也\l"
	.string "会遭到野生宝可梦的袭击。拿出勇\l"
	.string "气，勇往直前吧！$"

gPikachuIntro_Text_Page3::
	.string "我们希望你在冒险的过程中，能与各\n"
	.string "种各样的人交流并获得成长。这就是\l"
	.string "我们最大的心愿。按下A键，开启你\l"
	.string "的冒险之旅吧！$"

gOakSpeech_Text_WelcomeToTheWorld::
	.string "初次见面！很高兴见到你！\p"
	.string "欢迎来到宝可梦的世界！\p"
	.string "我叫大木。\p"
	.string "大家都亲切地称呼我为宝可梦博士。\p"
	.string "$"

gOakSpeech_Text_ThisWorld::
	.string "在这个世界上......$"

gOakSpeech_Text_IsInhabitedFarAndWide::
	.string "......到处都栖息着名为“宝可梦”的\n"
	.string "生物。\p"
	.string "$"

gOakSpeech_Text_IStudyPokemon::
	.string "有人把宝可梦当作宠物，也有人让他\n"
	.string "们来进行对战。\p"
	.string "至于我嘛......\p"
	.string "则是把研究宝可梦作为毕生的事业。\p"
	.string "$"

gOakSpeech_Text_TellMeALittleAboutYourself::
	.string "不过在此之前，先来跟我说说你自己\n"
	.string "的事吧。\p"
	.string "$"

gOakSpeech_Text_YourNameWhatIsIt::
	.string "首先是你的名字，你叫什么名字呢？\p"
	.string "$"

gOakSpeech_Text_SoYourNameIsPlayer::
	.string "好的......原来你叫\n"
	.string "{PLAYER}啊。$"

gOakSpeech_Text_WhatWasHisName::
	.string "这是我的孙子。\p"
	.string "从你们还是婴儿的时候起，他就一直\n"
	.string "是你的劲敌。\p"
	.string "......呃，他叫什么名字来着"
	.string "？$"

gOakSpeech_Text_YourRivalsNameWhatWasIt::
	.string "你的劲敌叫什么名字来着？$"

gOakSpeech_Text_ConfirmRivalName::
	.string "......呃，是叫{RIVAL}吗？$"

gOakSpeech_Text_RememberRivalsName::
	.string "对啦！我想起来了！他的名字叫\n"
	.string "{RIVAL}！\p"
	.string "$"

gOakSpeech_Text_LetsGo::
	.string "{PLAYER}！\p"
	.string "属于你自己的宝可梦传奇即将拉开序\n"
	.string "幕！\p"
	.string "与宝可梦相伴、充满梦想与冒险的世\n"
	.string "界正在等待着你！出发吧！$"
