gText_Oak_Welcome::
	.string "让你久等了！\p"
	.string "欢迎来到宝可梦的世界！\p"
	.string "我叫大木。\p"
	.string "大家都叫我宝可梦博士。\p"
	.string "$"

gText_Oak_Pokemon::
	.string "这就是我们所说的“宝可梦”。\p"
	.string "\n"
	.string "$"

gText_Oak_MainSpeech::
	.string "这个世界上广泛生活着被称为宝可梦\n"
	.string "的生物。\p"
	.string "人类和宝可梦互相支持，生活在一\n"
	.string "起。\p"
	.string "有人和宝可梦玩耍，有人和它们一起\n"
	.string "对战。\p"
	.string "但关于宝可梦，我们还未全知全晓。\p"
	.string "还有许多未解之谜等待解开。这就是\n"
	.string "我每天研究宝可梦的原因。\p"
	.string "$"

gText_Oak_AndYouAre::
	.string "那么你是？$"

gText_Oak_BoyOrGirl::
	.string "你是男孩？还是女孩？$"

gText_Oak_WhatChallenge::
	.string "你期待怎样的挑战？$"

gText_Oak_ChallengeSelected::
	.string "听起来是个很适合你的挑战难度！$"

gText_Oak_WhatsYourName::
	.string "你叫什么名字？$"

gText_Oak_SoItsPlayer::
	.string "哦！所以你是{PLAYER}\n"
	.string "{KUN}？$"

gText_Oak_YourePlayer::
	.string "{PLAYER}{KUN}，准备\n"
	.string "好了吗？\p"
	.string "属于你自己的冒险之旅即将展开。\p"
	.string "$"

gText_Oak_AreYouReady::
	.string "你将经历欢乐的时光与严峻的挑战。\p"
	.string "与宝可梦共度的梦想与冒险之旅在等\n"
	.string "着你！出发吧！\p"
	.string "待会儿见！\p"
	.string "$"
