gText_ObtainedTheItem::
	.string "Obtained the {STR_VAR_2}!$"

gText_TheBagIsFull::
	.string "包包满了………$"

gText_PutItemInPocket::
	.string "{PLAYER}把\n"
	.string "{STR_VAR_2}放入了\l"
	.string "{STR_VAR_3}口袋里。$"

gText_PlayerFoundOneItem::
	.string "{PLAYER}找到了\n"
	.string "{STR_VAR_2}！$"

gText_TooBadBagIsFull::
	.string "太遗憾了！包包满了……$"

gText_PlayerPutItemInBag::
	.string "{PLAYER}把\n"
	.string "{STR_VAR_2}放入了包包\l"
	.string "里。$"

gText_ObtainedTheDecor::
	.string "获得了{STR_VAR_2}！$"

gText_NoRoomLeftForAnother::
	.string "太遗憾了！{STR_VAR_2}\n"
	.string "的数量已满，没法再携带了！$"

gText_TheDecorWasTransferredToThePC::
	.string "{STR_VAR_2}传送到电脑\n"
	.string "里了。$"

gText_ObtainedTheItems::
	.string "Obtained {STR_VAR_1} {STR_VAR_2}!$"

gText_PlayerFoundItems::
	.string "{PLAYER}找到了\n"
	.string "{STR_VAR_1}个\l"
	.string "{STR_VAR_2}！$"

gText_PutCoinsAwayInCoinCase::
	.string "{PLAYER}将代币放入了代币\n"
	.string "盒中。$"

gText_FoundXCoins::
	.string "{PLAYER}找到了\n"
	.string "{STR_VAR_1}枚\l"
	.string "{STR_VAR_2}！$"

gText_FoundXItems::
	.string "{PLAYER}找到了\n"
	.string "{STR_VAR_1}个\l"
	.string "{STR_VAR_2}！$"

gText_CoinCaseIsFull::
	.string "太遗憾了！代币盒已满……$"

gText_NothingToPutThemIn::
	.string "太遗憾了！没有可以放入的物品……$"
