gText_WouldYouLikeToRestYourPkmn::
	.string "辛苦了！这里是宝可梦中心。\p"
	.string "在这里可以回复宝可梦的体力。\p"
	.string "要让您的宝可梦休息一下吗？$"

gText_IllTakeYourPkmn::
	.string "那么，就交给我吧！$"

gText_RestoredPkmnToFullHealth::
	.string "久等了！\p"
	.string "交给我的宝可梦们全都变得精力充沛\n"
	.string "了哦！$"

gText_WeHopeToSeeYouAgain::
	.string "欢迎下次再来！$"

gText_WelcomeCutShort::
	.string "辛苦了！这里是宝可梦中心。\p"
	.string "在这里，可以回复宝可梦的体力。\p"
	.string "要让您的宝可梦……$"

gText_NoticesGoldCard::
	.string "那、那是......难道是...\n"
	.string "...金色卡片？！\p"
	.string "哇，金色的光芒好耀眼！上面的4颗\n"
	.string "星就像在闪闪发亮！\p"
	.string "我以前见过几位拥有银色卡片的训练\n"
	.string "家，不过，{PLAYER}，拥有\l"
	.string "金色卡片的训练家，你还是我见到的\l"
	.string "第一位！\p"
	.string "好，{PLAYER}，请务必让我\n"
	.string "为你的宝可梦恢复体力！$"

gText_YouWantTheUsual::
	.string "见到你真高兴，{PLAYER}！\n"
	.string "还是老规矩，对吧？$"

gText_IllTakeYourPkmn2::
	.string "那就交给我吧！$"

gText_ThankYouForWaiting::
	.string "让您久等了！$"

gText_WeHopeToSeeYouAgain2::
	.string "欢迎您随时再来！$"

gText_PkmnCenterChallenge_NoVisitsLeft:: @ tx_difficulty_challenge
    .string "抱歉，你正在进行宝可梦中心挑战！\p"
    .string "祝你好运！\n"
    .string "{PAUSE_UNTIL_PRESS}$"
