gText_WouldYouLikeToRestYourPkmn::
	.string "辛苦了！这里是宝可梦中心。\p"
	.string "在这里可以回复宝可梦的体力。\p"
	.string "要让您的宝可梦休息一下吗？$"

gText_IllTakeYourPkmn::
	.string "那么，就交给我吧！$"

gText_RestoredPkmnToFullHealth::
	.string "久等了！\p"
	.string "交给我的宝可梦们全都变得精力充沛\n"
	.string "了哦！$"

gText_WeHopeToSeeYouAgain::
	.string "欢迎下次再来！$"

gText_WelcomeCutShort::
	.string "辛苦了！这里是宝可梦中心。\p"
	.string "在这里，可以回复宝可梦的体力。\p"
	.string "要让您的宝可梦……$"

gText_NoticesGoldCard::
	.string "Th-that card…\n"
	.string "Could it be… The GOLD CARD?!\p"
	.string "Oh, the gold color is brilliant!\n"
	.string "The four stars seem to sparkle!\p"
	.string "I've seen several TRAINERS with\n"
	.string "a SILVER CARD before, but, {PLAYER},\l"
	.string "you're the first TRAINER I've ever\l"
	.string "seen with a GOLD CARD!\p"
	.string "Okay, {PLAYER}, please allow me\n"
	.string "the honor of resting your POKéMON!$"

gText_YouWantTheUsual::
	.string "I'm delighted to see you, {PLAYER}!\n"
	.string "You want the usual, am I right?$"

gText_IllTakeYourPkmn2::
	.string "那就交给我吧！$"

gText_ThankYouForWaiting::
	.string "让您久等了！$"

gText_WeHopeToSeeYouAgain2::
	.string "欢迎您随时再来！$"

gText_PkmnCenterChallenge_NoVisitsLeft:: @ tx_difficulty_challenge
    .string "Sorry, but you are playing with\n"
    .string "the POKéCENTER challenge!\p"
    .string "Good luck!{PAUSE_UNTIL_PRESS}$"
