gBirchDexRatingText_AreYouCurious::
	.string "小田卷博士：啊，{PLAYER}\n"
	.string "{KUN}！\p"
	.string "你想知道你的宝可梦图鉴是什么水平\n"
	.string "吗？$"

gBirchDexRatingText_Cancel::
	.string "嗯，你收集的宝可梦还不够多，没什\n"
	.string "么太大的价值啊。$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "唔唔……\p"
	.string "见过了{STR_VAR_1}只宝\n"
	.string "可梦，捕捉了\l"
	.string "{STR_VAR_2}只宝可梦…\l"
	.string "…$"

gBirchDexRatingText_LessThan10::
	.string "多去草丛里转转，仔细寻找宝可梦吧\n"
	.string "。$"

gBirchDexRatingText_LessThan20::
	.string "看来你已经掌握诀窍了，但是从现在\n"
	.string "开始，收集将越来越困难。$"

gBirchDexRatingText_LessThan30::
	.string "有些宝可梦只在特定的地域出现，你\n"
	.string "必须坚持去寻找。$"

gBirchDexRatingText_LessThan40::
	.string "啊，现在看上去比较像一个宝可梦图\n"
	.string "鉴了，但还有很大的发展空间。$"

gBirchDexRatingText_LessThan50::
	.string "看起来挺好的，继续加油吧。$"

gBirchDexRatingText_LessThan60::
	.string "你用过钓竿吗？海里有很多宝可梦的\n"
	.string "。$"

gBirchDexRatingText_LessThan70::
	.string "除了捕捉宝可梦，让它们进化也是个\n"
	.string "不错的主意。$"

gBirchDexRatingText_LessThan80::
	.string "看着它，我就想说，真是不错的宝可\n"
	.string "梦图鉴！$"

gBirchDexRatingText_LessThan90::
	.string "已经收集这么多了……你一定有这方\n"
	.string "面的天赋！$"

gBirchDexRatingText_LessThan100::
	.string "你去过狩猎地带了吗？\p"
	.string "听说有些宝可梦只有在那里才能捕捉\n"
	.string "到。$"

gBirchDexRatingText_LessThan110::
	.string "You've finally reached\n"
	.string "the 100-kind mark.\p"
	.string "This is an impressive POKéDEX!$"

gBirchDexRatingText_LessThan120::
	.string "使用碎岩也有可能找到宝可梦哦。$"

gBirchDexRatingText_LessThan130::
	.string "你可以和其他人交换来得到更多的宝\n"
	.string "可梦。$"

gBirchDexRatingText_LessThan140::
	.string "听说有些宝可梦如果非常喜欢自己的\n"
	.string "训练家，它们就会进化。$"

gBirchDexRatingText_LessThan150::
	.string "没想到丰缘地区会有这么宝可梦种类\n"
	.string "。$"

gBirchDexRatingText_LessThan160::
	.string "On occasion, some POKéMON appear\n"
	.string "in large numbers like outbreaks.\p"
	.string "Don't miss opportunities like\n"
	.string "those.$"

gBirchDexRatingText_LessThan170::
	.string "看了你的宝可梦图鉴，基本就可以了\n"
	.string "解丰缘地区的宝可梦的情况了。$"

gBirchDexRatingText_LessThan180::
	.string "要我说，你已经可以被称作宝可梦专\n"
	.string "家了，而且是个优秀的专家！$"

gBirchDexRatingText_LessThan190::
	.string "有了这么完整的宝可梦图鉴，你可以\n"
	.string "成为一个真正的专家了！$"

gBirchDexRatingText_LessThan200::
	.string "我有很强烈的预感，你的宝可梦图鉴\n"
	.string "很快就能完成了！$"

gBirchDexRatingText_DexCompleted::
	.string "恭喜你！你做成了完美的宝可梦图鉴\n"
	.string "！$"

gBirchDexRatingText_OnANationwideBasis::
	.string "唔唔……从全国来看……\p"
	.string "见过了{STR_VAR_1}只宝\n"
	.string "可梦，捕捉了\l"
	.string "{STR_VAR_2}只宝可梦…\l"
	.string "…$"

@ FRLG

PokedexRating_Text_HowIsPokedexComingAlong::
	.string "OAK: Good to see you!\n"
	.string "How is your POKéDEX coming along?\p"
	.string "Here, let me take a look.$"

PokedexRating_Text_SeenXOwnedY::
	.string "The amount of progress you've made\n"
	.string "on your POKéDEX is:\p"
	.string "{STR_VAR_1} POKéMON seen and\n"
	.string "{STR_VAR_2} POKéMON owned.\p"
	.string "{FONT_NORMAL}PROF. OAK's rating:$"

PokedexRating_Text_LessThan10::
	.string "You still have lots to do.\p"
	.string "Go into every patch of grass you\n"
	.string "see and look for POKéMON!$"

PokedexRating_Text_LessThan20::
	.string "It looks as if you're getting on\n"
	.string "the right track!\p"
	.string "I've given one of my AIDES a FLASH\n"
	.string "HM. Make sure you go get it!$"

PokedexRating_Text_LessThan30::
	.string "Your POKéDEX could use a bit more\n"
	.string "volume still!\p"
	.string "Try to catch other species of\n"
	.string "POKéMON!$"

PokedexRating_Text_LessThan40::
	.string "Good, it's apparent that you're\n"
	.string "trying hard!\p"
	.string "I've given one of my AIDES an\n"
	.string "ITEMFINDER. Be sure to collect it!$"

PokedexRating_Text_LessThan50::
	.string "Your POKéDEX is coming along quite\n"
	.string "well!\p"
	.string "I've given one of my AIDES an\n"
	.string "AMULET COIN. Be sure to get it!$"

PokedexRating_Text_LessThan60::
	.string "Ah, you've finally topped 50\n"
	.string "species!\p"
	.string "I've given one of my AIDES an EXP.\n"
	.string "SHARE. Be sure to go get it!$"

PokedexRating_Text_LessThan70::
	.string "Hoho! This is turning into quite the\n"
	.string "respectable POKéDEX!$"

PokedexRating_Text_LessThan80::
	.string "Very good!\p"
	.string "I think you'll collect even more\n"
	.string "POKéMON by going fishing!$"

PokedexRating_Text_LessThan90::
	.string "Wonderful! Let me guess… You\n"
	.string "like to collect things, don't you?$"

PokedexRating_Text_LessThan100::
	.string "I'm impressed!\n"
	.string "It must have been difficult to do!$"

PokedexRating_Text_LessThan110::
	.string "You've finally hit 100 species!\n"
	.string "I can't believe how good you are!$"

PokedexRating_Text_LessThan120::
	.string "You even have the evolved forms\n"
	.string "of POKéMON! Super!$"

PokedexRating_Text_LessThan130::
	.string "Excellent! Trade with friends to\n"
	.string "get some more!$"

PokedexRating_Text_LessThan140::
	.string "Outstanding!\n"
	.string "You've become a real pro at this!$"

PokedexRating_Text_LessThan150::
	.string "I have nothing left to say!\n"
	.string "You're the POKéMON PROFESSOR now!$"

PokedexRating_Text_Complete::
	.string "Your POKéDEX is entirely complete!\n"
	.string "Congratulations!!$"

PokedexRating_Text_NationalDexSeenXOwnedY::
	.string "And your NATIONAL POKéDEX is:\p"
	.string "{STR_VAR_1} POKéMON seen and\n"
	.string "{STR_VAR_2} POKéMON owned.$"

PokedexRating_Text_LookForwardToFilledNationalDex::
	.string "I'll be looking forward to seeing\n"
	.string "you fill the NATIONAL POKéDEX!$"

PokedexRating_Text_YouveCompletedDex::
	.string "Finally…\p"
	.string "You've finally completed the\n"
	.string "POKéDEX!\p"
	.string "It's magnificent!\n"
	.string "Truly, this is a fantastic feat!$"

PokedexRating_Text_Wroooaaarrr::
	.string "Wroooooooaaaaaarrrr!$"

PokedexRating_Text_ThankYouMadeDreamReality::
	.string "Thank you, {PLAYER}!\n"
	.string "Sincerely, thank you!\l"
	.string "You've made my dream a reality!$"

PokedexRating_Text_LoveSeeingYourPokedex::
	.string "OAK: Ah, welcome!\p"
	.string "Tell me, how is your POKéDEX\n"
	.string "coming along?\p"
	.string "Wahaha!\p"
	.string "Actually, I know how it is, but I\n"
	.string "love seeing it anyway!\p"
	.string "Let's see…$"

@ HnS (mostly directly copied from HGSS)

gElmDexRatingText_GoFindMrPokemon::
	.string "PROF. ELM: Ah, {PLAYER}{KUN}!\p"
	.string "Have you found MR. POKéMON's\n"
	.string "home yet? It is on ROUTE 30,\p"
	.string "you can't miss it!$"

gElmDexRatingText_Robbery::
	.string "PROF. ELM: {PLAYER}{KUN}!\p"
	.string "Get here quick! Something\n"
	.string "awful has happened!$"

gElmDexRatingText_AreYouCurious::
	.string "PROF. ELM: Ah, {PLAYER}{KUN}!\p"
	.string "Are you curious about how your\n"
	.string "POKéDEX is coming along?$"

gElmDexRatingText_AreYouCuriousNational::
	.string "PROF. ELM: Ah, {PLAYER}{KUN}!\p"
	.string "Are you curious about how your\n"
	.string "National POKéDEX is coming along?$"

gJohtoDexRatingText_LessThan10::
	.string "Look for POKéMON in grassy areas!$"

gJohtoDexRatingText_LessThan20::
	.string "Good. I see you understand how to\n"
	.string "use Poké Balls.$"

gJohtoDexRatingText_LessThan35::
	.string "You're getting good at this,\n"
	.string "but you have a long way to go.$"

gJohtoDexRatingText_LessThan50::
	.string "Hmm, you're catching POKéMON at a\n"
	.string "decent pace!$"

gJohtoDexRatingText_LessThan65::
	.string "You're trying--I can see that.\n"
	.string "Your POKéDEX is coming together.$"

gJohtoDexRatingText_LessThan80::
	.string "You're training them well. You know\n"
	.string "some POKéMON don't evolve just by\p"
	.string "battling with others, right?$"

gJohtoDexRatingText_LessThan95::
	.string "Do you have a Fishing Rod?\n"
	.string "There are some POKéMON that can\p"
	.string "only be found by fishing!$"

gJohtoDexRatingText_LessThan110::
	.string "Excellent! You seem to be good at\n"
	.string "collecting things!$"

gJohtoDexRatingText_LessThan125::
	.string "Some POKéMON only appear during\n"
	.string "certain times of the day.$"

gJohtoDexRatingText_LessThan140::
	.string "Your POKéDEX is really filling up.\n"
	.string "Keep up the good work!$"

gJohtoDexRatingText_LessThan155::
	.string "I'm impressed.\n"
	.string "You're evolving POKéMON, not just\p"
	.string "catching them.$"

gJohtoDexRatingText_LessThan170::
	.string "If you can learn how to use the\n"
	.string "custom Poké Balls made by Kurt\p"
	.string "effectively, you'll be able to catch\n"
	.string "POKéMON better!$"

gJohtoDexRatingText_LessThan185::
	.string "When you trade POKéMON, you can\n"
	.string "also trade information. Your\p"
	.string "friends can really help you!$"

gJohtoDexRatingText_LessThan200::
	.string "Are you trading your POKéMON?\n"
	.string "It's tough to do this alone!$"

gJohtoDexRatingText_LessThan215::
	.string "Wow! You've reached 200!\n"
	.string "Your POKéDEX is looking great!$"

@ Taken from Platinum
gJohtoDexRatingText_LessThan230::
	.string "You've proven yourself capable.\n"
    .string "There's nothing to worry about.\p"
    .string "Keep catching POKéMON the way\n"
    .string "you've been doing so far.$"

@ Taken from Platinum
gJohtoDexRatingText_LessThan245::
	.string "Your POKéDEX is well on the way to\n"
	.string "being filled up.\p"
	.string "This POKéDEX can be considered a\n"
	.string "journal of your adventure.$"

gJohtoDexRatingText_LessThan260::
	.string "You've found so many POKéMON!\n"
	.string "You've really helped my studies!$"

gJohtoDexRatingText_LessThan275::
	.string "Magnificent! You have the ability\n"
	.string "to become a great POKéMON\p"
	.string "Professor someday!$"

gJohtoDexRatingText_LessThanMaxDex::
	.string "Your POKéDEX is amazing!\n"
	.string "You're ready to turn professional!$"

gJohtoDexRatingText_Complete::
	.string "Wow!\n"
	.string "That is a complete Johto POKéDEX!\p"  
	.string "Thanks to you, {PLAYER}, the Johto\n"
	.string "POKéDEX is complete!\p"
	.string "Wow...\n"
	.string "You've done an incredible job!$"

gNationalDexRatingText_LessThan100::
	.string "The goal may be far away, but don't\n"
	.string "give up yet! Keep going!$"

gNationalDexRatingText_LessThan150::
	.string "Don't forget, some POKéMON only\n"
	.string "appear at certain times of the day!$"

gNationalDexRatingText_LessThan200::
	.string "If you break rocks, some POKéMON\n"
	.string "that were hiding there might come\p"
	.string "jumping out!$"

gNationalDexRatingText_LessThan250::
	.string "That's wonderful you've been able\n"
	.string "to gather this many POKéMON!\p"
	.string "The path ahead is long. Keep up the\n"
	.string "great work!$"

gNationalDexRatingText_LessThan300::
	.string "If you Headbutt a tree, sometimes\n"
	.string "a POKéMON might fall out!$"

gNationalDexRatingText_LessThan350::
	.string "A lot of POKéMON not found in the\n"
	.string "Johto region like to congregate\p"
	.string "at the Safari Zone$"

gNationalDexRatingText_LessThan400::
@	.string "Music on the radio might also\n"
@	.string "entice POKéMON to leap out$"
	.string "There are hidden locations all\n"
	.string "over the world containing rare\p"
	.string "and unusual POKéMON, try to find\n"
	.string "them all!$"

gNationalDexRatingText_LessThan435::
	.string "Wow, you've gotten so far...!\n"
	.string "I'm actually a little surprised!$"

gNationalDexRatingText_LessThan465::
	.string "This is a critical moment!\n"
	.string "You can't become discouraged!$"

gNationalDexRatingText_LessThan475::
	.string "Just a little more!\n"
	.string "I've got high expectations for you!$"

gNationalDexRatingText_LessThanMaxDex::
	.string "I have never before in all my years\n"
	.string "seen such an incredible Trainer!$"

gNationalDexRatingText_Complete::
	.string "Excellent! That is an amazing\n"
	.string "National POKéDEX!\p"
	.string "Wow...{PAUSE 10}\p"
	.string "You've lived up to my\n"
	.string "expectations wonderfully!\p"
	.string "No, you've exceeded them, {PLAYER}.\n"
	.string "You've become an amazing Trainer!\p"
	.string "Thank you, {PLAYER}!$"
