gBirchDexRatingText_AreYouCurious::
	.string "小田卷博士：啊，{PLAYER}\n"
	.string "{KUN}！\p"
	.string "你想知道你的宝可梦图鉴是什么水平\n"
	.string "吗？$"

gBirchDexRatingText_Cancel::
	.string "嗯，你收集的宝可梦还不够多，没什\n"
	.string "么太大的价值啊。$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "唔唔……\p"
	.string "见过了{STR_VAR_1}只宝\n"
	.string "可梦，捕捉了\l"
	.string "{STR_VAR_2}只宝可梦…\l"
	.string "…$"

gBirchDexRatingText_LessThan10::
	.string "多去草丛里转转，仔细寻找宝可梦吧\n"
	.string "。$"

gBirchDexRatingText_LessThan20::
	.string "看来你已经掌握诀窍了，但是从现在\n"
	.string "开始，收集将越来越困难。$"

gBirchDexRatingText_LessThan30::
	.string "有些宝可梦只在特定的地域出现，你\n"
	.string "必须坚持去寻找。$"

gBirchDexRatingText_LessThan40::
	.string "啊，现在看上去比较像一个宝可梦图\n"
	.string "鉴了，但还有很大的发展空间。$"

gBirchDexRatingText_LessThan50::
	.string "看起来挺好的，继续加油吧。$"

gBirchDexRatingText_LessThan60::
	.string "你用过钓竿吗？海里有很多宝可梦的\n"
	.string "。$"

gBirchDexRatingText_LessThan70::
	.string "除了捕捉宝可梦，让它们进化也是个\n"
	.string "不错的主意。$"

gBirchDexRatingText_LessThan80::
	.string "看着它，我就想说，真是不错的宝可\n"
	.string "梦图鉴！$"

gBirchDexRatingText_LessThan90::
	.string "已经收集这么多了……你一定有这方\n"
	.string "面的天赋！$"

gBirchDexRatingText_LessThan100::
	.string "你去过狩猎地带了吗？\p"
	.string "听说有些宝可梦只有在那里才能捕捉\n"
	.string "到。$"

gBirchDexRatingText_LessThan110::
	.string "你终于突破了100种的大关。\p"
	.string "这本图鉴真是令人叹为观止！$"

gBirchDexRatingText_LessThan120::
	.string "使用碎岩也有可能找到宝可梦哦。$"

gBirchDexRatingText_LessThan130::
	.string "你可以和其他人交换来得到更多的宝\n"
	.string "可梦。$"

gBirchDexRatingText_LessThan140::
	.string "听说有些宝可梦如果非常喜欢自己的\n"
	.string "训练家，它们就会进化。$"

gBirchDexRatingText_LessThan150::
	.string "没想到丰缘地区会有这么宝可梦种类\n"
	.string "。$"

gBirchDexRatingText_LessThan160::
	.string "有时候，某些宝可梦会成群地大量出\n"
	.string "现。\p"
	.string "可千万不要错失这样的机会哦。$"

gBirchDexRatingText_LessThan170::
	.string "看了你的宝可梦图鉴，基本就可以了\n"
	.string "解丰缘地区的宝可梦的情况了。$"

gBirchDexRatingText_LessThan180::
	.string "要我说，你已经可以被称作宝可梦专\n"
	.string "家了，而且是个优秀的专家！$"

gBirchDexRatingText_LessThan190::
	.string "有了这么完整的宝可梦图鉴，你可以\n"
	.string "成为一个真正的专家了！$"

gBirchDexRatingText_LessThan200::
	.string "我有很强烈的预感，你的宝可梦图鉴\n"
	.string "很快就能完成了！$"

gBirchDexRatingText_DexCompleted::
	.string "恭喜你！你做成了完美的宝可梦图鉴\n"
	.string "！$"

gBirchDexRatingText_OnANationwideBasis::
	.string "唔唔……从全国来看……\p"
	.string "见过了{STR_VAR_1}只宝\n"
	.string "可梦，捕捉了\l"
	.string "{STR_VAR_2}只宝可梦…\l"
	.string "…$"

@ FRLG

PokedexRating_Text_HowIsPokedexComingAlong::
	.string "大木：见到你真高兴！图鉴收集得怎\n"
	.string "么样了？\p"
	.string "来，让我看一看。$"

PokedexRating_Text_SeenXOwnedY::
	.string "目前图鉴的收集进度如下：\p"
	.string "遇见的宝可梦：\n"
	.string "{STR_VAR_1}只，收服的\l"
	.string "宝可梦：{STR_VAR_2}只\l"
	.string "。\p"
	.string "{FONT_NORMAL}大木博\n"
	.string "士的评价：$"

PokedexRating_Text_LessThan10::
	.string "你还有很长的路要走呢。\p"
	.string "看到草丛就钻进去找找宝可梦吧！$"

PokedexRating_Text_LessThan20::
	.string "看起来你已经步入正轨了！\p"
	.string "我已经把秘传学习器“闪光”交给助\n"
	.string "手了。一定要记得去拿哦！$"

PokedexRating_Text_LessThan30::
	.string "你的宝可梦图鉴还需要再充实一些！\p"
	.string "试着去收服更多不同种类的宝可梦吧\n"
	.string "！$"

PokedexRating_Text_LessThan40::
	.string "很好，看得出你非常努力！\p"
	.string "我已经把“探宝器”交给了助手。一\n"
	.string "定要记得去领哦！$"

PokedexRating_Text_LessThan50::
	.string "你的图鉴收集得相当顺利嘛！\p"
	.string "我已经把“护符金币”交给了助手。\n"
	.string "一定要记得去拿！$"

PokedexRating_Text_LessThan60::
	.string "啊，你终于突破50种了！\p"
	.string "我已经把“学习装置”交给了助手。\n"
	.string "一定要记得去领哦！$"

PokedexRating_Text_LessThan70::
	.string "嗬嗬！这本图鉴变得越来越有模有样\n"
	.string "了！$"

PokedexRating_Text_LessThan80::
	.string "非常好！\p"
	.string "我想如果你去钓鱼的话，一定能收集\n"
	.string "到更多宝可梦的！$"

PokedexRating_Text_LessThan90::
	.string "太棒了！让我猜猜……你平\n"
	.string "时就很喜欢收集东西，对吧？$"

PokedexRating_Text_LessThan100::
	.string "真令人佩服！这一定相当不容易吧！$"

PokedexRating_Text_LessThan110::
	.string "终于突破100种了！没想到你居然\n"
	.string "这么厉害！$"

PokedexRating_Text_LessThan120::
	.string "连宝可梦的进化形都收集到了！太棒\n"
	.string "了！$"

PokedexRating_Text_LessThan130::
	.string "干得漂亮！和朋友通信交换，收集更\n"
	.string "多的宝可梦吧！$"

PokedexRating_Text_LessThan140::
	.string "太出色了！你已经是个货真价实的行\n"
	.string "家了！$"

PokedexRating_Text_LessThan150::
	.string "我真是无话可说了！现在的你简直就\n"
	.string "是宝可梦博士了！$"

PokedexRating_Text_Complete::
	.string "你的宝可梦图鉴彻底完成了！恭喜你\n"
	.string "！！$"

PokedexRating_Text_NationalDexSeenXOwnedY::
	.string "而你的全国图鉴则是：\p"
	.string "看见的宝可梦有\n"
	.string "{STR_VAR_1}只，捉到的\l"
	.string "宝可梦有{STR_VAR_2}只\l"
	.string "。$"

PokedexRating_Text_LookForwardToFilledNationalDex::
	.string "我很期待看到你填满全国图鉴的那一\n"
	.string "天！$"

PokedexRating_Text_YouveCompletedDex::
	.string "终于……\p"
	.string "你终于彻底完成了宝可梦图鉴！\p"
	.string "太壮观了！这真是一项了不起的壮举\n"
	.string "！$"

PokedexRating_Text_Wroooaaarrr::
	.string "吼噢噢噢噢噢噢噢--！$"

PokedexRating_Text_ThankYouMadeDreamReality::
	.string "谢谢你，{PLAYER}！衷心地\n"
	.string "感谢你！是你让我的梦想成为了现实\l"
	.string "！$"

PokedexRating_Text_LoveSeeingYourPokedex::
	.string "大木：啊，欢迎！\p"
	.string "快跟我说说，你的图鉴收集得怎么样\n"
	.string "了？\p"
	.string "哇哈哈！\p"
	.string "其实我心里有数，不过我就是喜欢亲\n"
	.string "眼瞧瞧！\p"
	.string "让我来看看……$"

@ HnS (mostly directly copied from HGSS)

gElmDexRatingText_GoFindMrPokemon::
	.string "空木博士：啊，{PLAYER}{KUN}！\p"
	.string "找到宝可梦爷爷的家了吗？\n"
	.string "就在30号道路上，\p"
	.string "你一定能找到的！$"

gElmDexRatingText_Robbery::
	.string "空木博士：{PLAYER}\n"
	.string "{KUN}！\p"
	.string "快点回来！出大事了！$"

gElmDexRatingText_AreYouCurious::
	.string "空木博士：啊，{PLAYER}\n"
	.string "{KUN}！\p"
	.string "想知道你的宝可梦图鉴完成得如何了\n"
	.string "吗？$"

gElmDexRatingText_AreYouCuriousNational::
	.string "空木博士：啊，{PLAYER}\n"
	.string "{KUN}！\p"
	.string "想知道你的全国图鉴完成得如何了吗\n"
	.string "？$"

gJohtoDexRatingText_LessThan10::
	.string "试着去草丛里找找宝可梦吧！$"

gJohtoDexRatingText_LessThan20::
	.string "不错，看来你已经懂得怎么使用精灵\n"
	.string "球了。$"

gJohtoDexRatingText_LessThan35::
	.string "你越来越熟练了，不过前面的路还长\n"
	.string "着呢。$"

gJohtoDexRatingText_LessThan50::
	.string "嗯，你捕捉宝可梦的节奏相当不错！$"

gJohtoDexRatingText_LessThan65::
	.string "看得到你的努力--你的图鉴已经逐\n"
	.string "渐成形了。$"

gJohtoDexRatingText_LessThan80::
	.string "你培育得很好。不过你也知道吧，有\n"
	.string "些宝可梦可不是单靠对战\p"
	.string "就能进化的哦？$"

gJohtoDexRatingText_LessThan95::
	.string "你有钓竿吗？有些宝可梦可是\p"
	.string "只能通过钓鱼才能遇到的哦！$"

gJohtoDexRatingText_LessThan110::
	.string "太棒了！看来你很擅长收集东西呢！$"

gJohtoDexRatingText_LessThan125::
	.string "有些宝可梦只会在特定的时间段出现\n"
	.string "哦。$"

gJohtoDexRatingText_LessThan140::
	.string "你的宝可梦图鉴越来越充实了呢。继\n"
	.string "续保持这股劲头吧！$"

gJohtoDexRatingText_LessThan155::
	.string "真令人佩服。你不仅只是捕捉，\p"
	.string "还在积极让宝可梦进化呢。$"

gJohtoDexRatingText_LessThan170::
	.string "如果能熟练运用钢铁先生特制的精灵\n"
	.string "球，\p"
	.string "捕捉宝可梦就会变得更加轻松哦！$"

gJohtoDexRatingText_LessThan185::
	.string "交换宝可梦不仅能互通有无，还能交\n"
	.string "流情报呢。\p"
	.string "朋友们一定能成为你的大帮手！$"

gJohtoDexRatingText_LessThan200::
	.string "你有和别人交换宝可梦吗？单凭一个\n"
	.string "人的力量可是很难完成的哦！$"

gJohtoDexRatingText_LessThan215::
	.string "哇！已经达到200只了！你的图鉴\n"
	.string "真了不起！$"

@ Taken from Platinum
gJohtoDexRatingText_LessThan230::
	.string "你的实力已经毋庸置疑了。完全不需\n"
	.string "要担心。\p"
	.string "就照着现在的节奏，继续去捕捉宝可\n"
	.string "梦吧。$"

@ Taken from Platinum
gJohtoDexRatingText_LessThan245::
	.string "你的图鉴已经逐渐成形了呢。\p"
	.string "这本图鉴，可以说就是你冒险历程的\n"
	.string "日记啊。$"

gJohtoDexRatingText_LessThan260::
	.string "你居然发现了这么多宝可梦！对我的\n"
	.string "研究真是帮了大忙了！$"

gJohtoDexRatingText_LessThan275::
	.string "太精彩了！照这样下去，你将来甚至\n"
	.string "能成为一名优秀的\p"
	.string "宝可梦博士呢！$"

gJohtoDexRatingText_LessThanMaxDex::
	.string "你的图鉴太惊人了！完全可以去当专\n"
	.string "业研究员了！$"

gJohtoDexRatingText_Complete::
	.string "哇！城都图鉴已经全部完成了！\p"
	.string "多亏了你，{PLAYER}，城都\n"
	.string "图鉴彻底完成了！\p"
	.string "太震撼了……你交出了一份\n"
	.string "不可思议的答卷！$"

gNationalDexRatingText_LessThan100::
	.string "距离目标虽然还很远，但千万别放弃\n"
	.string "！继续加油！$"

gNationalDexRatingText_LessThan150::
	.string "别忘了，有些宝可梦只会在特定的时\n"
	.string "间段出现哦！$"

gNationalDexRatingText_LessThan200::
	.string "如果把岩石击碎，藏在里面的宝可梦\n"
	.string "说不定\p"
	.string "就会跳出来呢！$"

gNationalDexRatingText_LessThan250::
	.string "能收集到这么多宝可梦，真了不起！\p"
	.string "未来的路还很长。继续保持这个势头\n"
	.string "加油吧！$"

gNationalDexRatingText_LessThan300::
	.string "用头锤去撞树的话，有时会有宝可梦\n"
	.string "掉下来哦！$"

gNationalDexRatingText_LessThan350::
	.string "许多在城都地区见不到的宝可梦，似\n"
	.string "乎都聚集在\p"
	.string "狩猎地带呢。$"

gNationalDexRatingText_LessThan400::
@	.string "Music on the radio might also\n"
@	.string "entice POKéMON to leap out$"
	.string "世界各地都有一些隐秘的场所，栖息\n"
	.string "着稀有而罕见的宝可梦，\p"
	.string "试着把它们全都找出来吧！$"

gNationalDexRatingText_LessThan435::
	.string "哇，你竟然收集了这么多……\n"
	.string "老实说，连我都有些惊讶了！$"

gNationalDexRatingText_LessThan465::
	.string "现在正是紧要关头！可千万不要灰心\n"
	.string "啊！$"

gNationalDexRatingText_LessThan475::
	.string "就差一点点了！我对你抱有很高的期\n"
	.string "望哦！$"

gNationalDexRatingText_LessThanMaxDex::
	.string "我活了这么大岁数，还从未见过如此\n"
	.string "惊人的训练家！$"

gNationalDexRatingText_Complete::
	.string "太完美了！这份全国图鉴实在太不可\n"
	.string "思议了！\p"
	.string "哇……\n"
	.string "{PAUSE 10}\p"
	.string "你出色地回应了我的期待！\p"
	.string "不，你甚至超越了我的想象，\n"
	.string "{PLAYER}。你已经是一位了\l"
	.string "不起的训练家了！\p"
	.string "谢谢你，{PLAYER}！$"
