Questionnaire_Text_FillOut::
	.string "这里有张问卷调查，要填一下吗？$"

Questionnaire_Text_ThankYou::
	.string "谢谢您抽出时间来填写我们的调查问\n"
	.string "卷，\p"
	.string "您的反馈将成为我们的参考。$"

Questionnaire_Text_YouKnowThoseWordsGift::
	.string "啊，您好！您知道这些短语吗？\p"
	.string "那么说您一定知道关于神秘礼物的事\n"
	.string "情了。\p"
	.string "从现在起，您将会收到神秘礼物！$"

Questionnaire_Text_YouCanAccessMysteryGift::
	.string "您写入记录后，就可以接收神秘礼物\n"
	.string "了。$"

Questionnaire_Text_YouKnowThoseWordsEvent::
	.string "啊，您好！您知道这些短语吗？\p"
	.string "那么说您一定知道关于神秘事件的事\n"
	.string "情了。$"

Questionnaire_Text_YouCanAccessMysteryEvent::
	.string "您写入记录后，就可以接收神秘事件\n"
	.string "了。$"

MysteryGift_Text_TheresATicketForYou::
	.string "感谢使用神秘事件系统。\p"
	.string "您是{PLAYER}吧，这是给您\n"
	.string "的船票。$"

MysteryGift_Text_TryUsingItAtLilycovePort::
	.string "这个看起来能在水静市的港口使用。\p"
	.string "不如去试试能到什么地方？$"
