	.align 2
gText_ConfirmSave::
	.string "要保存目前为止的冒险记录吗？$"

gText_AlreadySavedFile::
	.string "需要覆盖写入上次的保存记录，可以\n"
	.string "吗？$"

gText_SavingDontTurnOff::
	.string "正在写入记录……请勿切断电源。$"

gText_PlayerSavedGame::
	.string "{PLAYER}完好地写下了记录\n"
	.string "！$"

gText_DifferentSaveFile::
	.string "注意！！\p"
	.string "在“从记录继续”的选项里已经有了\n"
	.string "一个先前保存的冒险进度了！\p"
	.string "这样做的话，先前的冒险进度及所有\n"
	.string "已得到的宝可梦和道具全部都会消失\l"
	.string "……\p"
	.string "确定要将原来的记录从头覆盖掉吗？$"

gText_SaveError::
	.string "无法写入记录！\p"
	.string "请更换卡带的存档用记忆电池或电子\n"
	.string "基板！$"

gText_SavingDontTurnOffPower::
	.string "正在写入记录……请勿切断电源。$"
