SecretBase_Text_Trainer0Intro:
	.string "你已经做了秘密基地了吗？\p"
	.string "在选定这个地方之前，我已经走了不\n"
	.string "知多少地方。\p"
	.string "既然你来了，我们对战怎么样？$"

SecretBase_Text_Trainer0AcceptBattle:
	.string "好！来吧！$"

SecretBase_Text_Trainer0DeclineBattle:
	.string "哎？啊，现在不行啊……$"

SecretBase_Text_Trainer0Defeated::
	.string "哇啊啊！你真强！我输掉的事……请\n"
	.string "帮我保密！$"

SecretBase_Text_Trainer0PostBattle:
	.string "我的秘密基地怎么样？明天也来玩吧\n"
	.string "。$"

SecretBase_Text_Trainer0PreChampion:
	.string "你已经做了秘密基地了吗？\p"
	.string "在选定这个地方之前，我已经走了不\n"
	.string "知多少地方。\p"
	.string "随便转转吧！$"

SecretBase_Text_Trainer5Intro:
	.string "很多地方都可以制造秘密基地，\p"
	.string "但这个是我最喜欢的地方。你也认为\n"
	.string "这地方不错吧？\p"
	.string "哦，要来一次对战吗？$"

SecretBase_Text_Trainer5AcceptBattle:
	.string "好了，来吧！$"

SecretBase_Text_Trainer5DeclineBattle:
	.string "啊……现在不行吗，也罢。$"

SecretBase_Text_Trainer5Defeated::
	.string "唔……我们输了……别告诉别人啊！\n"
	.string "这是一级机密！$"

SecretBase_Text_Trainer5PostBattle:
	.string "下次来这附近的话，再来我这里转转\n"
	.string "吧。$"

SecretBase_Text_Trainer5PreChampion:
	.string "很多地方都可以制造秘密基地，\p"
	.string "但这个是我最喜欢的地方。你也认为\n"
	.string "这地方不错吧？$"

SecretBase_Text_Trainer1Intro:
	.string "这个地方非常受欢迎，经常会有人来\n"
	.string "这里。\p"
	.string "啊！你也想要这个地方吗？\p"
	.string "那好，如果你能打败我，这地方就归\n"
	.string "你了。$"

SecretBase_Text_Trainer1AcceptBattle:
	.string "好的！我要保护我的秘密基地！$"

SecretBase_Text_Trainer1DeclineBattle:
	.string "呃？是吗？你对这里不感兴趣？$"

SecretBase_Text_Trainer1Defeated::
	.string "我不行了！我放弃！$"

SecretBase_Text_Trainer1PostBattle:
	.string "好，等我有一天我搬走之后，这个地\n"
	.string "方就是你的了！$"

SecretBase_Text_Trainer1PreChampion:
	.string "这个地方非常受欢迎，经常会有人来\n"
	.string "这里。\p"
	.string "我一直在等它打开，我一定要得到它\n"
	.string "！$"

SecretBase_Text_Trainer6Intro:
	.string "欢迎来到我的宝可梦研究所。\p"
	.string "我正在秘密进行对战研究。\p"
	.string "想见识一下我有多强吗？$"

SecretBase_Text_Trainer6AcceptBattle:
	.string "我会全力以赴的！$"

SecretBase_Text_Trainer6DeclineBattle:
	.string "啊，那么下次吧！$"

SecretBase_Text_Trainer6Defeated::
	.string "嗯……我还有很多不足，还得继续学\n"
	.string "习啊。$"

SecretBase_Text_Trainer6PostBattle:
	.string "谢谢你和我对战，明天也来玩吧。$"

SecretBase_Text_Trainer6PreChampion:
	.string "欢迎来到我的宝可梦研究所。\p"
	.string "我正在秘密进行对战研究。$"

SecretBase_Text_Trainer2Intro:
	.string "拥有一座宅邸当然好，但我更喜欢这\n"
	.string "样的地方，\p"
	.string "因为各种各样的人都会来我这里做客\n"
	.string "。\p"
	.string "那么，来场对战怎么样？$"

SecretBase_Text_Trainer2AcceptBattle:
	.string "就是这样！$"

SecretBase_Text_Trainer2DeclineBattle:
	.string "准备好的话就叫我吧！$"

SecretBase_Text_Trainer2Defeated::
	.string "啊噢！挂了！但我还是喜欢对战！$"

SecretBase_Text_Trainer2PostBattle:
	.string "哎，不管怎么说，我还得去买些家具\n"
	.string "和装饰物品。\p"
	.string "希望我的秘密基地能成为大家都喜欢\n"
	.string "的地方。$"

SecretBase_Text_Trainer2PreChampion:
	.string "拥有一座宅邸当然好，但我更喜欢这\n"
	.string "样的地方，\p"
	.string "因为各种各样的人都会来我这里做客\n"
	.string "。$"

SecretBase_Text_Trainer7Intro:
	.string "我非常喜欢逛商店买家具和装饰物品\n"
	.string "，\p"
	.string "也同样喜欢培育宝可梦。\p"
	.string "如果你愿意的话，跟我的宝可梦对战\n"
	.string "怎么样？$"

SecretBase_Text_Trainer7AcceptBattle:
	.string "谢谢，开始吧？$"

SecretBase_Text_Trainer7DeclineBattle:
	.string "啊，真遗憾……$"

SecretBase_Text_Trainer7Defeated::
	.string "我认输……$"

SecretBase_Text_Trainer7PostBattle:
	.string "真高兴！现在我该去买东西了！$"

SecretBase_Text_Trainer7PreChampion:
	.string "我非常喜欢逛商店买家具和装饰物品\n"
	.string "，\p"
	.string "也同样喜欢培育宝可梦。$"

SecretBase_Text_Trainer3Intro:
	.string "有些人把秘密基地建在别人很难找到\n"
	.string "的地方，是因为想低调行事吗？\p"
	.string "不过你找到了我这里，来对战如何？$"

SecretBase_Text_Trainer3AcceptBattle:
	.string "我不会被你轻易打败的！$"

SecretBase_Text_Trainer3DeclineBattle:
	.string "哦……是因为你找来这个地方很累吗\n"
	.string "？$"

SecretBase_Text_Trainer3Defeated::
	.string "我失败了……$"

SecretBase_Text_Trainer3PostBattle:
	.string "我失败了……你的秘密基地在哪儿？\n"
	.string "我也会去拜访你的。$"

SecretBase_Text_Trainer3PreChampion:
	.string "有些人把秘密基地建在别人很难找到\n"
	.string "的地方，是因为想低调行事吗？$"

SecretBase_Text_Trainer8Intro:
	.string "人们说有很多得到装饰物品的方式，\p"
	.string "我们来比赛谁能得到更好的家具和装\n"
	.string "饰吧！\p"
	.string "不过同时，想对战吗？$"

SecretBase_Text_Trainer8AcceptBattle:
	.string "这里是我的秘密基地，我是不会输的\n"
	.string "！$"

SecretBase_Text_Trainer8DeclineBattle:
	.string "我随时愿意跟你对战。$"

SecretBase_Text_Trainer8Defeated::
	.string "哎？我刚刚输掉了？$"

SecretBase_Text_Trainer8PostBattle:
	.string "收集装饰物品我是不会输给你的，下\n"
	.string "次再来玩！$"

SecretBase_Text_Trainer8PreChampion:
	.string "人们说有很多得到装饰物品的方式，\p"
	.string "我们来比赛谁能得到更好的家具和装\n"
	.string "饰吧！$"

SecretBase_Text_Trainer4Intro:
	.string "我寻找一个中意的地点，然后用喜欢\n"
	.string "的装饰物品来装点它。\p"
	.string "我培育自己喜欢的宝可梦，并与它一\n"
	.string "同成长。\p"
	.string "这是我的生活。要和我对战吗？$"

SecretBase_Text_Trainer4AcceptBattle:
	.string "让我看看你的本事吧！$"

SecretBase_Text_Trainer4DeclineBattle:
	.string "我想有时候你也没有兴趣。$"

SecretBase_Text_Trainer4Defeated::
	.string "我已经领教了你的本领了。$"

SecretBase_Text_Trainer4PostBattle:
	.string "我们都可以变得更强，一起加油吧！$"

SecretBase_Text_Trainer4PreChampion:
	.string "我寻找一个中意的地点，然后用喜欢\n"
	.string "的装饰物品来装点它。\p"
	.string "我培育自己喜欢的宝可梦，并与它一\n"
	.string "同成长。\p"
	.string "每一天都是最好的一天。$"

SecretBase_Text_Trainer9Intro:
	.string "通过观察人们拥有的装饰物品的种类\n"
	.string "和摆放它们的方法，就可以了解到很\l"
	.string "多关于这个人的个性和品位的事情。\p"
	.string "你看出我的品味如何了吗？无话可说\n"
	.string "了吗？\p"
	.string "要不要再看看我的对战品味？$"

SecretBase_Text_Trainer9AcceptBattle:
	.string "不能退缩！$"

SecretBase_Text_Trainer9DeclineBattle:
	.string "我很乐意随时向你展示我的风格。$"

SecretBase_Text_Trainer9Defeated::
	.string "你拥有至高的天份！你的力量是无限\n"
	.string "大的……$"

SecretBase_Text_Trainer9PostBattle:
	.string "觉得我的风格怎么样？我一直在不断\n"
	.string "完善！$"

SecretBase_Text_Trainer9PreChampion:
	.string "通过观察人们拥有的装饰物品的种类\n"
	.string "和摆放它们的方法，就可以了解到很\l"
	.string "多关于这个人的个性和品位的事情。\p"
	.string "你看出我的品味如何了吗？无话可说\n"
	.string "了吗？$"
