ShoalCave_LowTideEntranceRoom_Text_AreYouPlanningOnGoingInThere:
	.string "你要向深处去吗？\p"
	.string "那么帮我收集一些浅滩海盐和浅滩贝\n"
	.string "壳怎么样？\p"
	.string "如果有足够的材料的话，我可以帮你\n"
	.string "制作点好东西。$"

ShoalCave_LowTideEntranceRoom_Text_BringMe4ShoalSaltAndShells:
	.string "如果浅滩海盐和浅滩贝壳各有4个的\n"
	.string "话，我就能制作贝壳之铃……\p"
	.string "原材料每天都可以采到。$"

ShoalCave_LowTideEntranceRoom_Text_WouldYouLikeShellBell:
	.string "啊，是浅滩海盐和浅滩贝壳！数量足\n"
	.string "够了！\p"
	.string "想要把它们做成贝壳之铃吗？$"

ShoalCave_LowTideEntranceRoom_Text_MakeShellBellRightAway:
	.string "好的，我马上帮你做贝壳之铃。\p"
	.string "…… …… …… ……\n"
	.string "…… …… …… ……\p"
	.string "好了！做完了！$"

ShoalCave_LowTideEntranceRoom_Text_ExplainShellBell:
	.string "把这个让宝可梦携带的话，宝可梦肯\n"
	.string "定会喜欢上它的。\p"
	.string "啊，贝壳之铃发出的乐声……那是多\n"
	.string "么美妙！\p"
	.string "原料每天都能采到原，想要的话我还\n"
	.string "可以做更多。$"

ShoalCave_LowTideEntranceRoom_Text_WantedToMakeShellBell:
	.string "哎……是吗……真想做一个贝壳之铃\n"
	.string "啊……$"

ShoalCave_LowTideEntranceRoom_Text_NoSpaceInYourBag:
	.string "如果我做好了的话你的包包里就没有\n"
	.string "空间了，\p"
	.string "腾出些地方再回来吧。$"

ShoalCave_Text_WasShoalSaltNowNothing:
	.string "这儿原来有浅滩海盐，但现在什么也\n"
	.string "没有了。$"

ShoalCave_Text_WasShoallShellNowNothing:
	.string "这儿原来有浅滩贝壳，但现在什么也\n"
	.string "没有了。$"
