CeladonCity_GameCorner_Text_TryPokemonPrinter::
	.string "这是宝可梦打印机！\p"
	.string "它可以把你的宝可梦印在训练家卡片\n"
	.string "的背面。\p"
	.string "只需要¥50。要试一试吗？$"

CeladonCity_GameCorner_Text_DontHaveEnoughMoney::
	.string "你的钱不够。$"

CeladonCity_GameCorner_Text_ChoosePrintType::
	.string "请选择打印类型。$"

CeladonCity_GameCorner_Text_BigSmileForPhoto::
	.string "拍照时请露出灿烂的笑容！三..\n"
	.string "....二......一...\l"
	.string "...\p"
	.string "咔嚓！$"

CeladonCity_GameCorner_Text_PrintIsReadyCheckTrainerCard::
	.string "宝可梦照片已经打印好啦！去确认一\n"
	.string "下你的训练家卡片吧。$"

FourIsland_House2_Text_WishICouldShowOffStickers::
	.string "嘻嘻......我收集了好多贴纸\n"
	.string "呢。真想好好炫耀一下......$"

FourIsland_House2_Text_GiveYouStickerIfYouBrag::
	.string "哇，太棒了！你可找对人啦！\p"
	.string "看呀看呀！看到了吗看到了吗？这些\n"
	.string "都是我的贴纸！看我收集了多少！\p"
	.string "你肯定也很想要吧？绝对想要对不\n"
	.string "对！\p"
	.string "只要你跟我吹嘘一下你身上有什么了\n"
	.string "不起的事情，我就送你一张贴纸。\p"
	.string "你要跟我吹嘘什么呢？$"

FourIsland_House2_Text_BragAboutSomethingForMe::
	.string "跟我吹嘘吹嘘你的事吧。我就送你一\n"
	.string "张贴纸。$"

FourIsland_House2_Text_BragAboutWhatToday::
	.string "哎呀，你好！吹牛大王来啦。\p"
	.string "你今天打算吹嘘些什么呢？$"

FourIsland_House2_Text_WowHoFLowest::
	.string "哇哦，你成功登上殿堂了啊。\p"
	.string "挺厉害的嘛，嗯！这个就送你一张\n"
	.string "吧。$"

FourIsland_House2_Text_WowHoFLow::
	.string "哇哦，你经常登上殿堂呢！\p"
	.string "真让人佩服，嗯！这个就送你一张\n"
	.string "吧。$"

FourIsland_House2_Text_WowHoFHigh::
	.string "哇塞！你登上殿堂这么多次啦？这真\n"
	.string "的太厉害了，嗯！\p"
	.string "宝可梦联盟都快成你家开的了！这个\n"
	.string "就送你一张吧。$"

FourIsland_House2_Text_WowHoFHighest::
	.string "不会吧！你登上殿堂这么多次？！\p"
	.string "简直厉害到没边了，嗯！服了你了，\n"
	.string "这个必须送给你。$"

FourIsland_House2_Text_HoFStickerApplied::
	.string "在训练家卡片上贴上了殿堂贴纸。$"

FourIsland_House2_Text_ComeBackWithBetterStoryHoF::
	.string "嗯......\p"
	.string "下次带个更厉害的故事来，好吗？$"

FourIsland_House2_Text_LivingLegendHoF::
	.string "哎呀，不行不行了。\p"
	.string "你简直就是活着的传奇啊。我已经没\n"
	.string "有贴纸可以给你了。$"

FourIsland_House2_Text_WowEggsLowest::
	.string "哇哦，原来还有宝可梦蛋这种东西？\n"
	.string "我以前都不知道呢！\p"
	.string "挺不错的嘛，嗯！这个就送你一张\n"
	.string "吧。$"

FourIsland_House2_Text_WowEggsLow::
	.string "你孵化了那么多蛋啊？你肯定特别喜\n"
	.string "欢蛋吧！\p"
	.string "真让人佩服，嗯！这个就送你一张\n"
	.string "吧。$"

FourIsland_House2_Text_WowEggsHigh::
	.string "哇塞！你孵了超级多的蛋啊！\p"
	.string "你简直就是一台孵蛋机！这个就送你\n"
	.string "一张吧。$"

FourIsland_House2_Text_WowEggsHighest::
	.string "什......你孵了那么多蛋？！\p"
	.string "你对蛋的爱到底是怎么回事啊？简直\n"
	.string "厉害到没边了，嗯！\p"
	.string "你实在太了不起了，真的。服了你\n"
	.string "了，这个必须送给你。$"

FourIsland_House2_Text_EggStickerApplied::
	.string "在训练家卡片上贴上了蛋贴纸。$"

FourIsland_House2_Text_ComeBackWithBetterStoryEggs::
	.string "嗯......\p"
	.string "下次带个更厉害的故事来，好吗？$"

FourIsland_House2_Text_LivingLegendEggs::
	.string "哎呀，不行不行了。\p"
	.string "你简直就是活着的传奇啊。我已经没\n"
	.string "有贴纸可以给你了。$"

FourIsland_House2_Text_WowLinkWinsLowest::
	.string "哇，你在通信对战中屡屡获胜是吧？\p"
	.string "确实相当厉害呢！这个送给你吧。$"

FourIsland_House2_Text_WowLinkWinsLow::
	.string "你在通信对战中赢过朋友很多次吧？\p"
	.string "实力真令人佩服呢！这个送给你吧。$"

FourIsland_House2_Text_WowLinkWinsHigh::
	.string "哇！你打败朋友的次数多得吓人啊。\p"
	.string "可别因此连朋友都做不成哦？这个送\n"
	.string "给你吧。$"

FourIsland_House2_Text_WowLinkWinsHighest::
	.string "哇、哇塞！太可怕了！你获胜的次数\n"
	.string "多得难以置信！\p"
	.string "光是想象你到底有多强，我就觉得喘\n"
	.string "不过气了。\p"
	.string "你简直就是对手的噩梦！好，这个非\n"
	.string "给你不可了。$"

FourIsland_House2_Text_VictoryStickerApplied::
	.string "在训练家卡片上贴上了胜利贴纸。$"

FourIsland_House2_Text_ComeBackWithBetterStoryLinkWins::
	.string "嗯......\p"
	.string "下次带个更厉害的故事来，好吗？$"

FourIsland_House2_Text_LivingLegendLinkWins::
	.string "哎呀，不行不行了。\p"
	.string "你简直就是活着的传奇啊。我已经没\n"
	.string "有贴纸可以给你了。$"
