Route3_Text_ColtonRematchIntro::
	.string "喂！我在常青森林见过你！$"

Route3_Text_BenRematchIntro::
	.string "嗨！我喜欢短裤！穿着既舒服又方便\n"
	.string "活动！\p"
	.string "你也应该穿短裤才对！$"

Route3_Text_JaniceRematchIntro::
	.string "打扰一下！你一直盯着我看，对不\n"
	.string "对？$"

Route3_Text_GregRematchIntro::
	.string "你也是训练家吧？那就马上来过过招\n"
	.string "吧！$"

Route3_Text_SallyRematchIntro::
	.string "你看我的那种眼神......真是让我太\n"
	.string "感兴趣了！$"

Route3_Text_CalvinRematchIntro::
	.string "喂！你怎么回事啊？你竟然还是没有\n"
	.string "穿短裤！$"

Route3_Text_JamesRematchIntro::
	.string "我要用我刚开始培育的宝可梦来和你\n"
	.string "对战！$"

Route3_Text_RobinRematchIntro::
	.string "呀！是你推我吗？$"

Route4_Text_CrissyRematchIntro::
	.string "我总是在月见山捕捉蘑菇宝可梦。$"

Route6_Text_RickyRematchIntro::
	.string "啊！你就是那个偷听我们说话的多管\n"
	.string "闲事的小孩！$"

Route6_Text_NancyRematchIntro::
	.string "打扰一下！我不是说过这是我们的私\n"
	.string "人谈话吗？\p"
	.string "随便偷听别人说话，你这也太没礼貌\n"
	.string "了！$"

Route6_Text_KeigoRematchIntro::
	.string "我正想找一只不是虫属性的好宝可\n"
	.string "梦，可是......$"

Route6_Text_JeffRematchIntro::
	.string "咦？你还想再和我较量一场吗？$"

Route6_Text_IsabelleRematchIntro::
	.string "我吗？好吧，那我就陪你玩一次。$"

Route6_Text_ElijahRematchIntro::
	.string "嘿，好久不见！你的实力变强了吗？$"

Route8_Text_AidanRematchIntro::
	.string "你玩宝可梦挺在行，不过化学成绩怎\n"
	.string "么样呢？$"

Route8_Text_StanRematchIntro::
	.string "好嘞！我们再来战一局吧！$"

Route8_Text_GlennRematchIntro::
	.string "想要在对战中取胜就必须讲究策略。\p"
	.string "你有照着我的建议做吗？$"

Route8_Text_PaigeRematchIntro::
	.string "我收集了好多尼多兰。虽然不想让它\n"
	.string "们进化，可是......$"

Route8_Text_LeslieRematchIntro::
	.string "上学很有趣，但我觉得宝可梦也一样\n"
	.string "很有趣。$"

Route8_Text_AndreaRematchIntro::
	.string "喵喵和猫老大都好可爱，喵~喵~喵\n"
	.string "~！$"

Route8_Text_MeganRematchIntro::
	.string "我们像这样傻站着可能看起来挺蠢\n"
	.string "的，但我随时都能对战！$"

Route8_Text_RichRematchIntro::
	.string "我可是个随性狂放的游戏老手！现在\n"
	.string "正连胜呢！$"

Route8_Text_JuliaRematchIntro::
	.string "有什么又可爱、又圆滚滚、又毛茸茸\n"
	.string "的宝可梦呢？\p"
	.string "你心里已经有答案了吧？$"

Route8_Text_RicardoRematchIntro::
	.string "哥们，我的单车还是毛病不断。$"

Route8_Text_JarenRematchIntro::
	.string "好小子！这次我可绝不会手下留情！$"

Route8_Text_EliRematchIntro::
	.string "惠里：我们双胞胎的力量变得更加厉\n"
	.string "害了！$"

Route8_Text_AnneRematchIntro::
	.string "安妮：我们双胞胎的力量升级了！$"

Route9_Text_AliciaRematchIntro::
	.string "我们又要对战了吗？这次你输定了！$"

Route9_Text_ChrisRematchIntro::
	.string "我可没忘记你带着那些帅气好看的宝\n"
	.string "可梦呢。$"

Route9_Text_DrewRematchIntro::
	.string "我想穿过岩山隧道去紫苑镇......\p"
	.string "可一路上总是被大家拦下来对战...\n"
	.string "...$"

Route9_Text_CaitlinRematchIntro::
	.string "今天你休想小看我！我们来动真格\n"
	.string "的！$"

Route9_Text_JeremyRematchIntro::
	.string "哇哈哈哈！太棒了！我正闲得发慌\n"
	.string "呢！$"

Route9_Text_BriceRematchIntro::
	.string "哈哈哈！还是一如既往地难缠啊！$"

Route9_Text_BrentRematchIntro::
	.string "我每天都起大早特训，终于把宝可梦\n"
	.string "从小茧给培养长大了！$"

Route9_Text_AlanRematchIntro::
	.string "哈哈哈哈！这次我一定会赢！$"

Route9_Text_ConnerRematchIntro::
	.string "去拿下胜利吧，我超级厉害的虫属性\n"
	.string "宝可梦！$"

Route10_Text_MarkRematchIntro::
	.string "哇，你又来啦？难道你也是宝可梦\n"
	.string "狂？想看看我的收藏吗？$"

Route10_Text_ClarkRematchIntro::
	.string "哈--阿嚏--！喷嚏完全停不下来啦！$"

Route10_Text_HermanRematchIntro::
	.string "嗨，小朋友！我给你看过我的宝可梦\n"
	.string "了吗？$"

Route10_Text_HeidiRematchIntro::
	.string "我又去挑战宝可梦道馆了。\p"
	.string "......不过还是老样子输掉了"
	.string "。$"

Route10_Text_TrentRematchIntro::
	.string "啊！山里的空气太清新美味了！真是\n"
	.string "好得让我舍不得离开！$"

Route10_Text_CarolRematchIntro::
	.string "我头都开始发晕了。登山走得太久\n"
	.string "了......$"

Route11_Text_HugoRematchIntro::
	.string "输赢平手都无所谓！现在就来再战一\n"
	.string "场！$"

Route11_Text_JasperRematchIntro::
	.string "全力对战才是最刺激的。我可还没玩\n"
	.string "够呢！$"

Route11_Text_EddieRematchIntro::
	.string "规则你都懂吧？来吧，可不许耍赖！$"

Route11_Text_BraxtonRematchIntro::
	.string "嗨，你好！\p"
	.string "不过小心点！我还在铺设电缆呢！$"

Route11_Text_DillonRematchIntro::
	.string "我刚当上训练家不久。不过，我觉得\n"
	.string "我能赢。$"

Route11_Text_DirkRematchIntro::
	.string "哇哈哈哈！我可从来没输过！\p"
	.string "......就算输过，我也早就忘得一干\n"
	.string "二净啦！$"

Route11_Text_DarianRematchIntro::
	.string "我以前从来没赢过......\p"
	.string "也许我注定就是这个命吧......$"

Route11_Text_YasuRematchIntro::
	.string "我可是全班最厉害的。每天早晚我都\n"
	.string "在特训！$"

Route11_Text_BernieRematchIntro::
	.string "小心带电的电线！$"

Route11_Text_DaveRematchIntro::
	.string "我精心培育了我的宝可梦。它们现在\n"
	.string "肯定准备好了。这次绝对能赢。$"

Route12_Text_NedRematchIntro::
	.string "好耶！有鱼咬钩了！这、这说不定是\n"
	.string "个大家伙！$"

Route12_Text_ChipRematchIntro::
	.string "你终于来啦。钓鱼就是一场耐心的等\n"
	.string "待。$"

Route12_Text_JustinRematchIntro::
	.string "还是找不到月之石......你找到了\n"
	.string "吗？$"

Route12_Text_LucaRematchIntro::
	.string "电属性一直都是我的专长。\p"
	.string "不过我对海里的宝可梦可是一窍不\n"
	.string "通。$"

Route12_Text_HankRematchIntro::
	.string "钓鱼狂 vs 宝可梦少年！再战一轮，\n"
	.string "开打！$"

Route12_Text_ElliotRematchIntro::
	.string "我很喜欢钓鱼，别误会啊。但我真希\n"
	.string "望能多接点活儿............可要戒\l"
	.string "掉钓鱼实在太难了！$"

Route12_Text_AndrewRematchIntro::
	.string "钓上来了什么？\p"
	.string "不打赢我，你可永远都不会知道！$"

Route12_Text_JesRematchIntro::
	.string "杰斯：今天只要赢了，我就向吉亚求\n"
	.string "婚。$"

Route12_Text_GiaRematchIntro::
	.string "吉亚：喂，杰斯......我都已经等了\n"
	.string "好久啦。\p"
	.string "如果我们今天赢了，我就嫁给你！$"

Route13_Text_SebastianRematchIntro::
	.string "我的鸟宝可梦还记得你呢！$"

Route13_Text_SusieRematchIntro::
	.string "我想趁着自己还是小孩子的时候，成\n"
	.string "为最厉害的训练家！$"

Route13_Text_ValerieRematchIntro::
	.string "哇！你拿到了更多帅气的徽章呢！$"

Route13_Text_GwenRematchIntro::
	.string "我那些可爱长大的宝可梦，希望能和\n"
	.string "你重新切磋一下呢。$"

Route13_Text_AlmaRematchIntro::
	.string "我掏空了所有积蓄，买了更多的速度\n"
	.string "增强剂。$"

Route13_Text_PerryRematchIntro::
	.string "这次我可不会输了。风势正站在我这\n"
	.string "一边！$"

Route13_Text_LolaRematchIntro::
	.string "哎呀，你又来啦？\p"
	.string "好啊，小可爱，我就再陪你玩一局\n"
	.string "吧。$"

Route13_Text_SheilaRematchIntro::
	.string "你就不能把和我对战过的事给忘了\n"
	.string "吗？$"

Route13_Text_JaredRematchIntro::
	.string "你瞅啥呢？！$"

Route13_Text_RobertRematchIntro::
	.string "我向来只用鸟宝可梦。我已经把一切\n"
	.string "都倾注在它们身上了。$"

Route14_Text_CarterRematchIntro::
	.string "我用了招式学习器，让宝可梦学会了\n"
	.string "很厉害的招式。$"

Route14_Text_MitchRematchIntro::
	.string "这一次，我的鸟宝可梦应该已经做好\n"
	.string "战斗的准备了。$"

Route14_Text_BeckRematchIntro::
	.string "你有在宝可梦身上用招式学习器吗？\n"
	.string "光放在包里可一点用都没有哦。$"

Route14_Text_MarlonRematchIntro::
	.string "你教会鸟宝可梦怎么“飞翔”了吗？\p"
	.string "学会的话，你就能和它一起翱翔天际\n"
	.string "了！一定要试试看哦。$"

Route14_Text_DonaldRematchIntro::
	.string "关于生着双翼的幻影传说......你应\n"
	.string "该听说过吧？$"

Route14_Text_BennyRematchIntro::
	.string "虽然我提不起什么劲，但行吧。来\n"
	.string "战！$"

Route14_Text_LukasRematchIntro::
	.string "嘿！我记得你！\p"
	.string "来吧来吧，上啊，上啊，上啊！$"

Route14_Text_IsaacRematchIntro::
	.string "你又跑来了啊？少废话，开打！$"

Route14_Text_GeraldRematchIntro::
	.string "就是因为这里地势开阔，我们才在这\n"
	.string "儿飙车的。$"

Route14_Text_MalikRematchIntro::
	.string "要宝可梦对战对吧？太酷了！大干一\n"
	.string "场吧！$"

Route14_Text_KiriRematchIntro::
	.string "琪莉：阿让，希望我们今天能赢。$"

Route14_Text_JanRematchIntro::
	.string "阿让：琪莉，上吧！这次我们一定要\n"
	.string "赢！$"

Route15_Text_KindraRematchIntro::
	.string "我要继续用交换来的宝可梦来进行对\n"
	.string "战！$"

Route15_Text_BeckyRematchIntro::
	.string "你看起来挺好对付的，我觉得我能\n"
	.string "赢。\p"
	.string "让我再试一次吧！$"

Route15_Text_EdwinRematchIntro::
	.string "只要我一吹口哨，鸟宝可梦们就会聚\n"
	.string "集过来。\p"
	.string "真是太可爱了！$"

Route15_Text_ChesterRematchIntro::
	.string "嗯？我的鸟儿们在发抖？！等等，你\n"
	.string "不是那个训练家......$"

Route15_Text_GraceRematchIntro::
	.string "哎呀，真是个可爱的小家伙！就像招\n"
	.string "人疼的宝可梦一样！我想起你来了！$"

Route15_Text_OliviaRematchIntro::
	.string "因为我一个人住，所以培育宝可梦来\n"
	.string "防身护卫。\p"
	.string "这一点至今未变。$"

Route15_Text_ErnestRematchIntro::
	.string "喂，小鬼！放马过来！这些可是我从\n"
	.string "某个窝囊废那里夺来的！$"

Route15_Text_AlexRematchIntro::
	.string "小鬼，输给我的话，就把你所有的钱\n"
	.string "都交出来！$"

Route15_Text_CeliaRematchIntro::
	.string "现在什么最潮最流行？那当然是交换\n"
	.string "宝可梦啦。$"

Route15_Text_YazminRematchIntro::
	.string "还想再和我的宝可梦对战吗？$"

Route15_Text_MyaRematchIntro::
	.string "玛亚：嗨，我们真有缘呢，总能遇\n"
	.string "到！\p"
	.string "能再帮我陪弟弟特训一下吗？$"

Route15_Text_RonRematchIntro::
	.string "罗恩：我姐姐变得更厉害了......$"

Route16_Text_LaoRematchIntro::
	.string "你想干嘛？$"

Route16_Text_KojiRematchIntro::
	.string "这自行车真帅！识相的就快交出来！$"

Route16_Text_LukeRematchIntro::
	.string "出来玩玩吧，小老鼠。我会好好招待\n"
	.string "你的！$"

Route16_Text_HideoRematchIntro::
	.string "喂，等等！不要叫了我之后又跑掉\n"
	.string "啊！$"

Route16_Text_CamronRematchIntro::
	.string "我现在肚子饿得发慌，脾气暴躁！真\n"
	.string "想找个沙包好好揍一顿！$"

Route16_Text_RubenRematchIntro::
	.string "哟，你好啊！咱们来痛痛快快玩一场\n"
	.string "吧！$"

Route16_Text_JedRematchIntro::
	.string "杰德：你是来看我们那无边无际的深\n"
	.string "情厚爱吗？$"

Route16_Text_LeaRematchIntro::
	.string "莉亚：有时候，我们这热烈的爱连我\n"
	.string "自己都感到害怕。$"

Route17_Text_RaulRematchIntro::
	.string "我早就说过了，靠跟小鬼对战根本不\n"
	.string "可能发大财。$"

Route17_Text_IsaiahRematchIntro::
	.string "小家伙，我可是对自己的体魄自豪得\n"
	.string "很。放马过来吧！$"

Route17_Text_VirgilRematchIntro::
	.string "你出来散步吗？$"

Route17_Text_BillyRematchIntro::
	.string "我们是骑行族！公路可是我们的天\n"
	.string "下，小子！$"

Route17_Text_NikolasRematchIntro::
	.string "今天霹雳电球可要狠狠电你一顿了！$"

Route17_Text_ZeekRematchIntro::
	.string "我明明给宝可梦升级了，可它就是不\n"
	.string "进化。为什么啊？$"

Route17_Text_JamalRematchIntro::
	.string "哇啊！我真的得好好运动，狠狠减掉\n"
	.string "点赘肉了！$"

Route17_Text_CoreyRematchIntro::
	.string "来当个叛逆少年吧！$"

Route17_Text_JaxonRematchIntro::
	.string "嘿，真是辆好自行车！骑起来手感怎\n"
	.string "么样？$"

Route17_Text_WilliamRematchIntro::
	.string "走开，小鬼！我都快累趴下了！$"

Route18_Text_WiltonRematchIntro::
	.string "我找遍了每一片草丛，想发现新的宝\n"
	.string "可梦。\p"
	.string "但找起来可真不容易啊......$"

Route18_Text_RamiroRematchIntro::
	.string "咕噜咕噜咕--！我学的鸟叫声是不是\n"
	.string "更像了？$"

Route18_Text_JacobRematchIntro::
	.string "我之前就警告过你，这里是我的地\n"
	.string "盘！\p"
	.string "别再让我看到你在这附近晃悠。$"

Route19_Text_RichardRematchIntro::
	.string "我的热身运动差不多做完了，准备去\n"
	.string "游泳咯。$"

Route19_Text_ReeceRematchIntro::
	.string "等等！慢一点！万一心脏受不了怎么\n"
	.string "办？$"

Route19_Text_MatthewRematchIntro::
	.string "我最喜欢游泳了！我想你是喜欢冲浪\n"
	.string "的那种吧。$"

Route19_Text_DouglasRematchIntro::
	.string "海平面的那一头有什么呢？你见过\n"
	.string "吗？$"

Route19_Text_DavidRematchIntro::
	.string "我又尝试潜水去抓宝可梦了，但还是\n"
	.string "跟之前一样无功而返。$"

Route19_Text_TonyRematchIntro::
	.string "看着大海就能让我忘掉所有不顺心的\n"
	.string "事。\p"
	.string "......比如上次输给你的事！$"

Route19_Text_AnyaRematchIntro::
	.string "你总能骑着你的宝可梦......\p"
	.string "看起来好惬意啊。如果我赢了，能把\n"
	.string "它让给我吗？$"

Route19_Text_AliceRematchIntro::
	.string "游泳虽然很棒！但晒伤可一点都不好\n"
	.string "受！$"

Route19_Text_AxleRematchIntro::
	.string "这片海域凶险得很！你可别再来这里\n"
	.string "了！$"

Route19_Text_ConnieRematchIntro::
	.string "我和朋友一起游到了这里......我都\n"
	.string "累坏了......真的还要再对战一次\l"
	.string "吗？$"

Route19_Text_LiaRematchIntro::
	.string "莉亚：你知道我弟弟才刚当上训练家\n"
	.string "对吧？\p"
	.string "我想让他变得更强，所以还要再请你\n"
	.string "帮个忙。$"

Route19_Text_LucRematchIntro::
	.string "卢克：姐姐把宝可梦的知识都教给我\n"
	.string "了。\p"
	.string "不知道我是不是变得更厉害了？$"

Route20_Text_BarryRematchIntro::
	.string "这里的水很浅，有很多人在这边游泳\n"
	.string "呢。$"

Route20_Text_ShirleyRematchIntro::
	.string "看到我在双子岛度假，你是不是很羡\n"
	.string "慕呀？$"

Route20_Text_TiffanyRematchIntro::
	.string "我喜欢在这波浪之间，和鱼儿们一起\n"
	.string "随波漂浮。$"

Route20_Text_IreneRematchIntro::
	.string "你也是在度假吗？$"

Route20_Text_DeanRematchIntro::
	.string "瞧瞧我这身健美的体魄！\p"
	.string "比以前还要更加壮硕了呢！$"

Route20_Text_DarrinRematchIntro::
	.string "你为什么骑着宝可梦呀？难道你还没\n"
	.string "学会游泳吗？$"

Route20_Text_RogerRematchIntro::
	.string "我是骑着鸟宝可梦飞过来的。$"

Route20_Text_NoraRematchIntro::
	.string "男朋友送了我大珍珠。而且，它们现\n"
	.string "在变得更大了！$"

Route20_Text_MissyRematchIntro::
	.string "我从红莲岛一路游到了这里。正如我\n"
	.string "之前所说，真是不容易啊。$"

Route20_Text_MelissaRematchIntro::
	.string "西边的红莲岛上有一座宝可梦研究\n"
	.string "所。\p"
	.string "我爸爸就在那里工作。$"

Route21_North_Text_RonaldRematchIntro::
	.string "你想知道鱼儿有没有上钩吗？$"

Route21_North_Text_WadeRematchIntro::
	.string "我又大丰收了！想再跟我比试一次\n"
	.string "吗？$"

Route21_North_Text_SpencerRematchIntro::
	.string "大海洗涤了我的身心！$"

@ Unused trainer from RB that had a rematch intro added
Route21_North_Text_CueBallRematchIntro::
	.string "今天我又忍不住跑来游泳了啊！$"

Route21_South_Text_JackRematchIntro::
	.string "我的宝可梦是在海上捉到的。我平时\n"
	.string "就在这里训练它们。$"

Route21_South_Text_JeromeRematchIntro::
	.string "我现在又在参加一场铁人三项比赛！$"

Route21_South_Text_RolandRematchIntro::
	.string "啊！感受这阳光和微风吧！$"

Route21_South_Text_ClaudeRematchIntro::
	.string "喂，快别闹了。你总是把鱼儿吓跑！$"

Route21_South_Text_NolanRematchIntro::
	.string "在有鱼咬钩之前，来陪陪我吧。$"

Route21_North_Text_LilRematchIntro::
	.string "莉尔：咦？又要对战吗？伊安，你就\n"
	.string "不能自己一个人上吗？$"

Route21_North_Text_IanRematchIntro::
	.string "伊安：我老姐还是这么懒散。帮我好\n"
	.string "好管管她吧！$"

Route25_Text_JoeyRematchIntro::
	.string "只要我在这里，就绝不会认输！$"

Route25_Text_DanRematchIntro::
	.string "爸爸曾带我参加过枯叶市圣特安努号\n"
	.string "上的盛大派对。$"

Route25_Text_FlintRematchIntro::
	.string "我可是个帅气的男人。我有女朋友\n"
	.string "啦！\p"
	.string "这次我一定要让她看看我有多帅气！$"

Route25_Text_KelseyRematchIntro::
	.string "嗨！我男朋友超帅的！我今天的状态\n"
	.string "也很棒哦！$"

Route25_Text_ChadRematchIntro::
	.string "我有一种预感......我知道一定要再\n"
	.string "跟你对战一次！$"

Route25_Text_HaleyRematchIntro::
	.string "我的朋友有好多可爱的宝可梦。真是\n"
	.string "太让人羡慕了！$"

Route25_Text_FranklinRematchIntro::
	.string "虽然我刚在月见山特训完，但我依然\n"
	.string "干劲十足呢！$"

Route25_Text_NobRematchIntro::
	.string "海角住着一位宝可梦狂人。你看过他\n"
	.string "的收藏了吗？$"

Route25_Text_WayneRematchIntro::
	.string "你又要去见正辉吗？先来和我对战\n"
	.string "吧！$"

Route24_Text_ShaneRematchIntro::
	.string "我在草丛里看到你神勇的表现了！$"

Route24_Text_EthanRematchIntro::
	.string "好！看我把你打得落花流水！$"

Route24_Text_ReliRematchIntro::
	.string "你看起来总是那么忙碌......不觉得\n"
	.string "累吗？$"

Route24_Text_TimmyRematchIntro::
	.string "你肯定非常喜欢来金球桥吧。$"

Route24_Text_AliRematchIntro::
	.string "上次我们对战的时候......\p"
	.string "虽然我是第二个出场的，但我其实是\n"
	.string "最厉害的，对吧？$"

Route24_Text_CaleRematchIntro::
	.string "大家都叫这里金球桥！\p"
	.string "既然你已经赢过我们了，就不能再接\n"
	.string "受桥上的试炼了......\p"
	.string "......不过，随时欢迎再来和我们切\n"
	.string "磋！$"

OneIsland_TreasureBeach_Text_AmaraRematchIntro::
	.string "仰躺着随波起伏......不知不觉时间\n"
	.string "就溜走了......$"

OneIsland_KindleRoad_Text_MariaRematchIntro::
	.string "天气真棒！可不能扫了兴致呢。$"

OneIsland_KindleRoad_Text_AbigailRematchIntro::
	.string "晒伤的地方开始痛起来了......$"

OneIsland_KindleRoad_Text_FinnRematchIntro::
	.string "火鸟之山投下了一片巨大的阴影...\n"
	.string "...$"

OneIsland_KindleRoad_Text_GarrettRematchIntro::
	.string "我有种强烈的预感，这次一定能赢！$"

OneIsland_KindleRoad_Text_TommyRematchIntro::
	.string "等等！等一下！我好像钓到一条大的\n"
	.string "了！$"

OneIsland_KindleRoad_Text_SharonRematchIntro::
	.string "愿意再陪我特训一次吗？$"

OneIsland_KindleRoad_Text_TanyaRematchIntro::
	.string "我们的特训还一天都没落下过！$"

OneIsland_KindleRoad_Text_SheaRematchIntro::
	.string "每天早上吃早饭前，我都会绕着这座\n"
	.string "岛游......整整三圈！$"

OneIsland_KindleRoad_Text_HughRematchIntro::
	.string "对战就要有对战的样子！我都说了，\n"
	.string "快脱掉那身轻浮的行头！$"

OneIsland_KindleRoad_Text_BryceRematchIntro::
	.string "你知道吗，在野外吃东西，不管什么\n"
	.string "都格外美味呢。$"

OneIsland_KindleRoad_Text_ClaireRematchIntro::
	.string "我又吃太饱了，能陪我们对战运动一\n"
	.string "下吗？$"

OneIsland_KindleRoad_Text_KiaRematchIntro::
	.string "希亚：我和哥哥的组合可是天下无敌\n"
	.string "的！\p"
	.string "这次我们绝对不会输！$"

OneIsland_KindleRoad_Text_MikRematchIntro::
	.string "米克：只要和希亚在一起，我们就无\n"
	.string "所畏惧！\p"
	.string "这次一定会证明给你看！$"

ThreeIsland_BondBridge_Text_NikkiRematchIntro::
	.string "我们又要再战一场了吗？$"

ThreeIsland_BondBridge_Text_VioletRematchIntro::
	.string "你从何处而来，又将往何处去？$"

ThreeIsland_BondBridge_Text_AmiraRematchIntro::
	.string "我好想早点不用救生圈就能自己游泳\n"
	.string "啊。$"

ThreeIsland_BondBridge_Text_AlexisRematchIntro::
	.string "好耶，好耶！宝可梦！$"

ThreeIsland_BondBridge_Text_TishaRematchIntro::
	.string "哎呀，我不是跟你说过了吗？拜托你\n"
	.string "离我远点！$"

ThreeIsland_BondBridge_Text_JoyRematchIntro::
	.string "乔伊：我们变强了！变强了好多好\n"
	.string "多！$"

ThreeIsland_BondBridge_Text_MegRematchIntro::
	.string "梅格：今天你可赢不了我们！$"

FiveIsland_WaterLabyrinth_Text_AlizeRematchIntro::
	.string "哎呀，你好！\p"
	.string "你有在优良的环境下培育你的宝可梦\n"
	.string "吗？$"

FiveIsland_ResortGorgeous_Text_DaisyRematchIntro::
	.string "今天我要用这双手，描绘出属于我的\n"
	.string "胜利！$"

FiveIsland_ResortGorgeous_Text_CelinaRematchIntro::
	.string "还要我说几遍？我正在画画呢。请别\n"
	.string "挡着我的视线！$"

FiveIsland_ResortGorgeous_Text_RaynaRematchIntro::
	.string "一点进展都没有......还是找不到合\n"
	.string "适的角度......$"

FiveIsland_ResortGorgeous_Text_JackiRematchIntro::
	.string "哦，你愿意再给我一次机会与你一较\n"
	.string "高下吗？$"

FiveIsland_ResortGorgeous_Text_GillianRematchIntro::
	.string "给我家宝可梦建的泳池马上就要完工\n"
	.string "了。\p"
	.string "到时候你一定要来玩哦。$"

FiveIsland_ResortGorgeous_Text_DestinRematchIntro::
	.string "我很擅长跑步。而且现在跑得更快\n"
	.string "了！$"

FiveIsland_ResortGorgeous_Text_TobyRematchIntro::
	.string "我说，朋友！让我们好好享受这段时\n"
	.string "光吧！$"

FiveIsland_MemorialPillar_Text_MiloRematchIntro::
	.string "我是鸟使者三兄弟的老大。还记得我\n"
	.string "吗？\p"
	.string "没错，我就是最喜欢鸟宝可梦喙部的\n"
	.string "那个人！$"

FiveIsland_MemorialPillar_Text_ChazRematchIntro::
	.string "我是鸟使者三兄弟的老二。\p"
	.string "我最喜欢的是翅膀。再来对战一次\n"
	.string "吧！$"

FiveIsland_MemorialPillar_Text_HaroldRematchIntro::
	.string "我是鸟使者三兄弟的老幺。\p"
	.string "我最喜欢鸟宝可梦的绒毛。真没想到\n"
	.string "还能再见到你！$"

SixIsland_OutcastIsland_Text_TylorRematchIntro::
	.string "我的运气还是那么差。来场对战换换\n"
	.string "心情吧！$"

SixIsland_OutcastIsland_Text_MymoRematchIntro::
	.string "呼......呼......\p"
	.string "我又一口气从6之岛的港口游到这里\n"
	.string "来了。$"

SixIsland_OutcastIsland_Text_NicoleRematchIntro::
	.string "每次我游泳的时候，你总会过来呢。$"

SixIsland_OutcastIsland_Text_AvaRematchIntro::
	.string "艾娃：今天也来一场二对二的海上对\n"
	.string "战吧！$"

SixIsland_OutcastIsland_Text_GebRematchIntro::
	.string "格布：我和姐姐可比以前厉害多啦！$"

SixIsland_GreenPath_Text_JaclynRematchIntro::
	.string "......咦？\p"
	.string "我脑海中明明想着自己家，但瞬间移\n"
	.string "动总是把我送到这里来！$"

SixIsland_WaterPath_Text_RoseRematchIntro::
	.string "哎呀，你好。微风吹拂得还是那么舒\n"
	.string "服呢。$"

SixIsland_WaterPath_Text_EdwardRematchIntro::
	.string "嘿嘿嘿，我又在偷偷练习了。$"

SixIsland_WaterPath_Text_SamirRematchIntro::
	.string "你已经看腻我这样的游泳选手了吗？\n"
	.string "哎呀，别嫌弃嘛！\p"
	.string "再和我对战一场吧！$"

SixIsland_WaterPath_Text_DeniseRematchIntro::
	.string "唉……我男朋友又忙起来了。……$"

SixIsland_WaterPath_Text_EarlRematchIntro::
	.string "快告诉我，这附近的山到底都在哪儿\n"
	.string "啊？$"

SixIsland_WaterPath_Text_MiuRematchIntro::
	.string "美羽：宝可梦，你好呀！又到了玩耍\n"
	.string "的时间啦！$"

SixIsland_WaterPath_Text_MiaRematchIntro::
	.string "美亚：宝可梦，你好呀！又到了对战\n"
	.string "的时间啦！$"

SixIsland_RuinValley_Text_StanlyRematchIntro::
	.string "看来在这个世界上，还留存着许多未\n"
	.string "解之谜呢。$"

SixIsland_RuinValley_Text_FosterRematchIntro::
	.string "嗨，我们之前见过吧？是什么风把你\n"
	.string "又吹来啦？$"

SixIsland_RuinValley_Text_LarryRematchIntro::
	.string "据说这座岛上有神秘的石头。\p"
	.string "自从我们上次相遇之后，你有什么新\n"
	.string "发现吗？$"

SixIsland_RuinValley_Text_DarylRematchIntro::
	.string "能在这么高的地方和你再战一场！$"

SixIsland_RuinValley_Text_HectorRematchIntro::
	.string "我对这一带的地形相当熟悉呢。$"

SevenIsland_TrainerTower_Text_DarioRematchIntro::
	.string "我感应到你的接近了。$"

SevenIsland_TrainerTower_Text_RodetteRematchIntro::
	.string "在这座岛上的某处，沉睡着奇异的宝\n"
	.string "可梦。$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahRematchIntro::
	.string "呀哈哈！\p"
	.string "就算你再来也是白费力气。看我轻轻\n"
	.string "松松把你弹飞！$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonRematchIntro::
	.string "哈罗！你也是我粉丝俱乐部的一员，\n"
	.string "对不对？$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasRematchIntro::
	.string "这座岛也太大了吧......巡逻起来真\n"
	.string "是一件苦差事......$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineRematchIntro::
	.string "我绝不原谅虐待宝可梦的家伙！$"

SevenIsland_SevaultCanyon_Entrance_Text_EveRematchIntro::
	.string "伊芙：我要和乔恩组队，再次并肩作\n"
	.string "战。$"

SevenIsland_SevaultCanyon_Entrance_Text_JonRematchIntro::
	.string "乔恩：只要和伊芙在一起，我就感觉\n"
	.string "我们绝不可能输，永远不会！$"

SevenIsland_SevaultCanyon_Text_CyndyRematchIntro::
	.string "再来对战一场吧。我现在状态绝佳！$"

SevenIsland_SevaultCanyon_Text_EvanRematchIntro::
	.string "就算你碰巧拥有最强的宝可梦也是没\n"
	.string "用的......\p"
	.string "如果不懂得如何驾驭它们，那就毫无\n"
	.string "意义！$"

SevenIsland_SevaultCanyon_Text_JacksonRematchIntro::
	.string "我为了保护环境而工作。反过来，大\n"
	.string "自然也会庇护我！$"

SevenIsland_SevaultCanyon_Text_KatelynRematchIntro::
	.string "每次见到你，你都穿着那双帅气的鞋\n"
	.string "子呢。$"

SevenIsland_SevaultCanyon_Text_LeroyRematchIntro::
	.string "你一定变得更强了吧。拜托了，请跟\n"
	.string "我对战一场！$"

SevenIsland_SevaultCanyon_Text_MichelleRematchIntro::
	.string "我接受了最好的英才教育才变得如此\n"
	.string "强大。\p"
	.string "这一次我绝不会输，绝对不会！$"

SevenIsland_SevaultCanyon_Text_LexRematchIntro::
	.string "雷克斯：我亲爱的妮娅，我们联手就\n"
	.string "必定能赢！$"

SevenIsland_SevaultCanyon_Text_NyaRematchIntro::
	.string "妮娅：我不会拖雷克斯导师的后腿\n"
	.string "的！我们赢定了！$"

SevenIsland_TanobyRuins_Text_BrandonRematchIntro::
	.string "关于这间石室，你有什么新发现吗？$"

SevenIsland_TanobyRuins_Text_BenjaminRematchIntro::
	.string "据说在这深处沉睡着一只神秘的宝可\n"
	.string "梦。$"

SevenIsland_TanobyRuins_Text_EdnaRematchIntro::
	.string "老师正在指导我如何画出更好的画。$"

SevenIsland_TanobyRuins_Text_CliffordRematchIntro::
	.string "今天除了上课，我们还特意再来看了\n"
	.string "看这个石室。$"
