Route4_Frlg_MapScripts::
	.byte 0

Route4_EventScript_Unused::
	end

Route4_EventScript_Woman::
	msgbox Route4_Text_TrippedOverGeodude, MSGBOX_NPC
	end

Route4_EventScript_MtMoonSign::
	msgbox Route4_Text_MtMoonEntrance, MSGBOX_SIGN
	end

Route4_EventScript_RouteSign::
	msgbox Route4_Text_RouteSign, MSGBOX_SIGN
	end

Route4_Text_TrippedOverGeodude::
	.string "哎哟！我被一只岩石宝可梦绊倒了，\n"
	.string "是小拳石啊！$"

Route4_Text_CrissyIntro::
	.string "我来月见山寻找蘑菇宝可梦。$"

Route4_Text_CrissyDefeat::
	.string "这次我一定要抓到它们！$"

Route4_Text_CrissyPostBattle::
	.string "这里应该已经没有蘑菇了。\p"
	.string "可能已经都被我采光了。$"

Route4_Text_MtMoonEntrance::
	.string "月见山山洞的入口$"

Route4_Text_RouteSign::
	.string "4号道路月见山-华蓝市$"

Text_MegaPunchTeach::
	.string "一声巨响！\p"
	.string "伴随着毁灭性的力量！\p"
	.string "在关键时刻，百万吨重拳就是最强悍\n"
	.string "的攻击！你也这么认为吧？\p"
	.string "现在！让我教你的宝可梦学会这个技\n"
	.string "能！$"

Text_MegaPunchDeclined::
	.string "当你知道百万吨重拳价值的时候，你\n"
	.string "一定会回来的。$"

Text_MegaPunchWhichMon::
	.string "很好！想要让哪只宝可梦学习？$"

Text_MegaPunchTaught::
	.string "现在，我们算是同一流派的人了！\p"
	.string "你得快点走，小心被在那边那个只知\n"
	.string "道一味训练攻击力的傻瓜发现。$"

Text_MegaKickTeach::
	.string "一次凶狠的踢击！\p"
	.string "伴随着毁灭性的力量！\p"
	.string "你若能善用百万吨重踢时，它会成为\n"
	.string "最强悍的攻击！你也这么认为吧？\p"
	.string "好的！让我教你的宝可梦使用这个技\n"
	.string "能！$"

Text_MegaKickDeclined::
	.string "当你意识到百万吨重踢的价值时，你\n"
	.string "一定会回来的。$"

Text_MegaKickWhichMon::
	.string "很好！想要让哪只宝可梦学习？$"

Text_MegaKickTaught::
	.string "现在，我们算是同一流派的人了！\p"
	.string "你得快点走，小心被在那边那个只知\n"
	.string "道一味训练攻击力的傻瓜发现。$"

Route4_Text_PeopleLikeAndRespectBrock::
	.string "哇，那是灰色徽章！你从小刚那里得\n"
	.string "到的，没错吧？\p"
	.string "小刚不仅冷静，还很坚强。人们都很\n"
	.string "喜欢他，尊敬他。\p"
	.string "我想成为像他一样的道馆馆主。$"
