SSAnne_1F_Corridor_Frlg_MapScripts::
	.byte 0

SSAnne_1F_Corridor_EventScript_WorkerM::
	msgbox SSAnne_1F_Corridor_Text_LeStrongSilentType, MSGBOX_NPC
	end

SSAnne_1F_Corridor_EventScript_Sailor::
	msgbox SSAnne_1F_Corridor_Text_PassengersAreRestless, MSGBOX_NPC
	end

SSAnne_1F_Corridor_Text_LeStrongSilentType::
	.string "早上好！我是这\n"
	.string "艘船上的服务生！\p"
	.string "很高兴能为您服务！\p"
	.string "………………啊！您是沉默寡言的类型啊！$"

SSAnne_1F_Corridor_Text_PassengersAreRestless::
	.string "这么长的航行使乘客们都感到无所事\n"
	.string "事。\p"
	.string "你可能会遇到一些烦人的家伙来挑战\n"
	.string "你哦！$"

