VerdanturfTown_House_MapScripts::
	.byte 0

VerdanturfTown_House_EventScript_Woman1::
	msgbox VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague, MSGBOX_NPC
	end

VerdanturfTown_House_EventScript_Woman2::
	msgbox VerdanturfTown_House_Text_DefeatEliteFourInARow, MSGBOX_NPC
	end

VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague:
	.string "在遥远的彩悠市最深处，就是宝可梦\n"
	.string "联盟的所在地。\p"
	.string "聚集在那里的训练家都异乎寻常地强\n"
	.string "大。$"

VerdanturfTown_House_Text_DefeatEliteFourInARow:
	.string "我记得，宝可梦联盟规定你要连续跟\n"
	.string "四天王战斗，\p"
	.string "一旦输了，就得从第一个重新开始。$"

