FuchsiaCity_House1_hns_MapScripts::
	.byte 0

FuchsiaCity_House1_EventScript_BillsOlderSister::
	msgbox FuchsiaCity_House1_Text_BillsOlderSister, MSGBOX_NPC
	end

FuchsiaCity_House1_EventScript_Youngster::
	msgbox FuchsiaCity_House1_Text_Youngster, MSGBOX_NPC
	end

FuchsiaCity_House1_Text_BillsOlderSister:
	.string "我爷爷在我哥哥正辉那里，就在华蓝\n"
	.string "海岬。$"

FuchsiaCity_House1_Text_Youngster:
	.string "我在自行车道上看到了这种动作慢吞\n"
	.string "吞的奇怪宝可梦。$"

