BattleFrontier_Lounge4_hns_MapScripts::
	.byte 0

BattleFrontier_Lounge4_EventScript_Woman_hns::
	msgbox BattleFrontier_Lounge4_Text_WonderIfInterviewsAiring_hns, MSGBOX_NPC
	end

BattleFrontier_Lounge4_EventScript_Cook_hns::
	msgbox BattleFrontier_Lounge4_Text_IfIOpenedRestaurantHere_hns, MSGBOX_NPC
	end

BattleFrontier_Lounge4_EventScript_Man_hns::
	msgbox BattleFrontier_Lounge4_Text_NeedBreatherAfterBattles_hns, MSGBOX_NPC
	end

BattleFrontier_Lounge4_Text_WonderIfInterviewsAiring_hns:
	.string "不知道今天会不会播出对强力训练家\n"
	.string "的采访呢？$"

BattleFrontier_Lounge4_Text_IfIOpenedRestaurantHere_hns:
	.string "要是我在这里开家餐厅，绝对能大赚\n"
	.string "一笔。$"

BattleFrontier_Lounge4_Text_NeedBreatherAfterBattles_hns:
	.string "呼……\p"
	.string "在经历了几场激烈的对战后，我得先\n"
	.string "喘口气……\p"
	.string "但即便在休息，我的脑子也一刻不停\n"
	.string "地在构思战术与连招。$"

