VermilionCity_House1_hns_MapScripts::
	.byte 0

VermilionCity_House1_EventScript_Fisher::
	msgbox VermilionCity_House1_Text_FishingDude, MSGBOX_NPC
	end
VermilionCity_House1_EventScript_Photo::
	msgbox VermilionCity_House1_Text_Photo, MSGBOX_NPC
	end
VermilionCity_House1_Text_FishingDude:
	.string "我是钓鱼老爹，钓鱼兄弟里的大哥。\p"
	.string "你见过愤怒之湖的钓鱼大叔了吗？\p"
	.string "他一直梦想着能见到世界上最棒的鲤\n"
	.string "鱼王。\p"
	.string "如果不介意的话，你能把钓到的鲤鱼\n"
	.string "王拿给他瞧瞧吗？\p"
	.string "说不定，你能钓到他梦寐以求的那只\n"
	.string "鲤鱼王呢。$"

VermilionCity_House1_Text_Photo:
	.string "这是一张大家在钓鱼的照片……\n"
	.string "..\p"
	.string "他们看起来玩得很开心……$"
