Route19_Frlg_MapScripts::
	.byte 0

Route19_EventScript_RouteSign::
	msgbox Route19_Text_RouteSign, MSGBOX_SIGN
	end

Route19_Text_RichardIntro::
	.string "在出去游泳前我必须先热身。$"

Route19_Text_RichardDefeat::
	.string "热身好了！$"

Route19_Text_RichardPostBattle::
	.string "谢谢你，孩子！我准备好去游泳了。$"

Route19_Text_ReeceIntro::
	.string "等等！慢慢来！你的心脏会受不了的\n"
	.string "！$"

Route19_Text_ReeceDefeat::
	.string "噢！真冷！$"

Route19_Text_ReecePostBattle::
	.string "注意玛瑙水母。被蛰到会很疼。$"

Route19_Text_MatthewIntro::
	.string "我喜欢游泳！你呢？$"

Route19_Text_MatthewDefeat::
	.string "失败了！$"

Route19_Text_MatthewPostBattle::
	.string "在海里畅游之时即便是遇到海中的宝\n"
	.string "可梦我也毫无惧色。$"

Route19_Text_DouglasIntro::
	.string "地平线外是什么？$"

Route19_Text_DouglasDefeat::
	.string "坏了！$"

Route19_Text_DouglasPostBattle::
	.string "我看见远处环绕着一些小岛！$"

Route19_Text_DavidIntro::
	.string "我试着和宝可梦一起潜水，但是失败\n"
	.string "了。$"

Route19_Text_DavidDefeat::
	.string "救命！$"

Route19_Text_DavidPostBattle::
	.string "我想你必须得钓上海里的宝可梦。$"

Route19_Text_TonyIntro::
	.string "我凝视着大海，就为忘掉所有不愉快\n"
	.string "的事情。$"

Route19_Text_TonyDefeat::
	.string "噢！受伤了！$"

Route19_Text_TonyPostBattle::
	.string "我正凝视着大海，这样就会忘掉所有\n"
	.string "的不快！$"

Route19_Text_AnyaIntro::
	.string "我好喜欢你的坐骑啊！如果我赢了能\n"
	.string "把它送给我吗？$"

Route19_Text_AnyaDefeat::
	.string "呃！我输了！$"

Route19_Text_AnyaPostBattle::
	.string "去双子岛还有老远的一大段路啊……\p"
	.string "我还是回浅红算了……$"

Route19_Text_AliceIntro::
	.string "游泳最棒！太阳什么的最讨厌了！$"

Route19_Text_AliceDefeat::
	.string "我震惊了！$"

Route19_Text_AlicePostBattle::
	.string "我男朋友想要游去双子岛。$"

Route19_Text_AxleIntro::
	.string "喂，小子！这儿的水流很急啊！$"

Route19_Text_AxleDefeat::
	.string "喂！危险！$"

Route19_Text_AxlePostBattle::
	.string "我，我的腿！抽筋了！糟了……$"

Route19_Text_ConnieIntro::
	.string "我和我的朋友一路游了过来……好累\n"
	.string "……$"

Route19_Text_ConnieDefeat::
	.string "我一点力气也没了……$"

Route19_Text_ConniePostBattle::
	.string "如果我要在海上骑一只宝可梦航行，\n"
	.string "那就是拉普拉斯啦。\p"
	.string "拉普拉斯好大的，能让我在海上不沾\n"
	.string "一点儿水。$"

Route19_Text_RouteSign::
	.string "19号航道浅红市-双子岛$"

Route19_Text_LiaIntro::
	.string "真奈：我照顾着我的弟弟。他才刚成\n"
	.string "为一名训练家。$"

Route19_Text_LiaDefeat::
	.string "真奈：对我的弟弟一点办法都没有！$"

Route19_Text_LiaPostBattle::
	.string "真奈：你也有弟弟吗？\p"
	.string "我希望你能教会他各种各样的东西。$"

Route19_Text_LiaNotEnoughMons::
	.string "真奈：我想和我的弟弟一起战斗。\p"
	.string "你没有带着两只宝可梦吗？$"

Route19_Text_LucIntro::
	.string "阿弘：我姐姐教会了我如何游泳和训\n"
	.string "练宝可梦。$"

Route19_Text_LucDefeat::
	.string "阿弘：哇，天哪！有人比我的姐姐还\n"
	.string "要厉害！$"

Route19_Text_LucPostBattle::
	.string "阿弘：我的姐姐又强又漂亮。我觉得\n"
	.string "她太棒了！$"

Route19_Text_LucNotEnoughMons::
	.string "阿弘：我不想和你单独战斗，我要和\n"
	.string "我姐姐一起。\p"
	.string "你没有带着两只宝可梦吗？$"
