Route21_North_Frlg_MapScripts::
	.byte 0

Route21_North_Text_RonaldIntro::
	.string "你想不想知道这儿的鱼是否咬人？$"

Route21_North_Text_RonaldDefeat::
	.string "铛！$"

Route21_North_Text_RonaldPostBattle::
	.string "我什么也捉不到。没有一只好的宝可\n"
	.string "梦！$"

Route21_North_Text_WadeIntro::
	.string "我收服了好多好多！你想不想要呢？$"

Route21_North_Text_WadeDefeat::
	.string "呵呵，鲤鱼王不仅仅是以等级区分\n"
	.string "的，懂吗？$"

Route21_North_Text_WadePostBattle::
	.string "我只想抓鲤鱼王！$"

Route21_North_Text_SpencerIntro::
	.string "海洋洗涤了我的身体和灵魂！$"

Route21_North_Text_SpencerDefeat::
	.string "妈呀！$"

Route21_North_Text_SpencerPostBattle::
	.string "大海是很伟大的，能包容一切，但是\n"
	.string "我也很喜欢山。$"

@ Below is the battle text for the Cue Ball that was on Route 21 in Gen 1.
@ This trainer wasnt used in Gen 3 so their text goes unused/untranslated
@ Interestingly they did add a rematch intro text for this trainer
@ English translations from RB are listed

@ "What's wrong with me swimming?"
Route21_North_Text_CueBallIntro::
	.string "大爷我偶尔也是会来游泳的！$"

@ "Cheap shot!"
Route21_North_Text_CueBallDefeat::
	.string "哇啊啊！$"

@ "I look like what? A studded inner tube? Get lost!"
Route21_North_Text_CueBallPostBattle::
	.string "说我看着很容易浮起来？吵死啦，要\n"
	.string "你多管闲事！$"
