BattleFrontier_Lounge8_hns_MapScripts::
	.byte 0

BattleFrontier_Lounge8_EventScript_Man_hns::
	msgbox BattleFrontier_Lounge8_Text_WhatATrainerNeeds_hns, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_Woman_hns::
	msgbox BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains_hns, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_NinjaBoy_hns::
	msgbox BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling_hns, MSGBOX_NPC
	end

BattleFrontier_Lounge8_Text_WhatATrainerNeeds_hns:
	.string "训练家所需要的......\p"
	.string "知识......策略......\n"
	.string "运气......毅力......\l"
	.string "心灵......勇气......\l"
	.string "还有才能......\p"
	.string "好，我已经全都具备了！我在每座设\n"
	.string "施里都会所向披靡！\p"
	.string "Huh？宝可梦？那是啥？$"

BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains_hns:
	.string "你知道对战开拓区首领吗？\p"
	.string "那是亚希达对管理对战开拓区7处设\n"
	.string "施的7位特别训练家的称呼。$"

BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling_hns:
	.string "在对战塔，有个大姐姐夸我很有对战\n"
	.string "的天赋呢！\p"
	.string "但我更喜欢宝可梦华丽大赛！\p"
	.string "可我一点也不擅长华丽大赛！\p"
	.string "看来有天赋和喜欢并不是一回事啊。$"

