TwoIsland_CapeBrink_House_Frlg_MapScripts::
	.byte 0

@ See move_tutors.inc

Text_UltimateMoveThatMon::
	.string "我终于完美的掌握了最终极的技能！\p"
	.string "但以后它能够被传承下去吗？\p"
	.string "……嗯……嗯！\p"
	.string "你的……啊，\n"
	.string "{STR_VAR_1}……$"

Text_JustMistaken::
	.string "……不……恐怕我看走眼了……$"

Text_AllowMeToTeachMonUltimateMove::
	.string "啊！这就是那个合适的人选！就是这\n"
	.string "只宝可梦！\p"
	.string "{STR_VAR_1}绝对可以掌\n"
	.string "握我的终极技能！\p"
	.string "可以吗？\p"
	.string "可以让{STR_VAR_1}学习\n"
	.string "我的{STR_VAR_2}吗？$"

Text_YouRejectIt::
	.string "哈？你不同意？！好吧……我做不了你\n"
	.string "的主……$"

Text_LetMeConferUltimateMove::
	.string "你答应了？\p"
	.string "太好了，现在我就把\n"
	.string "{STR_VAR_2}教给你的\l"
	.string "{STR_VAR_1}。\p"
	.string "哇哦-哇哦-$"

Text_TaughtMove::
	.string "哈……哈……\p"
	.string "看来这些技能注定是派不上用场了……$"

Text_MakeBestUseOfMove::
	.string "我希望你能把这个技能的威力发挥到\n"
	.string "极致，从而获得强大的力量！$"

Text_PassedOnEverythingIKnow::
	.string "哈……哈……\p"
	.string "我现在没有遗憾了。我已经把我所知\n"
	.string "道的都告诉它了。\p"
	.string "现在，我已经完成了我的使命，现在\n"
	.string "就算离开这个世界，我也没有遗憾\l"
	.string "了……$"

Text_FeelRejuvenated::
	.string "把我的知识传授给你后，我感觉我轻\n"
	.string "松了很多。\p"
	.string "事实上，我感觉我再一次充满了活\n"
	.string "力，就像是又年轻了一次！$"
