Route25_Frlg_MapScripts::
	.byte 0

Route25_EventScript_SeaCottageSign::
	msgbox Route25_Text_SeaCottageSign, MSGBOX_SIGN
	end

Route25_EventScript_Man::
	msgbox Route25_Text_AreYouHereAlone, MSGBOX_NPC
	end

Route25_Text_JoeyIntro::
	.string "本地的训练家都来这儿练习。$"

Route25_Text_JoeyDefeat::
	.string "你很厉害啊。$"

Route25_Text_JoeyPostBattle::
	.string "任何宝可梦都有弱点。哪怕是所谓的\n"
	.string "最强的。\p"
	.string "所以最好培养不同种类的宝可梦。$"

Route25_Text_DanIntro::
	.string "爸爸带着我在枯叶市的圣特安努号参\n"
	.string "加了一次大型的聚会。$"

Route25_Text_DanDefeat::
	.string "我没疯！$"

Route25_Text_DanPostBattle::
	.string "在圣特安努号，我看见了从世界各地\n"
	.string "来的训练家。$"

Route25_Text_FlintIntro::
	.string "我很帅。我已经有女朋友了！$"

Route25_Text_FlintDefeat::
	.string "唔，见鬼！$"

Route25_Text_FlintPostBattle::
	.string "呃，好吧。我女朋友会为我喝彩的。$"

Route25_Text_KelseyIntro::
	.string "嗨！我男朋友很帅！$"

Route25_Text_KelseyDefeat::
	.string "我的条件不是最好的……$"

Route25_Text_KelseyPostBattle::
	.string "我希望我的男朋友和你一样厉害。$"

Route25_Text_ChadIntro::
	.string "我有一种感觉……我感到我必须和你\n"
	.string "战斗！$"

Route25_Text_ChadDefeat::
	.string "我知道我也是会输的！$"

Route25_Text_ChadPostBattle::
	.string "如果你的宝可梦混乱了，就把它交换\n"
	.string "下场换上另一只。\p"
	.string "这是一种有名的战术。$"

Route25_Text_HaleyIntro::
	.string "我的朋友拥有很多可爱的宝可梦。我\n"
	.string "很羡慕！$"

Route25_Text_HaleyDefeat::
	.string "我也不是那么很羡慕！$"

Route25_Text_HaleyPostBattle::
	.string "你是从月见山来的？能给我一只皮皮\n"
	.string "吗？$"

Route25_Text_FranklinIntro::
	.string "我刚刚从月见山上下来，但是我依然\n"
	.string "精力充沛。$"

Route25_Text_FranklinDefeat::
	.string "你很努力！$"

Route25_Text_FranklinPostBattle::
	.string "见鬼！那个洞穴中的一个超音蝠把我\n"
	.string "赶回来了。$"

Route25_Text_NobIntro::
	.string "我正打算去海角看怪兽狂的收藏。$"

Route25_Text_NobDefeat::
	.string "你已经完成了，真的很了不起！$"

Route25_Text_NobPostBattle::
	.string "怪兽狂确实名副其实。\p"
	.string "他的收藏包括了很多珍贵品种的宝可\n"
	.string "梦。$"

Route25_Text_WayneIntro::
	.string "你打算去看正辉？首先，我们战斗吧\n"
	.string "！$"

Route25_Text_WayneDefeat::
	.string "你有两下子。$"

Route25_Text_WaynePostBattle::
	.string "下面的小路是去华蓝市的捷径。$"

Route25_Text_SeaCottageSign::
	.string "海角小屋正辉住在这儿！$"

Route25_Text_MistyHighHopesAboutThisPlace::
	.string "这个海角是一个著名的景点。\p"
	.string "道馆馆主小霞也十分憧憬着这儿。$"

Route25_Text_AreYouHereAlone::
	.string "嗨，你一个人来这儿吗？\p"
	.string "如果你想去华蓝的海角……你最好找\n"
	.string "个伴和你一起去。$"

