SixIsland_OutcastIsland_Frlg_MapScripts::
	.byte 0

SixIsland_OutcastIsland_EventScript_Rocket::
	trainerbattle_single TRAINER_TEAM_ROCKET_GRUNT_46, SixIsland_OutcastIsland_Text_RocketIntro, SixIsland_OutcastIsland_Text_RocketDefeat
	msgbox SixIsland_OutcastIsland_Text_RocketPostBattle, MSGBOX_AUTOCLOSE
	end

SixIsland_OutcastIsland_Text_RocketIntro::
	.string "这个地区没有什么珍贵的宝可梦！一\n"
	.string "直也没有！\p"
	.string "我受够了。我要把它从你身边带走！$"

SixIsland_OutcastIsland_Text_RocketDefeat::
	.string "……嗯？$"

SixIsland_OutcastIsland_Text_RocketPostBattle::
	.string "听着，你没有看见任何珍贵的宝可\n"
	.string "梦，是吧？$"

SixIsland_OutcastIsland_Text_TylorIntro::
	.string "我一点也没有好运气。一场战斗没准\n"
	.string "能改变现状。$"

SixIsland_OutcastIsland_Text_TylorDefeat::
	.string "不，还是没有好运气……$"

SixIsland_OutcastIsland_Text_TylorPostBattle::
	.string "没收服珍贵的宝可梦前，我不甘心就\n"
	.string "这样回去。$"

SixIsland_OutcastIsland_Text_MymoIntro::
	.string "呼……呼……\p"
	.string "我一口气从六之岛港口游到了这儿。$"

SixIsland_OutcastIsland_Text_MymoDefeat::
	.string "呼……呼……$"

SixIsland_OutcastIsland_Text_MymoPostBattle::
	.string "我只是游了一部分的路程……我被打败\n"
	.string "了……$"

SixIsland_OutcastIsland_Text_NicoleIntro::
	.string "在游泳时把宝可梦放出去不是那么简\n"
	.string "单的，你知道吗？$"

SixIsland_OutcastIsland_Text_NicoleDefeat::
	.string "我在游泳上没有输给你。所以我并不\n"
	.string "为这个困扰。$"

SixIsland_OutcastIsland_Text_NicolePostBattle::
	.string "你是为了前往上面的岛屿而路过这儿\n"
	.string "吗？\p"
	.string "我在那儿没有见到任何有趣的东西。$"

SixIsland_OutcastIsland_Text_AvaIntro::
	.string "美香：我们来一场2对2的水中战斗\n"
	.string "吧！$"

SixIsland_OutcastIsland_Text_AvaDefeat::
	.string "美香：噢，你太令人惊讶了！更厉害\n"
	.string "的是，你只是一个人！$"

SixIsland_OutcastIsland_Text_AvaPostBattle::
	.string "美香：我喜欢大海胜过喜欢任何水\n"
	.string "池。$"

SixIsland_OutcastIsland_Text_AvaNotEnoughMons::
	.string "美香：你是在挑战我们吗？\p"
	.string "如果你想要战斗，你至少需要两只宝\n"
	.string "可梦。$"

SixIsland_OutcastIsland_Text_GebIntro::
	.string "阿雅：姐姐，快来帮我！请和我并肩\n"
	.string "作战！$"

SixIsland_OutcastIsland_Text_GebDefeat::
	.string "阿雅：哇，姐姐，这个人可真是厉\n"
	.string "害！$"

SixIsland_OutcastIsland_Text_GebPostBattle::
	.string "阿雅：我骑在我姐姐肩膀上，因为我\n"
	.string "够不着底部。$"

SixIsland_OutcastIsland_Text_GebNotEnoughMons::
	.string "阿雅：请跟我和我姐姐战斗吧！\p"
	.string "……噢，你没有带着两只宝可梦吗？$"
