Route14_Frlg_MapScripts::
	.byte 0

Route14_EventScript_RouteSign::
	msgbox Route14_Text_RouteSign, MSGBOX_SIGN
	end

Route14_Text_CarterIntro::
	.string "要想让你的宝可梦学到更强劲的技能\n"
	.string "就要善用技能机。$"

Route14_Text_CarterDefeat::
	.string "不是很好。$"

Route14_Text_CarterPostBattle::
	.string "你已经得到秘传机了吗？宝可梦不会\n"
	.string "轻易忘记从上面学得的技能。$"

Route14_Text_MitchIntro::
	.string "我的鸟类宝可梦已经备战完毕。$"

Route14_Text_MitchDefeat::
	.string "看来还是没准备好！$"

Route14_Text_MitchPostBattle::
	.string "我的鸟系宝可梦需要学习更强的技能\n"
	.string "。$"

Route14_Text_BeckIntro::
	.string "玉虹百货大楼出售技能学习机。\p"
	.string "技能学习机并不是十分稀少，但是拥\n"
	.string "有它的人也不多。$"

Route14_Text_BeckDefeat::
	.string "啊，你这家伙！$"

Route14_Text_BeckPostBattle::
	.string "让宝可梦学习与它自身属性相符的技\n"
	.string "能。\p"
	.string "这样技能的强劲会有显著提升。$"

Route14_Text_MarlonIntro::
	.string "你教过你的鸟系宝可梦如何飞翔了吗\n"
	.string "？\p"
	.string "你可以跟它一同在天空中翱翔！$"

Route14_Text_MarlonDefeat::
	.string "在火焰中击落它！$"

Route14_Text_MarlonPostBattle::
	.string "鸟系宝可梦是我最钟爱的。任何其他\n"
	.string "的宝可梦都让我兴趣索然。$"

Route14_Text_DonaldIntro::
	.string "你听说过传说中飞行的幻影吗？$"

Route14_Text_DonaldDefeat::
	.string "为什么？为什么我会输？$"

Route14_Text_DonaldPostBattle::
	.string "飞行的幻影指的是传说中的鸟系宝可\n"
	.string "梦。\p"
	.string "有三只：急冻鸟，闪电鸟和火焰鸟。$"

Route14_Text_BennyIntro::
	.string "我没有进去过，不过没关系。我们出\n"
	.string "发吧！$"

Route14_Text_BennyDefeat::
	.string "我知道它！$"

Route14_Text_BennyPostBattle::
	.string "输与赢……在宽广的天空下皆是浮云\n"
	.string "。$"

Route14_Text_LukasIntro::
	.string "来吧，开战。擂鼓，呐喊，冲锋！$"

Route14_Text_LukasDefeat::
	.string "啊啊啊！输了！我输掉了！$"

Route14_Text_LukasPostBattle::
	.string "啊？什么？怎么了？你还想干嘛？$"

Route14_Text_IsaacIntro::
	.string "我想打发点时间。少废话，开打吧。$"

Route14_Text_IsaacDefeat::
	.string "什么？你！？$"

Route14_Text_IsaacPostBattle::
	.string "培育宝可梦真是个累赘。$"

Route14_Text_GeraldIntro::
	.string "这里地方很宽敞，所以我们就骑车过\n"
	.string "来了。$"

Route14_Text_GeraldDefeat::
	.string "失败了！$"

Route14_Text_GeraldPostBattle::
	.string "你把你的宝可梦培育得这么厉害，实\n"
	.string "在太酷了。\p"
	.string "速度即是力量！看来你已经领悟到了\n"
	.string "！$"

Route14_Text_MalikIntro::
	.string "宝可梦对战？太激动了！来吧！$"

Route14_Text_MalikDefeat::
	.string "被吹走了！$"

Route14_Text_MalikPostBattle::
	.string "你知道谁是胜者，不是你就是我！$"

Route14_Text_RouteSign::
	.string "14号道路往西到浅红市$"

Route14_Text_KiriIntro::
	.string "阿雾：惠娜，我们一起试试，两个人\n"
	.string "一起胜率会更高点。$"

Route14_Text_KiriDefeat::
	.string "阿雾：呜，呜……我们输了么？$"

Route14_Text_KiriPostBattle::
	.string "阿雾：是因为我太弱的关系么？$"

Route14_Text_KiriNotEnoughMons::
	.string "阿雾：如果你有两只宝可梦我们就可\n"
	.string "以战斗啦。$"

Route14_Text_JanIntro::
	.string "惠娜：走吧，阿雾！我们得再度投入\n"
	.string "修炼！$"

Route14_Text_JanDefeat::
	.string "惠娜：不！这不公平！$"

Route14_Text_JanPostBattle::
	.string "惠娜：阿雾，别哭了！我们下次要更\n"
	.string "加努力才行。$"

Route14_Text_JanNotEnoughMons::
	.string "惠娜：你想战斗吗？你没有足够的宝\n"
	.string "可梦。$"
