@ Flavor text for interacting with various background objects

EventScript_Bookshelf::
	msgbox Text_Bookshelf, MSGBOX_SIGN
	end

EventScript_PokeMartShelf::
	msgbox Text_PokeMartShelf, MSGBOX_SIGN
	end

EventScript_Food::
	msgbox Text_Food, MSGBOX_SIGN
	end

EventScript_VideoGame::
	msgbox Text_VideoGame, MSGBOX_SIGN
	end

EventScript_Computer::
	msgbox Text_Computer, MSGBOX_SIGN
	end

EventScript_ImpressiveMachine::
	msgbox Text_ImpressiveMachine, MSGBOX_SIGN
	end

EventScript_Blueprints::
	msgbox Text_Blueprints, MSGBOX_SIGN
	end

EventScript_Burglary::
	msgbox Text_Burglary, MSGBOX_SIGN
	end

EventScript_PlayerFacingTVScreen::
	msgbox Text_PlayerFacingTVScreen, MSGBOX_SIGN
	end

EventScript_Cabinet::
	msgbox Text_DishesPlatesNeatlyLinedUp, MSGBOX_SIGN
	end

EventScript_Kitchen::
	msgbox Text_Kitchen, MSGBOX_SIGN
	end

EventScript_Dresser::
	msgbox Text_Dresser, MSGBOX_SIGN
	end

EventScript_Snacks::
	msgbox Text_Snacks, MSGBOX_SIGN
	end

EventScript_Painting::
	msgbox Text_Painting, MSGBOX_SIGN
	end

EventScript_PowerPlantMachine::
	msgbox Text_PowerPlantMachine, MSGBOX_SIGN
	end

EventScript_Telephone::
	msgbox Text_Telephone, MSGBOX_SIGN
	end

EventScript_AdvertisingPoster::
	msgbox Text_AdvertisingPoster, MSGBOX_SIGN
	end

EventScript_TastyFood::
	msgbox Text_TastyFood, MSGBOX_SIGN
	end

EventScript_TrashBin::
	msgbox Text_TrashBin, MSGBOX_SIGN
	end

EventScript_Cup::
	msgbox Text_Cup, MSGBOX_SIGN
	end

EventScript_PolishedWindow::
	msgbox Text_PolishedWindow, MSGBOX_SIGN
	end

EventScript_BeautifulSkyWindow::
	msgbox Text_BeautifulSkyWindow, MSGBOX_SIGN
	end

EventScript_BlinkingLights::
	msgbox Text_BlinkingLights, MSGBOX_SIGN
	end

EventScript_NeatlyLinedUpTools::
	msgbox Text_NeatlyLinedUpTools, MSGBOX_SIGN
	end

EventScript_PokemartSign::
	msgbox Text_PokemartSign, MSGBOX_SIGN
	end

EventScript_PokecenterSign::
	msgbox Text_PokecenterSign, MSGBOX_SIGN
	end

EventScript_Indigo_UltimateGoal::
	msgbox Text_Indigo_UltimateGoal, MSGBOX_SIGN
	end

EventScript_Indigo_HighestAuthority::
	msgbox Text_Indigo_HighestAuthority, MSGBOX_SIGN
	end

@ Flavor text for interacting with various background objects

Text_Bookshelf::
	.string "书架上塞满了宝可梦的书。$"

Text_NothingButPokemonBooks::
	.string "ほんだなに　ならんでいるのはポケ\n"
	.string "モンの　ほん　ばかりだ$"

Text_ATownMap::
	.string "是一张城镇地图。$"

Text_PokeMartShelf::
	.string "哇！全都是宝可梦用品！$"

Text_DishesPlatesNeatlyLinedUp::
	.string "盘子和餐具摆放得整整齐齐。$"

Text_Kitchen::
	.string "真香！有人在这里做饭。$"

Text_Dresser::
	.string "做工精致的衣柜。能装下不少东西。$"

Text_Snacks::
	.string "这里堆着一些零食。$"

Text_PokemartSign::
	.string "各类道具应有尽有！宝可梦友好商店$"

Text_PokecenterSign::
	.string "为宝可梦恢复体力！宝可梦中心$"

Text_Indigo_UltimateGoal::
	.string "石英高原\p"
	.string "训练家的最终目标！宝可梦联盟总部$"

Text_Indigo_HighestAuthority::
	.string "石英高原\p"
	.string "实力至上的宝可梦联盟！宝可梦联盟\n"
	.string "总部$"

Text_Food::
	.string "里面一定装满了各种美食。$"

Text_Blueprints::
	.string "是一张设计图。上面画满图表和文\n"
	.string "字。$"

Text_Painting::
	.string "一幅漂亮的宝可梦画像。画里的它看\n"
	.string "起来很开心。$"

Text_PowerPlantMachine::
	.string "这是什么机器？还是别乱碰了！$"

Text_Telephone::
	.string "是一部电话。还是别乱打了。$"

Text_Computer::
	.string "满屏复杂的文字和数字……完全看不\n"
	.string "懂。$"

Text_AdvertisingPoster::
	.string "是一张介绍各种商品的广告。$"

Text_TastyFood::
	.string "好香！闻着肚子都饿了！$"

Text_TrashBin::
	.string "翻了翻垃圾桶……\p"
	.string "里面什么也没有！$"

Text_Cup::
	.string "杯子上印着宝可梦的图案。$"

Text_PolishedWindow::
	.string "窗户擦得锃亮。$"

Text_BeautifulSkyWindow::
	.string "望向窗外……\p"
	.string "天空美得让人看入了神。$"

Text_BlinkingLights::
	.string "不同颜色的灯光闪个不停。$"

Text_NeatlyLinedUpTools::
	.string "各种工具摆放得整整齐齐。$"

Text_ImpressiveMachine::
	.string "这是一台机器。看起来真厉害！$"

Text_VideoGame::
	.string "是最新的电子游戏！看起来很好玩！$"

Text_Burglary::
	.string "这里有明显的盗窃痕迹……$"

Text_PlayerFacingTVScreen::
	.string "电视上正播放着宝可梦！看起来它很\n"
	.string "开心。$"
