ThreeIsland_House4_Frlg_MapScripts::
	.byte 0

ThreeIsland_House4_EventScript_BaldingMan::
	msgbox ThreeIsland_House4_Text_GhostsInBerryForest, MSGBOX_NPC
	end

ThreeIsland_House4_EventScript_LittleBoy::
	msgbox ThreeIsland_House4_Text_PapaKeepsLyingToMe, MSGBOX_NPC
	end

ThreeIsland_House4_Text_GhostsInBerryForest::
	.string "你千万不要独自去树果森林。\p"
	.string "至于原因？传说那里有幽灵出没。$"

ThreeIsland_House4_Text_PapaKeepsLyingToMe::
	.string "爸爸一直和我住在一起，他从来不让\n"
	.string "我独自出去玩！$"

