PewterCity_Museum_2F_Frlg_MapScripts::
	.byte 0

PewterCity_Museum_2F_EventScript_Man::
	msgbox PewterCity_Museum_1F_Text_WhatsSpecialAboutMoonStone, MSGBOX_NPC
	end

PewterCity_Museum_2F_EventScript_OldMan::
	msgbox PewterCity_Museum_1F_Text_BoughtColorTVForMoonLanding, MSGBOX_NPC
	end

PewterCity_Museum_2F_EventScript_Scientist::
	msgbox PewterCity_Museum_1F_Text_RunningSpaceExhibitThisMonth, MSGBOX_NPC
	end

PewterCity_Museum_2F_EventScript_LittleGirl::
	msgbox PewterCity_Museum_1F_Text_AskedDaddyToCatchPikachu, MSGBOX_NPC
	end

PewterCity_Museum_2F_EventScript_BaldingMan::
	msgbox PewterCity_Museum_1F_Text_PikachuSoonIPromise, MSGBOX_NPC
	end

PewterCity_Museum_2F_EventScript_SpaceShuttle::
	msgbox PewterCity_Museum_1F_Text_SpaceShuttle, MSGBOX_SIGN
	end

PewterCity_Museum_2F_EventScript_MoonStone::
	msgbox PewterCity_Museum_1F_Text_MeteoriteThatFellOnMtMoon, MSGBOX_SIGN
	end

Text_SeismicTossTeach::
	.string "宇宙的秘密……地球的奥妙……\p"
	.string "我们对这个世界的事知道的太少了。\p"
	.string "但是这能激励我们更努力地学习。而\n"
	.string "不是乱折腾。\p"
	.string "你唯一能折腾的一件事就是……\p"
	.string "嗯，地球上投怎么样？要让我把这技\n"
	.string "能教给一只宝可梦吗？$"

Text_SeismicTossDeclined::
	.string "这样好吗？我确定你一定会回来的。$"

Text_SeismicTossWhichMon::
	.string "想要哪只宝可梦学习地球上投？$"

Text_SeismicTossTaught::
	.string "我希望你不再乱折腾了。继续吧。$"

PewterCity_Museum_1F_Text_WhatsSpecialAboutMoonStone::
	.string "月之石，哈？\p"
	.string "它很特殊吗？在我看来不过是普通石\n"
	.string "头罢了。$"

PewterCity_Museum_1F_Text_BoughtColorTVForMoonLanding::
	.string "1969年7月20日！\p"
	.string "人类在那一天第一次登上月球。\p"
	.string "为了看到那个新闻，我甚至买了台彩\n"
	.string "色电视机。$"

PewterCity_Museum_1F_Text_RunningSpaceExhibitThisMonth::
	.string "这个月我们正在进行关于宇宙的展\n"
	.string "览。$"

PewterCity_Museum_1F_Text_AskedDaddyToCatchPikachu::
	.string "我想要一只皮卡丘！它太可爱了！\p"
	.string "我让我的爸爸去给我收服一只！$"

PewterCity_Museum_1F_Text_PikachuSoonIPromise::
	.string "好的，一只皮卡丘吧，我去捉！$"

PewterCity_Museum_1F_Text_SpaceShuttle::
	.string "航天飞机哥伦比亚号$"

PewterCity_Museum_1F_Text_MeteoriteThatFellOnMtMoon::
	.string "落在的月见山的陨石被称作月之石。$"

