SSAnne_2F_Room3_Frlg_MapScripts::
	.byte 0

SSAnne_2F_Room3_EventScript_Gentleman::
	msgbox SSAnne_2F_Room3_Text_SeenMonsFerryPeople, MSGBOX_NPC
	end

SSAnne_2F_Room3_EventScript_OldMan::
	msgbox SSAnne_2F_Room3_Text_SomeTreesCanBeCutDown, MSGBOX_NPC
	end

SSAnne_2F_Room3_Text_SeenMonsFerryPeople::
	.string "噢，没错，我见过一些宝可梦载着人\n"
	.string "在水上穿梭！$"

SSAnne_2F_Room3_Text_SomeTreesCanBeCutDown::
	.string "小树可以用居合斩砍倒。\p"
	.string "但记住！居合斩是一个秘传机的技巧\n"
	.string "。\p"
	.string "一旦学会，它是不能轻易被遗忘的。$"

