PetalburgCity_House1_MapScripts::
	.byte 0

PetalburgCity_House1_EventScript_Man::
	msgbox PetalburgCity_House1_Text_TravelingIsWonderful, MSGBOX_NPC
	end

PetalburgCity_House1_EventScript_Woman::
	msgbox PetalburgCity_House1_Text_GoOnAdventure, MSGBOX_NPC
	end

PetalburgCity_House1_Text_TravelingIsWonderful:
	.string "旅行太美妙了！\p"
	.string "我年轻的时候经常去游泳登山！$"

PetalburgCity_House1_Text_GoOnAdventure:
	.string "哎……\p"
	.string "我要是能和宝可梦一起去探险多好……\p"
	.string "爬过潮湿的草丛……攀登崎岖的高山……\p"
	.string "穿越波涛汹涌的大海……在黑暗的洞窟\n"
	.string "里散步……\p"
	.string "然后，偶尔泛出点乡愁……\p"
	.string "旅行真的太美妙了！$"

