SafariZone_North_RestHouse_Frlg_MapScripts::
	.byte 0

SafariZone_North_RestHouse_EventScript_Fisher::
	msgbox SafariZone_East_Text_PrizeInDeepestPartOfSafariZone, MSGBOX_NPC
	end

SafariZone_North_RestHouse_EventScript_Scientist::
	msgbox SafariZone_East_Text_KeepAnyItemFoundOnSafari, MSGBOX_NPC
	end

SafariZone_North_RestHouse_EventScript_Gentleman::
	msgbox SafariZone_East_Text_MyEeveeEvolvedIntoFlareon, MSGBOX_NPC
	end

SafariZone_East_Text_KeepAnyItemFoundOnSafari::
	.string "你在狩猎地带里捡到的道具都可以带\n"
	.string "走哦。\p"
	.string "不过要是想一次把所有道具都捡光，\n"
	.string "时间可是会不够用的。$"

SafariZone_East_Text_PrizeInDeepestPartOfSafariZone::
	.string "走到野生原野区的最深处。你就会赢\n"
	.string "得奖品！$"

SafariZone_East_Text_MyEeveeEvolvedIntoFlareon::
	.string "我的伊布进化成了火精灵。\p"
	.string "但是，我一个朋友的伊布进化成了水\n"
	.string "精灵。我不知道这是为什么？$"

