Melemele_House_6_hns_MapScripts::
	.byte 0


Melemele_House6_Hiker::
	lock
	faceplayer
	msgbox Melemele_House6_Hiker_Text_0, MSGBOX_AUTOCLOSE
	release
	end


Melemele_House6_GameboyKid::
	lock
	faceplayer
	msgbox Melemele_House6_GameboyKid_Text_0, MSGBOX_AUTOCLOSE
	release
	end


Melemele_House6_Hiker_Text_0:
	.string "我买下这栋房子本是想带儿子好好探\n"
	.string "索一下大自然的......\p"
	.string "结果他满脑子就只想捧着那台Gam\n"
	.string "e Boy Advance玩个不\l"
	.string "停。$"

Melemele_House6_GameboyKid_Text_0:
	.string "我的Game Boy Advan\n"
	.string "ce里有个游戏，可以在里面探索阿\l"
	.string "罗拉地区！\p"
	.string "跟真的一模一样呢。\p"
	.string "名字叫《究极日蚀》，是PHANT\n"
	.string "ONOMY制作的！\p"
	.string "Haha，快看！我正骑着一只冰属\n"
	.string "性的音波龙呢！$"
