Melemele_House_6_hns_MapScripts::
	.byte 0


Melemele_House6_Hiker::
	lock
	faceplayer
	msgbox Melemele_House6_Hiker_Text_0, MSGBOX_AUTOCLOSE
	release
	end


Melemele_House6_GameboyKid::
	lock
	faceplayer
	msgbox Melemele_House6_GameboyKid_Text_0, MSGBOX_AUTOCLOSE
	release
	end


Melemele_House6_Hiker_Text_0:
	.string "我买下这栋房子，本想带儿子\n"
	.string "好好探索一下大自然……\p"
	.string "结果他满脑子就只想捧着那台\n"
	.string "GBA玩个不停。$"

Melemele_House6_GameboyKid_Text_0:
	.string "我的GBA里有个游戏，\n"
	.string "可以在里面探索阿罗拉地区！\p"
	.string "跟真的一模一样呢。\p"
	.string "名字叫《究极日蚀》，\n"
	.string "是PHANTONOMY制作的！\p"
	.string "哈哈，快看！\n"
	.string "我正骑着一只冰属性的音波龙呢！$"
