Melemele_House_6_hns_MapScripts::
	.byte 0


Melemele_House6_Hiker::
	lock
	faceplayer
	msgbox Melemele_House6_Hiker_Text_0, MSGBOX_AUTOCLOSE
	release
	end


Melemele_House6_GameboyKid::
	lock
	faceplayer
	msgbox Melemele_House6_GameboyKid_Text_0, MSGBOX_AUTOCLOSE
	release
	end


Melemele_House6_Hiker_Text_0:
	.string "我买下这栋房子，本想带儿子好好探\n"
	.string "索一下大自然……\p"
	.string "结果他满脑子就只想捧着那台GBA玩\n"
	.string "个不停。$"

Melemele_House6_GameboyKid_Text_0:
	.string "我的GBA里有个游戏，可以在里面探\n"
	.string "索阿罗拉地区！\p"
	.string "跟真的一模一样呢。\p"
	.string "名字叫《究极日蚀》，是PHANTONOMY\n"
	.string "制作的！\p"
	.string "哈哈，快看！我正骑着一只冰属性的\n"
	.string "音波龙呢！$"
