OneIsland_TreasureBeach_Frlg_MapScripts::
	.byte 0

OneIsland_TreasureBeach_EventScript_Boy::
	msgbox OneIsland_TreasureBeach_Text_GoodThingsWashUpOnBeach, MSGBOX_NPC
	end

OneIsland_TreasureBeach_Text_AmaraIntro::
	.string "被波浪冲刷的背部……这感觉很美妙"
	.string "。$"

OneIsland_TreasureBeach_Text_AmaraDefeat::
	.string "我输了……感觉很糟糕。$"

OneIsland_TreasureBeach_Text_AmaraPostBattle::
	.string "这个地方的海水很温暖。$"

OneIsland_TreasureBeach_Text_GoodThingsWashUpOnBeach::
	.string "有些好的东西有时候会被海浪冲到沙\n"
	.string "滩上来。\p"
	.string "所以所以我经常来这沙滩上碰碰运\n"
	.string "气。$"

