Route10_Frlg_MapScripts::
	.byte 0

Route10_EventScript_Unused::
	end

Route10_EventScript_NorthRockTunnelSign::
	msgbox Route10_Text_RockTunnelDetourToLavender, MSGBOX_SIGN
	end

Route10_EventScript_SouthRockTunnelSign::
	msgbox Route10_Text_RockTunnel, MSGBOX_SIGN
	end

Route10_EventScript_PowerPlantSign::
	msgbox Route10_Text_PowerPlant, MSGBOX_SIGN
	end

Route10_Text_MarkIntro::
	.string "哇，你历经磨难终于到了我这里？也\n"
	.string "许你也是一个怪兽狂对吗？想要看看\l"
	.string "我的收藏吗？$"

Route10_Text_MarkDefeat::
	.string "啊哼。我不会生气的！$"

Route10_Text_MarkPostBattle::
	.string "我还有很多稀有的宝可梦放在家里呢$"

Route10_Text_ClarkIntro::
	.string "哈哈-哈哈-啊哈哈$"

Route10_Text_ClarkDefeat::
	.string "哈-啊啊！不准笑！啊啊-发烧了！啊\n"
	.string "啊-啊嚏！$"

Route10_Text_ClarkPostBattle::
	.string "啊啊-啊嚏！啊嚏！抽鼻子，擦鼻\n"
	.string "涕。$"

Route10_Text_HermanIntro::
	.string "嘿，小子！想看我的宝可梦$"

Route10_Text_HermanDefeat::
	.string "喔，不！我的宝可梦$"

Route10_Text_HermanPostBattle::
	.string "我讨厌你。比我强的人我都不喜欢！$"

Route10_Text_HeidiIntro::
	.string "我已经在宝可梦道馆中辗转奋战多\n"
	.string "时。\p"
	.string "…可总是输多赢少。$"

Route10_Text_HeidiDefeat::
	.string "烦死了！有事等我训练完了再说！$"

Route10_Text_HeidiPostBattle::
	.string "我发现一些怪兽狂正在附近徘徊的踪\n"
	.string "迹。\p"
	.string "你想象得出来吗？从这山顶往下俯视\n"
	.string "的样子？$"

Route10_Text_TrentIntro::
	.string "哈！这山里的空气真爽！$"

Route10_Text_TrentDefeat::
	.string "它使我的心灵彻底得到了净化！$"

Route10_Text_TrentPostBattle::
	.string "这样的空气里人都像要飞起来了！$"

Route10_Text_CarolIntro::
	.string "我现在有点头晕，好久都没有登山\n"
	.string "了。$"

Route10_Text_CarolDefeat::
	.string "我实在坚持不住了。都怪我没有做好\n"
	.string "充足的准备。$"

Route10_Text_CarolPostBattle::
	.string "这座山里生活的宝可梦都是矮矮胖胖\n"
	.string "的那种……\p"
	.string "我希望能有一种宝可梦，它粉色的皮\n"
	.string "肤上有花瓣花纹！$"

Route10_Text_RockTunnelDetourToLavender::
	.string "岩山隧道绕道到紫苑镇$"

Route10_Text_RockTunnel::
	.string "岩山隧道$"

Route10_Text_PowerPlant::
	.string "无人发电厂$"

