LavenderTown_Mart_hns_MapScripts::
	.byte 0

LavenderTown_Mart_EventScript_Pokefan::
	msgbox LavenderMart_Text_PokefanM, MSGBOX_NPC
	end

LavenderTown_Mart_EventScript_Rocker::
	msgbox LavenderMart_Text_Rocker, MSGBOX_NPC
	end

LavenderMart_Text_PokefanM:
	.string "如果你想去洞窟探险的话，除虫喷雾\n"
	.string "可是必需品。\p"
	.string "虽然我喜欢探险，但我还没走遍所有\n"
	.string "的洞窟呢。$"

LavenderMart_Text_Rocker:
	.string "我听说城都地区的桧皮镇上有一位手\n"
	.string "工制作精灵球的工匠。\p"
	.string "真想弄几个来用用啊。$"
