SixIsland_GreenPath_Frlg_MapScripts::
	.byte 0

SixIsland_GreenPath_EventScript_RightRouteSign::
	msgbox SixIsland_GreenPath_Text_LeftRouteSign, MSGBOX_SIGN
	end

SixIsland_GreenPath_EventScript_LeftRouteSign::
	msgbox SixIsland_GreenPath_Text_RightRouteSign, MSGBOX_SIGN
	end

SixIsland_GreenPath_Text_JaclynIntro::
	.string "……呃？\p"
	.string "我正在想像着我的房子，就瞬间移动\n"
	.string "到这儿来了？$"

SixIsland_GreenPath_Text_JaclynDefeat::
	.string "大错特错了！$"

SixIsland_GreenPath_Text_JaclynPostBattle::
	.string "我太三心二意了！\p"
	.string "我必须集中精力来瞬间移动到我的房\n"
	.string "子！$"

SixIsland_GreenPath_Text_LeftRouteSign::
	.string "绿之步道前方标志之林$"

SixIsland_GreenPath_Text_RightRouteSign::
	.string "绿之步道畅想绿色，保持自然的纯净\n"
	.string "！$"

