#include "global.h"
#include "strings.h"
#include "battle_pyramid_bag.h"
#include "item_menu.h"

ALIGNED(4)
const u8 gText_ExpandedPlaceholder_Empty[] = _("");
const u8 gText_ExpandedPlaceholder_Kun[] = _("");
const u8 gText_ExpandedPlaceholder_Chan[] = _("");
const u8 gText_ExpandedPlaceholder_Sapphire[] = _("蓝宝石");
const u8 gText_ExpandedPlaceholder_Ruby[] = _("红宝石");
const u8 gText_ExpandedPlaceholder_Emerald[] = _("绿宝石");
const u8 gText_ExpandedPlaceholder_Aqua[] = _("海洋");
const u8 gText_ExpandedPlaceholder_Magma[] = _("熔岩");
const u8 gText_ExpandedPlaceholder_Archie[] = _("水梧桐");
const u8 gText_ExpandedPlaceholder_Maxie[] = _("赤焰松");
const u8 gText_ExpandedPlaceholder_Kyogre[] = _("盖欧卡");
const u8 gText_ExpandedPlaceholder_Groudon[] = _("固拉多");
const u8 gText_ExpandedPlaceholder_Brendan[] = _("小悠");
const u8 gText_ExpandedPlaceholder_May[] = _("小遥");
const u8 gText_ExpandedPlaceholder_Red[] = _("赤红");
const u8 gText_ExpandedPlaceholder_Green[] = _("碧蓝");
const u8 gText_ExpandedPlaceholder_Silver[] = _("银");
const u8 gText_EggNickname[POKEMON_NAME_LENGTH + 1] = _("蛋");
const u8 gText_Pokemon[POKEMON_NAME_LENGTH + 1] = _("宝可梦");
const u8 gText_Player[] = _("玩家"); // Unused
const u8 gText_Pokedex[] = _("图鉴"); // Unused
const u8 gText_Time[] = _("冒险时间");
const u8 gText_Badges[] = _("徽章"); // Unused
const u8 gText_AButton[] = _("A键"); // Unused
const u8 gText_BButton[] = _("B键"); // Unused
const u8 gText_RButton[] = _("R键"); // Unused
const u8 gText_LButton[] = _("L键"); // Unused
const u8 gText_Start[] = _("START"); // Unused
const u8 gText_Select[] = _("SELECT"); // Unused
const u8 gText_ControlPad[] = _("+ 十字键"); // Unused
const u8 gText_LButtonRButton[] = _("L键  R键"); // Unused
const u8 gText_Controls[] = _("控制器"); // Unused
ALIGNED(4) const u8 gText_PickOk[] = _("{DPAD_UPDOWN}选择 \n{A_BUTTON}好"); // Unused
ALIGNED(4) const u8 gText_Next[] = _("{A_BUTTON}下个");
ALIGNED(4) const u8 gText_NextBack[] = _("{A_BUTTON}下个 \n{B_BUTTON}返回");
ALIGNED(4) const u8 gText_PickNextCancel[] = _("{DPAD_UPDOWN}选择 \n{A_BUTTON}下个 \l{B_BUTTON}取消");
ALIGNED(4) const u8 gText_PickCancel[] = _("{DPAD_UPDOWN}选择 \n{A_BUTTON}\l{B_BUTTON}取消");
ALIGNED(4) const u8 gText_AButtonExit[] = _("{A_BUTTON}退出");
const u8 gText_Boy[] = _("男孩");
const u8 gText_Girl[] = _("女孩");
const u8 gText_ThisIsAPokemon[] = _("这就是被我们称为“宝可梦”的生物\n。{PAUSE 96}\p");
const u8 gText_5MarksPokemon[] = _("？？？宝可梦");
const u8 gText_UnkHeight[] = _("{CLEAR_TO 0x0C}??'??”");
const u8 gText_UnkHeightMetric[] = _("???.? m");
const u8 gText_UnkWeight[] = _("????.? lbs.");
const u8 gText_UnkWeightMetric[] = _("???.? kg.");
const u8 gText_EmptyPkmnCategory[] = _("宝可梦"); // Unused
const u8 gText_EmptyHeight[] = _("{CLEAR_TO 0x0C}    '    ”"); // Unused
const u8 gText_EmptyWeight[] = _("        .   lbs."); // Unused
const u8 gText_EmptyPokedexInfo1[] = _(""); // Unused
const u8 gText_CryOf[] = _("的叫声");
const u8 gText_EmptyPokedexInfo2[] = _(""); // Unused
const u8 gText_SizeComparedTo[] = _("体型比较：");
const u8 gText_PokedexRegistration[] = _("宝可梦图鉴登记完毕。");
const u8 gText_HTHeight[] = _("身高");
const u8 gText_WTWeight[] = _("体重");
const u8 gText_SearchingPleaseWait[] = _("正在搜索......请稍候。");
const u8 gText_SearchCompleted[] = _("搜索完毕。");
const u8 gText_NoMatchingPkmnWereFound[] = _("没有找到符合条件的宝可梦。");
const u8 gText_SearchForPkmnBasedOnParameters[] = _("根据所选条件搜索宝可梦。");
const u8 gText_SwitchPokedexListings[] = _("切换宝可梦图鉴的排列方式。");
const u8 gText_ReturnToPokedex[] = _("返回宝可梦图鉴。");
const u8 gText_SelectPokedexMode[] = _("选择宝可梦图鉴模式。");
const u8 gText_SelectPokedexListingMode[] = _("选择宝可梦图鉴的排列模式。");
const u8 gText_ListByFirstLetter[] = _("按名字的首字母排序。仅限已发现的\n宝可梦。");
const u8 gText_ListByBodyColor[] = _("按身体颜色排序。仅限已发现的宝可\n梦。");
const u8 gText_ListByType[] = _("按属性排序。仅限已捉到的宝可梦。");
const u8 gText_ExecuteSearchSwitch[] = _("Execute search/switch.");
#if IS_HNS
const u8 gText_DexHoennTitle[] = _("JOHTO DEX");
#else
const u8 gText_DexHoennTitle[] = _("HOENN DEX");
#endif
const u8 gText_DexNatTitle[] = _("NATIONAL DEX");
const u8 gText_DexSortNumericalTitle[] = _("编号模式");
const u8 gText_DexSortAtoZTitle[] = _("首字顺模式");
const u8 gText_DexSortHeaviestTitle[] = _("最重模式");
const u8 gText_DexSortLightestTitle[] = _("最轻模式");
const u8 gText_DexSortTallestTitle[] = _("最高模式");
const u8 gText_DexSortSmallestTitle[] = _("最矮模式");
const u8 gText_DexSearchAlphaABC[] = _("ABC");
const u8 gText_DexSearchAlphaDEF[] = _("DEF");
const u8 gText_DexSearchAlphaGHI[] = _("GHI");
const u8 gText_DexSearchAlphaJKL[] = _("JKL");
const u8 gText_DexSearchAlphaMNO[] = _("MNO");
const u8 gText_DexSearchAlphaPQR[] = _("PQR");
const u8 gText_DexSearchAlphaSTU[] = _("STU");
const u8 gText_DexSearchAlphaVWX[] = _("VWX");
const u8 gText_DexSearchAlphaYZ[] = _("YZ");
const u8 gText_DexSearchColorRed[] = _("红色");
const u8 gText_DexSearchColorBlue[] = _("蓝色");
const u8 gText_DexSearchColorYellow[] = _("黄色");
const u8 gText_DexSearchColorGreen[] = _("绿色");
const u8 gText_DexSearchColorBlack[] = _("黑色");
const u8 gText_DexSearchColorBrown[] = _("褐色");
const u8 gText_DexSearchColorPurple[] = _("紫色");
const u8 gText_DexSearchColorGray[] = _("灰色");
const u8 gText_DexSearchColorWhite[] = _("白色");
const u8 gText_DexSearchColorPink[] = _("PINK");
#if IS_HNS
const u8 gText_DexHoennDescription[] = _("JOHTO region's POKéDEX");
#else
const u8 gText_DexHoennDescription[] = _("HOENN region's POKéDEX");
#endif
const u8 gText_DexNatDescription[] = _("National edition POKéDEX");
const u8 gText_DexSortNumericalDescription[] = _("宝可梦将按照编号顺序列出。");
const u8 gText_DexSortAtoZDescription[] = _("已发现和已捉到的宝可梦将按首字母\n顺序列出。");
const u8 gText_DexSortHeaviestDescription[] = _("已捉到的宝可梦将按从重到轻顺序列\n出。");
const u8 gText_DexSortLightestDescription[] = _("已捉到的宝可梦将按从轻到重顺序列\n出。");
const u8 gText_DexSortTallestDescription[] = _("已捉到的宝可梦将按从高到矮顺序列\n出。");
const u8 gText_DexSortSmallestDescription[] = _("已捉到的宝可梦将按从矮到高顺序列\n出。");
const u8 gText_DexEmptyString[] = _("");
const u8 gText_DexSearchDontSpecify[] = _("不指定。");
const u8 gText_DexSearchTypeNone[] = _("无");
const u8 gText_SelectorArrow[] = _("▶");
const u8 gText_EmptySpace[] = _(" "); // Unused
const u8 gText_WelcomeToHOF[] = _("恭喜登入名人堂！");
const u8 gText_HOFDexRating[] = _("已发现的宝可梦：\n{STR_VAR_1}！已捕捉的\l宝可梦：{STR_VAR_2}！\p小田卷博士的图鉴评价！\p小田卷博士：让我看看……\p");
const u8 gText_HOFDexSaving[] = _("正在写入记录……请勿切断电源。");
const u8 gText_HOFCorrupted[] = _("名人堂的数据损坏了。");
const u8 gText_HOFNumber[] = _("名人堂 No.\n{STR_VAR_1}");
const u8 gText_LeagueChamp[] = _("联盟冠军！热烈祝贺！");
const u8 gText_Number[] = _("No. ");
const u8 gText_Level[] = _("Lv. ");
const u8 gText_IdNumberSlash[] = _("IDNo. /"); // Unused
const u8 gText_Name[] = _("名字");
const u8 gText_IDNumber[] = _("IDNo.");
const u8 gText_BirchInTrouble[] = _("小田卷博士遇到麻烦了！请拿出宝可\n梦去救助他吧！");
const u8 gText_ConfirmStarterChoice[] = _("确定选择这只宝可梦？");
const u8 gText_Pokemon4[] = _("宝可梦"); // Unused
const u8 gText_FlyToWhere[] = _("要飞到哪里？");
const u8 gMenuText_Use[] = _("使用");
const u8 gMenuText_Toss[] = _("扔掉");
const u8 gMenuText_Register[] = _("登录");
const u8 gMenuText_Give[] = _("携带");
const u8 gMenuText_Confirm[] = _("确定");
const u8 gText_Cancel[] = _("取消");
const u8 gText_Cancel2[] = _("退出");
const u8 gText_EmptyString2[] = _("");
const u8 gText_None[] = _("无");
const u8 gText_FiveMarks[] = _("?????");
const u8 gText_Slash[] = _("/");
const u8 gText_OneDash[] = _("-");
const u8 gText_TwoDashes[] = _("--");
const u8 gText_ThreeDashes[] = _("---");
const u8 gText_MaleSymbol[] = _("♂");
const u8 gText_FemaleSymbol[] = _("♀");
const u8 gText_LevelSymbol[] = _("{LV}");
const u8 gText_NumberClear01[] = _("{NO}{CLEAR 0x01}");
const u8 gText_RightArrow[] = _("{RIGHT_ARROW}"); // Unused
const u8 gText_IDNumber2[] = _("{ID}{NO}");
const u8 gText_Space[] = _(" ");
const u8 gText_SelectorArrow2[] = _("▶");
const u8 gText_GoBackPrevMenu[] = _("返回上一级菜单。");
const u8 gText_WhatWouldYouLike[] = _("请选择。");
const u8 gMenuText_Give2[] = _("给予");
const u8 gText_xVar1[] = _("×{STR_VAR_1}");
const u8 gText_Berry2[] = _("树果"); // Unused
const u8 gText_Coins[] = _("{STR_VAR_1}枚代币");
const u8 gText_CloseBag[] = _("合上包包");
const u8 gText_Var1IsSelected[] = _("要对{STR_VAR_1}做什么\n？");
const u8 gText_CantWriteMail[] = _("不能在这里写邮件。");
const u8 gText_NoPokemon[] = _("没有宝可梦哦！");
const u8 gText_MoveVar1Where[] = _("要将{STR_VAR_1}移动到\n哪个位置？");
const u8 gText_Var1CantBeHeld[] = _("无法携带{STR_VAR_1}！");
const u8 gText_TossHowManyVar1s[] = _("扔掉多少个{STR_VAR_1}\n？");
const u8 gText_ThrewAwayVar2Var1s[] = _("把{STR_VAR_2}个\n{STR_VAR_1}扔掉了。");
const u8 gText_ConfirmTossItems[] = _("Is it okay to\nthrow away {STR_VAR_2}\n{STR_VAR_1}?");
#if IS_HNS
    const u8 gText_DadsAdvice[] = _("ELM's advice…\n{PLAYER}, there's a time and place for\leverything!{PAUSE_UNTIL_PRESS}");
#else
    const u8 gText_DadsAdvice[] = _("DAD's advice…\n{PLAYER}, there's a time and place for\leverything!{PAUSE_UNTIL_PRESS}");
#endif
const u8 gText_PlayerUsedVar2[] = _("{PLAYER} used the\n{STR_VAR_2}.{PAUSE_UNTIL_PRESS}");
const u8 gText_RepelEffectsLingered[] = _("之前使用的喷雾效果还留着！\n{PAUSE_UNTIL_PRESS}");
const u8 gText_LureEffectsLingered[] = _("之前使用的香水效果还留着！\n{PAUSE_UNTIL_PRESS}");
const u8 gText_BoxFull[] = _("这个盒子满了。\n{PAUSE_UNTIL_PRESS}");
const u8 gText_TheField[] = _("野外");
const u8 gText_TheBattle[] = _("战斗");
const u8 gText_ThePokemonList[] = _("宝可梦列表");
const u8 gText_TheShop[] = _("友好商店");
const u8 gText_ThePC[] = _("电脑");

const u8 *const gBagMenu_ReturnToStrings[] =
{
    [ITEMMENULOCATION_FIELD]               = gText_TheField,
    [ITEMMENULOCATION_BATTLE]              = gText_TheBattle,
    [ITEMMENULOCATION_PARTY]               = gText_ThePokemonList,
    [ITEMMENULOCATION_SHOP]                = gText_TheShop,
    [ITEMMENULOCATION_BERRY_TREE]          = gText_TheField,
    [ITEMMENULOCATION_BERRY_BLENDER_CRUSH] = gText_TheField,
    [ITEMMENULOCATION_ITEMPC]              = gText_ThePC,
    [ITEMMENULOCATION_FAVOR_LADY]          = gText_TheField,
    [ITEMMENULOCATION_QUIZ_LADY]           = gText_TheField,
    [ITEMMENULOCATION_APPRENTICE]          = gText_TheField,
    [ITEMMENULOCATION_WALLY]               = gText_TheBattle,
    [ITEMMENULOCATION_PCBOX]               = gText_ThePC,
    [ITEMMENULOCATION_BERRY_TREE_MULCH]    = gText_TheField,
};

const u8 *const gPyramidBagMenu_ReturnToStrings[] =
{
    [PYRAMIDBAG_LOC_FIELD]       = gText_TheField,
    [PYRAMIDBAG_LOC_BATTLE]      = gText_TheBattle,
    [PYRAMIDBAG_LOC_PARTY]       = gText_ThePokemonList,
    [PYRAMIDBAG_LOC_CHOOSE_TOSS] = gText_TheField
};

const u8 gText_ReturnToVar1[] = _("返回{STR_VAR_1}。");

const u8 *const gPocketNamesStringsTable[] =
{
    [POCKET_ITEMS] =        COMPOUND_STRING("道  具"),
    [POCKET_POKE_BALLS] =   COMPOUND_STRING("精 灵 球"),
    [POCKET_TM_HM]  =       COMPOUND_STRING("招式学习器"),
    [POCKET_BERRIES] =      COMPOUND_STRING("树  果"),
    [POCKET_KEY_ITEMS] =    COMPOUND_STRING("重要物品"),
    [POCKET_MEDICINE] =     COMPOUND_STRING("MEDICINE"),
#if I_COMBINE_BAG_POCKETS == FALSE
    [POCKET_BATTLE_ITEMS] = COMPOUND_STRING("BATTLE"),
    [POCKET_TREASURES] =    COMPOUND_STRING("TREASURES"),
#endif
};

const u8 gText_NumberItem_TMBerry[] = _("{NO}{STR_VAR_1}{CLEAR 0x03}{STR_VAR_2}");
const u8 gText_NumberItem_HM[] = _("{CLEAR_TO 0x11}{STR_VAR_1}{CLEAR 0x05}{STR_VAR_2}");

const u8 gText_ShopBuy[] = _("购买");
const u8 gText_ShopSell[] = _("出售");
const u8 gText_ShopQuit[] = _("退出");
const u8 gText_ThatItemIsSoldOut[] = _("不好意思！该商品已售罄！\n{PAUSE_UNTIL_PRESS}");
const u8 gText_SoldOut[] = _("售罄");
const u8 gText_InBagVar1[] = _("持有：{STR_VAR_1}");
const u8 gText_QuitShopping[] = _("结束购物");
const u8 gText_Var1CertainlyHowMany[] = _("您要买几个{STR_VAR_1}\n？");
const u8 gText_Var1CertainlyHowMany2[] = _("您要买几个{STR_VAR_1}\n？");
const u8 gText_Var1AndYouWantedVar2[] = _("是{STR_VAR_1}啊。\n{STR_VAR_2}个一共是¥\l{STR_VAR_3}。");
const u8 gText_Var1AndYouWantedVar2BP[] = _("{STR_VAR_1}对吧？想要\n{STR_VAR_2}个吗？那需\l要{STR_VAR_3}BP。");
const u8 gText_Var1IsItThatllBeVar2[] = _("是{STR_VAR_1}啊。价格\n是¥{STR_VAR_2}。");
const u8 gText_YouWantedVar1ThatllBeVar2[] = _("是{STR_VAR_1}啊。价格\n是¥{STR_VAR_2}，可以\l吗？");
const u8 gText_YouWantedVar1ThatllBeVar2BP[] = _("你想要兑换{STR_VAR_1}\n？那需要{STR_VAR_2}B\lP，可以吗？");
const u8 gText_HereYouGoThankYou[] = _("请拿好。谢谢惠顾。");
const u8 gText_ThankYouIllSendItHome[] = _("谢谢惠顾。我会把商品送到您家的电\n脑中。");
const u8 gText_ThanksIllSendItHome[] = _("谢谢惠顾。我会把商品送到您家的电\n脑中。");
const u8 gText_YouDontHaveMoney[] = _("您的钱不够呢！\n{PAUSE_UNTIL_PRESS}");
const u8 gText_YouDontHaveEnoughBP[] = _("你的BP不够。\n{PAUSE_UNTIL_PRESS}");
const u8 gText_DontHaveEnoughVar1[] = _("你的{STR_VAR_1}数量不\n够。\l{PAUSE_UNTIL_PRESS}");
const u8 gText_Var1SureHowMany[] = _("{STR_VAR_1}是吧？好的\n。你想要多少个？");
const u8 gText_xOne[] = _("×1");
const u8 gText_xFive[] = _("×5");
const u8 gText_KurtVar1AndYouWantedVar2Plural[] = _("想要{STR_VAR_2}个是吧\n？一共需要{STR_VAR_3}\l个树果。");
const u8 gText_KurtVar1AndYouWantedVar2Singular[] = _("想要{STR_VAR_2}个是吧\n？一共需要{STR_VAR_3}\l个树果。");
const u8 gText_KurtGettingStarted[] = _("钢铁：我这就开工制作！");
const u8 gText_ExitMenu[] = _("退出菜单");
const u8 gText_NoMoreRoomForThis[] = _("不好意思，您好像已经拿不下呢……\n{PAUSE_UNTIL_PRESS}");
const u8 gText_SpaceForVar1Full[] = _("您已经拿不下更多的\n{STR_VAR_1}了！\l{PAUSE_UNTIL_PRESS}");
const u8 gText_AnythingElseICanHelp[] = _("还有什么其他需要吗？");
const u8 gText_CanIHelpWithAnythingElse[] = _("还有什么其他需要吗？");
const u8 gText_ThrowInPremierBall[] = _("还要多送个纪念球给您哦！\n{PAUSE_UNTIL_PRESS}");
const u8 gText_ThrowInPremierBalls[] = _("还要多送{STR_VAR_1}个\n纪念球给您哦！\l{PAUSE_UNTIL_PRESS}");
const u8 gText_CantBuyKeyItem[] = _("{STR_VAR_2}吗？不好意\n思。这个我们无法收购呢。\l{PAUSE_UNTIL_PRESS}");
const u8 gText_HowManyToSell[] = _("要卖出多少个\n{STR_VAR_2}？");
const u8 gText_ICanPayVar1[] = _("那么我用¥{STR_VAR_1}\n跟您收购吧。可以吗？");
const u8 gText_TurnedOverVar1ForVar2[] = _("给出{STR_VAR_2}，拿到\n了¥{STR_VAR_1}。");
const u8 gText_PokedollarVar1[] = _("¥{STR_VAR_1}");
const u8 gText_HP3[] = _("HP");
const u8 gText_SpAtk3[] = _("特攻");
const u8 gText_SpDef3[] = _("特防");
const u8 gText_WontHaveEffect[] = _("即便使用也无效果哦。\n{PAUSE_UNTIL_PRESS}");
const u8 gText_NextFusionMon[] = _("请选择要合体的{PKMN}。");
const u8 gText_CantBeUsedOnPkmn[] = _("不能用于这只宝可梦。\n{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCantSwitchOut[] = _("无法收回{STR_VAR_1}！\n{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyInBattle[] = _("{STR_VAR_1}已经在战斗\n了！\l{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadySelected[] = _("{STR_VAR_1}已经被选中\n了。\l{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHasNoEnergy[] = _("{STR_VAR_1}没有力气战\n斗了！\l{PAUSE_UNTIL_PRESS}");
const u8 gText_CantSwitchWithAlly[] = _("无法选择{STR_VAR_1}的\n宝可梦。\l{PAUSE_UNTIL_PRESS}");
const u8 gText_EggCantBattle[] = _("无法让蛋出场战斗。\n{PAUSE_UNTIL_PRESS}");
const u8 gText_CantUseUntilNewBadge[] = _("在得到新的徽章之前还不能使用。\n{PAUSE_UNTIL_PRESS}");
const u8 gText_NoMoreThanVar1Pkmn[] = _("参加的宝可梦数量不能超过\n{STR_VAR_1}只。\l{PAUSE_UNTIL_PRESS}");
const u8 gText_SendMailToPC[] = _("取下邮件并发送到你的电脑吗？");
const u8 gText_MailSentToPC[] = _("邮件已经发送到你的电脑了！\n{PAUSE_UNTIL_PRESS}");
const u8 gText_PCMailboxFull[] = _("你电脑的邮箱已经满了！\n{PAUSE_UNTIL_PRESS}");
const u8 gText_MailMessageWillBeLost[] = _("如果把邮件取下来，内容将会丢失，\n可以吗？");
const u8 gText_RemoveMailBeforeItem[] = _("取下邮件才能携带道具！\n{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnWasGivenItem[] = _("让{STR_VAR_1}携带了\n{STR_VAR_2}！\l{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyHoldingItemSwitch[] = _("{STR_VAR_1}已经携带了\n{STR_VAR_2}。\p要和它替换吗？");
const u8 gText_PkmnNotHolding[] = _("{STR_VAR_1}没有携带任\n何道具！\l{PAUSE_UNTIL_PRESS}");
const u8 gText_ReceivedItemFromPkmn[] = _("从{STR_VAR_1}那里收回\n了{STR_VAR_2}！\l{PAUSE_UNTIL_PRESS}");
const u8 gText_MailTakenFromPkmn[] = _("将宝可梦身上的邮件取下来了。\n{PAUSE_UNTIL_PRESS}");
const u8 gText_SwitchedPkmnItem[] = _("收回了{STR_VAR_2}，让\n宝可梦携带了\l{STR_VAR_1}！\l{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHoldingItemCantHoldMail[] = _("宝可梦已经携带了道具，不能再携带\n邮件了。\l{PAUSE_UNTIL_PRESS}");
const u8 gText_MailTransferredFromMailbox[] = _("从邮箱里拿出了邮件。\n{PAUSE_UNTIL_PRESS}");
const u8 gText_BagFullCouldNotRemoveItem[] = _("包包已满，不能接收道具了。\n{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnLearnedMove3[] = _("{STR_VAR_1}学会了\n{STR_VAR_2}！");
const u8 gText_PkmnLearnedMove4[] = _("{STR_VAR_1}学会了\n{STR_VAR_2}！\l{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCantLearnMove[] = _("{STR_VAR_1}与\n{STR_VAR_2}不匹配！\p{STR_VAR_2}是学不会的\n！\l{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnNeedsToReplaceMove[] = _("{STR_VAR_1}想要学会招\n式{STR_VAR_2}。\p但是，{STR_VAR_1}已经\n学会了4个招式。\p要遗忘一个招式来学会\n{STR_VAR_2}吗？");
const u8 gText_StopLearningMove2[] = _("要放弃学习{STR_VAR_2}\n吗？");
const u8 gText_MoveNotLearned[] = _("{STR_VAR_1}没有学习\n{STR_VAR_2}就结束了。\l{PAUSE_UNTIL_PRESS}");
const u8 gText_WhichMoveToForget[] = _("要忘记哪个招式呢？\n{PAUSE_UNTIL_PRESS}");
const u8 gText_12PoofForgotMove[] = _("1，{PAUSE 15}2，\n{PAUSE 15}……\l{PAUSE 15}……\l{PAUSE 15}……\l{PAUSE 15}\l{PLAY_SE SE_BALL_BOUNCE_1}\l空！\p{STR_VAR_1}把\n{STR_VAR_2}的使用方法\l忘得干干净净了！\p于是……！\n{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyKnows[] = _("{STR_VAR_1}学会了\n{STR_VAR_2}！\l{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHPRestoredByVar2[] = _("{STR_VAR_1}的体力回复\n了{STR_VAR_2}。\l{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCuredOfPoison[] = _("{STR_VAR_1}的毒消失得\n干干净净！\l{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCuredOfParalysis[] = _("{STR_VAR_1}身体的麻痹\n状态消除了！\l{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnWokeUp2[] = _("{STR_VAR_1}醒过来了！\n{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnBurnHealed[] = _("{STR_VAR_1}的灼伤治愈\n了！\l{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFrostbiteHealed[] = _("{STR_VAR_1}的冻伤治愈\n了！\l{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnThawedOut[] = _("{STR_VAR_1}身体的冰融\n化了！\l{PAUSE_UNTIL_PRESS}");
const u8 gText_PPWasRestored[] = _("回复PP了！\n{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnRegainhedHealth[] = _("{STR_VAR_1}回复体力了\n！\l{PAUSE_UNTIL_PRESS}"); // Unused
const u8 gText_PkmnBecameHealthy[] = _("{STR_VAR_1}变得健康了\n！\l{PAUSE_UNTIL_PRESS}");
const u8 gText_MovesPPIncreased[] = _("{STR_VAR_1}的PP上升\n了！\l{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnElevatedToLvVar2[] = _("{STR_VAR_1}的等级升到\n了Lv.{STR_VAR_2}！");
const u8 gText_PkmnGainedExp[] = _("{STR_VAR_1}获得了\n{STR_VAR_2}经验值！\l{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnGainedExpAndElevatedToLvVar3[] = _("{STR_VAR_1}获得了\n{STR_VAR_2}经验值，等\l级提升到了Lv. \l{STR_VAR_3}！");
const u8 gText_PkmnBaseVar2StatIncreased[] = _("{STR_VAR_1}的基础\n{STR_VAR_2}上升了！\l{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFriendlyBaseVar2Fell[] = _("{STR_VAR_1}和你有点亲\n密了！{STR_VAR_2}的基\l础点数降低了！\l{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAdoresBaseVar2Fell[] = _("{STR_VAR_1}和你的亲密\n度已经最高了！\l{STR_VAR_2}的基础点数\l降低了！\l{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFriendlyBaseVar2CantFall[] = _("{STR_VAR_1}和你有点亲\n密了！{STR_VAR_2}的基\l础点数不再降低！\l{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnSnappedOutOfConfusion[] = _("{STR_VAR_1}的混乱解除\n了！\l{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnGotOverInfatuation[] = _("{STR_VAR_1}的着迷解除\n了！\l{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnTransformed[] = _("{STR_VAR_1}变成其他样\n子了！\l{PAUSE_UNTIL_PRESS}");
const u8 gText_ThrowAwayItem[] = _("扔掉这个{STR_VAR_1}吗\n？");
const u8 gText_ItemThrownAway[] = _("{STR_VAR_1}被扔掉了。\n{PAUSE_UNTIL_PRESS}");
const u8 gText_TeachWhichPokemon2[] = _("要让哪只宝可梦学习？"); // Unused
const u8 gText_ChoosePokemon[] = _("请选择宝可梦。");
const u8 gText_MoveToWhere[] = _("要和哪只宝可梦替换？");
const u8 gText_TeachWhichPokemon[] = _("要让哪只宝可梦学习？");
const u8 gText_UseOnWhichPokemon[] = _("要用于哪只宝可梦？");
const u8 gText_GiveToWhichPokemon[] = _("要让哪只宝可梦携带？");
const u8 gText_DoWhatWithPokemon[] = _("要对这只{PKMN}做什么？");
const u8 gText_NothingToCut[] = _("没有能砍断的东西。");
const u8 gText_CantSurfHere[] = _("无法在这里冲浪。");
const u8 gText_AlreadySurfing[] = _("已经在冲浪中了。");
const u8 gText_CantUseHere[] = _("无法在这里使用！");
const u8 gText_RestoreWhichMove[] = _("要回复哪个招式？");
const u8 gText_BoostPp[] = _("要提升哪个招式的PP？");
const u8 gText_DoWhatWithItem[] = _("要拿这个道具做什么？");
const u8 gText_NoPokemonForBattle[] = _("没有能参加对战的宝可梦！");
const u8 gText_ChoosePokemon2[] = _("请选择要参加对战的宝可梦。");
const u8 gText_NotEnoughHp[] = _("没有足够的体力……");
const u8 gText_PokemonAreNeeded[] = _("需要选择{STR_VAR_1}只\n宝可梦！");
const u8 gText_PokemonCantBeSame[] = _("您选择了相同种类的宝可梦！");
const u8 gText_NoIdenticalHoldItems[] = _("有携带着相同道具的宝可梦！");
const u8 gText_CurrentIsTooFast[] = _("水流太急了！");
const u8 gText_DoWhatWithMail[] = _("要拿这个邮件怎么办？");
const u8 gText_ChoosePokemonCancel[] = _("请选择宝可梦或取消。");
const u8 gText_ChoosePokemonConfirm[] = _("请选择宝可梦并确认。");
const u8 gText_SendWhichMonToPC[] = _("要将哪只宝可梦发送到盒子里？");
const u8 gText_MoveItemWhere[] = _("要替换到哪里？");
const u8 gText_XsYAnd[] = _("将{STR_VAR_1}的\n{STR_VAR_2}与");
const u8 gText_XsYWereSwapped[] = _("{STR_VAR_1}的\n{STR_VAR_2}互换了！\l{PAUSE_UNTIL_PRESS}");
const u8 gText_EnjoyCycling[] = _("让我们享受兜风吧！");
const u8 gText_InUseAlready_PM[] = _("这个已经在使用了！");
const u8 gText_AlreadyHoldingOne[] = _("{STR_VAR_1}已经携带了\n一个{STR_VAR_2}！");
const u8 gText_WhichAppliance[] = _("要购买哪种电器呢？");
const u8 gText_NoUse[] = _("不能使用");
const u8 gText_Able[] = _("能使用！");
const u8 gText_First_PM[] = _("1号");
const u8 gText_Second_PM[] = _("2号");
const u8 gText_Third_PM[] = _("3号");
const u8 gText_Able2[] = _("能使用！");
const u8 gText_NotAble[] = _("不能使用");
const u8 gText_Able3[] = _("能学习！");
const u8 gText_NotAble2[] = _("不能学");
const u8 gText_Learned[] = _("已学会");
const u8 gText_Have[] = _("已有");
const u8 gText_DontHave[] = _("没有");
const u8 gText_Fourth[] = _("4号");
const u8 gText_PkmnCantParticipate[] = _("这只宝可梦无法参加！\n{PAUSE_UNTIL_PRESS}");
const u8 gText_CancelParticipation[] = _("要取消参加吗？");
const u8 gText_CancelBattle[] = _("要取消战斗吗？");
const u8 gText_ReturnToWaitingRoom[] = _("要返回等候大厅吗？");
const u8 gText_CancelChallenge[] = _("要取消挑战吗？");
const u8 gText_EscapeFromHere[] = _("要从这里脱离并返回\n{STR_VAR_1}吗？");
const u8 gText_ReturnToHealingSpot[] = _("要返回上一个在\n{STR_VAR_1}的回复点吗\l？");
const u8 gText_PauseUntilPress[] = _("{PAUSE_UNTIL_PRESS}");
const u8 gJPText_AreYouSureYouWantToSpinTradeMon[] = _("确定要把{STR_VAR_1}送\n去转转交换吗？");
ALIGNED(4) const u8 gText_OnlyPkmnForBattle[] = _("这是你最后1个能战斗的宝可梦了！");
ALIGNED(4) const u8 gText_PkmnCantBeTradedNow[] = _("这只宝可梦暂时不能交换！");
ALIGNED(4) const u8 gText_PkmnCantBeTraded[] = _("这只宝可梦不能交换！");
ALIGNED(4) const u8 gText_EggCantBeTradedNow[] = _("蛋不能交换！");
ALIGNED(4) const u8 gText_OtherTrainersPkmnCantBeTraded[] = _("对方训练家的宝可梦暂时不能交换！");
ALIGNED(4) const u8 gText_OtherTrainerCantAcceptPkmn[] = _("对方训练家暂时不能接收这只宝可梦\n！");
ALIGNED(4) const u8 gText_CantTradeWithTrainer[] = _("你暂时不能和那个训练家交换！");
ALIGNED(4) const u8 gText_NotPkmnOtherTrainerWants[] = _("这不是对方训练家想要的宝可梦种类\n！");
ALIGNED(4) const u8 gText_ThatIsntAnEgg[] = _("那不是宝可梦蛋！");
const u8 gText_Register[] = _("登记");
const u8 gText_Attack3[] = _("攻击");
const u8 gText_Defense3[] = _("防御");
const u8 gText_SpAtk4[] = _("特攻");
const u8 gText_SpDef4[] = _("特防");
const u8 gText_Speed2[] = _("速度");
const u8 gText_HP4[] = _("HP");
const u8 gText_EmptyString8[] = _(""); // Unused
const u8 gText_OTSlash[] = _("初训家/");
const u8 gText_RentalPkmn[] = _("租借宝可梦");
const u8 gText_TypeSlash[] = _("属性/");
const u8 gText_Power[] = _("威力");
const u8 gText_Accuracy2[] = _("命中");
const u8 gText_Appeal[] = _("吸引力");
const u8 gText_Jam[] = _("干扰力");
const u8 gText_Status[] = _("状态");
const u8 gText_ExpPoints[] = _("经验值");
const u8 gText_NextLv[] = _("再升级需");
const u8 gText_RibbonsVar1[] = _("奖章数：{STR_VAR_1}");
const u8 gText_EmptyString5[] = _("");
const u8 gText_Events[] = _("事件"); // Unused
const u8 gText_Switch[] = _("排序");
const u8 gText_PkmnInfo[] = _("宝可梦信息");
const u8 gText_PkmnSkills[] = _("宝可梦能力");
const u8 gText_BattleMoves[] = _("战斗招式");
const u8 gText_ContestMoves[] = _("华丽大赛招式");
const u8 gText_Info[] = _("查看招式");
const u8 gText_EggWillTakeALongTime[] = _("这只蛋孵出来好像需要很长一段时间\n。");
const u8 gText_EggWillTakeSomeTime[] = _("会孵出来什么呢？好像还要过段时间\n才会孵出来。");
const u8 gText_EggWillHatchSoon[] = _("好像偶尔在动。再过一点时间才会孵\n出来吧？");
const u8 gText_EggAboutToHatch[] = _("能听到从里面传来的声音！好像快要\n孵出来了！");
const u8 gText_EggReadyToHatch_Nuzlocke[] = _("就要孵化了，但受限于Nuzloc\nke规则限制！");
const u8 gText_HMMovesCantBeForgotten2[] = _("暂时不能忘记秘传招式。");
const u8 gText_XNatureMetAtYZ[] = _("{DYNAMIC 0}\n{DYNAMIC 2}\l{DYNAMIC 1}\l{DYNAMIC 5}\l{DYNAMIC 6}\l{DYNAMIC 7}性格，在\l{LV_2}\l{DYNAMIC 0}\l{DYNAMIC 3}\l{DYNAMIC 1}时，于\l{DYNAMIC 0}\l{DYNAMIC 4}\l{DYNAMIC 1}相遇。");
const u8 gText_XNatureHatchedAtYZ[] = _("{DYNAMIC 0}\n{DYNAMIC 2}\l{DYNAMIC 1}\l{DYNAMIC 5}\l{DYNAMIC 6}\l{DYNAMIC 7}性格，在\l{LV_2}\l{DYNAMIC 0}\l{DYNAMIC 3}\l{DYNAMIC 1}时，于\l{DYNAMIC 0}\l{DYNAMIC 4}\l{DYNAMIC 1}孵化。");
const u8 gText_XNatureObtainedInTrade[] = _("{DYNAMIC 0}\n{DYNAMIC 2}\l{DYNAMIC 1}\l{DYNAMIC 5}\l{DYNAMIC 6}\l{DYNAMIC 7}性格，通过\l连接交换获得。");
const u8 gText_XNatureFatefulEncounter[] = _("{DYNAMIC 0}\n{DYNAMIC 2}\l{DYNAMIC 1}\l{DYNAMIC 5}\l{DYNAMIC 6}\l{DYNAMIC 7}性格，在\l{LV_2}\l{DYNAMIC 0}\l{DYNAMIC 3}\l{DYNAMIC 1}时命运般的\l相遇。");
const u8 gText_XNatureProbablyMetAt[] = _("{DYNAMIC 0}\n{DYNAMIC 2}\l{DYNAMIC 1}\l{DYNAMIC 5}\l{DYNAMIC 6}\l{DYNAMIC 7}性格，似乎\l是在{LV_2}\l{DYNAMIC 0}\l{DYNAMIC 3}\l{DYNAMIC 1}时，于\l{DYNAMIC 0}\l{DYNAMIC 4}\l{DYNAMIC 1}相遇。");
const u8 gText_XNature[] = _("{DYNAMIC 0}\n{DYNAMIC 2}\l{DYNAMIC 1}\l{DYNAMIC 5}\l{DYNAMIC 6}\l{DYNAMIC 7}性格");
const u8 gText_XNatureMetSomewhereAt[] = _("{DYNAMIC 0}\n{DYNAMIC 2}\l{DYNAMIC 1}\l{DYNAMIC 5}\l{DYNAMIC 6}\l{DYNAMIC 7}性格，在某\l处的{LV_2}\l{DYNAMIC 0}\l{DYNAMIC 3}\l{DYNAMIC 1}时相遇。");
const u8 gText_XNatureHatchedSomewhereAt[] = _("{DYNAMIC 0}\n{DYNAMIC 2}\l{DYNAMIC 1}\l{DYNAMIC 5}\l{DYNAMIC 6}\l{DYNAMIC 7}性格，在某\l处的{LV_2}\l{DYNAMIC 0}\l{DYNAMIC 3}\l{DYNAMIC 1}时孵化。");
const u8 gText_OddEggFoundByCouple[] = _("从培育屋夫妇那里发现的不可思议的\n宝可梦蛋。");
const u8 gText_PeculiarEggNicePlace[] = _("在一个好地方得到的罕见的宝可梦蛋\n。");
const u8 gText_PeculiarEggTrade[] = _("通过交换得到的罕见的宝可梦蛋。");
const u8 gText_EggFromHotSprings[] = _("在温泉那里得到的宝可梦蛋。");
const u8 gText_OddEggFromDaycare[] = _("在培育屋得到的奇特宝可梦蛋。");
const u8 gText_EggFromTraveler[] = _("在一个旅行者那里得到的不可思议的\n宝可梦蛋。");
const u8 gText_ApostropheSBase[] = _("的基地");
const u8 gText_OkayToDeleteFromRegistry[] = _("要从登记列表中删除\n{STR_VAR_1}吗？");
const u8 gText_RegisteredDataDeleted[] = _("登记条目已被删除。\n{PAUSE_UNTIL_PRESS}");
const u8 gText_NoRegistry[] = _("登记列表是空的。\n{PAUSE_UNTIL_PRESS}");
const u8 gText_DelRegist[] = _("删除登记条目。");
const u8 gText_Var3Var1SlashVar2[] = _("{STR_VAR_3}{STR_VAR_1}/{STR_VAR_2}"); // Unused
const u8 gText_Decorate[] = _("装饰");
const u8 gText_PutAway[] = _("收回");
const u8 gText_Toss2[] = _("扔掉");
const u8 gText_Color161Shadow161[] = _("{COLOR 161}{SHADOW 161}");
const u8 gText_PutOutSelectedDecorItem[] = _("取出选择的装饰物品。");
const u8 gText_StoreChosenDecorInPC[] = _("将选择的装饰物品存入电脑中。");
const u8 gText_ThrowAwayUnwantedDecors[] = _("扔掉不想要的装饰物品。");
const u8 gText_NoDecorations[] = _("目前没有任何装饰物品。\n{PAUSE_UNTIL_PRESS}");
const u8 gText_Desk[] = _("桌子");
const u8 gText_Chair[] = _("椅子");
const u8 gText_Plant[] = _("盆栽");
const u8 gText_Ornament[] = _("物品");
const u8 gText_Mat[] = _("地毯");
const u8 gText_Poster[] = _("海报");
const u8 gText_Doll[] = _("玩偶");
const u8 gText_Cushion[] = _("垫子");
const u8 gText_Gold[] = _("金");
const u8 gText_Silver[] = _("银");
const u8 gText_PlaceItHere[] = _("要放在这里吗？");
const u8 gText_CantBePlacedHere[] = _("无法放在这里！");
const u8 gText_CancelDecorating[] = _("要停止装饰吗？");
const u8 gText_InUseAlready[] = _("这个已经在使用了。");
const u8 gText_NoMoreDecorations[] = _("无法再摆放装饰物品了！最多可以摆\n放{STR_VAR_1}个。");
const u8 gText_NoMoreDecorations2[] = _("无法再摆放装饰物品了！最多可以摆\n放{STR_VAR_1}个。");
const u8 gText_MustBePlacedOnDesk[] = _("无法放在这里。这里只能放桌子。"); // Unused
const u8 gText_CantPlaceInRoom[] = _("这个装饰物品无法放在你的个人房间\n。");
const u8 gText_CantThrowAwayInUse[] = _("这个装饰物品已经在使用了。现在无\n法扔掉！");
const u8 gText_DecorationWillBeDiscarded[] = _("要扔掉{STR_VAR_1}吗？");
const u8 gText_DecorationThrownAway[] = _("把那个装饰物品扔掉了。");
const u8 gText_StopPuttingAwayDecorations[] = _("停止收拾装饰物品？");
const u8 gText_NoDecorationHere[] = _("这里没有装饰物品。");
const u8 gText_ReturnDecorationToPC[] = _("将这个装饰物品收回电脑吗？");
const u8 gText_DecorationReturnedToPC[] = _("该装饰物品被收回了电脑。");
const u8 gText_NoDecorationsInUse[] = _("没有在使用的装饰物品。\n{PAUSE_UNTIL_PRESS}");
const u8 gText_NoItems[] = _("这里没有道具。\n{PAUSE_UNTIL_PRESS}");
const u8 gText_NoMailHere[] = _("这里没有邮件。\n{PAUSE_UNTIL_PRESS}");
const u8 gText_WhatToDoWithVar1sMail[] = _("你打算如何处理\n{STR_VAR_1}的邮件？");
const u8 gText_MessageWillBeLost[] = _("邮件信息将会丢失。确定吗？");
const u8 gText_BagIsFull[] = _("包包已经满了。\n{PAUSE_UNTIL_PRESS}");
const u8 gText_MailToBagMessageErased[] = _("邮件信息被清除掉了，邮件放回了包\n包。\l{PAUSE_UNTIL_PRESS}");
const u8 gText_Dad[] = _("爸爸");
const u8 gText_Mom[] = _("妈妈");
const u8 gText_MomHowMuchDeposit[] = _("想在妈妈这里存多少钱呢？");
const u8 gText_MomHowMuchWithdraw[] = _("想从妈妈这里取多少钱呢？");
const u8 gText_MomMatchCallDesc[] = _("温柔慈祥");
const u8 gText_MomMatchCallName[] = _("妈妈");
const u8 gText_MomMenuCheckSavings[] = _("查看存款");
const u8 gText_MomMenuDeposit[] = _("存入");
const u8 gText_MomMenuWithdraw[] = _("取出");
const u8 gText_MomMenuToggleSaving[] = _("储蓄");
const u8 gText_MomMenuExit[] = _("退出");
const u8 gText_Info2[] = _("说明");
const u8 gText_CoolnessContest[] = _("帅气华丽大赛");
const u8 gText_BeautyContest[] = _("美丽华丽大赛");
const u8 gText_CutenessContest[] = _("可爱华丽大赛");
const u8 gText_SmartnessContest[] = _("聪明华丽大赛");
const u8 gText_ToughnessContest[] = _("强壮华丽大赛");
const u8 gText_Decoration2[] = _("装饰");
const u8 gText_PackUp[] = _("收拾");
const u8 gText_Registry[] = _("登记册");
const u8 gText_Information[] = _("听说明");
const u8 gText_Yes[] = _("是");
const u8 gText_No[] = _("否");
const u8 gText_Lv50[] = _("Lv. 50级");
const u8 gText_OpenLevel[] = _("自由等级");
const u8 gText_RedShard[] = _("红碎片");
const u8 gText_YellowShard[] = _("黄碎片");
const u8 gText_BlueShard[] = _("蓝碎片");
const u8 gText_GreenShard[] = _("绿碎片");
const u8 gText_BattleFrontier[] = _("对战开拓区");
const u8 gText_Cool[] = _("帅气");
const u8 gText_Beauty[] = _("美丽");
const u8 gText_Cute[] = _("可爱");
const u8 gText_Smart[] = _("聪明");
const u8 gText_Tough[] = _("强壮");
const u8 gText_Normal[] = _("普通级");
const u8 gText_Super[] = _("高手级");
const u8 gText_Hyper[] = _("究极级");
const u8 gText_Master[] = _("大师级");
const u8 gText_Cool2[] = _("帅气");
const u8 gText_Beauty2[] = _("美丽");
const u8 gText_Cute2[] = _("可爱");
const u8 gText_Smart2[] = _("聪明");
const u8 gText_Tough2[] = _("强壮");
const u8 gText_Items[] = _("道具");
const u8 gText_Key_Items[] = _("重要宝物");
const u8 gText_Poke_Balls[] = _("精灵球");
const u8 gText_TMs_Hms[] = _("招式学习器");
const u8 gText_Berries2[] = _("树果");
const u8 gText_Medicine[] = _("MEDICINE");
#if I_COMBINE_BAG_POCKETS == FALSE
const u8 gText_BattleItems[] = _("BATTLE ITEMS");
const u8 gText_Treasures[] = _("TREASURES");
#endif
const u8 gText_SomeonesPC[] = _("SOMEONE'S PC");
const u8 gText_LanettesPC[] = _("真由美的电脑");
const u8 gText_BillsPc[] = _("正辉的电脑");
const u8 gText_PlayersPC[] = _("{PLAYER}的电脑");
const u8 gText_HallOfFame[] = _("登入名人堂");
const u8 gText_LogOff[] = _("关闭电源");
const u8 gText_Challenges[] = _("挑战");
const u8 gText_Opponent[] = _("对手");
const u8 gText_Tourney_Tree[] = _("对阵图");
const u8 gText_ReadyToStart[] = _("准备开始");
const u8 gText_Single2[] = _("单打");
const u8 gText_Double2[] = _("双打");
const u8 gText_Multi[] = _("多人");
const u8 gText_MultiLink[] = _("多人连线");
const u8 gText_MenuOptionPokedex[] = _("图鉴");
const u8 gText_MenuOptionPokemon[] = _("宝可梦");
const u8 gText_MenuOptionBag[] = _("BAG");
#if IS_HNS
const u8 gText_MenuOptionPokenav[] = _("POKéGEAR");
#else
const u8 gText_MenuOptionPokenav[] = _("POKéNAV");
#endif
const u8 gText_Blank[] = _("");
const u8 gText_MenuOptionSave[] = _("记录");
const u8 gText_MenuOptionOption[] = _("设置");
const u8 gText_MenuOptionExit[] = _("退出");
const u8 gText_SouthernIsland[] = _("南方孤岛");
const u8 gText_BirthIsland[] = _("诞生之岛");
const u8 gText_FarawayIsland[] = _("边境的小岛");
const u8 gText_NavelRock[] = _("脐之岩");
const u8 gText_NormalTagMatch[] = _("普通类比赛");
const u8 gText_VarietyTagMatch[] = _("多样类比赛");
const u8 gText_UniqueTagMatch[] = _("唯一类比赛");
const u8 gText_ExpertTagMatch[] = _("专家类比赛");
const u8 gText_TradeCenter[] = _("通信交换处");
const u8 gText_Colosseum[] = _("竞技场");
const u8 gText_RecordCorner[] = _("混合记录角");
const u8 gText_BerryCrush3[] = _("捣树果");
const u8 gText_BattleRules[] = _("对战规则");
const u8 gText_JudgeMind[] = _("判定：心");
const u8 gText_JudgeSkill[] = _("判定：技");
const u8 gText_JudgeBody[] = _("判定：体");
const u8 gText_BasicRules[] = _("基本规则");
const u8 gText_SwapPartners[] = _("交换：宝可梦");
const u8 gText_SwapNumber[] = _("交换：次数");
const u8 gText_SwapNotes[] = _("交换：注意事项");
const u8 gText_BattleBasics[] = _("对战基础");
const u8 gText_PokemonNature[] = _("宝可梦性格");
const u8 gText_PokemonMoves[] = _("宝可梦招式");
const u8 gText_Underpowered[] = _("难以发挥");
const u8 gText_WhenInDanger[] = _("陷入危机时");
const u8 gText_BattlePokemon[] = _("对战宝可梦");
const u8 gText_BattleTrainers[] = _("对战训练家");
const u8 gText_GoOn[] = _("继续");
const u8 gText_Record2[] = _("记录");
const u8 gText_Rest[] = _("睡觉");
const u8 gText_Retire[] = _("弃权");
const u8 gText_1F[] = _("1楼");
const u8 gText_2F[] = _("2楼");
const u8 gText_3F[] = _("3楼");
const u8 gText_4F[] = _("4楼");
const u8 gText_5F[] = _("5楼");
const u8 gText_6F[] = _("6楼");
const u8 gText_7F[] = _("7楼");
const u8 gText_8F[] = _("8楼");
const u8 gText_9F[] = _("9楼");
const u8 gText_10F[] = _("10楼");
const u8 gText_11F[] = _("11楼");
const u8 gText_B1F[] = _("地下1楼");
const u8 gText_B2F[] = _("地下2楼");
const u8 gText_B3F[] = _("地下3层");
const u8 gText_B4F[] = _("地下4层");
const u8 gText_Rooftop[] = _("屋顶");
const u8 gText_ElevatorNowOn[] = _("现在：");
const u8 gText_BP[] = _("BP");
const u8 gText_RankingHall[] = _("排名大厅");
const u8 gText_ExchangeService[] = _("兑换服务区");
const u8 gText_LilycoveCity[] = _("水静市");
const u8 gText_SlateportCity[] = _("凯那市");
const u8 gText_Exit[] = _("退出");
const u8 gText_YourPartysFull[] = _("同行的宝可梦已满！\n{PAUSE_UNTIL_PRESS}");
const u8 gText_InParty[] = _("同行中");
const u8 gText_PokemonMaleLv[] = _("{DYNAMIC 0}{BACKGROUND WHITE}{TEXT_COLORS LIGHT_RED GREEN WHITE}♂{BACKGROUND WHITE}{TEXT_COLORS DARK_GRAY LIGHT_GRAY WHITE}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonFemaleLv[] = _("{DYNAMIC 0}{BACKGROUND WHITE}{TEXT_COLORS LIGHT_GREEN BLUE WHITE}♀{BACKGROUND WHITE}{TEXT_COLORS DARK_GRAY LIGHT_GRAY WHITE}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonNoGenderLv[] = _("{DYNAMIC 0}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonMaleLv2[] = _("{DYNAMIC 0}{BACKGROUND WHITE}{TEXT_COLORS LIGHT_RED GREEN WHITE}♂{BACKGROUND WHITE}{TEXT_COLORS DARK_GRAY LIGHT_GRAY WHITE}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_PokemonFemaleLv2[] = _("{DYNAMIC 0}{BACKGROUND WHITE}{TEXT_COLORS LIGHT_GREEN BLUE WHITE}♀{BACKGROUND WHITE}{TEXT_COLORS DARK_GRAY LIGHT_GRAY WHITE}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_PokemonNoGenderLv2[] = _("{DYNAMIC 0}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_CombineFourWordsOrPhrases[] = _("请组合4个词语或者短语");
const u8 gText_AndMakeYourProfile[] = _("构成你的个人简介");
const u8 gText_CombineSixWordsOrPhrases[] = _("请组合6个词语或者短语");
const u8 gText_AndMakeAMessage[] = _("构成一段信息。");
const u8 gText_FindWordsThatDescribeYour[] = _("找出词语来描述");
const u8 gText_FeelingsRightNow[] = _("你当前的感觉吧！");
const u8 gText_WithFourPhrases[] = _("使用4个句子"); // Unused
const u8 gText_CombineNineWordsOrPhrases[] = _("组合9个词语或者短语");
const u8 gText_AndMakeAMessage2[] = _("来构成一段信息。");
const u8 gText_ChangeJustOneWordOrPhrase[] = _("更改1个词或者短语");
const u8 gText_AndImproveTheBardsSong[] = _("来改进诗人的歌词。");
const u8 gText_YourProfile[] = _("你的档案");
const u8 gText_YourFeelingAtTheBattlesStart[] = _("你在对战开始时的感觉");
const u8 gText_WhatYouSayIfYouWin[] = _("对战获胜后你会说什么");
const u8 gText_WhatYouSayIfYouLose[] = _("对战输掉后你会说什么");
const u8 gText_TheAnswer[] = _("答案");
const u8 gText_TheMailMessage[] = _("邮件信息");
const u8 gText_TheMailSalutation[] = _("邮件的称呼语"); // Unused
const u8 gText_TheBardsSong2[] = _("新歌");
const u8 gText_CombineTwoWordsOrPhrases[] = _("请组合2个词语或者短语");
const u8 gText_AndMakeATrendySaying[] = _("作为流行语。");
const u8 gText_TheTrendySaying[] = _("流行语");
const u8 gText_IsAsShownOkay[] = _("如上所示，可以吗？");
const u8 gText_CombineTwoWordsOrPhrases2[] = _("请组合2个词语或者短语");
const u8 gText_ToTeachHerAGoodSaying[] = _("来教她一句好谚语。");
const u8 gText_FindWordsWhichFit[] = _("请找出适合形容");
const u8 gText_TheTrainersImage[] = _("这个训练家的形象。");
const u8 gText_TheImage[] = _("形象：");
const u8 gText_OutOfTheListedChoices[] = _("从列出的选项中，");
const u8 gText_SelectTheAnswerToTheQuiz[] = _("选出谜题的答案！");
const u8 gText_AndCreateAQuiz[] = _("并创建一个谜题！");
const u8 gText_PickAWordOrPhraseAnd[] = _("挑选1个词语或者短语");
const u8 gText_SetTheQuizAnswer[] = _("并设置谜题的答案。");
const u8 gText_TheAnswerColon[] = _("答案：");
const u8 gText_TheQuizColon[] = _("谜题："); // Unused
const u8 gText_ApprenticePhrase[] = _("新手词汇：");
const u8 gText_QuitEditing[] = _("停止编辑吗？");
const u8 gText_StopGivingPkmnMail[] = _("放弃让宝可梦携带邮件吗？");
const u8 gText_AndFillOutTheQuestionnaire[] = _("并找出问卷。");
const u8 gText_LetsReplyToTheInterview[] = _("让我们回复采访吧！");
const u8 gText_AllTextBeingEditedWill[] = _("所有正在编辑的内容会被删除，");
const u8 gText_BeDeletedThatOkay[] = _("这样可以吗？");
const u8 gText_QuitEditing2[] = _("停止编辑吗？"); // Unused
const u8 gText_EditedTextWillNotBeSaved[] = _("已编辑的内容不会被保存，"); // Unused
const u8 gText_IsThatOkay[] = _("这样可以吗？"); // Unused
const u8 gText_PleaseEnterPhraseOrWord[] = _("请输入一个短语或者词语，"); // Unused
const u8 gText_EntireTextCantBeDeleted[] = _("无法删除所有的文本！");
const u8 gText_OnlyOnePhrase[] = _("只可以更改1个短语。");
const u8 gText_OriginalSongWillBeUsed[] = _("将会使用最初的歌曲。");
const u8 gText_ThatsTrendyAlready[] = _("这已经很流行了！"); // Unused
const u8 gText_CombineTwoWordsOrPhrases3[] = _("请组合2个词语或者短语。");
const u8 gText_QuitGivingInfo[] = _("放弃给予信息吗？"); // Unused
const u8 gText_StopGivingPkmnMail2[] = _("放弃让宝可梦携带邮件吗？"); // Unused
const u8 gText_CreateAQuiz2[] = _("创建一个谜题吧！"); // Unused
const u8 gText_SetTheAnswer[] = _("请设置答案！"); // Unused
const u8 gText_CancelSelection[] = _("是否取消选择？"); // Unused
const u8 gText_Profile[] = _("档案");
const u8 gText_AtTheBattlesStart[] = _("在对战开始时：");
const u8 gText_UponWinningABattle[] = _("在对战获胜时：");
const u8 gText_UponLosingABattle[] = _("在对战输掉时：");
const u8 gText_TheBardsSong[] = _("诗人之歌");
const u8 gText_WhatsHipAndHappening[] = _("现在什么最流行？");
const u8 gText_Interview[] = _("采访");
const u8 gText_GoodSaying[] = _("好的谚语");
const u8 gText_FansQuestion[] = _("粉丝的问题");
const u8 gJPText_WhatIsTheQuizAnswer[] = _("问答的答案是？"); // Unused
const u8 gText_ApprenticesPhrase[] = _("新手词组");
const u8 gText_Questionnaire[] = _("问卷");
const u8 gText_YouCannotQuitHere[] = _("现在无法退出。");
const u8 gText_SectionMustBeCompleted[] = _("必须完成这部分！");
const u8 gText_F700sQuiz[] = _("{DYNAMIC 0}的谜题");
const u8 gText_Lady[] = _("姐姐");
const u8 gText_AfterYouHaveReadTheQuiz[] = _("阅读谜题完毕后，");
const u8 gText_QuestionPressTheAButton[] = _("请按A键。");
const u8 gText_TheQuizAnswerIs[] = _("谜题答案的是？");
const u8 gText_LikeToQuitQuiz[] = _("要退出谜题");
const u8 gText_ChallengeQuestionMark[] = _("挑战吗？");
const u8 gText_IsThisQuizOK[] = _("谜题就这样可以吗？");
const u8 gText_CreateAQuiz[] = _("创建一个谜题吧！");
const u8 gText_SelectTheAnswer[] = _("请选择答案！");
const u8 gText_LyricsCantBeDeleted[] = _("无法删除这段词句！");
const u8 gText_PokemonLeague[] = _("宝可梦联盟");
const u8 gText_PokemonCenter[] = _("宝可梦中心");
const u8 gText_Coolness[] = _("帅气");
const u8 gText_Beauty3[] = _("美丽");
const u8 gText_Cuteness[] = _("可爱");
const u8 gText_Smartness[] = _("聪明");
const u8 gText_Toughness[] = _("强壮");
const u8 gText_SaveFailedCheckingBackup[] = _("记录失败。检查备份记录中……请稍\n等。{COLOR RED}“T所\l需时间：约1分钟”");
const u8 gText_BackupMemoryDamaged[] = _("备份记录已被损坏，或者内部电量已\n耗尽。您可以继续游戏，但是不能保\l存记录。");
const u8 gText_GamePlayCannotBeContinued[] = _("{COLOR RED}“游戏无法\n继续，正在返回标题画面……”");
const u8 gText_CheckCompleted[] = _("检查完毕，正在尝试再次写入记录，\n请稍候。");
const u8 gText_SaveCompleteGameCannotContinue[] = _("保存记录完毕。\n{COLOR RED}“游戏无法\l继续，正在返回标题画面……”");
const u8 gText_SaveCompletePressA[] = _("保存记录完毕。\n{COLOR RED}“请按下A\l键。”");
const u8 gText_Ferry[] = _("港口");
const u8 gText_SecretBase[] = _("秘密基地");
const u8 gText_Hideout[] = _("基地");
const u8 gText_ResetRTCConfirmCancel[] = _("重置实时时钟吗？A：确认， B：\n取消");
const u8 gText_PresentTime[] = _("当前游戏中的时间");
const u8 gText_PreviousTime[] = _("以前游戏中的时间");
const u8 gText_PleaseResetTime[] = _("请重置时间。");
const u8 gText_ClockHasBeenReset[] = _("时钟已经被重置了，即将保存记录，\n请稍候。");
const u8 gText_SaveCompleted[] = _("保存记录完毕。");
const u8 gText_SaveFailed[] = _("保存记录失败……");
const u8 gText_NoSaveFileCantSetTime[] = _("没有记录档案，因此不能设置时间。");
const u8 gText_InGameClockUsable[] = _("游戏时钟的调节系统现在可以使用了\n。");
const u8 gText_Spicy2[] = _("辣");
const u8 gText_Dry2[] = _("涩");
const u8 gText_Sweet2[] = _("甜");
const u8 gText_Bitter2[] = _("苦");
const u8 gText_Sour2[] = _("酸");
const u8 gText_Single[] = _("单打");
const u8 gText_Double[] = _("双打");
const u8 gText_Knockout[] = _("淘汰");
const u8 gText_Mixed[] = _("混合");
const u8 gText_First[] = _("一等");
const u8 gText_Second[] = _("二等");
const u8 gText_Third[] = _("third");
#if OW_POISON_DAMAGE < GEN_4
const u8 gText_PkmnFainted_FldPsn[] = _("{STR_VAR_1} fainted…\p\n");
#else
const u8 gText_PkmnFainted_FldPsn[] = _("{STR_VAR_1} survived the poisoning.\nThe poison faded away!\p");
#endif
const u8 gText_PkmnSurvived_FldPsn[] = _("{STR_VAR_1} survived the poisoning.\nThe poison faded away!\p");
const u8 gText_Marco[] = _("马可");
const u8 gText_TrainerCardName[] = _("名字：");
const u8 gText_TrainerCardIDNo[] = _("IDNo.");
const u8 gText_TrainerCardMoney[] = _("零花钱");
const u8 gText_PokeDollar[] = _("¥"); // Unused
const u8 gText_TrainerCardPokedex[] = _("宝可梦图鉴");
const u8 gText_EmptyString6[] = _("");
const u8 gText_Colon2[] = _(":");
const u8 gText_Points[] = _("点数"); // Unused
const u8 gText_TrainerCardTime[] = _("冒险时间");
const u8 gJPText_BattlePoints[] = _("游戏点数"); // Unused. Name presumed, translation is Game Points
const u8 gText_Var1sTrainerCard[] = _("{STR_VAR_1}的训练家卡");
const u8 gText_HallOfFameDebut[] = _("初次登入名人堂");
const u8 gText_LinkBattles[] = _("联机对战");
const u8 gText_LinkCableBattles[] = _("有线联机对战");
const u8 gText_WinsLosses[] = _("胜：{COLOR RED}\n{SHADOW LIGHT_RED}\l{STR_VAR_1}\l{COLOR DARK_GRAY}\l{SHADOW LIGHT_GRAY}\l 负：{COLOR RED}\l{SHADOW LIGHT_RED}\l{STR_VAR_2}\l{COLOR DARK_GRAY}\l{SHADOW LIGHT_GRAY}");
const u8 gText_PokemonTrades[] = _("宝可梦交换");
const u8 gText_UnionTradesAndBattles[] = _("联盟交谊厅交换/对战");
const u8 gText_BerryCrush[] = _("树果混合");
const u8 gText_WaitingTrainerFinishReading[] = _("正在等待对方训练家完成查看您的训\n练家卡。");
const u8 gText_PokeblocksWithFriends[] = _("与朋友制作{POKEBLOCK}");
const u8 gText_NumPokeblocks[] = _("{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}");
const u8 gText_WonContestsWFriends[] = _("赢得华丽大赛赢/个朋友");
const u8 gText_BattlePtsWon[] = _("赢得对战点数");
const u8 gText_NumBP[] = _("{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BP");
const u8 gText_BattleTower[] = _("对战塔");
const u8 gText_WinsStraight[] = _("胜/{COLOR RED}\n{SHADOW LIGHT_RED}\l{STR_VAR_1}\l{COLOR DARK_GRAY}\l{SHADOW LIGHT_GRAY}\l 连续/{COLOR RED}\l{SHADOW LIGHT_RED}\l{STR_VAR_2}");
const u8 gText_BattleTower2[] = _("对战塔");
const u8 gText_BattleDome[] = _("对战巨蛋");
const u8 gText_BattlePalace[] = _("对战宫殿");
const u8 gText_BattleFactory[] = _("对战工厂");
const u8 gText_BattleArena[] = _("对战竞技场");
const u8 gText_BattlePike[] = _("对战管道");
const u8 gText_BattlePyramid[] = _("对战金字塔");

ALIGNED(4) const u8 gText_FacilitySingle[] = _("{STR_VAR_1}单打");
ALIGNED(4) const u8 gText_FacilityDouble[] = _("{STR_VAR_1}双打");
ALIGNED(4) const u8 gText_FacilityMulti[] = _("{STR_VAR_1}多人");
ALIGNED(4) const u8 gText_FacilityLink[] = _("{STR_VAR_1}多人连线");
ALIGNED(4) const u8 gText_Facility[] = _("{STR_VAR_1}");

const u8 gText_Give[] = _("携带");
const u8 gText_NoNeed[] = _("不需要");
const u8 gText_AnnouncingResults[] = _("公布结果！");
const u8 gText_PreliminaryResults[] = _("第1轮成绩！");
const u8 gText_Round2Results[] = _("第2轮成绩！");
const u8 gText_ContestantsMonWon[] = _("{STR_VAR_1}的\n{STR_VAR_2}获胜了！");
const u8 gText_CommunicationStandby[] = _("正在等待连接……");
const u8 gText_ColorDarkGray[] = _("{COLOR DARK_GRAY}");
const u8 gText_ColorDynamic6WhiteDynamic5[] = _("{BACKGROUND WHITE}{TEXT_COLORS DYNAMIC_COLOR6 DYNAMIC_COLOR5 WHITE}"); // Unused
const u8 gText_HealthboxNickname[] = _("{BACKGROUND DARK_GRAY}{ACCENT DARK_GRAY}");
const u8 gText_EmptySpace2[] = _(" "); // Unused
const u8 gText_HealthboxGender_Male[] = _("{COLOR DYNAMIC_COLOR2}♂");
const u8 gText_HealthboxGender_Female[] = _("{COLOR DYNAMIC_COLOR1}♀");
const u8 gText_HealthboxGender_None[] = _("{COLOR DYNAMIC_COLOR2}");
const u8 gText_Upper[] = _("大写");
const u8 gText_Lower[] = _("小写");
const u8 gText_Others[] = _("其他");
const u8 gText_Symbols[] = _("符号");
const u8 gText_Register2[] = _("登记");
const u8 gText_Exit2[] = _("退出");
const u8 gText_QuitChatting[] = _("是否退出聊天？");
const u8 gText_RegisterTextWhere[] = _("在哪里登记文本？");
const u8 gText_RegisterTextHere[] = _("在这里登记文本？");
const u8 gText_InputText[] = _("输入正文。");
const u8 gText_F700JoinedChat[] = _("{DYNAMIC 0}参与聊天了\n！");
const u8 gText_F700LeftChat[] = _("{DYNAMIC 0}退出聊天了\n。");
const u8 gJPText_PlayersXPokemon[] = _("{DYNAMIC 0}的第\n{DYNAMIC 1}只："); // Unused
const u8 gJPText_PlayersXPokmonDoesNotExist[] = _("没有{DYNAMIC 0}的第\n{DYNAMIC 1}只"); // Unused
const u8 gText_ExitingChat[] = _("正在退出聊天……");
const u8 gText_LeaderLeftEndingChat[] = _("组长{DYNAMIC 0}已经离\n开，聊天结束。");
const u8 gText_RegisteredTextChangedOKToSave[] = _("登记的文本已经更改。要写入记录吗\n？");
const u8 gText_AlreadySavedFile_Chat[] = _("已经有其他的记录了，是否覆盖记录\n？");
const u8 gText_SavingDontTurnOff_Chat[] = _("正在写入记录……请勿切断电源。");
const u8 gText_PlayerSavedGame_Chat[] = _("{DYNAMIC 0}完好地写下\n了记录。");
const u8 gText_IfLeaderLeavesChatEnds[] = _("组长如果退出，聊天将会结束。确定\n要退出吗？");
const u8 gText_Hello[] = _("您好");
const u8 gText_Pokemon2[] = _("宝可梦");
const u8 gText_Trade[] = _("交换");
const u8 gText_Battle[] = _("对战");
const u8 gText_Lets[] = _("让我们");
const u8 gText_Ok[] = _("好！");
const u8 gText_Sorry[] = _("抱歉");
const u8 gText_YaySmileEmoji[] = _("哈！\n{EMOJI_BIGSMILE}");
const u8 gText_ThankYou[] = _("谢谢");
const u8 gText_ByeBye[] = _("拜拜！");
const u8 gText_HatchedFromEgg[] = _("蛋孵化成{STR_VAR_1}了\n！");
const u8 gText_NicknameHatchPrompt[] = _("要给{STR_VAR_1}起昵称\n吗？");
ALIGNED(4) const u8 gText_ReadyPickBerry[] = _("准备好开始树果粉碎了吗？请选择1\n个树果。\p");
ALIGNED(4) const u8 gText_WaitForAllChooseBerry[] = _("请等待所有成员选择树果。");
ALIGNED(4) const u8 gText_EndedWithXUnitsPowder[] = _("{PAUSE_MUSIC}\n{PLAY_BGM MUS_LEVEL_UP}\l您最终获得顺滑度为\l{STR_VAR_1}的树果粉末\l。{RESUME_MUSIC}\p您树果粉末的总数是\n{STR_VAR_2}。\p");
ALIGNED(4) const u8 gText_RecordingGameResults[] = _("正在将您的成绩写入记录，请稍候。");
ALIGNED(4) const u8 gText_PlayBerryCrushAgain[] = _("要再玩一次树果粉碎吗？");
ALIGNED(4) const u8 gText_YouHaveNoBerries[] = _("您没有树果。即将退出游戏。");
ALIGNED(4) const u8 gText_MemberDroppedOut[] = _("有一位成员退出，即将退出游戏。");
ALIGNED(4) const u8 gText_TimesUpNoGoodPowder[] = _("时间到。\p没能制作出好的树果粉末……\p");
ALIGNED(4) const u8 gText_CommunicationStandby2[] = _("正在等待连接……");
ALIGNED(4) const u8 gText_1DotBlueF700[] = _("1. {COLOR BLUE}{SHADOW LIGHT_BLUE}{DYNAMIC 0}");
ALIGNED(4) const u8 gText_1DotF700[] = _("1. {DYNAMIC 0}");
ALIGNED(4) const u8 gText_SpaceTimes2[] = _("次");
ALIGNED(4) const u8 gText_XDotY[] = _("{STR_VAR_1}.{STR_VAR_2}");
ALIGNED(4) const u8 gText_Var1Berry[] = _("{STR_VAR_1}个树果");
ALIGNED(4) const u8 gText_TimeColon[] = _("时间：");
ALIGNED(4) const u8 gText_PressingSpeed[] = _("按键速度：");
ALIGNED(4) const u8 gText_Silkiness[] = _("顺滑度：");
ALIGNED(4) const u8 gText_StrVar1[] = _("{STR_VAR_1}");
ALIGNED(4) const u8 gText_SpaceMin[] = _("分");
ALIGNED(4) const u8 gText_XDotY2[] = _("{STR_VAR_1}.{STR_VAR_2}");
ALIGNED(4) const u8 gText_SpaceSec[] = _("秒");
ALIGNED(4) const u8 gText_XDotY3[] = _("{STR_VAR_1}.{STR_VAR_2}");
ALIGNED(4) const u8 gText_TimesPerSec[] = _("次/秒");
ALIGNED(4) const u8 gText_Var1Percent[] = _("{STR_VAR_1}%");
ALIGNED(4) const u8 gText_PressesRankings[] = _("按键速度排名");
ALIGNED(4) const u8 gText_CrushingResults[] = _("粉碎成绩");
ALIGNED(4) const u8 gText_NeatnessRankings[] = _("顺滑度排名");
ALIGNED(4) const u8 gText_CoopRankings[] = _("协力合作排名");
ALIGNED(4) const u8 gText_PressingPowerRankings[] = _("按压力度排名");
const u8 gText_BerryCrush2[] = _("树果粉碎");
const u8 gText_PressingSpeedRankings[] = _("按压速度排名");
const u8 gText_Var1Players[] = _("{STR_VAR_1}个玩家");
const u8 gText_SymbolsEarned[] = _("已获得的象征");
const u8 gText_BattleRecord[] = _("对战记录");
const u8 gText_BattlePoints[] = _("对战点数");
const u8 gText_UnusedCancel[] = _("取消"); // Unused
const u8 gText_EmptyString7[] = _("");
const u8 gText_CheckFrontierMap[] = _("查看对战开拓区地图。");
const u8 gText_CheckTrainerCard[] = _("查看训练家卡。");
const u8 gText_ViewRecordedBattle[] = _("回放记录的对战。");
const u8 gText_PutAwayFrontierPass[] = _("放好开拓通行证。");
const u8 gText_CurrentBattlePoints[] = _("当前的对战点数。");
const u8 gText_CollectedSymbols[] = _("已收集的象征。");
const u8 gText_BattleTowerAbilitySymbol[] = _("对战塔——能力象征");
const u8 gText_BattleDomeTacticsSymbol[] = _("对战巨蛋——战术象征");
const u8 gText_BattlePalaceSpiritsSymbol[] = _("对战宫殿——精神象征");
const u8 gText_BattleArenaGutsSymbol[] = _("对战竞技场——毅力象征");
const u8 gText_BattleFactoryKnowledgeSymbol[] = _("对战工厂——知识象征");
const u8 gText_BattlePikeLuckSymbol[] = _("对战管道——运气象征");
const u8 gText_BattlePyramidBraveSymbol[] = _("对战金字塔——英勇象征");
const u8 gText_ThereIsNoBattleRecord[] = _("没有对战记录。");
const u8 gText_BattleTower3[] = _("对战塔");
const u8 gText_BattleDome2[] = _("对战巨蛋");
const u8 gText_BattlePalace2[] = _("对战宫殿");
const u8 gText_BattleArena2[] = _("对战竞技场");
const u8 gText_BattleFactory2[] = _("对战工厂");
const u8 gText_BattlePike2[] = _("对战管道");
const u8 gText_BattlePyramid2[] = _("对战金字塔");
const u8 gText_BattleTowerDesc[] = _("击败对手，勇攀巅峰！这里将会考验\n您的能力。");
const u8 gText_BattleDomeDesc[] = _("在锦标赛中连胜到底！这里将会考验\n您的战术。");
const u8 gText_BattlePalaceDesc[] = _("见证宝可梦自主战斗！这里将会考验\n您的精神。");
const u8 gText_BattleArenaDesc[] = _("用组队宝可梦赢得胜利！这里将会考\n验您的毅力。");
const u8 gText_BattleFactoryDesc[] = _("使用租借宝可梦夺取胜利！这里将会\n考验您的知识。");
const u8 gText_BattlePikeDesc[] = _("选择3条道路中的1条战斗！这里将\n会考验您的运气。");
const u8 gText_BattlePyramidDesc[] = _("通过探索攀登顶峰！这里将会考验您\n的英勇。");
const u8 gText_Powder[] = _("粉末");
const u8 gText_BerryPickingRecords[] = _("嘟嘟利摘树果纪录");
const u8 gText_BerriesPicked[] = _("摘得树果：");
const u8 gText_BestScore[] = _("最高得分：");
const u8 gText_BerriesInRowFivePlayers[] = _("树果被5位玩家挑选放到一起：");
const u8 gText_BerryPickingResults[] = _("公布摘树果成绩！");
const u8 gText_10P30P50P50P[] = _("{CLEAR_TO 0x03}10P{CLEAR_TO 0x2B}30P{CLEAR_TO 0x53}50P{CLEAR_TO 0x77}{EMOJI_MINUS}50P");
const u8 gText_AnnouncingRankings[] = _("宣布名次！");
const u8 gText_AnnouncingPrizes[] = _("宣布奖品！");
const u8 gText_1Colon[] = _("1:");
const u8 gText_2Colon[] = _("2:");
const u8 gText_3Colon[] = _("3:");
const u8 gText_4Colon[] = _("4:");
const u8 gText_5Colon[] = _("5:");
const u8 gText_FirstPlacePrize[] = _("第1名将获得这个\n{DYNAMIC 0}！");
const u8 gText_CantHoldAnyMore[] = _("你不能携带更多了！");
const u8 gText_FilledStorageSpace[] = _("存储空间已经满了。");
const u8 gText_WantToPlayAgain[] = _("再玩一次吗？");
const u8 gText_SomeoneDroppedOut[] = _("有人退出了，连接会断开。");
const u8 gText_SpacePoints[] = _("点数");
const u8 gText_CommunicationStandby3[] = _("正在等待连接……");
const u8 gText_SpacePoints2[] = _("点数");
const u8 gText_SpaceTimes3[] = _("次");
const u8 gText_PkmnJumpRecords[] = _("宝可梦跳绳纪录");
const u8 gText_JumpsInARow[] = _("连续跳跃：");
const u8 gText_BestScore2[] = _("最高分：");
const u8 gText_ExcellentsInARow[] = _("连续优秀：");
const u8 gText_AwesomeWonF701F700[] = _("了不起的得分！你赢得了\n{DYNAMIC 1} \l{DYNAMIC 0}！");
const u8 gText_FilledStorageSpace2[] = _("存储空间已经满了。");
const u8 gText_CantHoldMore[] = _("你不能携带更多了！");
const u8 gText_WantToPlayAgain2[] = _("再玩一次吗？");
const u8 gText_SomeoneDroppedOut2[] = _("有人退出了，连接会断开。");
const u8 gText_CommunicationStandby4[] = _("正在等待连接……");
const u8 gText_LinkContestResults[] = _("{PLAYER}的连接华丽大赛成\n绩");
const u8 gText_1st[] = _("第1");
const u8 gText_2nd[] = _("第2");
const u8 gText_3rd[] = _("第3");
const u8 gText_4th[] = _("第4");
const u8 gText_Friend[] = _("好友");
const u8 gText_Pokemon3[] = _("宝可梦"); // Unused
const u8 gJPText_MysteryGift[] = _("神秘礼物");
const u8 gJPText_DecideStop[] = _("{A_BUTTON}确定 \n{B_BUTTON}取消");
const u8 gJPText_ReceiveMysteryGiftWithEReader[] = _("使用Card-e Reader\n{PLUS}读取神秘礼物。");
const u8 gJPText_SelectConnectFromEReaderMenu[] = _("カードeリーダー{PLUS}の　メニューから\n‘つうしん'を　えらび");
const u8 gJPText_SelectConnectWithGBA[] = _("‘ゲームボーイアドバンスとつうしん'\nを　せんたく　してください");
const u8 gJPText_SelectConnectAndPressA[] = _("カードeリーダー{PLUS}の　‘つうしん'を\nえらんで　Aボタンを　おしてください"); // Unused
const u8 gJPText_LinkIsIncorrect[] = _("连接错误。");
const u8 gJPText_CardReadingHasBeenHalted[] = _("已中止卡片的读取。");
const u8 gJPText_UnableConnectWithEReader[] = _("无法与Card-e Reader\n{PLUS}通信。"); // Unused
const u8 gJPText_Connecting[] = _("正在通信中。");
const u8 gJPText_ConnectionErrorCheckLink[] = _("通信错误。请检查连接状态。");
const u8 gJPText_ConnectionErrorTryAgain[] = _("つうしん　エラーです\nはじめから　やりなおして　ください"); // Link error
const u8 gJPText_AllowEReaderToLoadCard[] = _("カードeリーダー{PLUS}　に\nカードを　よみこませて　ください");
const u8 gJPText_ConnectionComplete[] = _("通信结束！");
const u8 gJPText_NewTrainerHasComeToHoenn[] = _("あらたな　トレーナーが\nホウエンに　やってきた！");
const u8 gJPText_PleaseWaitAMoment[] = _("请稍候。");
const u8 gJPText_WriteErrorUnableToSaveData[] = _("かきこみ　エラー　です\nデータが　ほぞん　できませんでした");
const u8 gText_SingleBattleRoomResults[] = _("{PLAYER}的单打对战间成绩");
const u8 gText_DoubleBattleRoomResults[] = _("{PLAYER}的双打对战间成绩");
const u8 gText_MultiBattleRoomResults[] = _("{PLAYER}的多人对战间成绩");
const u8 gText_LinkMultiBattleRoomResults[] = _("{PLAYER}的多人连线对战间\n成绩");
const u8 gText_SingleBattleTourneyResults[] = _("{PLAYER}的单打对战锦标赛\n成绩");
const u8 gText_DoubleBattleTourneyResults[] = _("{PLAYER}的双打对战锦标赛\n成绩");
const u8 gText_SingleBattleHallResults[] = _("{PLAYER}的单打对战厅成绩");
const u8 gText_DoubleBattleHallResults[] = _("{PLAYER}的双打对战厅成绩");
const u8 gText_BattleChoiceResults[] = _("{PLAYER}的选择式对战成绩");
const u8 gText_SetKOTourneyResults[] = _("{PLAYER}的三回合定胜负锦\n标赛成绩");
const u8 gText_BattleSwapSingleResults[] = _("{PLAYER}的交换式对战单打\n成绩");
const u8 gText_BattleSwapDoubleResults[] = _("{PLAYER}的交换式对战双打\n成绩");
const u8 gText_BattleQuestResults[] = _("{PLAYER}的探索式对战成绩");
const u8 gText_Lv502[] = _("Lv. 50级");
const u8 gText_OpenLv[] = _("自由等级");
const u8 gText_WinStreak[] = _("连胜：{STR_VAR_1}");
const u8 gText_Current[] = _("当前");
const u8 gText_Record[] = _("最高");
const u8 gText_Prev[] = _("上次");
const u8 gText_RentalSwap[] = _("租用/交换");
const u8 gText_Total[] = _("累计");
const u8 gText_ClearStreak[] = _("连胜场次：{STR_VAR_1}");
const u8 gText_Championships[] = _("获得冠军：{STR_VAR_1}");
const u8 gText_RoomsCleared[] = _("通过房间：{STR_VAR_1}");
const u8 gText_TimesCleared[] = _("通关次数：\n{CLEAR 0x05}\l{STR_VAR_1}");
const u8 gText_KOsInARow[] = _("连续击倒：{STR_VAR_1}");
const u8 gText_TimesVar1[] = _("次数：{STR_VAR_1}");
const u8 gText_FloorsCleared[] = _("通过层数：{STR_VAR_1}");

ALIGNED(4) const u8 gText_RecordsLv50[] = _("Lv. 50级");
ALIGNED(4) const u8 gText_RecordsOpenLevel[] = _("自由等级");
ALIGNED(4) const u8 gText_FrontierFacilityWinStreak[] = _("连胜：{STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityClearStreak[] = _("连续过关：{STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityRoomsCleared[] = _("通过房间：{STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityKOsStreak[] = _("连续击败：{STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityFloorsCleared[] = _("通过楼层：{STR_VAR_2}");
ALIGNED(4) const u8 gText_123Dot[][3] = {_("1."), _("2."), _("3.")};
const u8 gText_FrontierFacilityTotalCaughtSpeciesBanned[] = _("和{STR_VAR_2}种您捕捉\n的宝可梦无法参加");
const u8 gText_FrontierFacilityIncluding[] = _("！\p其中包括");
const u8 gText_FrontierFacilityAreInelegible[] = _("无法参加");

const u8 gText_YesNo[] = _("是否");
const u8 gText_SelectorArrow3[] = _("▶");
const u8 gText_Peekaboo[] = _("躲猫猫！");
const u8 gText_CommErrorCheckConnections[] = _("发生连接错误……请检查所有的连接\n，然后关机重启。");
const u8 gText_CommErrorEllipsis[] = _("发生连接错误……");
const u8 gText_MoveCloserToLinkPartner[] = _("请靠近你的联机朋友，避免朋友之间\n的障碍物。");
const u8 gText_ABtnRegistrationCounter[] = _("A键：登记柜台");
const u8 gText_ABtnTitleScreen[] = _("A键：标题画面");
const u8 gText_NumPlayerLink[] = _("{STR_VAR_1}P连接");
const u8 gText_BronzeCard[] = _("青铜");
const u8 gText_CopperCard[] = _("紫铜");
const u8 gText_SilverCard[] = _("白银");
const u8 gText_GoldCard[] = _("黄金");
const u8 gText_Day[] = _("天");
const u8 gText_Colon3[] = _(":");
const u8 gText_Confirm2[] = _("确定");
const u8 gText_Days[] = _("天"); // Unused
const u8 gText_TimeColon2[] = _("时间："); // Unused
const u8 gText_GameTime[] = _("游戏时间"); // Unused
const u8 gText_RTCTime[] = _("时钟时间"); // Unused
const u8 gText_UpdatedTime[] = _("更新时间"); // Unused
const u8 gText_MenuPokedex[] = _("图鉴");
const u8 gText_MenuPokemon[] = _("宝可梦");
const u8 gText_MenuBag[] = _("BAG");
#if IS_HNS
const u8 gText_MenuPokenav[] = _("{POKE}GEAR");
#else
const u8 gText_MenuPokenav[] = _("POKéNAV");
#endif
const u8 gText_MenuPlayer[] = _("{PLAYER}");
const u8 gText_MenuSave[] = _("记录");
const u8 gText_MenuOption[] = _("设置");
const u8 gText_MenuExit[] = _("退出");
const u8 gText_MenuRetire[] = _("撤退");
const u8 gText_MenuRest[] = _("重置");
const u8 gText_MenuDexNav[] = _("图鉴导航");
const u8 gText_SafariBallStock[] = _("狩猎球还有：\n{STR_VAR_1}");
const u8 gText_MenuSafariStats[] = _("{STR_VAR_1}/\n{STR_VAR_2}精灵球  \l{STR_VAR_3}");
const u8 gText_BattlePyramidFloor[] = _("对战金字塔{STR_VAR_1}");
const u8 gText_Floor1[] = _("1楼");
const u8 gText_Floor2[] = _("2楼");
const u8 gText_Floor3[] = _("3楼");
const u8 gText_Floor4[] = _("4楼");
const u8 gText_Floor5[] = _("5楼");
const u8 gText_Floor6[] = _("6楼");
const u8 gText_Floor7[] = _("7楼");
const u8 gText_Peak[] = _("天台");
const u8 gText_LinkStandby2[] = _("连接待机………… B键：取消");
const u8 gText_PressAToLoadEvent[] = _("请按A键加载事件。…… B键：取\n消");
const u8 gText_LoadingEvent[] = _("加载事件中……");
const u8 gText_DontRemoveCableTurnOff[] = _("请不要拔除GBA连接线。请不要关\n闭电源。");
const u8 gText_EventSafelyLoaded[] = _("事件已成功加载。");
const u8 gText_LoadErrorEndingSession[] = _("加载错误。结束进程。");
const u8 gJPText_Player[] = _("玩家"); // Unused
const u8 gJPText_Sama[] = _("大人"); // Unused
const u8 gText_DexHoenn[] = _("丰缘");
const u8 gText_DexNational[] = _("全国");
const u8 gText_PokedexDiploma[] = _("PLAYER: {CLEAR 0x10}{COLOR RED}{SHADOW LIGHT_RED}{PLAYER}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}\n\nThis document certifies\nthat you have successfully\ncompleted your\n{STR_VAR_1} POKéDEX.\n\n{CLEAR_TO 0x42}{COLOR RED}{SHADOW LIGHT_RED}GAME FREAK");
const u8 gJPText_GameFreak[] = _("{COLOR RED}{SHADOW LIGHT_RED}GAME FREAK"); // Unused
const u8 gText_DiplomaEmpty[] = _("{COLOR RED}{SHADOW LIGHT_RED}"); // Unused
const u8 gText_Hoenn[] = _("丰缘");
const u8 gText_Kanto[] = _("关都");
const u8 gText_Johto[] = _("城都");
const u8 gText_JohtoKanto[] = _("城都&关都");
const u8 gText_XWillBeSentToY[] = _("{STR_VAR_2}将会被送到\n{STR_VAR_1}。");
const u8 gText_ByeByeVar1[] = _("再见，{STR_VAR_2}！");
const u8 gText_XSentOverY[] = _("{STR_VAR_1}送到了\n{STR_VAR_3}。");
const u8 gText_TakeGoodCareOfX[] = _("好好照顾{STR_VAR_3}！");

const u8 gText_ThreeQuestionMarks[] = _("???");
const u8 gText_FourQuestionMarks[] = _("????");
const u8 gText_MaxHP[] = _("最大HP");
const u8 gText_Attack[] = _("攻击");
const u8 gText_Defense[] = _("防御");
const u8 gText_Speed[] = _("速度");
const u8 gText_SpAtk[] = _("特攻");
const u8 gText_SpDef[] = _("特防");
const u8 gText_Plus[] = _("{PLUS}");
const u8 gText_Dash[] = _("-");
const u8 gText_MixingRecords[] = _("混合记录中……");
const u8 gText_RecordMixingComplete[] = _("记录混合完成。感谢您的等待。");
const u8 gText_RentalPkmn2[] = _("租借宝可梦");
const u8 gText_SelectFirstPkmn[] = _("选择第1只宝可梦。");
const u8 gText_SelectSecondPkmn[] = _("选择第2只宝可梦。");
const u8 gText_SelectThirdPkmn[] = _("选择第3只宝可梦。");
const u8 gText_Rent[] = _("租借");
const u8 gText_Summary[] = _("查看能力");
const u8 gText_Others2[] = _("选择其它");
const u8 gText_Deselect[] = _("取消选择");
const u8 gText_TheseThreePkmnOkay[] = _("这3只宝可梦可以吗？");
const u8 gText_Yes2[] = _("是");
const u8 gText_No2[] = _("否");
const u8 gText_CantSelectSamePkmn[] = _("无法选择相同的{PKMN}。");
const u8 gText_PkmnSwap[] = _("宝可梦交换");
const u8 gText_SelectPkmnToSwap[] = _("选择要交换的宝可梦。");
const u8 gText_SelectPkmnToAccept[] = _("选择要接收的宝可梦。");
const u8 gText_Swap[] = _("交换");
const u8 gText_Summary2[] = _("查看能力");
const u8 gText_Rechoose[] = _("重新选择");
const u8 gText_QuitSwapping[] = _("退出交换？");
const u8 gText_Yes3[] = _("是");
const u8 gText_No3[] = _("否");
const u8 gText_PkmnForSwap[] = _("交换用{PKMN}");
const u8 gText_Cancel3[] = _("取消选择");
const u8 gText_Swap2[] = _("交换"); // Unused
const u8 gText_Accept[] = _("接收"); // Unused
const u8 gText_AcceptThisPkmn[] = _("接收这只宝可梦？");
const u8 gText_4Spaces[] = _("    "); // Unused
const u8 gText_SamePkmnInPartyAlready[] = _("同行队伍中已有相同的{PKMN}\n。");
const u8 gText_DecimalPoint[] = _(".");
const u8 gText_SavingPlayer[] = _("主人公");
const u8 gText_SavingBadges[] = _("徽章");
const u8 gText_SavingPokedex[] = _("图鉴");
const u8 gText_SavingTime[] = _("冒险时间");
const u8 gText_WirelessCommStatus[] = _("无线连接状态");
const u8 gText_PeopleTrading[] = _("在进行交换的人：");
const u8 gText_PeopleBattling[] = _("在进行对战的人：");
const u8 gText_PeopleInUnionRoom[] = _("联盟交谊厅中的人：");
const u8 gText_PeopleCommunicating[] = _("在进行聊天的人：");
const u8 gText_F700Players[] = _("{DYNAMIC 0}名玩家");
const u8 gText_F701Players[] = _("{DYNAMIC 1}名玩家");
const u8 gText_F702Players[] = _("{DYNAMIC 2}名玩家");
const u8 gText_F703Players[] = _("{DYNAMIC 3}名玩家");

const u8 *const gTextTable_Players[] = {
    gText_F700Players,
    gText_F701Players,
    gText_F702Players,
    gText_F703Players
};

ALIGNED(4) const u8 gText_WonderCards[] = _("神秘卡片");
ALIGNED(4) const u8 gText_WonderNews[] = _("神秘新闻");
ALIGNED(4) const u8 gText_WirelessCommunication[] = _("无线连接");
ALIGNED(4) const u8 gText_Friend2[] = _("好友");
ALIGNED(4) const u8 gText_Exit3[] = _("退出");
ALIGNED(4) const u8 gText_Receive[] = _("接收");
ALIGNED(4) const u8 gText_Send[] = _("发送");
ALIGNED(4) const u8 gText_Toss[] = _("投掷");
ALIGNED(4) const u8 gText_VarietyOfEventsImportedWireless[] = _("各种各样的事件将会通过无线连接中\n载入。");
ALIGNED(4) const u8 gText_WonderCardsInPossession[] = _("阅读您拥有的神秘卡片。");
ALIGNED(4) const u8 gText_ReadNewsThatArrived[] = _("阅读最新的新闻。");
ALIGNED(4) const u8 gText_ReturnToTitle[] = _("返回标题画面。");
ALIGNED(4) const u8 gText_DontHaveCardNewOneInput[] = _("您现在没有神秘卡片，所以您将会收\n到一张新的卡片。");
ALIGNED(4) const u8 gText_DontHaveNewsNewOneInput[] = _("您没有任何神秘新闻，所以您将会收\n到新的新闻。");
ALIGNED(4) const u8 gText_WhereShouldCardBeAccessed[] = _("您希望从哪里获取神秘卡片？");
ALIGNED(4) const u8 gText_WhereShouldNewsBeAccessed[] = _("您希望在哪里察看神秘新闻？");
ALIGNED(4) const u8 gText_CommunicationStandbyBButtonCancel[] = _("正在等待连接……B键：取消"); // Unused
ALIGNED(4) const u8 gText_Communicating[] = _("连接中……");
ALIGNED(4) const u8 gText_CommunicationCompleted[] = _("连接完成。");
ALIGNED(4) const u8 gText_CommunicationError[] = _("连接错误。");
ALIGNED(4) const u8 gText_CommunicationCanceled[] = _("连接已被取消。");
ALIGNED(4) const u8 gText_ThrowAwayWonderCard[] = _("扔掉神秘卡片并重新领取新的？");
ALIGNED(4) const u8 gText_HaventReceivedCardsGift[] = _("您还未收到卡片的赠礼确认继续？");
ALIGNED(4) const u8 gText_WonderCardReceivedFrom[] = _("从{STR_VAR_1}处收到了\n一张神秘卡片。");
ALIGNED(4) const u8 gText_WonderNewsReceivedFrom[] = _("从{STR_VAR_1}处收到了\n一条神秘新闻。");
ALIGNED(4) const u8 gText_WonderCardReceived[] = _("已收到了新的神秘卡片");
ALIGNED(4) const u8 gText_WonderNewsReceived[] = _("已收到了新的神秘新闻");
ALIGNED(4) const u8 gText_NewStampReceived[] = _("已收到了新的印章。");
ALIGNED(4) const u8 gText_NewTrainerReceived[] = _("新的训练家已经到达。");
ALIGNED(4) const u8 gText_AlreadyHadCard[] = _("您已经拥有那张神秘卡片。");
ALIGNED(4) const u8 gText_AlreadyHadNews[] = _("您已经拥有那条神秘新闻。");
ALIGNED(4) const u8 gText_AlreadyHadStamp[] = _("您已经拥有那个印章。");
ALIGNED(4) const u8 gText_NoMoreRoomForStamps[] = _("没有增加印章的空间了。");
ALIGNED(4) const u8 gText_RecordUploadedViaWireless[] = _("您的记录已用无线连接更新。");
ALIGNED(4) const u8 gText_CantAcceptCardFromTrainer[] = _("您不能从这个训练家处接收神秘卡片\n。");
ALIGNED(4) const u8 gText_CantAcceptNewsFromTrainer[] = _("您不能从这个训练家处接收神秘新闻\n。");
ALIGNED(4) const u8 gText_NothingSentOver[] = _("什么也没发生……");
ALIGNED(4) const u8 gText_WhatToDoWithCards[] = _("您想用神秘卡片做什么？");
ALIGNED(4) const u8 gText_WhatToDoWithNews[] = _("您想用神秘新闻做什么？");
ALIGNED(4) const u8 gText_SendingWonderCard[] = _("正在发送您的神秘卡片……");
ALIGNED(4) const u8 gText_SendingWonderNews[] = _("正在发送您的神秘新闻……");
ALIGNED(4) const u8 gText_WonderCardSentTo[] = _("您的神秘卡片已发送给\n{STR_VAR_1}。");
ALIGNED(4) const u8 gText_WonderNewsSentTo[] = _("您的神秘新闻已发送给\n{STR_VAR_1}。");
ALIGNED(4) const u8 gText_StampSentTo[] = _("一个印章已发送给\n{STR_VAR_1}。");
ALIGNED(4) const u8 gText_GiftSentTo[] = _("一份礼物也发送给\n{STR_VAR_1}。");
ALIGNED(4) const u8 gText_OtherTrainerHasCard[] = _("对方训练家已有同样的神秘卡片。");
ALIGNED(4) const u8 gText_OtherTrainerHasNews[] = _("对方训练家已有同样的神秘新闻。");
ALIGNED(4) const u8 gText_OtherTrainerHasStamp[] = _("对方训练家已有同样的印章。");
ALIGNED(4) const u8 gText_OtherTrainerCanceled[] = _("对方训练家取消了连接。");
ALIGNED(4) const u8 gText_CantSendGiftToTrainer[] = _("您不能将神秘礼物送给这个训练家。");
ALIGNED(4) const u8 gText_IfThrowAwayCardEventWontHappen[] = _("如果扔掉卡片，其中的事件将不会发\n生。可以吗？");
ALIGNED(4) const u8 gText_OkayToDiscardNews[] = _("删除这条新闻可以吗？");
ALIGNED(4) const u8 gText_HaventReceivedGiftOkayToDiscard[] = _("您还未收到礼物，真的确定删除吗？");
ALIGNED(4) const u8 gText_DataWillBeSaved[] = _("资料正在写入记录中……请稍候。");
ALIGNED(4) const u8 gText_SaveCompletedPressA[] = _("保存记录完毕。请按A键。");
ALIGNED(4) const u8 gText_WonderCardThrownAway[] = _("扔掉了神秘卡片。");
ALIGNED(4) const u8 gText_WonderNewsThrownAway[] = _("删除了神秘新闻。");
ALIGNED(4) const u8 gText_MysteryGift[] = _("神秘礼物");
ALIGNED(4) const u8 gText_PickOKExit[] = _("{DPAD_UPDOWN}选择 \n{A_BUTTON}确认 \l{B_BUTTON}退出");
ALIGNED(4) const u8 gText_PickOKCancel[] = _("{DPAD_UPDOWN}选择 \n{A_BUTTON}确认 \l{B_BUTTON}取消");
const u8 gText_PlayersBattleResults[] = _("{PLAYER}的对战成绩");
const u8 gText_TotalRecordWLD[] = _("总战绩 胜：\n{STR_VAR_1} 负：\l{STR_VAR_2} 平：\l{STR_VAR_3}");
const u8 gText_WinLoseDraw[] = _("{CLEAR_TO 0x53}胜\n{CLEAR_TO 0x80}负\l{CLEAR_TO 0xB0}平");
const u8 gText_CommunicationStandby5[] = _("正在等待连接……");
const u8 gDaycareText_GetAlongVeryWell[] = _("这2只的关系好像挺好的！");
const u8 gDaycareText_GetAlong[] = _("这2只的关系感觉还不错啊。");
const u8 gDaycareText_DontLikeOther[] = _("这2只的关系似乎不太好啊。");
const u8 gDaycareText_PlayOther[] = _("这2只各自跑去和其他宝可梦玩了…\n…");
const u8 gText_NewLine2[] = _("\n");
const u8 gText_Exit4[] = _("退出");
const u8 gText_Lv[] = _("{LV}");
const u8 gText_TimeBoard[] = _("时间板");
const u8 gText_TimeCleared[] = _("完成时间");
const u8 gText_XMinYDotZSec[] = _("{STR_VAR_1} 分\n{STR_VAR_2}.\l{STR_VAR_3} 秒。");
const u8 gText_TrainerHill1F[] = _("1楼");
const u8 gText_TrainerHill2F[] = _("2楼");
const u8 gText_TrainerHill3F[] = _("3楼");
const u8 gText_TrainerHill4F[] = _("4楼");
const u8 gText_TeachWhichMoveToPkmn[] = _("要让{STR_VAR_1}学习哪\n个{STR_VAR_3}呢？");
const u8 gText_MoveRelearnerTeachMoveConfirm[] = _("要学习{STR_VAR_2}吗？");
const u8 gText_MoveRelearnerPkmnLearnedMove[] = _("{STR_VAR_1}学会了\n{STR_VAR_2}！");
const u8 gText_MoveRelearnerPkmnTryingToLearnMove[] = _("{STR_VAR_1}想要学会\n{STR_VAR_2}。\p但是{STR_VAR_1}已经学\n会了4个招式，不能再学了。\p要遗忘原有的招式，学会\n{STR_VAR_2}吗？");
const u8 gText_MoveRelearnerStopTryingToTeachMove[] = _("放弃学习{STR_VAR_2}吗\n？");
const u8 gText_MoveRelearnerAndPoof[] = _("{PAUSE 32}1， \n{PAUSE 15}2， \l{PAUSE 15}……\l{PAUSE 15}……\l{PAUSE 15}……\l{PAUSE 15}\l{PLAY_SE SE_BALL_BOUNCE_1}\l空！\p");
const u8 gText_MoveRelearnerPkmnForgotMoveAndLearnedNew[] = _("{STR_VAR_1}遗忘了\n{STR_VAR_3}。\p然后......\p{STR_VAR_1}学会了\n{STR_VAR_2}。");
const u8 gText_MoveRelearnedPkmnDidNotLearnMove[] = _("{STR_VAR_1}没有学习\n{STR_VAR_2}。"); // Unused
const u8 gText_MoveRelearnerGiveUp[] = _("要放弃让{STR_VAR_1}学\n习新招式吗？");
const u8 gText_MoveRelearnerWhichMoveToForget[] = _("要忘记哪个招式呢？\p");
const u8 gText_MoveRelearnerBattleMoves[] = _("战斗招式");
const u8 gText_MoveRelearnerContestMovesTitle[] = _("华丽大赛招式");
const u8 gText_MoveRelearnerType[] = _("属性/"); // Unused
const u8 gText_MoveRelearnerPP[] = _("PP/");
const u8 gText_MoveRelearnerPower[] = _("威力/");
const u8 gText_MoveRelearnerAccuracy[] = _("命中/");
const u8 gText_MoveRelearnerAppeal[] = _("吸引力");
const u8 gText_MoveRelearnerJam[] = _("干扰力");
const u8 gText_ClearAllSaveData[] = _("要清除卡带所有保存记录区域的数据\n吗？");
const u8 gText_ClearingData[] = _("正在清除记录……请稍等。");
const u8 gText_IsThisTheCorrectTime[] = _("这是正确的时间吗？");
const u8 gText_Confirm3[] = _("确定");
const u8 gText_Cancel4[] = _("取消");
const u8 gText_CommStandbyAwaitingOtherPlayer[] = _("正在等待连接……等待其他玩家选择\n。");
const u8 gText_BattleWasRefused[] = _("对战要求被拒绝。\n{PAUSE 60}！");
const u8 gText_RefusedBattle[] = _("拒绝对战。{PAUSE 60}！");
const u8 gText_NoWeather[] = _("天气正常"); // Below are unused debug names for weather types
const u8 gText_Sunny[] = _("晴天"); // Unused
const u8 gText_Sunny2[] = _("晴天2"); // Unused
const u8 gText_Rain[] = _("下雨"); // Unused
const u8 gText_Snow[] = _("下雪"); // Unused
const u8 gText_Lightning[] = _("闪电"); // Unused
const u8 gText_Fog[] = _("雾"); // Unused
const u8 gText_VolcanoAsh[] = _("火山灰"); // Unused
const u8 gText_Sandstorm[] = _("沙尘暴"); // Unused
const u8 gText_Fog2[] = _("雾2"); // Unused
const u8 gText_Seafloor[] = _("海底"); // Unused
const u8 gText_Cloudy[] = _("多云"); // Unused
const u8 gText_Sunny3[] = _("晴天3"); // Unused
const u8 gText_HeavyRain[] = _("大雨"); // Unused
const u8 gText_Seafloor2[] = _("海底2"); // Unused
const u8 gText_DelAll[] = _("全部清除");
const u8 gText_Cancel5[] = _("取消");
const u8 gText_Ok2[] = _("好了");
const u8 gText_Quiz[] = _("测验");
const u8 gText_Answer[] = _("回答");
const u8 gText_PokeBalls[] = _("精灵球");
const u8 gText_Berry[] = _("树果");
const u8 gText_Berries[] = _("树果");
const u8 gText_Obtained999RareCandies[] = _("获得了999个神奇糖果！\n{PAUSE_UNTIL_PRESS}");
const u8 gText_ExpShareOn[] = _("打开了学习装置。\n{PAUSE_UNTIL_PRESS}");
const u8 gText_ExpShareOff[] = _("关闭了学习装置。\n{PAUSE_UNTIL_PRESS}");
ALIGNED(4) const u8 gText_Ghost[] = _("幽灵");
const u8 gText_Boulderbadge[] = _("深灰徽章");
const u8 gText_Cascadebadge[] = _("华蓝徽章");
const u8 gText_Thunderbadge[] = _("枯叶徽章");
const u8 gText_Rainbowbadge[] = _("彩虹徽章");
const u8 gText_Soulbadge[] = _("浅红徽章");
const u8 gText_Marshbadge[] = _("金黄徽章");
const u8 gText_Volcanobadge[] = _("红莲徽章");
const u8 gText_Earthbadge[] = _("常青徽章");
const u8 gText_OakImportantToGetToKnowPokemonThroughly[] = _("大木博士：彻底了解你的宝可梦是非\n常重要的。\p");
const u8 gText_OakThisIsListOfPokemon[] = _("这是你的宝可梦列表，\n{PLAYER}。\p打开它就可以确认宝可梦的能力和招\n式。\p如果你想对宝可梦使用道具，也是在\n这里进行选择。\l{PAUSE_UNTIL_PRESS}");

const u8 gText_GBPlayerOn[] = _("打开了GB播放器。回响着令人怀念\n的声音。\l{PAUSE_UNTIL_PRESS}");
const u8 gText_GBPlayerOff[] = _("关闭了GB播放器。令人怀念的声音\n渐渐散去。\l{PAUSE_UNTIL_PRESS}");

const u8 gText_Sunday[] = _("星期日");
const u8 gText_Monday[] = _("星期一");
const u8 gText_Tuesday[] = _("星期二");
const u8 gText_Wednesday[] = _("星期三");
const u8 gText_Thursday[] = _("星期四");
const u8 gText_Friday[] = _("星期五");
const u8 gText_Saturday[] = _("星期六");
const u8 gText_LoveBall[] =     _("甜蜜球  / 桃桃果 / (妖精\n/超能)");
const u8 gText_Lure[] =         _("诱饵球  / 莓莓果 / (水/\n龙)");
const u8 gText_FriendBall[] =   _("友友球  / 樱子果 / (虫/\n草)");
const u8 gText_Heavy[] =        _("沉重球  / 橙橙果 / (岩石\n/地面/钢)");
const u8 gText_Moon[] =         _("月亮球  / 零余果 / (恶/\n幽灵/毒)");
const u8 gText_Fast[] =         _("速度球  / 梨梨果 / (电/\n格斗/火)");
const u8 gText_LevelBall[] =    _("等级  / 柿仔果 / (一般/\n飞行/冰)");
const u8 gText_Vermilion[] = _("枯叶市");
const u8 gText_Olivine[] = _("浅葱市");
const u8 gText_Floor0[] = _("0楼");
const u8 gText_Pal[] = _("伙伴");
const u8 gText_Underling[] = _("部下");
const u8 gText_Strategy[] = _("作战");
const u8 gText_Training[] = _("特训");
const u8 gText_Cheating[] = _("作弊");
const u8 gText_WeakPerson[] = _("弱者");
const u8 gText_ToughPerson[] = _("强者");
const u8 gText_Anybody[] = _("谁都可以");
const u8 gText_Love2[] = _("慈爱");
const u8 gText_Violence[] = _("暴力");
const u8 gText_Knowledge[] = _("知识");
const u8 gText_Tough3[] = _("强大的");
const u8 gText_Weak[] = _("弱小的");
const u8 gText_Both[] = _("都重要");
const u8 gText_GreenStone[] = _("绿色石头");
const u8 gText_RedStone[] = _("红色石头");
const u8 gText_BlueStone[] = _("蓝色石头");
