FortreeCity_House3_MapScripts::
	.byte 0

FortreeCity_House3_EventScript_Maniac::
	msgbox FortreeCity_House3_Text_MetStevenHadAmazingPokemon, MSGBOX_NPC
	end

FortreeCity_House3_EventScript_SchoolKidM::
	msgbox FortreeCity_House3_Text_OhYouHavePokedex, MSGBOX_NPC
	end

FortreeCity_House3_Text_MetStevenHadAmazingPokemon:
	.string "说到宝可梦图鉴，我想起来了，\p"
	.string "我寻找稀有石头的时候遇到了那个叫\n"
	.string "大吾的训练家。\p"
	.string "哈，他带着一些奇妙的宝可梦，\p"
	.string "它们不止是强大，还在训练中发挥到\n"
	.string "了极致！\p"
	.string "他也许比这城镇的道馆馆主还要强…\n"
	.string "…$"

FortreeCity_House3_Text_OhYouHavePokedex:
	.string "你拿着的那是什么？\p"
	.string "…… …… ……\p"
	.string "哦？它叫宝可梦图鉴？真奇妙！$"

