VermilionCity_House2_hns_MapScripts::
	.byte 0

VermilionCity_House2_EventScript_PokefanF::
	msgbox VermilionCity_House2_Text_PokefanF, MSGBOX_NPC
	end

VermilionCity_House2_EventScript_Youngster::
	msgbox VermilionCity_House2_Text_Youngster, MSGBOX_NPC
	end

VermilionCity_House2_Text_PokefanF:
	.string "你知道磁浮列车吗？\p"
	.string "那是通往城都地区满金市的铁路哦。$"

VermilionCity_House2_Text_Youngster:
	.string "我想去金黄市看看磁浮列车。$"
