SootopolisCity_Gym_B1F_MapScripts::
	.byte 0

SootopolisCity_Gym_B1F_EventScript_Andrea::
	trainerbattle_single TRAINER_ANDREA, SootopolisCity_Gym_B1F_Text_AndreaIntro, SootopolisCity_Gym_B1F_Text_AndreaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_AndreaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Crissy::
	trainerbattle_single TRAINER_CRISSY, SootopolisCity_Gym_B1F_Text_CrissyIntro, SootopolisCity_Gym_B1F_Text_CrissyDefeat
	msgbox SootopolisCity_Gym_B1F_Text_CrissyPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Brianna::
	trainerbattle_single TRAINER_BRIANNA, SootopolisCity_Gym_B1F_Text_BriannaIntro, SootopolisCity_Gym_B1F_Text_BriannaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_BriannaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Connie::
	trainerbattle_single TRAINER_CONNIE, SootopolisCity_Gym_B1F_Text_ConnieIntro, SootopolisCity_Gym_B1F_Text_ConnieDefeat
	msgbox SootopolisCity_Gym_B1F_Text_ConniePostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Bridget::
	trainerbattle_single TRAINER_BRIDGET, SootopolisCity_Gym_B1F_Text_BridgetIntro, SootopolisCity_Gym_B1F_Text_BridgetDefeat
	msgbox SootopolisCity_Gym_B1F_Text_BridgetPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Olivia::
	trainerbattle_single TRAINER_OLIVIA, SootopolisCity_Gym_B1F_Text_OliviaIntro, SootopolisCity_Gym_B1F_Text_OliviaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_OliviaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Tiffany::
	trainerbattle_single TRAINER_TIFFANY, SootopolisCity_Gym_B1F_Text_TiffanyIntro, SootopolisCity_Gym_B1F_Text_TiffanyDefeat
	msgbox SootopolisCity_Gym_B1F_Text_TiffanyPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Bethany::
	trainerbattle_single TRAINER_BETHANY, SootopolisCity_Gym_B1F_Text_BethanyIntro, SootopolisCity_Gym_B1F_Text_BethanyDefeat
	msgbox SootopolisCity_Gym_B1F_Text_BethanyPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Annika::
	trainerbattle_single TRAINER_ANNIKA, SootopolisCity_Gym_B1F_Text_AnnikaIntro, SootopolisCity_Gym_B1F_Text_AnnikaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_AnnikaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Daphne::
	trainerbattle_single TRAINER_DAPHNE, SootopolisCity_Gym_B1F_Text_DaphneIntro, SootopolisCity_Gym_B1F_Text_DaphneDefeat
	msgbox SootopolisCity_Gym_B1F_Text_DaphnePostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_Text_AndreaIntro:
	.string "给你看看我从馆主亚当那里学到的超\n"
	.string "凡的技术！$"

SootopolisCity_Gym_B1F_Text_AndreaDefeat:
	.string "请原谅我，亚当……$"

SootopolisCity_Gym_B1F_Text_AndreaPostBattle:
	.string "看看踩碎所有地板后会发生什么吧。$"

SootopolisCity_Gym_B1F_Text_CrissyIntro:
	.string "你一路到这儿来，但却不可能见到亚\n"
	.string "当，\p"
	.string "因为你会输给我！$"

SootopolisCity_Gym_B1F_Text_CrissyDefeat:
	.string "你真强！我被你可爱的外表骗过了！$"

SootopolisCity_Gym_B1F_Text_CrissyPostBattle:
	.string "你也许能够躲过被亚当一击打倒的命\n"
	.string "运。$"

SootopolisCity_Gym_B1F_Text_DaphneIntro:
	.string "亚当对战时的样子……\p"
	.string "我被那令人心醉的美丽吸引，才决定\n"
	.string "成为训练家。$"

SootopolisCity_Gym_B1F_Text_DaphneDefeat:
	.string "你的对战比我更加美丽……$"

SootopolisCity_Gym_B1F_Text_DaphnePostBattle:
	.string "你的对战非常优雅。\p"
	.string "啊……跟宝可梦在一起真幸运。$"

SootopolisCity_Gym_B1F_Text_ConnieIntro:
	.string "让我告诉你对战的严酷吧。$"

SootopolisCity_Gym_B1F_Text_ConnieDefeat:
	.string "啊，你很强。$"

SootopolisCity_Gym_B1F_Text_ConniePostBattle:
	.string "告诉你一件事吧。\p"
	.string "如果你想走到亚当那儿，就得在每块\n"
	.string "地板上走过一次。$"

SootopolisCity_Gym_B1F_Text_BridgetIntro:
	.string "丰缘地区最高水平的宝可梦道馆……\p"
	.string "就是琉璃市道馆。$"

SootopolisCity_Gym_B1F_Text_BridgetDefeat:
	.string "你的水平更高！$"

SootopolisCity_Gym_B1F_Text_BridgetPostBattle:
	.string "比起成为强大的道馆的一员，我想在\n"
	.string "其他地方训练会让你变得更强。但无\l"
	.string "论如何，那都更有趣一些。$"

SootopolisCity_Gym_B1F_Text_OliviaIntro:
	.string "我和亚当一起训练宝可梦，\p"
	.string "别以为你能轻易打倒我。$"

SootopolisCity_Gym_B1F_Text_OliviaDefeat:
	.string "我被打败了……$"

SootopolisCity_Gym_B1F_Text_OliviaPostBattle:
	.string "看来你有潜力，为何不和我们一起训\n"
	.string "练呢？$"

SootopolisCity_Gym_B1F_Text_TiffanyIntro:
	.string "优雅地滑过冰面，道路却没有交叉…\n"
	.string "…\p"
	.string "能做到这一点的训练家才拥有最高雅\n"
	.string "的美丽！$"

SootopolisCity_Gym_B1F_Text_TiffanyDefeat:
	.string "啊，打扰了。$"

SootopolisCity_Gym_B1F_Text_TiffanyPostBattle:
	.string "很明显，一个训练家有多强与年龄并\n"
	.string "无关系。$"

SootopolisCity_Gym_B1F_Text_BethanyIntro:
	.string "当我和宝可梦在一起时，时光飞逝得\n"
	.string "连说声“呀”都来不及！$"

SootopolisCity_Gym_B1F_Text_BethanyDefeat:
	.string "呀！$"

SootopolisCity_Gym_B1F_Text_BethanyPostBattle:
	.string "真希望我能在说“呀”之前就忘记这\n"
	.string "场注定的失败！$"

SootopolisCity_Gym_B1F_Text_AnnikaIntro:
	.string "我的稀有宝可梦也会和我一起战斗。$"

SootopolisCity_Gym_B1F_Text_AnnikaDefeat:
	.string "哎呀！你仔细看过我的宝可梦了吗？$"

SootopolisCity_Gym_B1F_Text_AnnikaPostBattle:
	.string "我来到这道馆只因亚当会欣赏我亲爱\n"
	.string "的宝可梦。\p"
	.string "啊，如果我还年轻的时候就遇到了亚\n"
	.string "当多好……$"

SootopolisCity_Gym_B1F_Text_BriannaIntro:
	.string "嘻嘻……你那严肃的面孔真迷人。$"

SootopolisCity_Gym_B1F_Text_BriannaDefeat:
	.string "呀，天啊，我太小看你了。$"

SootopolisCity_Gym_B1F_Text_BriannaPostBattle:
	.string "你根本碰不到亚当分毫，嘻嘻，我肯\n"
	.string "定……$"

