LilycoveCity_House4_MapScripts::
	.byte 0

LilycoveCity_House4_EventScript_Man1::
	msgbox LilycoveCity_House4_Text_MysteriesAtBottomOfSea, MSGBOX_NPC
	end

LilycoveCity_House4_EventScript_Man2::
	msgbox LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis, MSGBOX_NPC
	end

LilycoveCity_House4_Text_MysteriesAtBottomOfSea:
	.string "这个星球上最大的谜就在海底。\p"
	.string "这是听别人说的，我并不知道……$"

LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis:
	.string "绿岭市和琉璃市之间有个极深的海\n"
	.string "沟。\p"
	.string "这是我从别人那儿听说的。$"

